import {CanvasSurface,canvasVisualCSS} from './canvas-renderer.js';
import {cleanCanvas,canvasSize,canvasDuration,sceneSchedule} from './canvas-model.js';
import {escapeHtml as esc} from './data.js';

export function mount(host,value){
  const project=cleanCanvas(value),size=canvasSize(project.ratio),duration=canvasDuration(project),schedule=sceneSchedule(project),reduced=matchMedia('(prefers-reduced-motion: reduce)');
  let time=reduced.matches?schedule[0].holdStart:0,playing=false,raf=0,last=0,destroyed=false;
  const style=document.createElement('style');style.textContent=canvasVisualCSS+`.fcp{max-width:1280px;margin:24px auto;padding:0 20px;color:#292824;font:13px/1.5 -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif}.fcp *{box-sizing:border-box}.fcp button{font:inherit;cursor:pointer;background:#f8f7f4;border:1px solid #d4cfc5;border-radius:3px;padding:8px 12px;color:inherit}.fcp button:focus-visible,.fcp input:focus-visible{outline:2px solid #8c6b54;outline-offset:3px}.fcp h1{font-size:18px;font-weight:500;margin:0 0 15px}.fcp-fit{position:relative;width:100%;overflow:hidden;border:1px solid #d4cfc5}.fcp-stage{position:absolute;top:0;left:0;transform-origin:top left}.fcp-controls{display:flex;align-items:center;gap:10px;padding:16px 0;flex-wrap:wrap}.fcp-controls input{flex:1;min-width:100px;accent-color:#79746b}.fcp-controls output{font:11px monospace}.fcp-pages{display:flex;gap:6px;overflow:auto;padding-bottom:12px}.fcp-pages button{white-space:nowrap;font-size:12px}.fcp-pages [aria-current=true]{background:#292824;color:#f8f7f4}.fcp[data-dark=true]{color:#e6e3db}.fcp[data-dark=true] button{background:#272725;border-color:#55534d}.fcp[data-dark=true] [aria-current=true]{background:#e6e3db;color:#292824}.fcp-caption{font-size:11px;color:#827c72}@media(max-width:500px){.fcp{padding:0 10px;margin:14px auto}.fcp-controls{gap:6px}.fcp-controls button{padding:8px}.fcp-controls output{width:100%}}`;document.head.append(style);
  document.body.style.margin='0';document.body.style.background=project.dark?'#151515':'#ebe9e3';
  host.innerHTML=`<section class="fcp" data-dark="${project.dark}"><h1>${esc(project.name)}</h1><div class="fcp-fit" style="aspect-ratio:${size.width}/${size.height}"><div class="fcp-stage" style="width:${size.width}px;height:${size.height}px"></div></div><div class="fcp-controls"><button data-fcp="play">播放</button><button data-fcp="restart">重播</button><input type="range" min="0" max="${duration}" step="0.01" value="${time}" aria-label="画布播放进度"><output></output></div><nav class="fcp-pages" aria-label="切换画布页面">${project.scenes.map((s,i)=>`<button data-page="${i}">${i+1}. ${esc(s.name)}</button>`).join('')}</nav><p class="fcp-caption">${project.scenes.length} 页 · 数据与图形保存在此 HTML 中</p></section>`;
  const $=q=>host.querySelector(q),surface=new CanvasSurface($('.fcp-stage'),project),range=$('input'),out=$('output');
  const paint=()=>{const frame=surface.frame(time,{staticFrame:reduced.matches});range.value=String(time);out.textContent=`${time.toFixed(1)} / ${duration.toFixed(1)} s`;$('[data-fcp=play]').textContent=playing?'暂停':'播放';host.querySelectorAll('[data-page]').forEach(b=>b.setAttribute('aria-current',String(+b.dataset.page===frame.index)));};
  const resize=()=>{$('.fcp-stage').style.transform=`scale(${$('.fcp-fit').clientWidth/size.width})`;};
  const observer=new ResizeObserver(resize);observer.observe($('.fcp-fit'));resize();paint();
  function tick(now){if(destroyed)return;if(playing&&!document.hidden){time=Math.min(duration,time+Math.min(.12,(now-last)/1000));if(time>=duration){if(project.loop)time=0;else playing=false;}paint();}last=now;if(playing)raf=requestAnimationFrame(tick);}
  function play(){if(time>=duration)time=0;playing=true;last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(tick);paint();}
  function pause(){playing=false;cancelAnimationFrame(raf);paint();}
  const click=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.fcp==='play')playing?pause():play();else if(b.dataset.fcp==='restart'){time=0;play();}else if(b.dataset.page!==undefined){pause();time=schedule[+b.dataset.page].holdStart;paint();}};
  const input=()=>{pause();time=Number(range.value);paint();};host.addEventListener('click',click);range.addEventListener('input',input);
  const visibility=()=>{if(document.hidden)pause();};document.addEventListener('visibilitychange',visibility);const reduce=()=>{pause();paint();};reduced.addEventListener('change',reduce);
  return {play,pause,seek(seconds){pause();time=Math.max(0,Math.min(duration,seconds));paint();},destroy(){destroyed=true;playing=false;cancelAnimationFrame(raf);observer.disconnect();document.removeEventListener('visibilitychange',visibility);reduced.removeEventListener('change',reduce);host.removeEventListener('click',click);range.removeEventListener('input',input);surface.destroy();host.replaceChildren();style.remove();}};
}
