export function exploratoryAgentGuide(english=false){return english?`Additional coherent encodings:

series includes small-multiples alongside multi-line and the grouped/stacked/percentage views. Each stored observation _id and series identity is retained. Facets share a single value domain and time extent, never scale each panel independently. YYYY-MM-DD periods use actual time spacing. Missing observations break the line on both sides and remain in the table. The small-multiple route moves each observation's local contour into its own series panel; it does not fade between completed screenshots. Current multi-series display capacity is 2–36 periods and 2–6 series; a larger source table remains intact.

matrix-heatmap and matrix-bubbles use the original row/column/value table. A cell's persistent _id is its key; row and column labels locate and describe it but do not replace identity. The complete cross-product includes explicit null cells. Heatmaps may contain signed values. Bubble matrix requires nonnegative values: radius = availableRadius × sqrt(value / maximum), using the shared maximum across related steps. Zero has zero area and a visible 0 label; missing cells retain a slashed placeholder in both views. Never take absolute values to make a signed table eligible. Retain configured valueColors, its neutral center and numeric domain. Interpolate the same cell outline from its rectangle into its circle at the same center.

ordered-estimate-line, ordered-estimate-band and ordered-estimate-intervals use period/estimate/low/high and intervalLabel. Sort by valid unique YYYY-MM-DD dates and use actual time spacing. Bounds are supplied analysis results, not newly estimated confidence limits. estimate, low and high are either all valid with low ≤ estimate ≤ high, or all null. Partition the ribbon at observation midpoints with one contour per persistent _id; close the contour at its own date next to a missing observation so no band or line bridges the gap. Transition each interval piece into that date's vertical error interval; keep the estimate point throughout. All views share the same full lower/upper range and interval definition.

trajectory-points and trajectory-path use one object's time-stamped period/x/y observations. Keep every point at its real coordinates and extend connectors in chronological order. Record IDs identify observations; table row order is not time. Label both axes and preserve their units. The connecting path shows temporal order, not regression or causality. Do not fabricate dates for an arbitrary scatter table or join multiple unrelated objects.

spatial-3d, spatial-xy, spatial-xz and spatial-yz preserve label/group/x/y/z and all record IDs. Normalize each labeled coordinate to its shared padded range for display. Use an orthographic 3D basis [1/√2,−1/√2,0] and [1/√6,1/√6,−2/√6]; XY, XZ and YZ use the corresponding two original dimensions. Move every existing point continuously into the destination plane and keep the hidden coordinate in data and tooltips. Equal-size points retain object identity even when projections overlap. Display the visible dimensions and warn that screen distance is not 3D distance. No dimensionality reduction, refitting or synthetic coordinates are implied. Changed axis meaning or units requires native entry instead of correspondence-based morphing.`:`新增关联编码：

series 现在包括 small-multiples 共尺分面折线，与 multi-line 及各分组、堆叠、百分比图共用原始观测。持久化 _id 与系列身份不变；各分面共用数值范围和时间范围，禁止分别缩放。YYYY-MM-DD 日期按真实时间间距排列，缺失观测在两侧断开并保留表格行。每个观测的局部轮廓连续移动到自己系列的分面，不能用两张完成图淡入淡出代替。当前展示容量为 2–36 个时期、2–6 个系列，更大的原表保持完整。

matrix-heatmap 与 matrix-bubbles 使用原始 row/column/value 表。每格以持久化 _id 为身份，行列名称只负责定位与显示；完整交叉组合包含显式 null。热力矩阵可包含负数，气泡矩阵只适用于非负原值：半径 = 可用半径 × sqrt(value / maximum)，maximum 为相关步骤的共用最大值。真实零值面积为零并显示 0；缺失格在两种图中都保留斜线占位。不得对负数取绝对值来强行使用气泡。保留 valueColors、自定义中点和真实数值范围；同一格的轮廓在中心不变的情况下从矩形连续收成圆。

ordered-estimate-line、ordered-estimate-band、ordered-estimate-intervals 使用 period/estimate/low/high 和 intervalLabel。按唯一真实日期排序，以真实时间间距定位；上下界来自用户已有分析，不重新计算。三项需满足 low ≤ estimate ≤ high，或一起为 null。区间带在相邻日期中点分片，每条记录有独立轮廓；缺失观测邻侧在本日期收束，线和色带都不能跨缺口。每片连续收成该日期的误差区间，点估计始终保留。三种编码共用完整上下界范围与区间定义。

trajectory-points 与 trajectory-path 使用同一对象的 period/x/y 时间观测。点位保持在真实坐标，连线按日期顺序延伸；记录 ID 识别观测，表格行顺序不作为时间。两轴注明指标和单位。连线只表达时间路径，不是回归或因果关系；不得为任意散点补造日期，也不能把无关对象连接成路径。

spatial-3d、spatial-xy、spatial-xz、spatial-yz 保留 label/group/x/y/z 与全部记录 ID。每个坐标按带留白的共用范围归一用于显示；三维正交投影基为 [1/√2,−1/√2,0] 与 [1/√6,1/√6,−2/√6]，平面投影使用对应的两项原始维度。每个原有点连续移入目标平面，隐藏维度仍保留在原表和提示中。等大点代表原始对象，投影重叠也保留各自身份。明确显示可见维度并说明屏幕距离不是三维真实距离；不暗含降维算法、重新拟合或合成坐标。轴含义或单位改变时使用原生入场。`;}
