export function multivariateAgentGuide(english=false){return english?`Multivariate matrix and focus use the same complete sample × variable table (splom). Keep every observation _id, the variable registry entities={version:1,kind:'variable',items:[{id,name}]}, row._variableId, the independent sampleEntities={version:1,kind:'sample',items:[{id,name}]} and row._sampleId. Names are display text only. Existing works acquire missing registries once; subsequent renaming, sorting, saving and reopening must retain stored IDs. A matrix point key is ['multivariate-sample',sampleId,xVariableId,yVariableId,'point'], with both original X and Y record IDs attached. Symmetric copies have different ordered variable-pair keys. Never identify a point by sample display name, a variable name or row position.

multivariate-matrix displays every off-diagonal pair for the same population. multivariate-focus expands doc.selectedPair=[xVariableId,yVariableId] into one plot: the selected panel's existing points continuously move into the larger coordinate frame, while other panel copies contract at their own facet centers and become hidden. The return restores the complete matrix. Persistent variable identity determines each shared raw-value domain, padded by 8% on each side (constant values use 10% of magnitude, or 1 at zero); no standardization or forcing zero is applied. Variable units remain independent, from variableUnits[id] when explicitly provided or the original 'Name / unit' label. A changed variable unit or selected pair is a different measurement space: use explicit new-coordinate entry, or return to the matrix before selecting another pair; never impersonate a previous X/Y value. Do not pool bounds across unrelated variable IDs.

Use 2–5 variables and 3–80 complete samples, at most 6 consistent sample groups. Every sample must have one row for every variable, with the same group throughout. Missing values stay in the source table and block this complete-case layout; do not delete samples pairwise, impute zero, average duplicate observations or truncate data to fit. Group color bindings use the sorted persistent sample IDs in each group, independent of variable display order. Focus is a reading operation, not regression, Pearson correlation, significance or a PCA transformation. Deliver every step, explicit selectedPair, original source and per-variable units in the saved work and standalone player.`:`多变量散点矩阵与聚焦使用同一份完整的 splom 样本 × 变量长表。每条原始测量保留 _id；变量登记 entities={version:1,kind:'variable',items:[{id,name}]}，每行通过 _variableId 引用；样本独立登记 sampleEntities={version:1,kind:'sample',items:[{id,name}]}，每行通过 _sampleId 引用。名称仅显示。旧作品仅首次补登记，之后改名、排序、保存和重开保持存储身份。矩阵点的 key 为 ['multivariate-sample',样本ID,X变量ID,Y变量ID,'point']，同时携带原始 X 与 Y 两行的记录 ID。对称镜像的变量对顺序不同，key 也不同，不能用样本名称、变量名称或行号定义对应。

multivariate-matrix 在所有非对角分面显示相同完整样本；multivariate-focus 将 doc.selectedPair=[X变量ID,Y变量ID] 选中的原分面放大，原有样本点连续移到较大的坐标框，其余分面副本在各自原分面中心收起并隐藏，反向恢复完整矩阵。每个变量按其稳定ID保留自己的原值范围，两端各加8%留白；恒定值用绝对量级10%留白，恒定零用1。不得标准化或强制从零开始；各变量使用自己的单位，优先 variableUnits[变量ID]，否则保留原始「变量 / 单位」标签。变量单位或选中的变量对改变时，坐标含义已改变，正常展开新坐标，或先返回矩阵再聚焦；不能将新测量假冒为上一对 X/Y 值，不合并无关变量的坐标范围。

此布局接收2–5个变量、3–80个完整样本和最多6个样本分组；每个样本与每个变量组合仅一行，同一样本分组一致。缺失保留在原表并报告完整性不足，不按分面对样本删行，不补0，不自动平均重复观测，不截断数据凑容量。分组颜色以每组排序后的持久样本ID集合绑定，与变量顺序无关。聚焦只是阅读操作，不执行回归、相关、显著性检验或PCA。保存与独立播放器完整保留所有步骤、selectedPair、原始来源和各变量单位。`;}
