export function processAgentGuide(english=false){return english?`Process variation: process-individual ↔ process-imr uses the SAME complete period/value source table in acquisition order and the existing imr10 estimator. Keep each stored observation _id unchanged. For i>0, MR[i]=abs(value[i]−value[i−1]); its identity is the ORDERED pair of the two adjacent observation IDs, never a row position or period label. MR[0] is undefined and has no dot or fake zero. Derived MR links retain all three contributing IDs. The I view retains every original observation while the I+MR view resizes the I panel and unfolds moving ranges below. Never delete outliers, replace missing values with zero, or supply an MR as if it were an original measurement.

All supplied observations estimate one baseline: mean=mean(value), MRmean=mean(defined MR), sigma=MRmean/1.128; I limits=mean±3*sigma. MR center=MRmean, LCL=0, UCL=3.267*MRmean. Use the same estimator as the native I-MR chart without fitting another model. The I axis includes every measurement and both limits with padding; it need not start at zero. The MR axis MUST start at zero and contain every MR and its limit. Outside-limit points additionally use an outlined outer ring with a paper gap, retaining user colors: the flag must remain visible even when normal and accent colors are identical. Only outside-limit points are flagged; control limits are not product specification limits, confidence intervals, or a complete run-rule test. Layout eligibility is 4–300 complete nonconstant ordered observations, not a reason to trim or alter the source table.

Continuous unfolding requires the same process/data group, units, source, ordered observation IDs and identical original values. Because the current baseline is estimated from ALL inputs, reordering, adding/removing or changing a measurement changes adjacency or baseline and must use a visible explanatory normal chart entrance instead. Renaming labels does not change identity. During guided opening, resize I in the first 66% and unfold MR from its zero baseline after 42%; reverse playback folds MR in the first 58% before restoring the I panel after 34%. Match actual contours by persistent identity. Keep deterministic 0/25/50/75/100%, reverse and interrupted playback, and use the same renderer for HTML and video. Explain that moving ranges are derived adjacent differences, not additional independent measurements.`:`过程波动：process-individual ↔ process-imr 共用同一份完整 period/value 原表，保持实际采集顺序，复用已有 imr10 估计器。每次原始测量保留持久 _id。i>0 时 MR[i]=abs(value[i]−value[i−1])，其身份为有序的相邻两条记录 ID 对，不能用行号或时期显示名称替代。MR[0] 未定义，不产生点、不补零；MR 连线保留三个参与计算的原始 ID。I 视图保留全部单值，I+MR 视图先缩放 I 上区，再展开 MR 下区。不得删除异常值、填零补缺或把派生 MR 当作原始测量输入。

全部输入估计一条基线：mean=mean(value)，MRmean=mean(非空 MR)，sigma=MRmean/1.128；I 控制限 mean±3*sigma。MR 中心线为 MRmean，下限为 0，上限为 3.267*MRmean。与原生 I-MR 图共用估计器，不另拟合模型。I 轴包含所有测量及上下控制限并留白，不强制零起点；MR 轴必须从零开始，并包含所有 MR 与上控制限。越限点同时使用带纸白间隙的空心外环作为冗余标记，保留用户配色；即使正常色和强调色相同，也能识别越限。只标记越限，控制限不是产品规格限、置信区间或完整运行规则检验。4–300 条完整非恒定观测是当前变形展示条件，不得据此删改原表。

连续展开要求相同过程/关联数据组、单位、来源、有序观测 ID 与完全相同原值。现有基线由全部输入估计，所以重排、增删、修改观测都会改变相邻关系或基线，应展示原因并正常入场，不伪装为同一基线变形。改名不改变身份。guided 展开时前 66% 缩放 I 区，42% 后 MR 从零基线展开；反向前 58% 收起 MR，34% 后恢复 I 区。按持久身份对应真实轮廓，支持确定性 0/25/50/75/100%、反向、中途切换，HTML 和视频共用渲染器。画面说明 MR 是相邻原始测量的派生绝对差，不是额外独立观测。`;}
