export function refinementAgentGuide(english=false){return english?`Further coherent encodings:

series-rank joins the existing series family. Keep every stored observation _id and _seriesId and the original period/series/value table. At each period compute descending competition rank as 1 plus the count of strictly larger values, producing 1,1,3 for ties. Equal values must occupy the same rank; do not break ties using a name or table position, average ranks, or rewrite value with rank. Sort valid ISO dates chronologically and keep their actual spacing; other period labels retain their explicitly entered order, require the same complete set of series in every period, and never infer a missing rank as zero. The rank axis runs from 1 at the top to the number of series at the bottom. Original-value views share their measurement domain separately: rank units must not enlarge that domain. Match each observation to its own local line contour so direct jumps and reverse playback can transform original-value positions into rank positions. Clearly state that rank distances do not measure value differences. In the reverse transition show that ranks are returning to original values and wait until the geometry settles before reading values. Legacy smallmultiples and race tables acquire the existing persistent series registry once, preserving stored record IDs and saved works.

sample-ridge joins sample-swarm, sample-box, sample-violin, sample-raincloud and sample-sd. Use the SAME Gaussian KDE calculation, bandwidth, sample domain and maximum density amplitude as the existing sample family. Place the density contour above each horizontal group baseline and keep every original sample, with its stored _id, visible immediately below that baseline. Each group has a stable derived summary identity from its sorted member IDs; derived density is never one arbitrarily selected sample. Do not normalize each ridge independently or encode sample count by density height. Require 2–6 groups with 12–160 raw samples per group for density layouts; leave a larger or insufficient raw source table intact and fall back to its native chart instead of trimming rows. Keep original values, outliers, duplicates and scientific-scale decimals.

matrix-clustered joins matrix-heatmap and matrix-bubbles and accepts complete, comparable row/column/value measurements with at least two row objects and two column variables. Use Euclidean distances and average linkage (UPGMA); no z-score conversion, rescaling of inputs or missing-value imputation occurs. Canonically order row and column populations by their sorted persistent cell IDs BEFORE resolving equal-distance clustering ties, so renaming or reordering spreadsheet rows does not change tied trees. Clustering only changes display order; cell keys, original values, numeric color domain, configured valueColors and neutral center remain identical. Animate existing cells along the row direction first and then the column direction, with no false object matching. Hide dendrogram branches while cells reorder, then reveal them in the final 18% of the transition; reverse playback retracts them in its first 15%. Dendrogram branches represent actual merge distance, not significance or causality. An all-identical matrix has zero merge distances, not a synthetic separation. Display capacity remains 12 rows × 16 columns for these morph layouts; keep all source records and use native entry when capacity or completeness is not met. Signed matrices remain valid for heatmaps and clustering; bubble area still requires nonnegative values. No row deletion or absolute-value conversion makes incompatible data morphable.`:`继续扩充的关联编码：

series-rank 与已有系列图共用 period/series/value 原表。每个观测保留持久化 _id 与 _seriesId，按当期原值降序计算竞赛排名：rank = 1 + 严格大于该原值的系列数，因此同值按 1、1、3 并列。禁止用名称或行号打破并列、使用平均名次，或把 value 改写成 rank。有效 ISO 日期按真实时间升序连接并保留实际间隔；其他时期标签按明确的输入顺序排列；每期必须有同一组完整系列，不能把缺失名次补零。排名轴自上而下为 1 到系列数，原值视图共用自己的数值域，不能把名次混入测量值域。每条观测的局部线段按原 ID 对应，原值位置连续移动到名次位置，可反向和跳步。必须提示名次差不表示数值差；反向时明确由名次返回原值，中态停稳后读数。旧 smallmultiples 与 race 作品仅首次迁移到已有系列登记表，记录 ID 和用户作品保留。

sample-ridge 与 sample-swarm、sample-box、sample-violin、sample-raincloud、sample-sd 共用原始样本家族。使用完全相同的高斯 KDE、带宽、样本数值域与最大密度幅度；每组密度轮廓位于横向基线上方，全部原始样本按存储的 _id 留在该基线下方。派生摘要用组内持久样本 ID 的排序集合构造身份，不把任意原始点伪装成密度摘要。不得按组独立归一化山脊，也不能把密度高度当作样本量。密度布局需要 2–6 组、每组 12–160 原始样本；过多或不足时完整保留原表，正常切换原生图，不删行凑数。保留重复值、离群值、负数和科研小数。

matrix-clustered 与 matrix-heatmap、matrix-bubbles 共用完整、同量纲的 row/column/value 测量矩阵，至少两个行对象与两个列指标。按欧氏距离和平均连接 UPGMA 聚类，不自动标准化、换算原值或填补缺测。先按各行/列包含的持久单元 ID 排序形成规范顺序，再处理相等聚类距离，使改名和表格行重排不能改变并列树。聚类只改变显示顺序，每格身份、原值、数值色域、valueColors 与参考中心完全保留。既有单元先沿行方向、再沿列方向连续移动，不通过假匹配或替换图片实现。单元重排时隐藏树枝，在最后 18% 阶段展开；反向时先在前 15% 收起树枝。树枝表达实际合并距离，不是显著性或因果；全部相同的矩阵合并距离为零，不能制造分隔。变形布局容量仍为 12 行 × 16 列，容量或完整性不足时保留所有源记录并使用原生入场。负数矩阵可以热图与聚类重排，气泡仍仅支持非负值；不得删行或取绝对值来强行变形。`;}
