import {locale,isEnglish} from './locale.js';
import {recommendationGoals} from './chart-use-cases.js';
import {findTemplate,getExample} from './catalog.js';
import {escapeHtml as esc} from './data.js';
import {recommendForTask,tableProfile} from './task-recommendations.js';
import {parseTable,splitTable} from './table-data.js';
import {textSource,checkedSource} from './source-table.js';
import {editorDialog,openDataHelp} from './editor-assistance.js';
import {ChartScene} from './charts.js';
import {entityReferences} from './entity-identity.js';
import {mappedAxes} from './data-contract.js';
import {toClipboardTSV} from './sheet-range.js';
import {openDataImporter} from './data-importer.js';
import './task-picker.css';
const text=(zh,en)=>isEnglish()?en:zh;
export function mountTaskPicker(host,{onGoal=()=>{},onUse=()=>{},initialGoal='all',initialSource,initialHeader=true,initialMetadata={},original,options={},isCurrent=()=>true}={}){
 let table=null,source=initialSource?structuredClone(checkedSource(initialSource)):null,header=initialHeader,goal=initialGoal,importer=null,help=null,disposed=false,revision=0,limit=6,scenes=[],sourceMode='paste',format='tsv',entriesCache=null;
 host.classList.add('task-picker');
 host.innerHTML=`<div class="task-picker-head"><label>${text('你想说明什么？','What do you want to show?')}<select data-task-goal><option value="all">${text('查看所有适用图表','All suitable charts')}</option>${Object.entries(recommendationGoals).map(([id,n])=>`<option value="${id}">${esc(n[locale()])}</option>`).join('')}</select></label><details data-task-input ${source?'open':''}><summary>${text('根据我的表格选图','Match my table')}</summary><label class="task-table-label">${text('从 Excel / WPS 复制单元格区域','Copy a cell range from Excel / WPS')}<textarea data-task-table rows="4" spellcheck="false" placeholder="${text('类别&#9;销售额&#10;线上&#9;128&#10;线下&#9;156','Category&#9;Revenue&#10;Online&#9;128&#10;Offline&#9;156')}"></textarea></label><div><select data-task-format aria-label="${text('表格文本格式','Table text format')}"><option value="tsv">Excel / WPS</option><option value="csv">CSV</option></select><label class="task-header-choice"><input type="checkbox" data-task-header ${header?'checked':''}>${text('首行是表头','First row is a header')}</label><button class="button small" data-task-analyze>${text('查看推荐','Find charts')}</button><button class="button small" data-task-select-file>${text('选择 CSV / TSV','Choose CSV / TSV')}</button><input data-task-file type="file" accept=".csv,.tsv,.txt" hidden><button data-task-clear class="text-button">${text('清除表格','Clear table')}</button></div><p data-task-status role="status" aria-live="polite"></p></details></div><div data-task-profile></div><div data-task-results class="task-results"></div><nav class="task-pages" aria-label="${text('推荐图表分页','Recommended charts pages')}"><button class="text-button" data-task-prev hidden>${text('上一组','Previous')}</button><span data-task-page-count></span><button class="text-button task-more" data-task-more hidden>${text('下一组图表','More charts')}</button></nav>`;
 const $=s=>host.querySelector(s);
 function clearScenes(){scenes.forEach(s=>s.destroy());scenes=[];}
 function clearResults(){clearScenes();$('[data-task-results]').replaceChildren();$('[data-task-profile]').replaceChildren();$('[data-task-more]').hidden=true;$('[data-task-prev]').hidden=true;$('[data-task-page-count]').textContent='';}
 const needsAnalysis=()=>!!original||!!initialSource||!!$('[data-task-table]').value.trim();
 function render(){
  clearScenes();const results=$('[data-task-results]');results.hidden=!table&&(goal==='all'||needsAnalysis());if(results.hidden){clearResults();return;}
  const entries=entriesCache??=recommendForTask({goal,table,limit:204,metadata:initialMetadata}),shown=entries.slice(limit-6,limit);
  results.innerHTML=shown.map(r=>{const t=findTemplate(r.id),ready=r.status==='compatible';return `<article data-task-chart="${r.id}"><div class="task-result-title"><h3>${esc(t.type)}</h3>${table?`<span class="task-fit ${ready?'task-fit-ready':''}">${text(ready?'可直接使用':r.status==='parameters'?'需补充参数':r.status==='mapping'?'需对应字段':'不符合条件',ready?'Ready':r.status==='parameters'?'Parameters needed':r.status==='mapping'?'Map fields':'Not compatible')}</span>`:''}</div>${ready?`<div class="task-chart-preview" data-task-preview="${r.id}" aria-label="${esc(t.name)} ${text('当前数据预览','current data preview')}"></div>`:''}<p>${esc(r.use.choice[locale()])}</p>${table?`<small>${esc(r.status==='parameters'?text('需要真实参数：','Real parameters required: ')+r.missingParameters.map(p=>p.label).join('、'):r.status==='mapping'?text('请选择每个字段对应的原列。','Select the source column for each field.'):r.status==='incompatible'?r.errors[0]||text('当前数据不满足图表条件。','The table does not meet the chart requirements.'):text('保留全部记录，请核对字段与使用条件。','All records are retained. Review fields and use conditions.'))}</small>${r.mapping?.length?`<dl class="task-field-mapping">${r.fields.map((f,i)=>`<div><dt>${esc(f[0])}</dt><dd>${esc(r.mapping[i]<0?text('待对应','Not mapped'):table.headers[r.mapping[i]])}</dd></div>`).join('')}</dl>`:''}`:''}<button class="text-button" ${r.status==='parameters'||r.status==='incompatible'?`data-task-help="${r.id}"`:`data-task-use="${r.id}"`}>${table?text(r.status==='parameters'||r.status==='incompatible'?'查看填写要求':'核对并使用',r.status==='parameters'||r.status==='incompatible'?'View requirements':'Review & use'):text('使用示例','Use example')} →</button></article>`;}).join('');
  if(table){const profile=tableProfile(table);$('[data-task-profile]').textContent=text(`${profile.rows} 行 · ${profile.columns.length} 列 · 数值 ${profile.numbers} 列 · 日期 ${profile.dates} 列 · 文字 ${profile.texts} 列${profile.missing?` · ${profile.missing} 个空白格（保留缺失）`:''}`,`${profile.rows} rows · ${profile.columns.length} columns · ${profile.numbers} numeric · ${profile.dates} dates · ${profile.texts} text${profile.missing?` · ${profile.missing} empty cells retained`:''}`);$('[data-task-status]').textContent=text(`已读取 ${table.rows.length} 条记录。数据仅在浏览器处理。`,`${table.rows.length} records. Processed in this browser.`);
   for(const entry of shown.filter(r=>r.status==='compatible'))try{scenes.push(new ChartScene($(`[data-task-preview="${entry.id}"]`),entry.doc,{...options,width:300,height:170,compact:true,progress:1,interactive:false,annotations:[]}));}catch{$(`[data-task-preview="${entry.id}"]`).textContent=text('请在编辑器预览完整图表','Preview the full chart in the editor');}
  }else $('[data-task-profile]').textContent='';
  $('[data-task-more]').hidden=limit>=entries.length;$('[data-task-prev]').hidden=limit<=6;$('[data-task-page-count]').textContent=entries.length?`${limit-5}–${Math.min(limit,entries.length)} / ${entries.length}`:'';
 }
 function analyze(){entriesCache=null;limit=6;try{if(!source){source=textSource(parseTable($('[data-task-table]').value,{...(sourceMode==='paste'?{delimiter:format==='csv'?',':'\t'}:{})}),{kind:sourceMode});}const s=source;table={...splitTable(s.matrix,header),locations:s.locations.slice(header?1:0),headerRefs:header?s.locations[0]:[],origin:s.origin};render();}catch(e){table=null;clearResults();$('[data-task-status]').textContent=e.message;}}
 function closeImporter(){importer?.close();importer=null;}
 function invalidate(){closeImporter();revision++;entriesCache=null;limit=6;table=null;source=null;sourceMode='paste';clearResults();$('[data-task-status]').textContent=text('内容已修改，点击「查看推荐」重新检查。','Table changed. Find charts again to recheck.');}
 const input=e=>{if(e.target.matches('[data-task-table]'))invalidate();};
 const change=async e=>{if(e.target.matches('[data-task-goal]')){goal=e.target.value;limit=6;entriesCache=null;onGoal(goal);render();}if(e.target.matches('[data-task-format]')){format=e.target.value;invalidate();}if(e.target.matches('[data-task-header]')){header=e.target.checked;closeImporter();revision++;if(source)analyze();}if(e.target.matches('[data-task-file]')){closeImporter();const serial=++revision;try{const file=e.target.files?.[0];if(!file)return;if(!/\.(csv|tsv|txt)$/i.test(file.name)||file.size>2000000)throw Error(text('请选择 2 MB 以内的 CSV / TSV / TXT。','Choose CSV / TSV / TXT smaller than 2 MB.'));const value=await file.text();if(disposed||serial!==revision)return;sourceMode='text-file';format=/\.csv$/i.test(file.name)?'csv':/\.tsv$/i.test(file.name)?'tsv':format;$('[data-task-format]').value=format;source=textSource(parseTable(value,{delimiter:format==='csv'?',':'\t'}),{kind:'text-file',file:file.name});$('[data-task-table]').value=value;analyze();}catch(e){if(!disposed&&serial===revision){source=null;table=null;clearResults();$('[data-task-status]').textContent=e.message;}}finally{e.target.value='';}}};
 const click=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-task-select-file'))$('[data-task-file]').click();if(b.hasAttribute('data-task-analyze')){limit=6;analyze();}if(b.hasAttribute('data-task-clear')){closeImporter();revision++;source=null;table=null;sourceMode='paste';entriesCache=null;limit=6;$('[data-task-table]').value='';$('[data-task-status]').textContent='';render();}if(b.hasAttribute('data-task-more')){limit+=6;render();}if(b.hasAttribute('data-task-prev')){limit=Math.max(6,limit-6);render();}if(b.dataset.taskHelp){help?.close();help=openDataHelp(getExample(b.dataset.taskHelp));}if(b.dataset.taskUse){if(!table){if(needsAnalysis())return;onUse(getExample(b.dataset.taskUse),{sameData:false});return;}if(!isCurrent()){ $('[data-task-status]').textContent=text('当前数据已变化，请关闭并重新选图。','Current data changed. Close and reopen chart matching.');return;}const entry=entriesCache?.find(r=>r.id===b.dataset.taskUse);if(!entry||entry.status==='parameters'||entry.status==='incompatible')return;
   const base=entry.doc||{version:1,template:entry.id,title:initialMetadata.title||findTemplate(entry.id).name,subtitle:initialMetadata.subtitle||'',unit:initialMetadata.unit||text('数值','Value'),source:{type:'user',name:initialMetadata.source||source.origin.file||''},data:[]},captured=revision;importer?.close();importer=openDataImporter(base,{initialSource:structuredClone(source),initialHeader:header,initialMetadata:{...initialMetadata,source:initialMetadata.source||source.origin.file||''},onApply(result){const doc=result.doc||result;let sameData=false;if(original&&initialSource&&header&&JSON.stringify(source.matrix)===JSON.stringify(initialSource.matrix)&&doc.data.length===original.data.length){const sourceFields=findTemplate(original.template).fields,targetFields=findTemplate(doc.template).fields;const sameKeys=targetFields.every(f=>sourceFields.some(s=>s[0]===f[0]));const declaredIds=doc.tableInput?.idColumn>=0,matchingIds=doc.data.every((row,i)=>row._id===original.data[i]._id);sameData=sameKeys&&doc.unit===original.unit&&(!declaredIds||matchingIds)&&doc.data.every((row,i)=>targetFields.every(f=>Object.is(row[f[0]],original.data[i][f[0]])));if(sameData){
        const axes=mappedAxes(original,doc.template);if(axes)doc.axes=axes;
        if(!declaredIds)doc.tableInput.idColumn=original.tableInput?.idColumn??-1;
        const rowRefs=doc.tableInput?.rowRefs,restoredRefs={};doc.data.forEach((row,i)=>{const generated=row._id,prior=original.data[i];row._id=prior._id;if(rowRefs?.[generated])restoredRefs[row._id]=rowRefs[generated];});if(rowRefs)doc.tableInput.rowRefs=restoredRefs;
        if(doc.source.name===original.source.name){doc.source=structuredClone(original.source);if(original.provenance)doc.provenance=structuredClone(original.provenance);else delete doc.provenance;}
        if(original.entities&&doc.entities?.kind===original.entities.kind){doc.entities=structuredClone(original.entities);doc.data.forEach((row,i)=>{for(const key of entityReferences)if(original.data[i][key]!==undefined)row[key]=original.data[i][key];});}
      }}
     onUse(doc,{sameData});},isCurrent:()=>!disposed&&captured===revision&&isCurrent()});}};
 $('[data-task-goal]').value=goal;host.addEventListener('input',input);host.addEventListener('change',change);host.addEventListener('click',click);if(source){$('[data-task-table]').value=toClipboardTSV(source.matrix);analyze();}else render();
 return {destroy(){if(disposed)return;disposed=true;revision++;clearScenes();importer?.close();help?.close();host.removeEventListener('input',input);host.removeEventListener('change',change);host.removeEventListener('click',click);}};
}
export function openTaskPicker({onUse=()=>{},...options}={}){
 const ui=editorDialog('task-picker-dialog',text('按我的数据选图','Choose charts for my data'),'FORMA / DATA'),{dialog}=ui;dialog.innerHTML=ui.header+'<div class="task-picker-dialog-body"></div>';let picker,closed=false;
 const close=()=>{if(closed)return;closed=true;ui.close();picker?.destroy();};picker=mountTaskPicker(dialog.querySelector('.task-picker-dialog-body'),{...options,onUse(doc,meta){close();onUse(doc,meta);}});dialog.addEventListener('close',()=>{closed=true;picker?.destroy();},{once:true});dialog.show();return{dialog,close};
}
