import * as d3 from 'd3';
import {measurementDomain} from './axis-policy.js';
import {phase7 as phase,number7 as fmt,num7 as num,label7 as label} from './volume7-utils.js';
import {t14,andrews14,taylor14,target14,youden14,contingency14} from './volume14-data.js';
const unique=a=>[...new Set(a)],groupColor=(s,g,i)=>s.theme.groupColor?.(g,s.theme.color(i))??s.theme.color(i),record=r=>({'data-record-id':r._id}),raw=v=>String(v);
function frame(s,xd,yd,{left=s.compact?43:57,right=s.w-20,top=36,bottom=s.h-43,xlabel='',ylabel='',square=false}={}){
 if(square){const side=Math.min(right-left,bottom-top),cx=(left+right)/2,cy=(top+bottom)/2;left=cx-side/2;right=cx+side/2;top=cy-side/2;bottom=cy+side/2;}
 const x=d3.scaleLinear(xd,[left,right]),y=d3.scaleLinear(yd,[bottom,top]);
 x.ticks(s.compact?3:5).forEach(v=>{s.line(x(v),top,x(v),bottom,{'stroke-width':.55,'stroke-dasharray':'2 5'});num(s,x(v),bottom+16,fmt(v),{'font-size':s.fs-2,'text-anchor':'middle'});});
 y.ticks(s.compact?3:5).forEach(v=>{s.line(left,y(v),right,y(v),{'stroke-width':.55,'stroke-dasharray':'2 5'});num(s,left-7,y(v)+3,fmt(v),{'font-size':s.fs-2,'text-anchor':'end'});});
 label(s,left,top-13,ylabel,{'font-size':s.fs-2},s.compact?36:70);label(s,right,bottom+33,xlabel,{'font-size':s.fs-2,'text-anchor':'end'},s.compact?37:70);return{x,y,left,right,top,bottom};
}
function zeroAxes(s,f){if(f.x.domain()[0]<=0&&f.x.domain()[1]>=0)s.line(f.x(0),f.top,f.x(0),f.bottom,{stroke:s.theme.secondary,'stroke-width':.8});if(f.y.domain()[0]<=0&&f.y.domain()[1]>=0)s.line(f.left,f.y(0),f.right,f.y(0),{stroke:s.theme.secondary,'stroke-width':.8});}
function point(s,row,x,y,{color=s.theme.accent,field='x',delay=0,radius=s.compact?3:4,attrs={},tip=''}={}){const mark=s.circle(x,y,radius,{fill:color,stroke:s.theme.bg,'stroke-width':1,...record(row),...attrs});s.growCircle(mark,radius,delay,.55);s.edit(mark,row,field);s.tip(mark,tip);return mark;}
function arrow(s,x0,y0,x1,y1,color,delay=0,attrs={}){const g=s.group(attrs),shaft=s.line(x0,y0,x1,y1,{stroke:color,'stroke-width':1.5},g),angle=Math.atan2(y1-y0,x1-x0),length=s.compact?4:6,head=s.path(`M${x1},${y1}L${x1-length*Math.cos(angle-.45)},${y1-length*Math.sin(angle-.45)}L${x1-length*Math.cos(angle+.45)},${y1-length*Math.sin(angle+.45)}Z`,{fill:color},g);s.add(p=>{const q=phase(p,delay,.58);g.setAttribute('transform',`translate(${x0} ${y0}) scale(${q}) translate(${-x0} ${-y0})`);g.setAttribute('opacity',q);});return{g,shaft,head};}
function residualColor(s,v,max){return d3.interpolateRgb(s.theme.bg,v>=0?s.theme.fg:s.theme.accent)(.12+.78*Math.min(1,Math.abs(v)/(max||1)));}
function andrews(s,doc){
 const curves=andrews14(doc),groups=unique(curves.map(c=>c.group)),legendBottom=s.legend(groups.map((group,i)=>({label:group,color:groupColor(s,group,i)})),s.compact?43:57,13),left=s.compact?43:57,right=s.w-19,top=Math.max(legendBottom+15,38),bottom=s.h-(s.compact?89:102),x=d3.scaleLinear([-Math.PI,Math.PI],[left,right]),y=d3.scaleLinear(measurementDomain(curves.flatMap(c=>c.points.map(p=>p.value)),{padding:.07}),[bottom,top]);
 y.ticks(3).forEach(v=>{s.line(left,y(v),right,y(v),{'stroke-width':.6,'stroke-dasharray':'2 5'});num(s,left-7,y(v)+3,fmt(v),{'text-anchor':'end','font-size':s.fs-2});});
 [-Math.PI,0,Math.PI].forEach((v,i)=>num(s,x(v),bottom+16,['−π','0','π'][i],{'font-size':s.fs-2,'text-anchor':'middle'}));label(s,right,bottom+16,'t',{'text-anchor':'end','font-size':s.fs-2},2);
 curves.forEach((curve,i)=>{const color=groupColor(s,curve.group,groups.indexOf(curve.group)),path=s.path(d3.line().x(p=>x(p.t)).y(p=>y(p.value))(curve.points),{stroke:color,'stroke-width':s.compact?1:1.3,'stroke-opacity':.66,'data-mark':'andrews-curve','data-group':curve.group,'data-object':curve.label});s.draw(path,i/curves.length*.2,.74);s.tip(path,`${curve.label} · ${curve.group}\n${curve.rows.map(r=>`${r.variable}: ${raw(r.value)}`).join('\n')}\n${t14('整条曲线由全部维度构造','Entire curve constructed from all dimensions')}`);});
 const my=bottom+32,mh=Math.max(24,s.h-my-15),cellW=(right-left)/curves.length,cellH=mh/doc.variables.length,max=d3.max(doc.data,r=>Math.abs(r.value))||1;
 doc.variables.forEach((variable,j)=>label(s,left-6,my+(j+.7)*cellH,variable,{'text-anchor':'end','font-size':s.fs-3},s.compact?4:6));
 curves.forEach((curve,i)=>curve.rows.forEach((row,j)=>{const color=groupColor(s,curve.group,groups.indexOf(curve.group)),mark=s.rect(left+i*cellW,my+j*cellH,cellW,cellH,{fill:d3.interpolateRgb(s.theme.bg,color)(.12+.78*Math.abs(row.value)/max),stroke:s.theme.bg,'stroke-width':.7,'data-mark':'andrews-coefficient','data-value':row.value,...record(row)});s.reveal(mark,.25+i/curves.length*.2,.35);s.edit(mark,row,'value');s.tip(mark,`${row.label} · ${row.group}\n${row.variable}: ${raw(row.value)} ${doc.unit}\n${t14('输入原值；色深为绝对值','Original input; intensity encodes absolute value')}`);}));
 label(s,right,s.h-1,t14('原值矩阵 · 点击修改','Input matrix · click to edit'),{'text-anchor':'end','font-size':s.fs-3},45);
}
function biplot(s,doc){
 const scores=doc.data.filter(r=>r.kind==='score'),loads=doc.data.filter(r=>r.kind==='loading'),groups=unique(scores.map(r=>r.group)),legendBottom=s.legend(groups.map((g,i)=>({label:g,color:groupColor(s,g,i)})),s.compact?43:57,13),extent=Math.max(...scores.flatMap(r=>[Math.abs(r.x),Math.abs(r.y)]),...loads.flatMap(r=>[Math.abs(r.x*doc.loadingScale),Math.abs(r.y*doc.loadingScale)]))*1.23||1,f=frame(s,[-extent,extent],[-extent,extent],{square:true,top:Math.max(legendBottom+18,48),bottom:s.h-44,xlabel:`PC1 · ${raw(doc.variance1)}%`,ylabel:`PC2 · ${raw(doc.variance2)}%`});zeroAxes(s,f);
 scores.forEach((row,i)=>point(s,row,f.x(row.x),f.y(row.y),{color:groupColor(s,row.group,groups.indexOf(row.group)),field:'x',delay:i/scores.length*.26,attrs:{'data-mark':'biplot-score','data-x':row.x,'data-y':row.y,'data-group':row.group},tip:`${row.label} · ${row.group}\nPC1: ${raw(row.x)}\nPC2: ${raw(row.y)}\n${t14('样本得分','Sample score')}`}));
 loads.forEach((row,i)=>{const color=groupColor(s,row.group,groups.length),x=f.x(row.x*doc.loadingScale),y=f.y(row.y*doc.loadingScale),a=arrow(s,f.x(0),f.y(0),x,y,color,.16+i*.045,{'data-mark':'biplot-loading','data-x':row.x,'data-y':row.y,...record(row)});s.edit(a.shaft,row,'x');s.tip(a.g,`${row.label}\nPC1: ${raw(row.x)}\nPC2: ${raw(row.y)}\n${t14('显示倍率','Display multiplier')}: ×${raw(doc.loadingScale)}\n${doc.scaling}`);const target=s.circle(x,y,s.compact?3:4,{fill:s.theme.bg,stroke:color,'stroke-width':1,'data-mark':'biplot-loading-edit'});s.edit(target,row,'y');s.reveal(target,.3+i*.045,.5);s.tip(target,`${row.label}\nPC1: ${raw(row.x)} · PC2: ${raw(row.y)}`);const name=label(s,x+(row.x>=0?6:-6),y-5,row.label,{'text-anchor':row.x>=0?'start':'end',fill:color,'font-size':s.fs-2},s.compact?7:10);s.reveal(name,.3+i*.045,.5);});
 label(s,s.w-13,14,`${t14('载荷','Loadings')} ×${raw(doc.loadingScale)}`,{'text-anchor':'end',fill:s.theme.accent,'font-size':s.fs-2},27);
}
function taylor(s,doc){
 const model=taylor14(doc),limit=Math.max(1.2,d3.max(model,d=>d.ratio)*1.17),left=s.compact?26:42,right=s.w-(s.compact?26:42),top=30,bottom=s.h-40,cx=(left+right)/2,scale=Math.min((right-left)/(2*limit),(bottom-top)/limit),cy=bottom,px=v=>cx+v*scale,py=v=>cy-v*scale,arc=(center,r,a0=0,a1=Math.PI)=>d3.line()(Array.from({length:97},(_,i)=>{const a=a0+(a1-a0)*i/96;return[px(center+r*Math.cos(a)),py(r*Math.sin(a))];}));
 const clip=s.el('clipPath',{id:`${s.id}-taylor-domain`},s.defs);s.path(`${arc(0,limit)}L${px(-limit)},${cy}L${px(limit)},${cy}Z`,{},clip);const grid=s.group({'clip-path':`url(#${s.id}-taylor-domain)`});
 d3.ticks(0,limit,4).filter(v=>v>0).forEach(r=>{s.path(arc(0,r),{stroke:s.theme.line,'stroke-width':.7});num(s,px(-r),cy+16,fmt(r),{'text-anchor':'middle','font-size':s.fs-2});num(s,px(r),cy+16,fmt(r),{'text-anchor':'middle','font-size':s.fs-2});});
 [-1,-.8,-.5,0,.5,.8,.95,1].forEach(c=>{const a=Math.acos(c),x=px(limit*c),y=py(limit*Math.sin(a));s.line(cx,cy,x,y,{stroke:s.theme.line,'stroke-width':.6,'stroke-dasharray':'2 5'});num(s,x+(c<0?-5:c>0?5:0),y-6,raw(c),{'text-anchor':c<0?'end':c>0?'start':'middle','font-size':s.fs-3});});
 [0.5,1,1.5,2,3].filter(r=>r<limit+1).forEach(r=>{s.path(arc(1,r),{stroke:s.theme.accent,'stroke-width':.75,'stroke-opacity':.43,'stroke-dasharray':'4 4'},grid);const a=Math.min(Math.PI*.7,Math.acos(Math.min(1,(limit*limit-1-r*r)/(2*r))));if(Number.isFinite(a)){const x=1+r*Math.cos(a),y=r*Math.sin(a);if(Math.hypot(x,y)<limit*.99)num(s,px(x),py(y),fmt(r),{fill:s.theme.accent,'font-size':s.fs-3},grid);}});
 s.line(px(-limit),cy,px(limit),cy,{stroke:s.theme.secondary});const ref=s.rect(px(1)-3,cy-3,6,6,{fill:s.theme.fg,'data-mark':'taylor-reference'});s.tip(ref,`${t14('共同参考','Common reference')}\nσ: ${raw(doc.referenceSD)} ${doc.unit}\nσ/σref=1 · ρ=1`);
 model.forEach((m,i)=>{point(s,m.row,px(m.x),py(m.y),{field:'sd',delay:.08+i/model.length*.3,attrs:{'data-mark':'taylor-model','data-ratio':m.ratio,'data-correlation':m.row.correlation,'data-centered-rmse':m.centeredRMSE},tip:`${m.row.label}\nσ: ${raw(m.row.sd)} ${doc.unit}\nρ: ${raw(m.row.correlation)}\n${t14('归一化中心 RMSE','Normalized centered RMSE')}: ${fmt(m.centeredRMSE)}`});const name=label(s,px(m.x)+6,py(m.y)-7,m.row.label,{fill:s.theme.fg,'font-size':s.fs-2},s.compact?6:14);s.reveal(name,.2+i/model.length*.3,.4);});
 label(s,left,13,t14('弧外数字：相关系数 ρ','Outer labels: correlation ρ'),{'font-size':s.fs-2},45);label(s,right,s.h-1,t14('半径 σ/σ参考 · 红虚线：中心 RMSE/σ参考','Radius: σ/σref · dashed: centered RMSE/σref'),{'text-anchor':'end','font-size':s.fs-3},s.compact?48:85);
}
function targetdiagram(s,doc){
 const model=target14(doc),limit=Math.max(1.2,d3.max(model,d=>Math.max(Math.abs(d.x),Math.abs(d.y)))*1.24),f=frame(s,[-limit,limit],[-limit,limit],{square:true,top:40,xlabel:t14('带符号中心 RMSE / σ参考','Signed centered RMSE / reference SD'),ylabel:t14('均值偏差 / σ参考','Mean bias / reference SD')});zeroAxes(s,f);
 d3.ticks(0,limit,4).filter(v=>v>0).forEach(r=>{s.circle(f.x(0),f.y(0),f.x(r)-f.x(0),{fill:'none',stroke:s.theme.line,'stroke-width':.8,'stroke-dasharray':'3 4','data-mark':'target-rmse-ring','data-rmse':r});num(s,f.x(r/Math.SQRT2)+3,f.y(r/Math.SQRT2)-3,fmt(r),{'font-size':s.fs-3});});
 model.forEach((m,i)=>{const col=m.x<0?s.theme.fg:s.theme.accent;point(s,m.row,f.x(m.x),f.y(m.y),{color:col,field:'bias',delay:i/model.length*.35,attrs:{'data-mark':'target-model','data-x':m.x,'data-y':m.y,'data-total-rmse':m.rmse},tip:`${m.row.label}\n${t14('偏差','Bias')}: ${raw(m.row.bias)} ${doc.unit}\n${t14('中心 RMSE','Centered RMSE')}: ${raw(m.row.centeredRMSE)} ${doc.unit}\nσ: ${raw(m.row.sd)} ${doc.unit}\n${t14('归一化总 RMSE','Normalized total RMSE')}: ${fmt(m.rmse)}`});const name=label(s,f.x(m.x)+6,f.y(m.y)-6,m.row.label,{fill:col,'font-size':s.fs-2},s.compact?7:14);s.reveal(name,.2+i/model.length*.3,.4);});
 label(s,s.w-15,14,t14('左：波动不足 · 右：波动相等或更大','Left: lower SD · right: equal or greater SD'),{'text-anchor':'end','font-size':s.fs-3},s.compact?45:75);
}
function youden(s,doc){
 const med=youden14(doc),span=Math.max(d3.max(doc.data,r=>Math.abs(r.sampleA-med.medianA)),d3.max(doc.data,r=>Math.abs(r.sampleB-med.medianB)))*1.22,f=frame(s,[med.medianA-span,med.medianA+span],[med.medianB-span,med.medianB+span],{square:true,top:38,xlabel:doc.axes.x,ylabel:doc.axes.y});
 s.line(f.x(med.medianA),f.top,f.x(med.medianA),f.bottom,{stroke:s.theme.secondary,'stroke-dasharray':'4 4'});s.line(f.left,f.y(med.medianB),f.right,f.y(med.medianB),{stroke:s.theme.secondary,'stroke-dasharray':'4 4'});s.line(f.left,f.bottom,f.right,f.top,{stroke:s.theme.accent,'stroke-opacity':.55,'stroke-dasharray':'3 4','data-mark':'youden-diagonal'});
 doc.data.forEach((row,i)=>point(s,row,f.x(row.sampleA),f.y(row.sampleB),{field:'sampleA',delay:i/doc.data.length*.4,radius:s.compact?2.7:3.7,attrs:{'data-mark':'youden-laboratory','data-a':row.sampleA,'data-b':row.sampleB},tip:`${row.label}\n${doc.axes.x}: ${raw(row.sampleA)}\n${doc.axes.y}: ${raw(row.sampleB)}\n${t14('实验室原始成对观测','Original paired laboratory observations')}`}));
 label(s,s.w-15,14,`${t14('中位数','Medians')} ${fmt(med.medianA)} / ${fmt(med.medianB)}`,{'text-anchor':'end','font-size':s.fs-3},55);
}
function cellTip(c,m,doc){return`${c.row.row} × ${c.row.column}\n${t14('原始频数','Observed count')}: ${raw(c.row.count)} ${doc.unit}\n${t14('独立性期望','Expected under independence')}: ${fmt(c.expected)}\nPearson r: ${fmt(c.residual)}`;}
function agreement(s,doc){
 const m=contingency14(doc),left=s.compact?38:54,top=39,bottom=s.h-41,tableW=Math.min(s.compact?85:158,s.w*.31),right=s.w-tableW-(s.compact?19:36),side=Math.min(right-left,bottom-top),x0=left+(right-left-side)/2,y0=top+(bottom-top-side)/2,k=side/m.total,xTotals=[0,...d3.cumsum(m.columnTotals)],yTotals=[0,...d3.cumsum(m.rowTotals)];
 s.rect(x0,y0,side,side,{fill:'none',stroke:s.theme.line,'stroke-width':.8});s.line(x0,y0,x0+side,y0+side,{stroke:s.theme.accent,'stroke-dasharray':'3 4','stroke-opacity':.65});
 m.rows.forEach((name,i)=>{const x=x0+xTotals[i]*k,y=y0+yTotals[i]*k,w=m.columnTotals[i]*k,h=m.rowTotals[i]*k,c=m.cells.find(c=>c.i===i&&c.j===i),square=c.row.count*k,outline=s.rect(x,y,w,h,{fill:s.theme.bg,stroke:s.theme.secondary,'stroke-width':.8,'data-mark':'agreement-margin','data-row-total':m.rowTotals[i],'data-column-total':m.columnTotals[i]});s.reveal(outline,i*.08,.55);s.tip(outline,`${name}\n${doc.axes.y}: ${raw(m.rowTotals[i])}\n${doc.axes.x}: ${raw(m.columnTotals[i])}\n${t14('边际矩形，非单个输入单元','Marginal rectangle, not an individual input cell')}`);
  const mark=s.rect(x+(w-square)/2,y+(h-square)/2,square,square,{fill:s.theme.accent,'fill-opacity':.84,'data-mark':'agreement-square','data-count':c.row.count,...record(c.row)});s.add(p=>{const q=phase(p,.12+i*.08,.58);mark.setAttribute('width',square*Math.sqrt(q));mark.setAttribute('height',square*Math.sqrt(q));mark.setAttribute('x',x+w/2-square*Math.sqrt(q)/2);mark.setAttribute('y',y+h/2-square*Math.sqrt(q)/2);});s.edit(mark,c.row,'count');s.tip(mark,`${name}\n${t14('完全一致频数','Exact agreement count')}: ${raw(c.row.count)} ${doc.unit}`);label(s,x+w/2,y0+side+17,name,{'text-anchor':'middle','font-size':s.fs-3},s.compact?4:9);label(s,x0-6,y+h/2+3,name,{'text-anchor':'end','font-size':s.fs-3},s.compact?3:8);
 });
 const tx=s.w-tableW-6,cell=Math.min(tableW/m.columns.length,(bottom-top-36)/m.rows.length),ty=top+26;label(s,tx,top+8,t14('完整计数表','Complete counts'),{'font-size':s.fs-2},24);
 m.cells.forEach((c,i)=>{const xx=tx+c.j*cell,yy=ty+c.i*cell,r=s.rect(xx,yy,cell,cell,{fill:c.i===c.j?s.theme.accent:s.theme.bg,'fill-opacity':c.i===c.j?.1:1,stroke:s.theme.line,'stroke-width':.6,'data-mark':'agreement-count','data-count':c.row.count,...record(c.row)});s.edit(r,c.row,'count');s.tip(r,cellTip(c,m,doc));s.reveal(r,.18+i/m.cells.length*.3,.45);const txt=num(s,xx+cell/2,yy+cell/2+3,raw(c.row.count),{'text-anchor':'middle',fill:c.i===c.j?s.theme.accent:s.theme.fg,'font-size':s.fs-3});s.edit(txt,c.row,'count');s.tip(txt,cellTip(c,m,doc));s.reveal(txt,.18+i/m.cells.length*.3,.45);});
 label(s,tx,ty+m.rows.length*cell+16,t14('行 / 列顺序同主图','Rows / columns match main plot'),{'font-size':s.fs-3},s.compact?18:28);label(s,left,15,`B = ${fmt(m.agreement,{significantDigits:3})} · ${t14('完全一致率','Exact match')} ${fmt(m.exactRate*100,{significantDigits:3})}%`,{fill:s.theme.fg,'font-size':s.fs-1},s.compact?43:70);label(s,x0,s.h-2,`${doc.axes.y} × ${doc.axes.x}`,{'font-size':s.fs-2},45);
}
function association(s,doc){
 const m=contingency14(doc),left=s.compact?40:62,right=s.w-15,top=42,bottom=s.h-28,cw=(right-left)/m.columns.length,rh=(bottom-top)/m.rows.length,maxExpected=d3.max(m.cells,c=>Math.sqrt(c.expected)),maxResidual=Math.max(1,d3.max(m.cells,c=>Math.abs(c.residual))),widthScale=cw*.78/maxExpected,heightScale=rh*.35/maxResidual;
 m.columns.forEach((name,j)=>label(s,left+(j+.5)*cw,top-12,name,{'text-anchor':'middle','font-size':s.fs-2},s.compact?8:18));m.rows.forEach((name,i)=>{const base=top+(i+.5)*rh;label(s,left-7,base+3,name,{'text-anchor':'end','font-size':s.fs-2},s.compact?4:8);s.line(left,base,right,base,{stroke:s.theme.secondary,'stroke-width':.7});});
 m.cells.forEach((c,i)=>{const center=left+(c.j+.5)*cw,base=top+(c.i+.5)*rh,w=Math.sqrt(c.expected)*widthScale,h=Math.abs(c.residual)*heightScale,col=c.residual>=0?s.theme.fg:s.theme.accent,mark=s.rect(center-w/2,c.residual>=0?base-h:base,w,h,{fill:col,'fill-opacity':.75,'data-mark':'association-cell','data-residual':c.residual,'data-expected':c.expected,'data-count':c.row.count,...record(c.row)});s.add(p=>{const q=phase(p,i/m.cells.length*.3,.62);mark.setAttribute('height',h*q);mark.setAttribute('y',c.residual>=0?base-h*q:base);});s.edit(mark,c.row,'count');s.tip(mark,cellTip(c,m,doc));const hit=s.rect(left+c.j*cw+1,top+c.i*rh+1,cw-2,rh-2,{fill:'transparent',stroke:'none','data-mark':'association-input'});s.edit(hit,c.row,'count');s.tip(hit,cellTip(c,m,doc));const txt=num(s,center,c.residual>=0?base-h-5:base+h+11,`${c.residual>0?'+':''}${fmt(c.residual,{significantDigits:3})}`,{'text-anchor':'middle',fill:col,'font-size':s.fs-3});s.reveal(txt,.3+i/m.cells.length*.25,.45);});
 label(s,left,14,t14('上方：高于期望 · 下方：低于期望','Above: observed > expected · below: observed < expected'),{'font-size':s.fs-2},s.compact?47:95);label(s,right,s.h-1,t14('高度：Pearson 残差 · 宽度：√期望频数','Height: Pearson residual · width: √expected count'),{'text-anchor':'end','font-size':s.fs-3},s.compact?46:85);
}
function mosaicplot(s,doc){
 const m=contingency14(doc),left=s.compact?29:43,right=s.w-17,top=43,bottom=s.h-41,width=right-left,height=bottom-top,maxResidual=Math.max(1,d3.max(m.cells,c=>Math.abs(c.residual))),margins=[0,...d3.cumsum(m.rowTotals)];
 m.rows.forEach((name,i)=>{const xx=left+margins[i]/m.total*width,w=m.rowTotals[i]/m.total*width;let cumulative=0;label(s,xx+w/2,bottom+18,name,{'text-anchor':'middle','font-size':s.fs-2},s.compact?8:18);
  m.cells.filter(c=>c.i===i).forEach((c,j)=>{const yy=top+cumulative/m.rowTotals[i]*height,h=c.row.count/m.rowTotals[i]*height;cumulative+=c.row.count;const color=residualColor(s,c.residual,maxResidual),mark=s.rect(xx,yy,w,h,{fill:color,stroke:s.theme.bg,'stroke-width':1,'data-mark':'mosaic-cell','data-share':c.share,'data-count':c.row.count,'data-residual':c.residual,...record(c.row)});s.add(p=>{const q=phase(p,i/m.rows.length*.22+j*.035,.62);mark.setAttribute('height',h*q);});s.edit(mark,c.row,'count');s.tip(mark,cellTip(c,m,doc));
   if(c.row.count===0){const zero=s.circle(xx+w/2,yy,3,{fill:s.theme.bg,stroke:s.theme.accent,'stroke-width':1,'data-mark':'mosaic-zero'});s.edit(zero,c.row,'count');s.tip(zero,cellTip(c,m,doc));s.reveal(zero,.3,.5);}
   if(h>22&&w>40){const txt=label(s,xx+w/2,yy+h/2+(h>39?-2:3),c.row.column,{'text-anchor':'middle',fill:Math.abs(c.residual)/maxResidual>.62?s.theme.bg:s.theme.fg,'font-size':s.fs-2},Math.max(4,Math.floor(w/(s.fs*.7))));s.reveal(txt,.35+i*.06+j*.035,.45);if(h>39){const count=num(s,xx+w/2,yy+h/2+13,raw(c.row.count),{'text-anchor':'middle',fill:Math.abs(c.residual)/maxResidual>.62?s.theme.bg:s.theme.fg,'font-size':s.fs-3});s.reveal(count,.35+i*.06+j*.035,.45);}}
  });
 });
 label(s,left,14,t14('深灰：高于期望 · 红：低于期望','Dark: observed > expected · red: observed < expected'),{'font-size':s.fs-2},s.compact?49:95);label(s,left,29,t14('面积：联合频数 · 色深：|Pearson 残差|','Area: joint count · intensity: |Pearson residual|'),{'font-size':s.fs-3},s.compact?46:95);label(s,right,s.h-1,`${doc.axes.x} × ${doc.axes.y} · N=${raw(m.total)}`,{'text-anchor':'end','font-size':s.fs-3},60);
}
export const volume14Renderers={andrews,biplot,taylor,targetdiagram,youden,agreement,association,mosaicplot};
