// Deterministic synthetic examples, not measurements or fitted forecasts.
const text=(key,label)=>[key,'string',label],number=(key,label)=>[key,'number',label],nullable=(key,label)=>[key,'number | null',label];
const timeFields=[text('period','按采集顺序排列的等间隔时期'),number('value','该时期的原始测量值')];
const specs=[
 ['pcontrol','不合格比例控制图','Variable-size p chart',[text('period','批次的采集顺序'),number('defectives','不合格件数，非负整数'),number('sampleSize','该批检查件数，正整数')],'按各批实际样本量绘制不同宽度的控制限，比较不合格比例。','不等批量抽检、制造质量与服务差错','混淆不合格件与缺陷数；将控制限当规格限','4–150 个批次；不合格件数不超过检查件数；unit 为 %'],
 ['ucontrol','单位缺陷率控制图','Variable-exposure u chart',[text('period','批次的采集顺序'),number('defects','缺陷事件数，非负整数'),number('exposure','同口径检查暴露量，正数')],'把缺陷数除以实际检查暴露量，显示随暴露量变化的泊松控制限。','每平方米缺陷、每工时故障与每件缺陷','把缺陷事件当不合格件；混用暴露量口径','4–150 个批次；exposure > 0；unit 明确为缺陷数 / 暴露单位'],
 ['cusum','双侧累积和控制图','Two-sided tabular CUSUM',timeFields,'围绕外部基线累计向上与向下的小偏移，区分两侧持续漂移。','稳定过程的小幅均值偏移监控','把监测期重估成基线；把阈值当显著性概率','4–300 个原始观测；提供基线 target、sigma，以及正的 referenceK、decisionH'],
 ['ewma','指数加权控制图','EWMA with startup limits',timeFields,'在原始测量之上显示指数加权轨迹，控制限从启动阶段逐步展开。','缓慢漂移监测、过程偏差与设备校准','自动拟合基线；把平滑轨迹当原始值','4–300 个观测；target 有限，sigma > 0，0 < lambda ≤ 1，limitSigma > 0'],
 ['xbar','子组均值与极差图','Subgroup X-bar and R',[text('period','子组采集时期，按首次出现排序'),text('sample','该子组内的样本标识'),number('value','每一个样本的原始测量值')],'均值与极差双面板保留每组原始点，区分过程水平变化与组内波动。','等样本量子组抽检、批次稳定性','子组大小不等；只输入均值；把控制限当规格限','3–60 个子组，每组相同的 2–10 个原始样本；至少一组极差非零'],
 ['lagplot','滞后散点图','Lagged observation plot',timeFields,'将每个当前观测与指定滞后的原观测配对，保留共同单位和真实时间顺序。','周期性、序列依赖与时序结构探索','将相关当因果；混用不等时间间隔','5–500 个非恒定等间隔原始观测；lag 为 1–60 且小于 n−1'],
 ['periodogram','周期功率谱','One-sided power spectrum',timeFields,'从等间隔原序列计算去均值、矩形窗的单边离散功率谱，定位周期能量。','振动频率、重复节律和周期探索','不等间隔采样；把泄漏峰当独立周期；混淆功率与功率密度','8–512 个非恒定观测；sampleInterval > 0；timeUnit 说明采样时间单位'],
 ['forecastfan','多层预测区间扇形图','Nested forecast fan',[text('period','先历史后预测的等间隔时期'),nullable('observed','历史真实值；预测期填 null'),nullable('median','预测中位数；历史期填 null'),...['50','80','95'].flatMap(level=>[nullable(`lower${level}`,`${level}% 中央预测区间下界；历史期填 null`),nullable(`upper${level}`,`${level}% 中央预测区间上界；历史期填 null`)])],'保留历史观测与外部模型给出的中位数、50% / 80% / 95% 中央预测区间。','业务预测汇报、需求区间与风险沟通','把区间当实际结果；混用不同模型或区间定义','3–60 个历史时期后接 2–40 个预测时期；每期区间完整且正确嵌套']
];
export const volume11Catalog=specs.map(([id,name,en,fields,description,use,avoid,limit],i)=>({id,no:String(121+i),name,en,type:name,category:'research',fields,description,use,avoid,limit,motion:'基准展开 / 原始轨迹推进 / 区间与异常显影',keywords:`${name} ${en} ${use}`,edition:11,research:true,dataMode:id==='forecastfan'?'analysis':'observations',duration:8}));
const raw=Array.from({length:36},(_,i)=>({period:String(i+1),value:+(50+Math.sin(i*1.9)*.9+Math.cos(i*.81)*.55+(i>19?(i-19)*.13:0)).toFixed(3)}));
const forecastFields=['median','lower50','upper50','lower80','upper80','lower95','upper95'];
export const volume11Contents={
 pcontrol:{title:'批次不合格比例',subtitle:'合成抽检 · 加权基线 · 按实际样本量计算 3σ 控制限',unit:'%',data:Array.from({length:26},(_,i)=>{const sampleSize=[120,180,240,150,210][i%5];return{period:String(i+1),sampleSize,defectives:Math.round(sampleSize*(.075+Math.sin(i*1.8)*.026+(i===18?.12:0)))};})},
 ucontrol:{title:'表面检查缺陷率',subtitle:'合成检查 · 泊松假设 · 暴露量不同，控制限不同',unit:'defects / m²',data:Array.from({length:24},(_,i)=>{const exposure=[8,12,18,10,15,20][i%6];return{period:String(i+1),exposure,defects:Math.round(exposure*(2.3+Math.sin(i*1.6)*.44+(i===17?2.2:0)))};})},
 cusum:{title:'微小过程偏移监测',subtitle:'合成测量 · 独立基线 · 下侧累积量以负值显示',unit:'mm',target:50,sigma:1,referenceK:.5,decisionH:5,data:raw},
 ewma:{title:'渐进漂移监测',subtitle:'合成测量 · λ=0.25 · 启动期有限样本控制限',unit:'mm',target:50,sigma:1,lambda:.25,limitSigma:3,data:raw},
 xbar:{title:'子组水平与组内波动',subtitle:'合成等样本量抽检 · 原始值保留 · 基线来自全部子组',unit:'mm',data:Array.from({length:18},(_,i)=>Array.from({length:5},(_,j)=>({period:String(i+1),sample:`S${j+1}`,value:+(25+Math.sin(i*.79)*.17+Math.sin(j*1.7+i*2.3)*.7+(i===13?.85:0)).toFixed(3)}))).flat()},
 lagplot:{title:'相邻周期的关联结构',subtitle:'确定性合成序列 · lag=2 · 两轴同单位、等比例',unit:'kPa',lag:2,data:Array.from({length:64},(_,i)=>({period:String(i+1),value:+(20+4*Math.sin(i*Math.PI/8)+.55*Math.cos(i*1.8)).toFixed(4)}))},
 periodogram:{title:'周期能量分解',subtitle:'确定性合成序列 · 去均值 · 矩形窗 · 单边每频点功率',unit:'V',sampleInterval:.5,timeUnit:'s',data:Array.from({length:96},(_,i)=>({period:String(i+1),value:3*Math.sin(2*Math.PI*i/12)+1.2*Math.cos(2*Math.PI*i/6)+.35*Math.sin(2*Math.PI*i/32)}))},
 forecastfan:{title:'需求预测的不确定范围',subtitle:'合成演示区间 · 输入外部预测结果，不在图内拟合模型',unit:'units',data:[...Array.from({length:16},(_,i)=>({period:`W${i+1}`,observed:+(85+i*1.55+Math.sin(i*.9)*5).toFixed(2),...Object.fromEntries(forecastFields.map(k=>[k,null]))})),...Array.from({length:14},(_,i)=>{const median=110+i*1.8,spread=4+Math.sqrt(i+1)*3;return{period:`W${i+17}`,observed:null,median,lower50:median-spread*.67,upper50:median+spread*.67,lower80:median-spread*1.28,upper80:median+spread*1.28,lower95:median-spread*1.96,upper95:median+spread*1.96};})]}
};
const timeFieldsEN=[text('period','Equally spaced acquisition period, in input order'),number('value','Original measurement at this period')];
export const volume11English={
 pcontrol:{description:'Each batch retains its own sample size and binomial three-sigma limits. The baseline is weighted by inspected units.',use:'Unequal-batch inspection and nonconforming-item monitoring',avoid:'Confusing nonconforming items with individual defects or specification limits',limit:'4–150 batches; integer 0 ≤ defectives ≤ sampleSize, sampleSize > 0; unit must be %.',rowMeaning:'One row is one batch with the original count of nonconforming items and total inspected units.',fields:[text('period','Batch in acquisition order'),number('defectives','Nonnegative integer count of nonconforming items'),number('sampleSize','Positive integer number of inspected units')]},
 ucontrol:{description:'Defect counts are divided by actual exposure. Poisson control limits vary with each exposure rather than an average batch size.',use:'Surface defects, failures per operating hour and defects per unit',avoid:'Mixing exposure units or treating defect events as defective items',limit:'4–150 batches; integer defects ≥ 0 and exposure > 0. Declare defects per exposure unit.',rowMeaning:'One row is the original defect-event count and the inspected exposure, all measured using the same denominator unit.',fields:[text('period','Batch in acquisition order'),number('defects','Nonnegative integer count of defect events'),number('exposure','Positive inspection exposure, using one common unit')]},
 cusum:{description:'Standardized upper and lower tabular cumulative sums detect sustained shifts from a supplied baseline. Lower sums are displayed with a minus sign.',use:'Monitoring small process-mean shifts against a historical baseline',avoid:'Refitting the baseline from monitoring data or reading thresholds as p-values',limit:'4–300 measurements; finite target, positive sigma, referenceK and decisionH.',rowMeaning:'Each row is one original individual measurement. target and sigma describe an independently established in-control baseline; referenceK and decisionH are dimensionless sigma units.',fields:timeFieldsEN},
 ewma:{description:'Raw measurements accompany an exponentially weighted trace. Finite-startup limits widen from the supplied in-control target.',use:'Gradual process drift and calibration monitoring',avoid:'Automatically estimating the baseline or presenting weighted values as raw observations',limit:'4–300 observations; finite target, sigma > 0, 0 < lambda ≤ 1 and limitSigma > 0.',rowMeaning:'Each row is one original individual measurement. target and sigma come from a historical baseline, lambda is the weight of the current value, and limitSigma is the limit multiplier.',fields:timeFieldsEN},
 xbar:{description:'Aligned panels show subgroup means and ranges, with every original measurement retained beside its mean. Limits use the common subgroup size.',use:'Equal-size subgroup inspection and process stability',avoid:'Unequal subgroup sizes, pre-aggregated means or confusing control and specification limits',limit:'3–60 subgroups with the same 2–10 measurements each; at least one nonzero range.',rowMeaning:'Each row is one original measurement in a subgroup identified by period; sample must be unique within that subgroup. Subgroups follow first appearance.',fields:[text('period','Subgroup period, ordered by first appearance'),text('sample','Unique sample identifier within this subgroup'),number('value','Original individual measurement')]},
 lagplot:{description:'Current observations are paired with their lagged values. Both axes preserve the original unit with equal geometric scales.',use:'Serial-dependence and periodicity exploration',avoid:'Inferring causality or using irregularly spaced measurements',limit:'5–500 nonconstant observations; integer lag is 1–60 and less than n−1.',rowMeaning:'Each row is one original equally spaced observation. Point t pairs value[t−lag] on X with value[t] on Y; no pairs are imputed.',fields:timeFieldsEN},
 periodogram:{description:'A mean-centered rectangular-window DFT produces a one-sided power spectrum. Frequency-bin power sums to the population variance.',use:'Oscillation frequencies and repeated temporal patterns',avoid:'Irregular sampling, interpreting leakage as separate cycles or confusing power and power density',limit:'8–512 nonconstant observations; sampleInterval > 0 and a declared timeUnit.',rowMeaning:'Each row is one raw equally spaced sample. sampleInterval is elapsed time between samples in timeUnit; unit is the measured signal unit. The output uses squared signal units per frequency bin.',fields:timeFieldsEN},
 forecastfan:{description:'Observed history leads into externally supplied median forecasts and nested central 50%, 80% and 95% prediction intervals.',use:'Forecast reporting, demand uncertainty and risk communication',avoid:'Treating prediction intervals as observations or mixing models and interval definitions',limit:'3–60 historical periods followed by 2–40 forecast periods; complete nested interval fields.',rowMeaning:'Historical rows contain observed only and null for all forecast fields. Future rows contain null observed and all seven forecast fields from the same model and forecast origin.',fields:[text('period','Equally spaced period: all history first, then forecasts'),nullable('observed','Historical observation; null in forecast periods'),nullable('median','Forecast median; null in historical periods'),...['50','80','95'].flatMap(level=>[nullable(`lower${level}`,`Lower bound of the central ${level}% prediction interval; null in history`),nullable(`upper${level}`,`Upper bound of the central ${level}% prediction interval; null in history`)])]}
};
