// Scientific templates accept observations or explicit analysis results; no synthetic inference.
const f=(key,type,label)=>[key,type,label], n=(key,label)=>f(key,'number',label), str=(key,label)=>f(key,'string',label);
const label=str('label','唯一样本 / 对象'),group=str('group','分组'),value=n('value','观测值');
const prediction=[label,str('model','模型'),n('actual','真实类别：0 或 1'),n('score','正类得分，越大越可能为正类')];
const specs=[
  ['errorbar','原始散点误差图','Raw points & SD',[label,group,value],'observations','原始样本、均值与样本标准差同时呈现。','实验分组、重复测量汇总','把 SD 当成置信区间；混合技术与生物学重复','样本落位 / 误差范围展开','误差棒 均值 标准差 SD','2–5 组，每组 3–60 个独立样本；label 唯一'],
  ['paired','配对散点图','Paired observations',[label,n('before','第一次观测'),n('after','第二次观测')],'observations','同一对象的两次观测由细线连接，保留个体差异。','干预前后、重复观测','未配对的两组数据；把连线当成因果证据','起点显现 / 配对连线 / 终点落位','配对 前后 paired','6–50 个唯一样本；pairLabels 明确两次观测'],
  ['regression','回归散点图','Linear regression',[label,n('x','自变量'),n('y','响应变量')],'observations','最小二乘直线与均值响应的 95% 置信带。','线性关系、实验标定','非线性数据；把置信带当成个体预测区间','样本显现 / 回归描线 / 置信带展开','回归 线性 regression confidence','4–300 个独立观测；x 具有变异；axes.x/y 明确量纲'],
  ['blandaltman','一致性分析图','Bland–Altman',[label,n('a','方法 A 测量'),n('b','方法 B 测量')],'observations','横轴为两方法均值，纵轴为 A−B；展示偏倚与一致性界限。','测量方法比较、仪器一致性','把高相关当成一致；重复样本不独立','配对定位 / 偏倚线 / 界限延展','一致性 Bland Altman','6–200 对测量；相同单位；methodLabels 指明方法'],
  ['forest','森林图','Forest plot',[label,n('estimate','比值效应估计'),n('lower','区间下界'),n('upper','区间上界'),n('n','研究样本量')],'analysis','在共同对数轴展示比值效应及已计算的置信区间。','研究效应比较、亚组结果','把样本量当成逆方差权重；由图自动合并效应','参考线建立 / 区间展开 / 估计点落位','森林 比值 效应 forest','4–12 项；0 < lower ≤ estimate ≤ upper；n 为正整数；intervalLabel 注明区间'],
  ['volcano','火山图','Volcano plot',[label,n('log2FC','log₂ 倍数变化'),n('padj','已校正的 p 值')],'analysis','用倍数变化与 −log₁₀ 校正 p 值呈现差异分析结果。','差异表达、差异蛋白筛选','使用未经校正的 p 值冒充 padj；由均值生成显著性','散点展开 / 阈值显现 / 候选标记','火山 差异表达 volcano','20–1000 个唯一对象；0 < padj ≤ 1；qThreshold 与 fcThreshold 明确阈值'],
  ['ma','MA 图','MA plot',[label,n('mean','标准化平均表达量'),n('log2FC','log₂ 倍数变化'),n('padj','已校正的 p 值')],'analysis','对数平均表达量与 log₂ 倍数变化的联合分布。','表达量依赖效应、差异分析检查','把原始计数当成标准化表达量；省略低表达不确定性','表达量落位 / 零线建立 / 候选显现','MA 表达量 log fold change','20–1000 个唯一对象；mean > 0，0 < padj ≤ 1'],
  ['pca','PCA 得分图','PCA scores',[label,group,n('pc1','第一主成分得分'),n('pc2','第二主成分得分')],'analysis','以输入的 PCA 得分定位样本，轴标题注明解释方差。','样本结构、批次效应、降维检查','把二维距离视作原始空间距离；从组标签推断显著性','坐标建立 / 分组样本落位','PCA 主成分 得分 降维','8–300 个样本，1–5 组；pc1Variance + pc2Variance ≤ 100；输入已计算得分'],
  ['roc','ROC 曲线','Receiver operating characteristic',prediction,'observations','按得分阈值计算真阳性率与假阳性率，保留得分并列。','二分类判别能力、模型比较','仅有类别预测没有得分；混用训练集与测试集','对角线建立 / 阈值推进 / AUC 显现','ROC AUC 二分类','每模型 8–300 样本，1–3 模型；同一批样本含正负类'],
  ['precisionrecall','PR 曲线','Precision–recall',prediction,'observations','展示不同阈值下的精确率与召回率，计算非插值 AP。','少数正类识别、检索评估','把 AP 当成梯形积分；忽略正类比例','基准线建立 / 阶梯展开 / AP 显现','PR AP 精确率 召回率','每模型 8–300 样本，1–3 模型；同一批样本含正负类'],
  ['confusion','混淆矩阵','Confusion matrix',[str('actual','真实类别'),str('predicted','预测类别'),n('count','样本数')],'counts','行表示真实类别，列表示预测类别；颜色和数字表示计数。','分类错误分布、多类别评估','转置真实与预测；把缺失格默认为零','矩阵建立 / 计数逐格显现','混淆 矩阵 分类 confusion','2–6 类，完整方阵；非负整数，每行总量大于零'],
  ['calibration','校准曲线','Calibration curve',prediction,'observations','等宽概率分箱，对比平均预测概率与实际正类比例。','概率可靠性、预测风险校准','只凭校准图判断判别能力；空分箱补零','概率区间建立 / 分箱点连线','校准 概率 calibration reliability','每模型 8–300 样本；score 在 0–1；bins 为 3–12'],
  ['residual','残差图','Residual plot',[label,n('observed','观测值'),n('predicted','预测值')],'observations','残差定义为观测值减预测值，围绕零线检查结构。','模型诊断、异方差与异常点','将残差的平滑趋势自动解释为因果关系','零线建立 / 残差落位','残差 诊断 residual','8–300 个独立样本；观测值与预测值同单位'],
  ['dose','剂量响应图','Dose–response',[label,n('dose','正剂量'),value],'observations','对数剂量轴上的原始重复、均值与样本标准差。','浓度实验、剂量响应初步检查','把均值连线当作拟合模型；从图读取未经拟合的 IC50','剂量展开 / 重复落位 / 均值连线','剂量 响应 浓度 dose response','4–12 个正剂量，每剂量 3–30 次重复；doseUnit 明确单位'],
  ['learning','学习曲线','Learning curves',[n('epoch','训练轮次'),f('train','number | null','训练集损失'),f('validation','number | null','验证集损失')],'observations','训练与验证损失共用坐标，缺失位置保留断点。','训练监控、过拟合检查','不同损失函数混用；将测试集作为验证集反复调参','训练描线 / 验证跟进','学习 训练 验证 loss learning','6–120 个递增整数轮次；非负损失；缺失填 null'],
  ['scree','碎石图','Scree plot',[str('component','主成分'),n('eigenvalue','特征值')],'analysis','将特征值换算为解释方差比例，以柱高和折线呈现。','主成分保留、降维解释度','仅输入截断的前几项却当成全部解释方差','柱高建立 / 碎石线连接','碎石 特征值 方差 scree','3–16 个按特征值降序排列的全部主成分；非负，总和大于零'],
  ['enrichment','富集气泡图','Enrichment dot plot',[label,n('count','命中基因数'),n('total','该次分析输入基因总数'),n('padj','已校正的 p 值')],'analysis','横轴为命中比例，面积为命中数，色深为 −log₁₀ 校正 p 值。','通路与基因集富集结果','用气泡图替代富集检验；把色深当成效应量','比例落位 / 面积生长 / 色阶显现','富集 基因集 通路 enrichment','5–12 项；0 < count ≤ total，整数；0 < padj ≤ 1'],
  ['upset','UpSet 集合图','UpSet intersections',[str('members','所属集合，用 | 分隔'),n('count','排他交集的元素数')],'counts','柱高展示排他交集大小，下方点阵标出集合组合。','多组基因交集、集合重叠','将包含更多集合的元素重复计入较小交集','交集柱升起 / 成员矩阵连线','UpSet 集合 交集 upset','sets 明确 2–5 集合；4–20 个唯一非空排他交集；正整数计数'],
  ['manhattan','曼哈顿图','Manhattan plot',[label,str('chromosome','染色体'),n('position','染色体内位置 / bp'),n('pvalue','未校正的 p 值')],'analysis','按染色体物理位置排列关联结果，纵轴为 −log₁₀ p。','全基因组关联结果、位点筛查','把图中阈值当作所有研究通用标准；p=0 直接取对数','染色体分区 / 位点升起 / 阈值延展','曼哈顿 GWAS 染色体 manhattan','20–1000 个位点；chromosomes 注明名称与长度；0 < pvalue ≤ 1'],
  ['metafunnel','研究漏斗图','Study funnel plot',[label,n('effect','研究效应值'),n('se','效应标准误')],'analysis','以输入参考效应为中心，展示效应值与标准误的关系。','研究结果分布、小样本效应探索','单凭不对称断定发表偏倚；将参考中心当成自动合并效应','漏斗边界建立 / 研究落位','漏斗 研究 meta 标准误 funnel','6–100 个研究；se > 0；referenceEffect 明确参考效应；对数比值须预先变换']
];
export const volume8Catalog=specs.map(([id,name,en,fields,dataMode,description,use,avoid,motion,keywords,limit],i)=>({id,no:String(81+i),name,en,type:name,category:'research',fields,dataMode,description,use,avoid,motion,keywords:`科研 统计 scientific ${keywords}`,limit,edition:8,duration:8}));
const round=x=>+x.toFixed(4), series=(n,fn)=>Array.from({length:n},(_,i)=>fn(i));
const assay=series(48,i=>({label:`S${String(i+1).padStart(2,'0')}`,group:['对照','处理 A','处理 B'][i%3],value:round(28+Math.floor(i%3)*9+Math.sin(i*2.399)*7+Math.cos(i*.65)*4)}));
const models=['模型 A','模型 B'], predictionData=models.flatMap((model,j)=>series(72,i=>{const actual=(i*17%23)<9?1:0;return{label:`S${i+1}`,model,actual,score:round(Math.max(.01,Math.min(.99,.18+actual*.48+Math.sin(i*2.399+j)*(.26+j*.1)+Math.cos(i*.3)*.12)))};}));
const differential=series(210,i=>{const log2FC=round(Math.sin(i*2.399)*(i%7===0?3.4:1.6)),padj=round(0.04+((i*31%101)/101)*.95);return{label:`GENE${i+1}`,log2FC,padj:i%7===0?10**(-2-(i%6)*.6):padj};});
export const volume8Contents={
  errorbar:{title:'实验组响应分布',subtitle:'原始样本 · 均值 ± 样本标准差',unit:'a.u.',data:assay},
  paired:{title:'干预前后测量',subtitle:'同一样本配对 · 连线保留个体差异',unit:'分',pairLabels:['干预前','干预后'],data:series(20,i=>({label:`S${i+1}`,before:round(40+i*.9+Math.sin(i*2.399)*10),after:round(53+i*.9+Math.cos(i*2.399)*9)}))},
  regression:{title:'标定数据线性回归',subtitle:'OLS · 均值响应 95% 置信带',unit:'原始量纲',axes:{x:'浓度 / μg·mL⁻¹',y:'吸光度 / a.u.'},data:series(42,i=>({label:`S${i+1}`,x:round(1+i*.3),y:round(.2+i*.075+Math.sin(i*2.399)*.36)}))},
  blandaltman:{title:'两种方法测量一致性',subtitle:'差值 A−B · 偏倚 ± 1.96 SD',unit:'mg/L',methodLabels:['方法 A','方法 B'],data:series(36,i=>({label:`S${i+1}`,a:round(20+i*2+Math.sin(i)*4),b:round(18+i*2+Math.cos(i*2.399)*5)}))},
  forest:{title:'研究效应与置信区间',subtitle:'比值效应 · 对数尺度 · 区间为输入结果',unit:'风险比 RR',intervalLabel:'95% 置信区间',data:series(7,i=>{const estimate=round(.64+i*.085+Math.sin(i)*.12),spread=.17+(i%3)*.065;return{label:`研究 ${String.fromCharCode(65+i)}`,estimate,lower:round(estimate*Math.exp(-spread)),upper:round(estimate*Math.exp(spread)),n:80+i*37};})},
  volcano:{title:'差异表达筛选',subtitle:'输入差异分析结果 · 标记通过预设阈值的对象',unit:'分析结果',qThreshold:.05,fcThreshold:1,data:differential},
  ma:{title:'表达量与倍数变化',subtitle:'标准化均值 · 校正 p 值筛选',unit:'分析结果',qThreshold:.05,data:differential.map((r,i)=>({...r,mean:round(10**(1+(i*17%100)/24))}))},
  pca:{title:'样本主成分得分',subtitle:'输入 PCA 得分 · 标记形状区分分组',unit:'主成分得分',pc1Variance:42.6,pc2Variance:21.3,data:series(48,i=>({label:`S${i+1}`,group:['对照','处理 A','处理 B'][i%3],pc1:round([-3,2.8,.3][i%3]+Math.sin(i*2.399)*1.35+Math.cos(i*.47)*.7),pc2:round([-.6,-1.3,3][i%3]+Math.cos(i*2.399)*.95+Math.sin(i*.73)*.65)}))},
  roc:{title:'二分类模型 ROC',subtitle:'同一测试集 · 正类为 1 · 得分并列共同处理',unit:'比例',positiveLabel:'正类 1',data:predictionData},
  precisionrecall:{title:'二分类模型精确率与召回率',subtitle:'同一测试集 · AP 按召回增量加权',unit:'比例',positiveLabel:'正类 1',data:predictionData},
  confusion:{title:'分类预测混淆矩阵',subtitle:'行：真实类别 · 列：预测类别',unit:'个样本',data:['A 类','B 类','C 类','D 类'].flatMap((actual,i)=>['A 类','B 类','C 类','D 类'].map((predicted,j)=>({actual,predicted,count:i===j?[86,73,79,68][i]:[3,8,5,6][(i+j)%4]})))},
  calibration:{title:'预测概率校准',subtitle:'等宽分箱 · 空箱保留断点 · 提示含样本数',unit:'概率',positiveLabel:'正类 1',bins:6,data:predictionData},
  residual:{title:'预测模型残差',subtitle:'残差 = 观测 − 预测',unit:'mg/L',data:series(54,i=>{const predicted=round(15+i*.8);return{label:`S${i+1}`,predicted,observed:round(predicted+Math.sin(i*2.399)*(2+i*.05)+Math.cos(i*.5))};})},
  dose:{title:'浓度与实验响应',subtitle:'原始重复 · 均值 ± SD · 连线连接剂量均值',unit:'响应 / %',doseUnit:'μmol/L',data:[.01,.03,.1,.3,1,3,10,30].flatMap((dose,j)=>series(6,i=>({label:`D${j+1}-${i+1}`,dose,value:round(12+80/(1+(dose/1.4)**.85)+Math.sin((j*6+i)*2.399)*4.8)})))},
  learning:{title:'训练与验证损失',subtitle:'共同损失尺度 · 未记录轮次保留断点',unit:'交叉熵',data:series(40,i=>({epoch:i+1,train:round(.16+1.2*Math.exp(-i/9)+Math.sin(i)*.017),validation:i===18?null:round(.3+1.06*Math.exp(-i/8)+Math.max(0,i-22)*.013+Math.cos(i)*.022)}))},
  scree:{title:'主成分解释方差',subtitle:'输入全部特征值 · 比例合计 100%',unit:'%',data:[5.3,2.7,1.65,1.1,.72,.51,.35,.25,.17,.1].map((eigenvalue,i)=>({component:`PC${i+1}`,eigenvalue}))},
  enrichment:{title:'通路富集结果',subtitle:'比例 × 命中数 × 校正 p 值',unit:'分析结果',data:['信号转导','细胞周期','氧化应激','能量代谢','DNA 修复','蛋白转运','细胞黏附','免疫应答'].map((label,i)=>({label,count:42-i*4,total:180,padj:10**(-7+i*.62)}))},
  upset:{title:'基因集合排他交集',subtitle:'每个元素只属于一个交集组合',unit:'个基因',sets:['实验 A','实验 B','实验 C','实验 D'],data:[['实验 A',92],['实验 B',81],['实验 C',66],['实验 D',48],['实验 A|实验 B',53],['实验 B|实验 C',38],['实验 A|实验 C|实验 D',27],['实验 A|实验 B|实验 C|实验 D',19],['实验 C|实验 D',31],['实验 B|实验 D',22]].map(([members,count])=>({members,count}))},
  manhattan:{title:'基因组关联结果',subtitle:'物理位置 · 阈值按当前设置',unit:'分析结果',threshold:5e-8,chromosomes:[{name:'1',length:240000000},{name:'2',length:220000000},{name:'3',length:190000000},{name:'4',length:180000000}],data:series(200,i=>({label:`rs${10000+i}`,chromosome:String(Math.floor(i/50)+1),position:Math.round((i%50+1)/51*[240e6,220e6,190e6,180e6][Math.floor(i/50)]),pvalue:10**(-(0.3+(i*37%59)/13+(Math.abs(i-73)<5?5-Math.abs(i-73)*.55:0)+(Math.abs(i-157)<4?5.2-Math.abs(i-157)*.65:0)))}))},
  metafunnel:{title:'研究效应与标准误',subtitle:'输入参考效应 · 虚线范围为参考 ± 1.96 SE',unit:'对数风险比',referenceEffect:-.18,data:series(32,i=>{const se=.045+(i*17%31)/95;return{label:`研究 ${i+1}`,se:round(se),effect:round(-.18+Math.sin(i*2.399)*se*1.65)};})}
};
