import {uiText,uiMarkup,uiMessage} from './locale.js';
import {formatDecimal} from './number-format.js';
import * as d3 from 'd3';
import { volume8Catalog } from './volume8-catalog.js';
export const unique8=values=>[...new Set(values)];
const ids=new Set(volume8Catalog.map(t=>t.id)), finite=Number.isFinite, text=v=>typeof v==='string'&&v.trim().length>0&&v.length<=80;
const key=(...parts)=>JSON.stringify(parts), integer=v=>Number.isSafeInteger(v), probability=v=>finite(v)&&v>0&&v<=1;

// Lanczos log-gamma and the continued-fraction incomplete beta give Student t
// critical values without a large table or replacing small-sample t with z.
function logGamma(z){const c=[676.5203681218851,-1259.1392167224028,771.32342877765313,-176.61502916214059,12.507343278686905,-.13857109526572012,9.9843695780195716e-6,1.5056327351493116e-7];if(z<.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*z))-logGamma(1-z);z--;let x=.99999999999980993;for(let i=0;i<c.length;i++)x+=c[i]/(z+i+1);const t=z+c.length-.5;return .5*Math.log(2*Math.PI)+(z+.5)*Math.log(t)-t+Math.log(x);}
function betaFraction(a,b,x){const tiny=1e-30,safe=v=>Math.abs(v)<tiny?tiny:v;let c=1,d=1/safe(1-(a+b)*x/(a+1)),h=d;for(let m=1;m<=220;m++){const m2=2*m;let aa=m*(b-m)*x/((a+m2-1)*(a+m2));d=1/safe(1+aa*d);c=safe(1+aa/c);h*=d*c;aa=-(a+m)*(a+b+m)*x/((a+m2)*(a+m2+1));d=1/safe(1+aa*d);c=safe(1+aa/c);const delta=d*c;h*=delta;if(Math.abs(delta-1)<3e-14)break;}return h;}
function betaI(x,a,b){if(x<=0)return 0;if(x>=1)return 1;const bt=Math.exp(logGamma(a+b)-logGamma(a)-logGamma(b)+a*Math.log(x)+b*Math.log1p(-x));return x<(a+1)/(a+b+2)?bt*betaFraction(a,b,x)/a:1-bt*betaFraction(b,a,1-x)/b;}
export function studentT975(df){if(!integer(df)||df<1)throw new RangeError('Positive integer degrees of freedom required');let lo=0,hi=16;for(let i=0;i<64;i++){const mid=(lo+hi)/2,cdf=1-.5*betaI(df/(df+mid*mid),df/2,.5);if(cdf<.975)lo=mid;else hi=mid;}return(lo+hi)/2;}
export function linearFit(rows){
  const n=rows.length,mx=d3.mean(rows,d=>d.x),my=d3.mean(rows,d=>d.y);
  const sx=d3.max(rows,d=>Math.abs(d.x-mx)),sy=d3.max(rows,d=>Math.abs(d.y-my))||1;
  const points=rows.map(d=>({x:(d.x-mx)/sx,y:(d.y-my)/sy}));
  const xx=d3.sum(points,d=>d.x*d.x),yy=d3.sum(points,d=>d.y*d.y),beta=d3.sum(points,d=>d.x*d.y)/xx;
  const slope=beta*sy/sx,intercept=my-slope*mx,predict=x=>my+beta*((x-mx)/sx)*sy;
  const sse=d3.sum(points,d=>(d.y-beta*d.x)**2),sd=Math.sqrt(sse/(n-2))*sy,critical=studentT975(n-2);
  return{n,mx,my,sxx:xx*sx*sx,slope,intercept,sd,critical,r2:yy>0?Math.max(0,1-sse/yy):null,predict,
    interval(x){const center=predict(x),margin=critical*sd*Math.sqrt(1/n+((x-mx)/sx)**2/xx);return{x,center,lower:center-margin,upper:center+margin};}};
}
export function blandAltman(rows){const points=rows.map(d=>({...d,mean:(d.a+d.b)/2,difference:d.a-d.b})),bias=d3.mean(points,d=>d.difference),sd=d3.deviation(points,d=>d.difference);return{points,bias,sd,lower:bias-1.96*sd,upper:bias+1.96*sd};}
export function groupStats(rows,field='group'){return d3.groups(rows,d=>d[field]).map(([name,items])=>({name,rows:items,n:items.length,mean:d3.mean(items,d=>d.value),sd:d3.deviation(items,d=>d.value)||0}));}
export function classificationCurve(rows){const positives=d3.sum(rows,d=>d.actual),negatives=rows.length-positives,groups=d3.groups(rows,d=>d.score).sort((a,b)=>b[0]-a[0]);let tp=0,fp=0,auc=0,ap=0,oldFpr=0,oldTpr=0;const points=[{threshold:null,fpr:0,tpr:0,recall:0,precision:1,tp:0,fp:0}];for(const [threshold,own]of groups){tp+=d3.sum(own,d=>d.actual);fp+=own.length-d3.sum(own,d=>d.actual);const tpr=tp/positives,fpr=fp/negatives,precision=tp/(tp+fp);auc+=(fpr-oldFpr)*(tpr+oldTpr)/2;ap+=(tpr-oldTpr)*precision;points.push({threshold,fpr,tpr,recall:tpr,precision,tp,fp});oldFpr=fpr;oldTpr=tpr;}return{points,auc,ap,positives,negatives,prevalence:positives/rows.length,n:rows.length};}
// Fixed equal-width bins; an unobserved bin stays null, never a fabricated zero.
export function calibrationBins(rows,bins=6){return Array.from({length:bins},(_,index)=>{const own=rows.filter(r=>Math.min(bins-1,Math.floor(r.score*bins))===index);return own.length?{index,lower:index/bins,upper:(index+1)/bins,n:own.length,probability:d3.mean(own,d=>d.score),frequency:d3.mean(own,d=>d.actual)}:null;});}
export function upsetLayout(doc){const intersections=doc.data.map(d=>({...d,members:d.members.split('|'),value:d.count})).sort((a,b)=>b.count-a.count);return{intersections,total:d3.sum(intersections,d=>d.count),sets:doc.sets.map(name=>({name,count:d3.sum(intersections.filter(d=>d.members.includes(name)),d=>d.count)}))};}
export function manhattanLayout(doc){const gap=d3.sum(doc.chromosomes,d=>d.length)*.012;let cursor=0;const chromosomes=doc.chromosomes.map(d=>{const start=cursor;cursor+=d.length+gap;return{...d,start,end:start+d.length};}),lookup=new Map(chromosomes.map(d=>[d.name,d]));return{chromosomes,total:cursor-gap,points:doc.data.map(d=>({...d,x:lookup.get(d.chromosome).start+d.position,y:-Math.log10(d.pvalue)}))};}

export function validateVolume8(doc,{fail,count,noDuplicates,positive,warnings}){
  const id=doc.template;if(!ids.has(id))return;const rows=doc.data,u=k=>unique8(rows.map(d=>d[k]));
  const axes=()=>{if(!text(doc.axes?.x)||!text(doc.axes?.y))fail(uiText('axes.x 和 axes.y 需要明确指标名称与单位。'));};
  const names=(field,len)=>{if(!Array.isArray(doc[field])||doc[field].length!==len||doc[field].some(d=>!text(d))||unique8(doc[field]).length!==len)fail(uiMessage`${field} 需要 ${len} 个不同的有效名称。`);};
  if(rows[0].label!==undefined&&!['roc','precisionrecall','calibration'].includes(id))noDuplicates(rows.map(d=>d.label),uiText('样本 / 对象名称'));
  if(id==='errorbar'){count(u('group').length,2,5,uiText('实验分组'));u('group').forEach(g=>count(rows.filter(d=>d.group===g).length,3,60,uiText('每组样本')));warnings.push(uiText('误差棒为均值 ± 样本标准差（SD，分母 n−1），不是 SEM 或置信区间。请保证独立重复，原始点全部保留。'));}
  if(id==='paired'){count(rows.length,6,50,uiText('配对样本'));names('pairLabels',2);warnings.push(uiText('一行是一对来自同一对象的观测；未执行配对检验，不生成 p 值。'));}
  if(id==='regression'){count(rows.length,4,300,uiText('独立观测'));axes();if(rows.every(d=>d.x===rows[0].x))fail(uiText('x 需要非零变异；所有观测的 x 不能相同。'));else if(rows.length>=4){const fit=linearFit(rows);if(![fit.slope,fit.intercept,fit.sd].every(finite))fail(uiText('数值尺度不适合稳定回归，请先换算单位。'));}warnings.push(uiText('OLS 与逐点均值响应 95% 置信带，使用 t(n−2)。假设独立、线性、同方差与正态误差；不是个体预测区间或同时置信带。R² 不表示因果关系。'));}
  if(id==='blandaltman'){count(rows.length,6,200,uiText('配对测量'));names('methodLabels',2);warnings.push(uiText('差值为 A−B。一致性界限 = 平均差 ± 1.96×样本 SD，依赖独立、近似正态且方差稳定的差值；界限本身的置信区间未计算。'));}
  if(id==='forest'){count(rows.length,4,12,uiText('研究'));if(rows.some(d=>d.lower<=0||d.lower>d.estimate||d.estimate>d.upper||!integer(d.n)||d.n<=0))fail(uiText('需要 0 < lower ≤ estimate ≤ upper，n 为正整数。'));if(!text(doc.intervalLabel))fail(uiText('intervalLabel 需要说明输入置信区间的水平与定义。'));warnings.push(uiText('按输入顺序展示；方形标记大小一致，n 仅为样本量，不代表逆方差权重。参考线为比值 1，不自动合并效应。'));}
  if(['volcano','ma','enrichment'].includes(id)){if(rows.some(d=>!probability(d.padj)))fail(uiText('padj 必须在 (0, 1]；缺失或下溢为 0 的结果请先在分析流程处理。'));warnings.push(uiText('padj 为外部统计分析得到的多重检验校正 p 值；本模板不执行差异或富集检验。'));}
  if(['volcano','ma'].includes(id)){count(rows.length,20,1000,uiText('对象'));if(!probability(doc.qThreshold))fail(uiText('qThreshold 必须在 (0, 1]。'));if(id==='volcano'&&(!finite(doc.fcThreshold)||doc.fcThreshold<=0||doc.fcThreshold>1e6))fail(uiText('fcThreshold 必须为正数且不超过 10⁶。'));if(id==='ma')positive('mean');}
  if(id==='pca'){count(rows.length,8,300,uiText('样本'));count(u('group').length,1,5,uiText('分组'));if(![doc.pc1Variance,doc.pc2Variance].every(v=>finite(v)&&v>0&&v<=100)||doc.pc1Variance+doc.pc2Variance>100+1e-8)fail(uiText('pc1Variance 与 pc2Variance 为正百分比，合计不超过 100。'));warnings.push(uiText('输入已计算的主成分得分；这里不重新执行标准化或 PCA，不绘制未经计算的组置信椭圆。'));}
  if(['roc','precisionrecall','calibration'].includes(id)){
    count(u('model').length,1,3,uiText('模型'));noDuplicates(rows.map(d=>key(d.model,d.label)),uiText('同模型同样本'));if(rows.some(d=>![0,1].includes(d.actual)))fail(uiText('actual 必须为二分类标签 0 或 1。'));if(!text(doc.positiveLabel))fail(uiText('positiveLabel 需要说明正类 1 的含义。'));const models=u('model'),first=rows.filter(d=>d.model===models[0]),truth=new Map(first.map(d=>[d.label,d.actual]));
    for(const model of models){const own=rows.filter(d=>d.model===model);count(own.length,8,300,uiText('每模型样本'));if(!own.some(d=>d.actual===0)||!own.some(d=>d.actual===1))fail(uiText('每个模型的评估样本必须同时含正类与负类。'));if(own.length!==first.length||own.some(d=>truth.get(d.label)!==d.actual))fail(uiText('模型比较需使用同一批样本与一致的真实标签。'));}
    if(id==='calibration'){if(rows.some(d=>d.score<0||d.score>1))fail(uiText('校准图的 score 必须为 [0, 1] 内的概率。'));if(!integer(doc.bins)||doc.bins<3||doc.bins>12)fail(uiText('bins 必须为 3–12 的整数。'));warnings.push(uiText('等宽概率分箱，区间左闭右开，最后一箱包含 1。空箱保留断点；每箱显示样本数，未估计分箱置信区间。'));}
    else warnings.push(uiText('得分越大越可能属于正类 1；同分样本共同进入阈值。请使用独立测试集。')+(id==='precisionrecall'?uiText('AP = Σ 召回增量 × 该阈值精确率，非梯形积分。'):uiText('AUC 使用 ROC 线段的梯形积分，未估计其置信区间。')));
  }
  if(id==='confusion'){const labels=u('actual');count(labels.length,2,6,uiText('类别'));if(u('predicted').length!==labels.length||rows.some(d=>!labels.includes(d.predicted))||rows.length!==labels.length**2)fail(uiText('需要真实类别 × 预测类别的完整方阵，零计数也须显式输入。'));noDuplicates(rows.map(d=>key(d.actual,d.predicted)),uiText('矩阵格'));if(rows.some(d=>!integer(d.count)||d.count<0))fail(uiText('count 必须为非负整数。'));if(labels.some(c=>d3.sum(rows.filter(d=>d.actual===c),d=>d.count)<=0))fail(uiText('每个真实类别需要至少一个样本。'));warnings.push(uiText('行是真实类别，列是预测类别；色深和主数字编码原始计数，悬浮提示另列行内百分比。'));}
  if(id==='residual')count(rows.length,8,300,uiText('观测'));
  if(id==='dose'){count(u('dose').length,4,12,uiText('剂量'));positive('dose');u('dose').forEach(g=>count(rows.filter(d=>d.dose===g).length,3,30,uiText('每剂量重复')));if(!text(doc.doseUnit))fail(uiText('doseUnit 需要明确剂量单位。'));warnings.push(uiText('使用对数剂量轴，零剂量须单独处理；误差棒为均值 ± 样本 SD。连线只连接均值，未拟合 4PL 或估计 IC50。'));}
  if(id==='learning'){count(rows.length,6,120,uiText('轮次'));if(rows.some((d,i)=>!integer(d.epoch)||d.epoch<0||(i&&d.epoch<=rows[i-1].epoch)))fail(uiText('epoch 必须为严格递增的非负整数。'));if(rows.some(d=>d.train<0||d.validation<0))fail(uiText('损失不得小于零。'));if(['train','validation'].some(k=>rows.filter(d=>finite(d[k])).length<2))fail(uiText('训练与验证各需要至少两个有效观测。'));warnings.push(uiText('横轴按真实 epoch 数值定位；null 保留断点。训练与验证需使用同一个损失定义。'));}
  if(id==='scree'){count(rows.length,3,16,uiText('全部主成分'));noDuplicates(rows.map(d=>d.component),uiText('主成分名称'));if(rows.some((d,i)=>d.eigenvalue<0||(i&&d.eigenvalue>rows[i-1].eigenvalue))||d3.sum(rows,d=>d.eigenvalue)<=0)fail(uiText('特征值需非负、按降序排列且合计大于零。'));warnings.push(uiText('请提供全部主成分的特征值，比例分母为输入特征值之和。不能将截断的前几项归一化后冒充总解释度。'));}
  if(id==='enrichment'){count(rows.length,5,12,uiText('通路'));if(rows.some(d=>!integer(d.count)||!integer(d.total)||d.count<=0||d.count>d.total))fail(uiText('命中数与分母需要正整数，count 不超过 total。'));warnings.push(uiText('横轴 GeneRatio = count/total，total 应明确为该次分析输入基因总数。不同通路若分母不同，须在来源中说明。气泡面积编码命中数。'));}
  if(id==='upset'){const sets=doc.sets;count(rows.length,4,20,uiText('排他交集'));if(!Array.isArray(sets)||sets.length<2||sets.length>5||sets.some(v=>!text(v)||v.includes('|'))||unique8(sets).length!==sets.length)fail(uiText('sets 需要 2–5 个不同集合名称，名称不可含 |。'));else{if(rows.some(d=>{const parts=d.members.split('|');return parts.some(v=>!sets.includes(v))||unique8(parts).length!==parts.length;}))fail(uiText('members 需要 sets 内的非重复集合名，用 | 分隔。'));if(sets.some(g=>!rows.some(d=>d.members.split('|').includes(g))))fail(uiText('每个声明的集合须出现在至少一个交集中。'));}noDuplicates(rows.map(d=>key(...d.members.split('|').sort())),uiText('交集组合'));if(rows.some(d=>!integer(d.count)||d.count<=0))fail(uiText('交集 count 必须为正整数。'));warnings.push(uiText('count 表示恰好属于列出集合且不属于其余声明集合的元素数。一个元素只计入一个排他交集；图中总量仅覆盖输入交集。'));}
  if(id==='manhattan'){count(rows.length,20,1000,uiText('位点'));const cs=doc.chromosomes;if(!Array.isArray(cs)||cs.length<2||cs.length>12||cs.some(d=>!d||!text(d.name)||!integer(d.length)||d.length<=0||d.length>1e12)||unique8(cs.map(d=>d.name)).length!==cs.length)fail(uiText('chromosomes 需要 2–12 个唯一 name 与正整数 length（bp，不超过 10¹²）。'));else if(rows.some(d=>!cs.some(c=>c.name===d.chromosome&&integer(d.position)&&d.position>=0&&d.position<=c.length)))fail(uiText('每个位点需匹配染色体，position 是该长度范围内的整数 bp 坐标。'));noDuplicates(rows.map(d=>key(d.chromosome,d.position)),uiText('位点坐标'));if(rows.some(d=>!probability(d.pvalue))||!probability(doc.threshold))fail(uiText('pvalue 与 threshold 必须在 (0, 1]。'));warnings.push(uiText('阈值是用户预设，并非所有研究通用。按 chromosomes 顺序与真实长度定位，染色体之间加入明确间隔。输入的是已完成关联检验的 p 值。'));}
  if(id==='metafunnel'){count(rows.length,6,100,uiText('研究'));positive('se');if(!finite(doc.referenceEffect)||Math.abs(doc.referenceEffect)>1e15)fail(uiText('referenceEffect 需要有限参考效应。'));warnings.push(uiText('纵轴为倒置 SE，虚线是参考效应 ± 1.96 SE，不是每项研究的置信区间。不自动合并效应，单凭不对称不能断定发表偏倚。'));}
}

export function volume8Summary(doc,fmt){if(!ids.has(doc.template))return null;const d=doc.data;if(['roc','precisionrecall'].includes(doc.template)){const own=d.filter(r=>r.model===d[0].model),result=classificationCurve(own);return{value:formatDecimal((doc.template==='roc'?result.auc:result.ap),3),label:`${d[0].model} · ${doc.template==='roc'?'AUC':'AP'}`,unit:''};}if(doc.template==='upset')return{value:fmt(d3.sum(d,r=>r.count)),label:uiText('输入交集覆盖的元素'),unit:doc.unit};if(doc.template==='confusion')return{value:fmt(d3.sum(d,r=>r.count)),label:uiText('全部评估样本'),unit:uiText('个样本')};return{value:fmt(d.length),label:volume8Catalog.find(t=>t.id===doc.template).dataMode==='analysis'?uiText('已输入的分析结果'):uiText('原始数据记录'),unit:uiText('条')};}
