import * as d3 from 'd3';
import {isEnglish} from './locale.js';
import {volume13Catalog,volume13English} from './volume13-catalog.js';
export const t13=(zh,en)=>isEnglish()?en:zh;
const ids=new Set(volume13Catalog.map(t=>t.id)),unique=a=>[...new Set(a)],pair=(a,b)=>JSON.stringify([a,b]),text=v=>typeof v==='string'&&v.trim().length>0&&v.length<=80,finite=v=>typeof v==='number'&&Number.isFinite(v)&&Math.abs(v)<=1e15;
const rowMeanings={geoflow:'一行表示从 source 到 target 的一条有向联系，同时提供两个地点的十进制度经纬度和正流量；不是实测路径。',circlehierarchy:'一行是一个节点：id 是稳定且唯一的 ASCII 标识，parent 指向父 id，唯一根的 parent 填 ROOT；只有叶节点填写正数量，内部节点 value 填 0。',radialtree:'一行是一个唯一节点，parent 指向父 id，根 parent 填 ROOT。内部节点 value 为 0，叶节点填写正数量；同一节点不能引用多个父节点。',tornado:'一行是一个参数；low 和 high 分别填参数处于低、高情景时得到的模型输出，不是输入参数值；baseline 是所有参数处于基准情景的输出。',cohortcurve:'一行是一个同期群在一个群龄的记录；size 是该群固定起始人数，retained 是当期活跃人数；period 从 0 开始且不跳期。',venn:'一行是一个排他交集，members 用 | 分隔精确所属集合。只在 A 与 B 中的元素不包含三重交集；全部七种组合均须填入，允许 0。',sankeycycle:'一行是一条从 source 到 target 的有向正流量。反向流与自环都是独立记录；回流不代表新增人数，节点净流入/净流出不被补平。',adjacency:'一行是一个 source × target 单元；行是起点、列是终点。nodes 决定相同的行列顺序，全部单元必须明确提供，包括 0 和对角线。'};
export function hierarchy13(rows){
 const byId=new Map(rows.map(row=>[row.id,{row,children:[],depth:0,total:0}]));
 if(byId.size!==rows.length)throw new Error(t13('节点 id 不能重复。','Node ids must be unique.'));
 if(rows.some(d=>!(/^[A-Za-z][A-Za-z0-9_-]*$/).test(d.id)||d.id==='ROOT'))throw new Error(t13('id 需为以字母开头的 ASCII 字母、数字、_ 或 -，且不能使用 ROOT。','Use stable ASCII ids starting with a letter, with letters, digits, _ or -; ROOT is reserved.'));
 const roots=rows.filter(d=>d.parent==='ROOT');
 if(roots.length!==1)throw new Error(t13('层级必须恰有一个 parent 为 ROOT 的根节点。','Hierarchy requires exactly one root with parent ROOT.'));
 for(const d of rows){if(d.parent==='ROOT')continue;const parent=byId.get(d.parent);if(!parent)throw new Error(t13('每个非根 parent 必须引用已存在的节点 id。','Every non-root parent must reference an existing node id.'));parent.children.push(byId.get(d.id));}
 const visited=new Set(),active=new Set();
 function visit(node,depth){if(active.has(node.row.id))throw new Error(t13('层级不能包含循环。','Hierarchy cannot contain a cycle.'));active.add(node.row.id);visited.add(node.row.id);node.depth=depth;if(node.children.length&&node.row.value!==0)throw new Error(t13('内部节点 value 必须为 0，避免重复计算子节点总量。','Internal node value must be zero to avoid double-counting descendants.'));if(!node.children.length&&!(node.row.value>0))throw new Error(t13('叶节点 value 必须大于 0。','Leaf values must be positive.'));node.total=node.children.length?d3.sum(node.children,c=>visit(c,depth+1)):node.row.value;active.delete(node.row.id);return node.total;}
 const root=byId.get(roots[0].id);visit(root,0);
 if(visited.size!==rows.length)throw new Error(t13('所有节点都必须连接到唯一根，不能有独立循环或断开的子树。','Every node must connect to the root; disconnected cycles or subtrees are invalid.'));
 return{root,nodes:[...byId.values()],total:root.total,depth:d3.max([...byId.values()],d=>d.depth)};
}
export function tornado13(doc){return doc.data.map((row,index)=>({row,index,lowDelta:row.low-doc.baseline,highDelta:row.high-doc.baseline,impact:Math.max(Math.abs(row.low-doc.baseline),Math.abs(row.high-doc.baseline))})).sort((a,b)=>b.impact-a.impact||a.index-b.index);}
export function cohorts13(doc){return unique(doc.data.map(d=>d.cohort)).map(cohort=>({cohort,rows:doc.data.filter(d=>d.cohort===cohort).sort((a,b)=>a.period-b.period).map(row=>({row,rate:row.retained/row.size}))}));}
export function venn13(doc){const regions=doc.data.map(row=>({row,mask:row.members.split('|').reduce((mask,set)=>mask|(1<<doc.sets.indexOf(set)),0)}));return{regions,total:d3.sum(regions,d=>d.row.count),setTotals:doc.sets.map((_,i)=>d3.sum(regions,d=>d.mask&(1<<i)?d.row.count:0))};}
// Tarjan components are condensed to a DAG. Within each component, input-order
// ranks make one or more backward links explicit instead of deleting cycles.
export function cyclicFlow13(rows,{width=680,height=360,compact=false}={}){
 const names=unique(rows.flatMap(d=>[d.source,d.target])),nodes=names.map((name,index)=>({name,index,incoming:0,outgoing:0,links:[]})),byName=new Map(nodes.map(n=>[n.name,n]));
 const links=rows.map((row,index)=>{const source=byName.get(row.source),target=byName.get(row.target);source.outgoing+=row.value;target.incoming+=row.value;source.links.push(target);return{row,index,source,target};});
 let next=0;const stack=[],components=[];
 function strong(node){node.visit=next;node.low=next++;stack.push(node);node.onStack=true;for(const target of node.links){if(target.visit===undefined){strong(target);node.low=Math.min(node.low,target.low);}else if(target.onStack)node.low=Math.min(node.low,target.visit);}if(node.low===node.visit){const members=[];let member;do{member=stack.pop();member.onStack=false;members.push(member);}while(member!==node);members.sort((a,b)=>a.index-b.index);const component={members,index:components.length,base:0};members.forEach(n=>n.component=component);components.push(component);}}
 nodes.forEach(n=>{if(n.visit===undefined)strong(n);});
 // At most n condensation passes; only inter-component links propagate depth.
 for(let pass=0;pass<components.length;pass++)for(const l of links)if(l.source.component!==l.target.component)l.target.component.base=Math.max(l.target.component.base,l.source.component.base+l.source.component.members.length);
 nodes.forEach(n=>{n.layer=n.component.base+n.component.members.indexOf(n);n.value=Math.max(n.incoming,n.outgoing);n.balance=n.incoming-n.outgoing;});
 const layers=unique(nodes.map(n=>n.layer)).sort((a,b)=>a-b),left=compact?24:38,right=width-(compact?24:38),top=compact?49:64,bottom=height-(compact?48:60),requestedGap=compact?10:16,nodeWidth=compact?7:10,available=Math.max(30,bottom-top),columns=layers.map(layer=>nodes.filter(n=>n.layer===layer)),gap=Math.min(requestedGap,available/Math.max(...columns.map(c=>c.length))*.4);
 const magnitude=d3.max(rows,d=>d.value),normalized=v=>v/magnitude;
 let returnIndex=0;links.forEach(l=>{l.returning=l.target.layer<=l.source.layer;if(l.returning)l.returnIndex=returnIndex++;});
 const sideLinks=[links.filter(l=>l.returning&&l.returnIndex%2===0),links.filter(l=>l.returning&&l.returnIndex%2===1)],sideSpace=[top-23,height-bottom-23],laneGap=2;
 const columnScale=d3.min(columns,column=>Math.max(10,available-gap*(column.length-1))/d3.sum(column,n=>normalized(n.value)));
 const k=Math.min(columnScale,...sideLinks.map((ls,i)=>ls.length?Math.max(4,sideSpace[i]-laneGap*(ls.length-1))/d3.sum(ls,l=>normalized(l.row.value)):Infinity)),x=d3.scalePoint(layers,[left,right-nodeWidth]);
 columns.forEach(column=>{const total=d3.sum(column,n=>normalized(n.value)*k)+gap*(column.length-1);let y=top+(available-total)/2;column.forEach(n=>{n.x=x(n.layer);n.y=y;n.height=normalized(n.value)*k;n.width=nodeWidth;y+=n.height+gap;});});
 const offsets=new Map(nodes.map(n=>[n.name,{out:0,in:0}]));
 links.forEach(l=>{l.width=normalized(l.row.value)*k;const a=offsets.get(l.source.name),b=offsets.get(l.target.name);l.y0=l.source.y+a.out+l.width/2;l.y1=l.target.y+b.in+l.width/2;a.out+=l.width;b.in+=l.width;});
 sideLinks.forEach((ls,side)=>{let used=0;ls.forEach(l=>{l.lane=side===0?top-12-used-l.width/2:bottom+12+used+l.width/2;used+=l.width+laneGap;});});
 return{nodes,links,scale:k,magnitude,layers,top,bottom,nodeWidth,returnCount:returnIndex};
}
export function validateVolume13(doc,{fail,count,noDuplicates,warnings}){
 if(!ids.has(doc.template))return;const rows=doc.data,id=doc.template;
 if(id==='geoflow'){
  count(rows.length,2,40,t13('流向','flows'));noDuplicates(rows.map(d=>pair(d.source,d.target)),t13('有向地点组合','Directed location pairs'));const locations=new Map();
  for(const d of rows){for(const side of['source','target']){const point=[d[`${side}Longitude`],d[`${side}Latitude`]];if(point[0]<-180||point[0]>180||point[1]<-85||point[1]>85)fail(t13('地点经度必须在 −180–180°，纬度在 −85–85°。','Longitude must be −180…180° and latitude −85…85°.'));if(locations.has(d[side])&&locations.get(d[side]).some((v,i)=>v!==point[i]))fail(t13('同名地点必须始终使用相同经纬度。','A named location must retain the same coordinates.'));locations.set(d[side],point);}const angle=d3.geoDistance([d.sourceLongitude,d.sourceLatitude],[d.targetLongitude,d.targetLatitude]);if(angle<1e-7||Math.PI-angle<1e-6)fail(t13('流向端点不能重合或互为对跖点；这些大圆方向未定义。','Endpoints cannot coincide or be antipodal because the great-circle direction is undefined.'));if(d.value<=0)fail(t13('流量必须大于 0。','Flow must be positive.'));}
  warnings.push(t13('线宽表示流量；大圆弧为地理关系示意，不是实测运输路线。Natural Earth 1:110m 底图；跨日期变更线的路线分段显示。','Width represents flow; great-circle arcs are schematic geographic connections, not recorded routes. Natural Earth 1:110m; antimeridian crossings are split.'));
 }
 if(['circlehierarchy','radialtree'].includes(id)){count(rows.length,3,80,t13('节点','nodes'));try{const tree=hierarchy13(rows);count(tree.depth+1,2,7,t13('层级','levels'));}catch(e){fail(e.message);}warnings.push(id==='circlehierarchy'?t13('只有叶圆面积严格对应数量；父圆是含留白的包络，父值为叶子加总。','Only leaf-circle area encodes quantity. Parent circles are padded enclosures; parent totals sum leaves.'):t13('半径层级、枝长和角度仅用于布局；叶点面积对应数量，内部节点不重复计量。','Radial depth, edge length and angle are layout only. Leaf-marker area represents quantity; internal values are not double-counted.'));}
 if(id==='tornado'){count(rows.length,3,16,t13('参数','parameters'));noDuplicates(rows.map(d=>d.parameter),t13('参数','Parameters'));if(!finite(doc.baseline))fail(t13('baseline 必须为绝对值不超过 10¹⁵ 的有限数值。','baseline must be a finite number with magnitude at most 10¹⁵.'));warnings.push(t13('low/high 是输入参数的低/高情景产生的输出，允许 low > high 或二者位于基准同侧；不是置信区间。每次仅改变一个参数。','low/high label low/high input scenarios, not ordered output bounds; low > high and same-side outcomes are valid. These are not confidence intervals. Change one parameter at a time.'));}
 if(id==='cohortcurve'){
  if(!text(doc.periodUnit))fail(t13('periodUnit 必须明确群龄单位。','periodUnit must name the cohort-age unit.'));noDuplicates(rows.map(d=>pair(d.cohort,d.period)),t13('同期群与期数组合','Cohort-age pairs'));const groups=cohorts13(doc);count(groups.length,2,8,t13('同期群','cohorts'));
  for(const {rows:points}of groups){count(points.length,2,36,t13('每群期数','periods per cohort'));if(points.some(({row},i)=>!Number.isInteger(row.period)||row.period!==i))fail(t13('每群 period 必须从 0 开始连续递增，缺失期不能隐含为零。','Each cohort requires contiguous integer ages starting at zero; missing periods are not zeros.'));if(points.some(({row})=>!Number.isInteger(row.size)||row.size<=0||!Number.isInteger(row.retained)||row.retained<0||row.retained>row.size))fail(t13('size 必须为正整数，retained 为 0–size 的整数。','size must be a positive integer and retained an integer from zero to size.'));if(points.some(({row})=>row.size!==points[0].row.size))fail(t13('同一同期群的 size 必须固定。','Cohort size must remain constant.'));if(points[0].row.retained!==points[0].row.size)fail(t13('第 0 期 retained 必须等于起始 size。','Age-zero retained must equal the initial size.'));}
  warnings.push(t13('分母固定为各群起始人数；活跃回访可造成比例回升；未成熟期间不延长、不补零。','Each cohort retains its initial denominator. Returning users can raise retention; immature future periods are not extended or zero-filled.'));
 }
 if(id==='venn'){
  if(!Array.isArray(doc.sets)||doc.sets.length!==3||doc.sets.some(v=>!text(v)||v.includes('|'))||new Set(doc.sets).size!==3){fail(t13('sets 必须是三个不含 | 的唯一集合名称。','sets must contain three unique names without |.'));return;}
  const keys=rows.map(d=>{const members=d.members.split('|');if(new Set(members).size!==members.length||members.some(v=>!doc.sets.includes(v)))fail(t13('members 必须由 sets 中不重复的名称以 | 连接。','members must join distinct names from sets using |.'));return members.map(v=>doc.sets.indexOf(v)).sort().join(',');});noDuplicates(keys,t13('排他交集','Exclusive intersections'));if(rows.length!==7||new Set(keys).size!==7)fail(t13('必须完整提供七种非空排他交集，包括零值。','Supply all seven nonempty exclusive combinations, including zeros.'));if(rows.some(d=>!Number.isInteger(d.count)||d.count<0))fail(t13('交集 count 必须为非负整数。','Intersection counts must be nonnegative integers.'));warnings.push(t13('圆和区域面积不编码数量；每条记录只计入一个排他交集，集合总数由相关区域相加。','Circle and region area do not encode count. Each record is one exclusive intersection; set totals sum the relevant regions.'));
 }
 if(id==='sankeycycle'){const names=unique(rows.flatMap(d=>[d.source,d.target]));count(names.length,2,16,t13('节点','nodes'));count(rows.length,2,40,t13('有向流','directed flows'));noDuplicates(rows.map(d=>pair(d.source,d.target)),t13('有向节点组合','Directed node pairs'));if(rows.some(d=>d.value<=0))fail(t13('流量必须大于 0。','Flow must be positive.'));warnings.push(t13('同一线宽比例用于全部流；节点高度为流入与流出的较大值。两侧不平衡代表未配平的外部净流，提示分别显示入、出、净额；回流不能当作新流量或新增人数。','One width scale applies to all links. Node height is max(inflow,outflow). Imbalance remains visible and tooltips report in, out and net; recirculation does not imply new flow or unique people.'));}
 if(id==='adjacency'){
  if(!Array.isArray(doc.nodes)||doc.nodes.some(v=>!text(v))||new Set(doc.nodes).size!==doc.nodes.length){fail(t13('nodes 必须是唯一节点名称的列表。','nodes must be a list of unique node names.'));return;}count(doc.nodes.length,2,12,t13('节点','nodes'));noDuplicates(rows.map(d=>pair(d.source,d.target)),t13('矩阵单元','Matrix cells'));if(rows.some(d=>!doc.nodes.includes(d.source)||!doc.nodes.includes(d.target)))fail(t13('source/target 必须属于 nodes。','source/target must belong to nodes.'));if(rows.length!==doc.nodes.length**2)fail(t13('必须提供完整方阵，不能把未提供的联系补零。','A complete square matrix is required; absent connections are not zero-filled.'));if(rows.some(d=>d.value<0))fail(t13('联系权重不能为负。','Connection weights cannot be negative.'));warnings.push(t13('行为起点，列为终点；使用共同零起点色阶，不自动对称化，零值与缺测不混用。','Rows are sources and columns targets. A common zero-based color scale preserves direction; no symmetrization or missing-to-zero conversion.'));
 }
}
export function volume13Summary(doc,fmt){if(!ids.has(doc.template))return null;if(['circlehierarchy','radialtree'].includes(doc.template))return{value:fmt(hierarchy13(doc.data).total),label:t13('叶节点合计','Leaf total'),unit:doc.unit};return{value:fmt(doc.data.length),label:t13('输入记录','Input records'),unit:t13('条','rows')};}
export function volume13MethodNotes(id){const notes={geoflow:['https://d3js.org/d3-geo/shape','https://www.naturalearthdata.com/about/terms-of-use/'],circlehierarchy:['https://d3js.org/d3-hierarchy/pack'],radialtree:['https://d3js.org/d3-hierarchy/tree'],sankeycycle:['https://github.com/d3/d3-sankey#sankey_nodeWidth']};return(notes[id]||[]).map(url=>t13('方法 / 底图参考：','Method / geography reference: ')+url);}
export function guide13(t,guide){if(!ids.has(t.id))return guide;const en=volume13English[t.id],sampleReport={warnings:[]};validateVolume13(guide.example,{fail:()=>{},count:()=>{},noDuplicates:()=>{},warnings:sampleReport.warnings});return{...guide,introduction:isEnglish()?en.description:t.description,rowMeaning:isEnglish()?en.rowMeaning:rowMeanings[t.id],use:isEnglish()?en.use:t.use,avoid:isEnglish()?en.avoid:t.avoid,limit:isEnglish()?en.limit:t.limit,notes:[...sampleReport.warnings,...volume13MethodNotes(t.id)],fields:guide.fields.map((f,i)=>({...f,description:isEnglish()?en.fields[i][2]:t.fields[i][2]}))};}
