const s=(k,d)=>[k,'string',d],n=(k,d)=>[k,'number',d],nullable=['value','number | null','原始测量值；null 明确保留缺测'];
const prediction=[s('label','测试样本唯一编号'),s('model','预测模型'),n('actual','真实类别 0 或 1'),n('score','正类预测概率 [0,1]')];
const specs=[
['bipartite','双部关系网络','Bipartite network','flow',[s('source','左侧节点'),s('target','右侧节点'),n('value','已观测正联系强度')],'两类节点分居两侧，以共同线宽尺度展示已观测的跨类联系。','供需关系、人员与任务、产品与渠道','把未列出的联系当已知零；在同侧连接节点','两侧各 2–12 节点；3–60 条唯一正联系；显式 leftNodes/rightNodes'],
['egonetwork','自我中心网络','Ego network','flow',[s('source','无向联系端点 A'),s('target','无向联系端点 B'),n('value','已观测正联系强度')],'中心对象的一阶邻居围绕中心排列，邻居间联系补充局部关系结构。','关键账号关系、组织合作、局部依赖','把圆周距离当社会距离；将孤立对象假装为一阶邻居','显式 ego；3–16 个直接邻居；无向边唯一、正值、无自环'],
['radialheatmap','径向热力图','Radial heatmap','matrix',[s('sector','扇区名称'),s('ring','圆环名称'),nullable],'完整扇区与环带交叉表使用共同数值色带，缺测以纹理保留。','周期矩阵、轮班监测、季节对照','比较扇区面积推断数量；省略缺测单元','4–16 sectors × 2–8 rings；显式有序数组；完整组合；缺失填 null'],
['spiralheatmap','螺旋时间热力图','Spiral heatmap','trend',[s('period','按输入顺序排列的等间隔时期'),nullable],'沿连续螺旋推进等间隔观测，同一角度便于比较相邻周期。','长期周期变化、重复季节、过程监测','不等间隔时间；把环宽或面积当原值','cycleLength 为 6–24；2–6 个周期，允许最后周期不完整；缺失填 null'],
['variwide','变宽率量图','Variwide rate–volume','comparison',[s('label','观察类别'),n('width','正数量：横轴宽度'),n('rate','非负率：纵轴高度')],'连续宽度表示数量、高度表示同单位率，面积精确对应数量与率的乘积。','数量与单位成本、流量与转化率、资源效率','当作百分比堆叠；用同宽柱掩盖数量差异','3–16 类；width > 0，rate ≥ 0；axes.x/y 明确数量和率单位'],
['stackedwaterfall','分解瀑布图','Decomposed waterfall','comparison',[s('step','变化步骤'),s('component','变化分量'),n('value','带正负号的增减量')],'每一步以正负分量分解变化，净额逐步连接起始与最终总量。','预算变动、利润桥接、组成因素归因','把正负分量抵消后隐藏；终值与逐步变化不守恒','2–8 步 × 2–6 分量完整组合；baseline/finalTotal 与变化守恒'],
['treetable','层级条形树表','Hierarchy bar table','hierarchy',[s('id','稳定唯一 ASCII 节点 id'),s('parent','父节点 id；唯一根填 ROOT'),s('label','显示名称'),n('value','叶节点正数量；内部节点填 0')],'缩进结构、父子连接与共同尺度的汇总条形一起展示层级组成。','组织预算、资产分类、项目工作量','把父子汇总条再次相加；为内部节点填重复数量','3–24 节点，最多 6 层深度；唯一根，无循环；叶值正，内部值 0'],
['nelsonaalen','累积风险曲线','Nelson–Aalen hazard','research',[s('label','观测唯一编号'),s('group','观察分组'),n('duration','非负持续时间'),['status','ended | censored','ended 为事件发生；censored 为右删失']],'按事件时刻累加事件数除以在险人数，保留同刻事件与右删失。','设备失效、会话终止、持续时间研究','把累积风险当概率；混入左截断或区间删失','1–4 组，每组 4–120 条；同刻先计事件，再移出所有截止记录'],
['ksplot','预测分布 KS 图','Score KS diagnostic','research',prediction,'比较正负真实类别的预测得分累积分布，以最大竖直距离诊断分离程度。','二分类得分分离、测试集模型检查','对离散同分数据套连续 KS 检验显著性；把距离当准确率','1–2 模型，每个 8–300 共同测试样本；正负类齐全；仅描述 D'],
['liftcurve','提升曲线','Lift curve','research',prediction,'按同分块整体筛选，展示已选人群的正类富集倍数，基线为 1。','定向触达、排序价值、测试集模型比较','随意打散同分；在零筛选比例定义提升值','1–2 模型，每个 8–300 共同测试样本；同分整组进入；零份额未定义'],
['thresholdmetrics','阈值指标曲线','Threshold metrics','research',prediction,'共同阈值下展示精确率、召回率与 F1，保留得分同分跳跃和未定义精确率。','阈值取舍、分类器诊断、指标敏感性','把没有选中样本的精确率补零；在测试集反复调参','1–2 模型，每个 8–300 共同测试样本；score≥t；无预测正类时精确率为空'],
['costcurve','期望代价曲线','Expected cost curve','research',prediction,'用显式误报与漏报代价比较阈值策略，并显示全部判正与全部判负基线。','业务误判代价、策略阈值敏感性','与阈值赔率净获益混淆；忽略成本单位或部署分布改变','1–2 模型，8–300 共同样本；两种代价非负且至少一种为正']
];
export const volume18Catalog=specs.map(([id,name,en,category,fields,description,use,avoid,limit],i)=>({id,no:String(181+i),name,en,type:name,category,fields,description,use,avoid,limit,motion:'结构展开 / 观测定位 / 统计轨迹推进',keywords:`${name} ${en} ${use}`,edition:18,research:category==='research',dataMode:'observations',duration:8}));
const left=['Strategy','Design','Engineering','Research','Support'],right=['Atlas','Beacon','Cedar','Delta','Ember','Flux'];
const sectors=Array.from({length:12},(_,i)=>`M${i+1}`),rings=['2023','2024','2025','2026'];
const steps=['Volume','Price','Mix','Efficiency'],components=['Core','New','Other'];
const predictions=['A','B'].flatMap((model,j)=>Array.from({length:56},(_,i)=>{const actual=(i*17%29)<12?1:0;return{label:`S${i+1}`,model,actual,score:Math.round(Math.max(.02,Math.min(.98,.22+actual*.43+Math.sin(i*2.13+j)*(.23+j*.09)))*20)/20};}));
const classifier={unit:'ratio',positiveLabel:'Target event',data:predictions};
export const volume18Contents={
 bipartite:{title:'两类节点的协作关系',subtitle:'确定性合成联系 · 仅显示已观测边 · 未列边不推断',unit:'hours',leftNodes:left,rightNodes:right,data:left.flatMap((source,i)=>right.filter((_,j)=>(i+j)%3!==0).map((target,j)=>({source,target,value:8+(i*13+j*7)%35})))},
 egonetwork:{title:'关键节点的局部网络',subtitle:'确定性合成无向联系 · 所有邻居均与中心直接相连',unit:'times',ego:'FORMA',data:[...Array.from({length:10},(_,i)=>({source:'FORMA',target:`N${i+1}`,value:12+(i*11)%32})),...Array.from({length:12},(_,i)=>({source:`N${i%10+1}`,target:`N${(i*3+3)%10+1}`,value:5+(i*7)%21})).filter((r,i,a)=>r.source!==r.target&&a.findIndex(q=>[q.source,q.target].sort().join('|')===[r.source,r.target].sort().join('|'))===i)]},
 radialheatmap:{title:'多年度季节强度',subtitle:'确定性合成测量 · 统一色标 · 纹理为缺测',unit:'index',sectors,rings,data:rings.flatMap((ring,i)=>sectors.map((sector,j)=>({sector,ring,value:i===1&&j===8?null:+(40+22*Math.sin(j*.7+i*.5)+i*6).toFixed(2)})))},
 spiralheatmap:{title:'时间沿螺旋流动',subtitle:'确定性合成等间隔序列 · 每圈 12 期 · 纹理为缺测',unit:'index',cycleLength:12,data:Array.from({length:60},(_,i)=>({period:`T${i+1}`,value:i===25?null:+(50+28*Math.sin(i*Math.PI/6)+i*.45+6*Math.cos(i*.37)).toFixed(2)}))},
 variwide:{title:'数量与单位率共同决定总量',subtitle:'确定性合成数据 · 宽度为工时 · 高度为单位成本 · 面积为总成本',unit:'USD',axes:{x:'Hours',y:'USD / hour'},data:[['Strategy',22,160],['Design',47,115],['Engineering',94,145],['Research',31,180],['Support',56,70]].map(([label,width,rate])=>({label,width,rate}))},
 stackedwaterfall:{title:'从起始到最终的分量桥接',subtitle:'确定性合成分解 · 正负分开累计 · 逐步净额守恒',unit:'k USD',baseline:180,finalTotal:237,stepOrder:steps,components,data:steps.flatMap((step,i)=>components.map((component,j)=>({step,component,value:[[35,18,-8],[-12,6,-4],[14,-9,3],[8,4,2]][i][j]})))},
 treetable:{title:'层级预算与组成',subtitle:'确定性合成叶值 · 内部节点为后代叶值之和 · 父子不能重复相加',unit:'k USD',data:[['all','ROOT','Portfolio',0],['build','all','Build',0],['research','all','Research',0],['operate','all','Operate',0],['design','build','Design',38],['platform','build','Platform',64],['delivery','build','Delivery',42],['models','research','Models',53],['data','research','Data',31],['support','operate','Support',22],['infra','operate','Infrastructure',36]].map(([id,parent,label,value])=>({id,parent,label,value}))},
 nelsonaalen:{title:'事件累积风险与右删失',subtitle:'确定性合成时长 · H(t)=Σd/n · 非概率 · 同刻删失仍在险',unit:'days',data:['A','B'].flatMap((group,j)=>Array.from({length:32},(_,i)=>({label:`${group}${i+1}`,group,duration:2+(i*13%47)+j*7,status:i%5===0?'censored':'ended'})))},
 ksplot:{...classifier,title:'真实类别的得分分离',subtitle:'确定性合成测试集 · 经验 CDF 最大距离 · 不计算显著性'},
 liftcurve:{...classifier,title:'优先筛选带来的富集倍数',subtitle:'确定性合成测试集 · 同分整组纳入 · 随机筛选基线为 1'},
 thresholdmetrics:{...classifier,title:'阈值改变指标的取舍',subtitle:'确定性合成测试集 · 精确率 / 召回率 / F1 · 不自动选阈值'},
 costcurve:{...classifier,title:'不同阈值的平均误判代价',subtitle:'确定性合成测试集 · 显式业务成本 · 与全部判正、判负比较',unit:'USD / record',falsePositiveCost:8,falseNegativeCost:35}
};
const en={
 bipartite:['Observed weighted relations connect two explicit, disjoint node partitions.','Supply–demand, assignments and cross-category relations','Interpreting unlisted edges as measured zeros or linking within one partition','2–12 nodes per side; 3–60 unique positive observed edges; ordered leftNodes/rightNodes.','One row is one observed weighted edge from a left node to a right node. Unlisted relations are not imputed.'],
 egonetwork:['A focal node and its direct neighbors reveal their local weighted, undirected relationships.','Local collaboration, account networks and dependencies','Reading geometric distance as relationship distance or including non-neighbors','Explicit ego; 3–16 direct neighbors; unique positive undirected edges without loops.','One row is one undirected observed edge. Every alter must have an observed direct edge to ego.'],
 radialheatmap:['A complete ring × sector matrix uses one numeric color scale and textured missing cells.','Seasonal matrices and repeated-cycle comparisons','Interpreting unequal cell areas as magnitudes or omitting missing cells','4–16 ordered sectors × 2–8 ordered rings; every pair required; null means missing.','One row is one original measurement for a ring-sector pair. Arrays explicitly order both dimensions.'],
 spiralheatmap:['Equal-interval observations advance along a spiral, aligning repeated cycle positions.','Repeated seasons and long-range periodic monitoring','Using irregular time intervals or reading area as the measured value','cycleLength 6–24; 2–6 cycles, with a partial last cycle permitted; explicit null gaps.','One row is one time interval, in chronological input order. Period labels are unique and no dates are inferred.'],
 variwide:['Contiguous width encodes quantity, height a nonnegative rate, and area their product.','Volume with unit cost, traffic with conversion rate and resource use','Treating this as percentage stacking or overlooking measurement units','3–16 categories; width > 0 and rate ≥ 0; axes.x/y name quantity and rate units.','Each row supplies one category, its original quantity and rate. Area is width × rate, not an additional input.'],
 stackedwaterfall:['Signed components explain each change, with running net totals connecting the initial and final balances.','Budget bridges, profit changes and component attribution','Hiding opposing components or supplying a final total that does not reconcile','2–8 ordered steps × 2–6 ordered components; complete grid and consistent baseline/finalTotal.','Each row is a signed component change in one step. Supply zero explicitly; no missing component is filled.'],
 treetable:['An indented tree table aligns every node with its descendant-leaf total on a shared quantitative axis.','Hierarchical budgets, assets and work allocation','Adding parent and child totals again or duplicating counts in internal nodes','3–24 nodes, depth at most 6; one root, no cycles, positive leaves and zero internal inputs.','One row is a stable ASCII id, parent id, label and original leaf quantity. Only the root uses parent ROOT.'],
 nelsonaalen:['Event-time increments d/n accumulate the Nelson–Aalen hazard while preserving right censoring.','Failure-time and event-duration analysis','Reading cumulative hazard as probability or mixing left truncation and interval censoring','1–4 groups with 4–120 records each; tied events occur before all same-time withdrawals.','Each row is one complete duration and event/censor status. Censored observations remain at risk through their observed time.'],
 ksplot:['Empirical score CDFs for actual classes 0 and 1 expose their maximum absolute vertical separation.','Held-out binary score separation and model diagnosis','Using a continuous-null KS significance test on tied prediction scores','1–2 models, each with 8–300 identical test samples and both classes; descriptive D only.','Each row is a sample-model observation with actual binary class and predicted positive-class probability.'],
 liftcurve:['Whole tied-score blocks reveal selected-population enrichment relative to random selection.','Targeting, ranking utility and held-out model comparison','Breaking score ties arbitrarily or assigning a value at zero population share','1–2 models, 8–300 common samples each; complete tie blocks only; lift is undefined at zero share.','Each row is one true outcome and predicted probability; sample identity and outcome match across models.'],
 thresholdmetrics:['Precision, recall and F1 follow the same score threshold, preserving ties and undefined precision.','Threshold trade-offs and classifier diagnosis','Replacing undefined precision by zero or repeatedly tuning on test outcomes','1–2 models, 8–300 common samples each; select score≥t; precision missing when nothing is selected.','One row is a held-out sample, model, actual class and predicted probability.'],
 costcurve:['Explicit false-positive and false-negative costs give mean loss across thresholds, including all/none baselines.','Business loss, threshold sensitivity and fixed-cost strategies','Confusing fixed costs with threshold-odds net benefit or ignoring deployment shifts','1–2 models with 8–300 common samples; nonnegative costs and at least one positive cost.','One row is a held-out prediction. Supplied costs share one currency or loss unit per erroneous record.']
};
const fe={source:'First endpoint; the left partition for bipartite links',target:'Second endpoint; the right partition for bipartite links',value:'Original numeric measurement or explicitly null when allowed',sector:'Sector name from the ordered sectors array',ring:'Ring name from the ordered rings array',period:'Unique, equally spaced period in chronological input order',label:'Original observation or category label',width:'Strictly positive quantity; horizontal width',rate:'Nonnegative rate; vertical height',step:'Step name in the explicit stepOrder',component:'Component name in the explicit components order',id:'Stable unique ASCII node identifier',parent:'Parent identifier; only the root uses ROOT',group:'Observation group',duration:'Nonnegative observed time in the stated unit',status:'ended for an observed event; censored for right censoring',model:'Prediction model',actual:'Observed binary class, 0 or 1',score:'Predicted probability of class 1, within [0,1]'};
export const volume18English=Object.fromEntries(volume18Catalog.map(t=>{const[description,use,avoid,limit,rowMeaning]=en[t.id];return[t.id,{description,use,avoid,limit,rowMeaning,fields:t.fields.map(([k,type])=>[k,type,fe[k]])}];}));
