// All examples are deterministic synthetic observations or explicitly synthetic analysis results.
const str=(k,d)=>[k,'string',d],num=(k,d)=>[k,'number',d];
const counts=[str('row','行类别'),str('column','列类别'),num('count','完整列联表中的非负整数频数')];
const specs=[
 ['andrews','安德鲁斯曲线','Andrews curves','research',[str('label','对象唯一名称'),str('group','对象分组'),str('variable','维度名称，属于 variables'),num('value','已预处理至可比尺度的观测值')],'将多个维度依次映射为傅里叶系数，以整条曲线比较多变量对象。','多变量聚类检查、群体轮廓和异常模式','把横轴当时间；混用未归一化的不同单位；从曲线交叉推断相关','3–60 个对象、3–8 个共同维度；variables 声明固定顺序；所有组合完整'],
 ['biplot','主成分双标图','PCA biplot','research',[str('label','样本或变量唯一名称'),str('kind','score 为样本得分；loading 为变量载荷'),str('group','样本分组；载荷也填写说明性分组'),num('x','预先计算的 PC1 坐标'),num('y','预先计算的 PC2 坐标')],'在同一平面展示已计算的样本得分与变量载荷方向，明确标注载荷展示倍率。','解读主成分中的样本结构和变量方向','把图内箭头当因果关系；忽略外部分析的缩放约定；从任意缩放推断相关','3–120 个样本、2–12 个非零载荷；必须声明 scaling、loadingScale 和两个解释方差百分比'],
 ['taylor','泰勒图','Taylor diagram','research',[str('label','模型唯一名称'),num('sd','模型总体标准差，分母 N'),num('correlation','模型与共同参考的相关系数，−1 至 1')],'径向距离为标准差比，夹角余弦为相关系数；到共同参考点的距离是归一化中心均方根误差。','气候模型、仿真结果和共同参考的模式比较','混用不同样本、掩码或权重；把中心误差当包含均值偏差的总误差','2–24 个模型；正 referenceSD 与 sd；所有指标来自同一组配对观测及同一加权方式'],
 ['targetdiagram','模型误差靶心图','Target diagram','research',[str('label','模型唯一名称'),num('bias','模型均值减参考均值'),num('centeredRMSE','去均值后的均方根误差，非负'),num('sd','模型总体标准差，分母 N')],'把归一化偏差与带符号的中心均方根误差分开；到原点的距离表示总归一化 RMSE。','比较模型偏差、幅度不足和总误差','将横坐标正负当相关方向；混用分母或配对样本；把参考圆当显著性界线','2–24 个模型；referenceSD > 0；中心误差须符合标准差的三角不等式'],
 ['youden','实验室尤登图','Youden laboratory plot','research',[str('label','实验室唯一名称'),num('sampleA','实验室对样本 A 的测量原值'),num('sampleB','同一实验室对样本 B 的测量原值')],'每个实验室对两个相似样本的成对测量构成一点；中位十字线和等尺度斜线辅助识别共同偏移。','实验室间比对、测量过程诊断、能力验证探索','把中位数当认证真值；把参考线当置信区间或自动判定不合格','5–80 个实验室；两个样本须单位相同且量级可比；每轴有变化'],
 ['agreement','分类一致性方块图','Bangdiwala agreement chart','research',counts,'沿对角路径排列边际矩形，以内部同尺度实心方块表示完全一致频数，旁表保留全部计数。','两个评审者、标注者或分类方法的一致性','将 B 当 Cohen κ；将一致率当准确率；赋予未定义的相邻分类部分分数','categories 声明 2–6 个共同有序类别；完整方阵，零值显式填 0；边际均为正'],
 ['association','列联关联残差图','Association plot','research',counts,'矩形宽度对应期望频数平方根，高度对应带符号 Pearson 残差，面积表达观察与期望的差。','寻找列联表中高于或低于独立性期望的组合','把图形残差阈值当显著性检验；隐藏零频数；将计数替换为百分比','2–6 行、2–6 列；完整非负整数频数表；边际均为正'],
 ['mosaicplot','统计马赛克图','Statistical mosaic plot','research',counts,'矩形面积对应联合频数，宽度对应行边际占比；颜色深浅表示 Pearson 残差偏离独立性期望。','类别联合分布、渠道偏好、分层构成和关联探索','把等宽分组柱当马赛克；仅凭色深断言显著；漏填零频数组合','2–6 行、2–6 列；完整非负整数频数表；边际均为正']
];
export const volume14Catalog=specs.map(([id,name,en,category,fields,description,use,avoid,limit],i)=>({id,no:String(145+i),name,en,type:name,category,fields,description,use,avoid,limit,motion:'原生几何展开 / 数据标记显现 / 可逆定位',keywords:`${name} ${en} ${use}`,edition:14,dataMode:['biplot','taylor','targetdiagram'].includes(id)?'analysis':['agreement','association','mosaicplot'].includes(id)?'counts':'observations',research:true,duration:8}));
const variables=['稳定性','响应','精度','效率','扩展性'];
const tableRows=['研究','产品','运营'],tableCols=['在线','线下','混合'],tableCounts=[[38,12,25],[15,31,17],[9,14,39]];
const contingency=tableRows.flatMap((row,i)=>tableCols.map((column,j)=>({row,column,count:tableCounts[i][j]})));
const categories=['优秀','良好','待改进'],agreementCounts=[[35,5,1],[4,28,6],[0,5,20]];
export const volume14Contents={
 andrews:{title:'多维能力的曲线指纹',subtitle:'确定性合成观测 · 同一预处理尺度，维度顺序固定',unit:'标准分',variables,data:Array.from({length:18},(_,i)=>variables.map((variable,j)=>({label:`S${i+1}`,group:['A','B','C'][Math.floor(i/6)],variable,value:Math.round((Math.sin(j*.9+Math.floor(i/6)*1.7)*1.15+Math.cos(i*1.3+j)*.16)*100)/100}))).flat()},
 biplot:{title:'样本结构与变量方向',subtitle:'确定性合成分析结果 · 载荷箭头与样本坐标使用已声明倍率',unit:'坐标',scaling:'合成标准化 PCA 得分与单位特征向量；箭头仅按 loadingScale 放大',loadingScale:2.8,variance1:48,variance2:27,data:[...Array.from({length:30},(_,i)=>({label:`S${i+1}`,kind:'score',group:['A','B','C'][Math.floor(i/10)],x:Math.round((Math.cos(i/30*Math.PI*2)*2.4)*100)/100,y:Math.round((Math.sin(i/30*Math.PI*2)*1.8)*100)/100})),...['精度','效率','规模','成本','响应'].map((label,j)=>({label,kind:'loading',group:'变量',x:Math.cos(j/5*Math.PI*2)*Math.sqrt(2/5),y:Math.sin(j/5*Math.PI*2)*Math.sqrt(2/5)}))]},
 taylor:{title:'模型与参考的模式匹配',subtitle:'确定性合成分析结果 · 归一化标准差与中心误差',unit:'mm',referenceSD:12,data:[['A',11.4,.96],['B',14.8,.91],['C',8.2,.84],['D',13.1,.71],['E',9.8,.44],['F',12.5,-.3]].map(([label,sd,correlation])=>({label,sd,correlation}))},
 targetdiagram:{title:'区分模型偏差与波动误差',subtitle:'确定性合成分析结果 · 所有坐标除以参考总体标准差',unit:'mm',referenceSD:12,data:[['A',1.2,3.6,11.4],['B',-3.4,5.2,14.8],['C',.8,6.1,8.2],['D',5.1,8.3,13.1],['E',-6.3,10.4,9.8],['F',2.5,13.2,12.5]].map(([label,bias,centeredRMSE,sd])=>({label,bias,centeredRMSE,sd}))},
 youden:{title:'实验室间成对测量比对',subtitle:'确定性合成观测 · 中位十字线仅作诊断参考',unit:'mg/L',axes:{x:'样本 A / mg/L',y:'样本 B / mg/L'},data:Array.from({length:24},(_,i)=>({label:`Lab ${i+1}`,sampleA:Math.round((50+Math.sin(i*1.7)*2.1+Math.cos(i*.7)*.75)*100)/100,sampleB:Math.round((54+Math.sin(i*1.7)*2+Math.sin(i*.8)*.8)*100)/100}))},
 agreement:{title:'两位评审者的一致性',subtitle:'确定性合成计数 · B 只计完全一致，旁表保留全部输入',unit:'件',categories,axes:{x:'评审者 B',y:'评审者 A'},data:categories.flatMap((row,i)=>categories.map((column,j)=>({row,column,count:agreementCounts[i][j]})))},
 association:{title:'哪些组合偏离独立性期望',subtitle:'确定性合成计数 · 正负 Pearson 残差，未作显著性检验',unit:'人',axes:{x:'参与方式',y:'部门'},data:contingency},
 mosaicplot:{title:'不同部门的参与方式',subtitle:'确定性合成计数 · 面积表示频数，色深表示残差强度',unit:'人',axes:{x:'部门',y:'参与方式'},data:contingency}
};
export const volume14English={
 andrews:{description:'Fourier coefficients encode an ordered multivariate vector as a whole curve.',use:'Inspecting multivariate clusters, group profiles and unusual patterns',avoid:'Reading the horizontal axis as time, mixing incomparable units or inferring correlation from crossings',limit:'3–60 objects and 3–8 common dimensions; variables declares a fixed order and every object-dimension pair is supplied.',rowMeaning:'One row is one original value for one object and one declared dimension, with a stable group. Supply values already on a comparable scale.'},
 biplot:{description:'Precomputed sample scores and variable loading directions share a plane, with an explicit loading display multiplier.',use:'Explaining sample structure and variable direction in principal components',avoid:'Inferring causality or correlations without the external analysis scaling convention',limit:'3–120 scores and 2–12 nonzero loading vectors. Declare scaling, positive loadingScale and both explained-variance percentages.',rowMeaning:'One row is either a precomputed sample score (kind=score) or loading vector (kind=loading). No PCA or normalization is fitted in the chart.'},
 taylor:{description:'Radius is the standard-deviation ratio and angle cosine is correlation. Distance to the common reference is normalized centered RMS error.',use:'Comparing simulations or climate models against a common reference',avoid:'Mixing sample masks or weights, or reading centered error as total error including mean bias',limit:'2–24 models; positive referenceSD and sd. All metrics must use the same paired observations and weighting convention.',rowMeaning:'One row contains an external model population standard deviation (denominator N) and correlation to the common reference.'},
 targetdiagram:{description:'Normalized bias and signed centered RMS error separate two error components. Distance to the origin is total normalized RMSE.',use:'Comparing model bias, under-dispersion and total prediction error',avoid:'Reading the horizontal sign as correlation direction or reference circles as significance limits',limit:'2–24 models; positive referenceSD. Centered error must satisfy the standard-deviation triangle bounds.',rowMeaning:'One row supplies external mean bias, centered RMSE and model population SD from the same paired observations and weighting convention.'},
 youden:{description:'Paired measurements of two similar samples locate each laboratory. Median crosshairs and an equal-unit diagonal aid diagnostic comparison.',use:'Interlaboratory comparisons and measurement-process diagnostics',avoid:'Treating medians as certified truth or reference lines as confidence or acceptance limits',limit:'5–80 laboratories; samples share measurement units and comparable scales; both axes must vary.',rowMeaning:'One row is one laboratory and its two original measurements on samples A and B. No results are averaged or omitted.'},
 agreement:{description:'Marginal rectangles follow a diagonal path; equal-scale inner squares show exact agreement counts. A side table retains all counts.',use:'Agreement of two raters, annotators or categorical methods',avoid:'Calling B Cohen kappa or accuracy, or assigning undeclared partial agreement credit',limit:'categories declares 2–6 common ordered categories; supply a complete square count table with explicit zeros and positive margins.',rowMeaning:'One row is the nonnegative integer count for rater A category row and rater B category column; all category pairs are required.'},
 association:{description:'Rectangle width is proportional to the square root of the expected count; signed height is the Pearson residual, so area expresses observed-minus-expected count.',use:'Finding contingency-table combinations above or below independence expectations',avoid:'Treating residual colors as significance tests or substituting percentages for counts',limit:'2–6 rows and columns; supply all nonnegative integer counts with positive margins.',rowMeaning:'One row is one observed count for a row-category and column-category pair, including every genuine zero.'},
 mosaicplot:{description:'Rectangle area represents joint frequency and width represents the row margin; signed shading shows departure from independence expectations.',use:'Joint categorical distributions, channel preferences and association exploration',avoid:'Inferring significance from shading or omitting zero-count combinations',limit:'2–6 rows and columns; supply a complete nonnegative integer count table with positive margins.',rowMeaning:'One row is one observed cell count. Row widths and conditional column heights are calculated from the complete table.'}
};
const labels={andrews:['Unique object label','Object group','Declared dimension in variables','Original value already on a comparable scale'],biplot:['Unique sample or variable label','score or loading','Group or loading descriptor','Precomputed PC1 coordinate','Precomputed PC2 coordinate'],taylor:['Unique model label','Population standard deviation, denominator N','Correlation with the reference, from −1 to 1'],targetdiagram:['Unique model label','Model mean minus reference mean','Nonnegative centered root mean squared error','Model population standard deviation, denominator N'],youden:['Unique laboratory label','Original measurement of sample A','Original measurement of sample B'],agreement:['Rater A category / row','Rater B category / column','Nonnegative integer cell count'],association:['Row category','Column category','Nonnegative integer cell count'],mosaicplot:['Row category','Column category','Nonnegative integer cell count']};
for(const t of volume14Catalog)volume14English[t.id].fields=t.fields.map(([key,type],i)=>[key,type,labels[t.id][i]]);
