import {populationId} from './data-identity.js';
import * as d3 from 'd3';
import {measurementDomain} from './axis-policy.js';
import {phase7 as phase,number7 as fmt,num7 as num,label7 as label} from './volume7-utils.js';
import {t12,groups12,lorenz12,pp12,delta12,ecdfDifference12,quantileDots12,bins12,densityGrid12,halfeye12} from './volume12-data.js';
const groupColor=(s,g,i)=>s.theme.groupColor?.(g,s.theme.color(i))||s.theme.color(i);
const shade=(s,v,max)=>s.theme.valueColor?.(v,[0,max])??d3.interpolateRgb(s.theme.bg,s.theme.accent)(.08+.88*v/(max||1));
const probability=v=>`${Math.round(v*100)}%`;
// A saved work declares comparison direction once; row sorting must not reverse it.
const comparisonRows=doc=>Array.isArray(doc.groupOrder)&&doc.groupOrder.length===2&&new Set(doc.groupOrder).size===2&&doc.groupOrder.every(g=>doc.data.some(r=>r.group===g))&&doc.data.every(r=>doc.groupOrder.includes(r.group))?doc.groupOrder.flatMap(g=>doc.data.filter(r=>r.group===g)):doc.data;
function frame(s,xd,yd,{left=s.compact?43:55,top=32,bottom=s.h-43,right=s.w-19,xlabel='',ylabel='',xformat=fmt,yformat=fmt,tickOffset=16,labelOffset=33}={}){
 const x=d3.scaleLinear(xd,[left,right]),y=d3.scaleLinear(yd,[bottom,top]);
 for(const v of y.ticks(s.compact?3:4)){s.line(left,y(v),right,y(v),{'stroke-width':.55,'stroke-dasharray':'2 4'});num(s,left-7,y(v)+3,yformat(v),{'text-anchor':'end','font-size':s.fs-2});}
 for(const v of x.ticks(s.compact?3:5)){s.line(x(v),bottom,x(v),bottom+4,{'stroke-width':.6});num(s,x(v),bottom+tickOffset,xformat(v),{'text-anchor':'middle','font-size':s.fs-2});}
 s.line(left,bottom,right,bottom,{'stroke-width':.7});label(s,left,top-12,ylabel,{'font-size':s.fs-2},s.compact?28:65);label(s,right,bottom+labelOffset,xlabel,{'text-anchor':'end','font-size':s.fs-2},s.compact?28:65);return{x,y,left,right,top,bottom};
}
function recordAttrs(row){return{'data-record-id':row._id,'data-record-label':row.label};}
function rawRug(s,rows,x,y,{color=s.theme.secondary,field='value',height=5,delay=.2,parent}={}){rows.forEach((row,i)=>{const px=x(row[field]),mark=s.line(px,y,px,y+height,{stroke:color,'stroke-width':1,'stroke-opacity':.48,'data-mark':'distribution-raw',...recordAttrs(row),'data-value':row[field]},parent);s.reveal(mark,delay+i/rows.length*.22,.33);s.edit(mark,row,field);s.tip(mark,`${row.label}${row.group?' · '+row.group:''}\n${field}: ${String(row[field])} ${s.doc.unit}\n${t12('原始观测','Raw observation')}`);});}
function reference(s,f,y=0){s.line(f.left,f.y(y),f.right,f.y(y),{stroke:s.theme.secondary,'stroke-width':1,'stroke-dasharray':'4 4'});}
function lorenz(s,doc){const populationColor=s.theme.objectColor(populationId('sample-group',doc.data),s.theme.accent);
 const stats=lorenz12(doc.data),f=frame(s,[0,1],[0,1],{xlabel:t12('累计样本份额','Cumulative sample share'),ylabel:t12('累计资源份额','Cumulative resource share'),xformat:probability,yformat:probability}),{x,y}=f,g=s.group();
 s.line(x(0),y(0),x(1),y(1),{stroke:s.theme.secondary,'stroke-dasharray':'4 4','data-mark':'lorenz-equality'});
 const fill=s.path(d3.area().x(d=>x(d.population)).y0(d=>y(d.population)).y1(d=>y(d.share))(stats.points),{fill:populationColor,'fill-opacity':.10},g),curve=s.path(d3.line().x(d=>x(d.population)).y(d=>y(d.share))(stats.points),{stroke:populationColor,'stroke-width':2,'data-mark':'lorenz-curve','data-gini':stats.gini},g);s.draw(curve,.08,.75);s.reveal(fill,.06,.65);
 stats.points.slice(1).forEach((p,i)=>{const mark=s.circle(x(p.population),y(p.share),s.compact?1.8:2.5,{fill:populationColor,'data-mark':'lorenz-point','data-population':p.population,'data-share':p.share,...recordAttrs(p.row)},g);s.growCircle(mark,s.compact?1.8:2.5,i/doc.data.length*.38,.38);s.edit(mark,p.row,'value');s.tip(mark,`${p.row.label}: ${String(p.row.value)} ${doc.unit}\n${t12('累计样本','Cumulative sample')}: ${probability(p.population)}\n${t12('累计资源','Cumulative resource')}: ${fmt(p.share*100)}%`);});
 label(s,f.left+10,f.top+18,`Gini ${fmt(stats.gini,{significantDigits:4})}`,{'font-size':s.fs+3,fill:s.theme.fg},25);label(s,f.left+10,f.top+36,t12('虚线：完全均等','Dashed: equal distribution'),{'font-size':s.fs-2},35);
}
function ppplot(s,doc){const populationColor=s.theme.objectColor(populationId('sample-group',doc.data),s.theme.accent);
 const points=pp12(doc.data,doc.referenceMean,doc.referenceSD),f=frame(s,[0,1],[0,1],{xlabel:t12('参考正态累计概率','Reference normal CDF'),ylabel:t12('经验累计概率','Empirical CDF'),xformat:probability,yformat:probability});s.line(f.x(0),f.y(0),f.x(1),f.y(1),{stroke:s.theme.secondary,'stroke-dasharray':'4 4'});
 points.forEach((p,i)=>{const r=s.compact?2.1:3,mark=s.circle(f.x(p.theoretical),f.y(p.empirical),r,{fill:populationColor,'fill-opacity':.7,'data-mark':'pp-point','data-theoretical':p.theoretical,'data-empirical':p.empirical,...recordAttrs(p.row)});s.add(progress=>{const q=phase(progress,i/points.length*.34,.5);mark.setAttribute('cy',f.y(p.theoretical+(p.empirical-p.theoretical)*q));mark.setAttribute('r',r*Math.sqrt(q));});s.edit(mark,p.row,'value');s.tip(mark,`${p.row.label}: ${String(p.row.value)} ${doc.unit}\nF₀: ${fmt(p.theoretical)} · Fₙ: ${fmt(p.empirical)}`);});
 label(s,f.left+8,f.top+15,`N(${fmt(doc.referenceMean)}, ${fmt(doc.referenceSD)}²)`,{fill:s.theme.fg,'font-size':s.fs-1},35);
}
function deltaplot(s,doc){
 const stats=delta12(comparisonRows(doc)),difference=stats.points.map(d=>d.difference),f=frame(s,[0,1],measurementDomain([...difference,0],{padding:.15}),{bottom:s.h-111,xlabel:t12('分位概率 p','Quantile probability p'),ylabel:`${stats.groups[1]} − ${stats.groups[0]} / ${doc.unit}`,xformat:probability});reference(s,f);const g=s.group(),line=s.path(d3.line().x(p=>f.x(p.p)).y(p=>f.y(p.difference))(stats.points),{stroke:s.theme.accent,'stroke-width':2,'data-mark':'delta-line'},g);s.draw(line,.05,.7);
 stats.points.forEach((p,i)=>{const mark=s.circle(f.x(p.p),f.y(p.difference),3,{fill:s.theme.accent,'data-mark':'delta-point','data-quantile':p.p,'data-value':p.difference});s.add(progress=>{const q=phase(progress,i/stats.points.length*.3,.5);mark.setAttribute('cy',f.y(p.difference*q));mark.setAttribute('r',3*Math.sqrt(q));});s.tip(mark,`p=${probability(p.p)}\n${stats.groups[0]}: ${fmt(p.a)} ${doc.unit}\n${stats.groups[1]}: ${fmt(p.b)} ${doc.unit}\nΔ: ${fmt(p.difference)} ${doc.unit}`);});
 const rx=d3.scaleLinear(measurementDomain(doc.data.map(d=>d.value),{padding:.03}),[f.left,f.right]),base=s.h-48;label(s,f.left,base-14,t12('原始值（独立横轴）','Raw values (separate X axis)'),{'font-size':s.fs-3},35);
 stats.groups.forEach((group,i)=>{const col=groupColor(s,group,i),rows=doc.data.filter(r=>r.group===group);label(s,f.left-7,base+i*12+4,group,{'text-anchor':'end',fill:col,'font-size':s.fs-2},6);rawRug(s,rows,rx,base+i*12,{color:col,height:7});});
 rx.ticks(s.compact?3:5).forEach(v=>num(s,rx(v),s.h-10,fmt(v),{'font-size':s.fs-3,'text-anchor':'middle'}));label(s,f.right,s.h-1,doc.unit,{'text-anchor':'end','font-size':s.fs-3},20);
}
function ecdfdiff(s,doc){
 const stats=ecdfDifference12(comparisonRows(doc)),xd=measurementDomain(doc.data.map(d=>d.value),{padding:.05}),limit=Math.min(1,Math.max(.1,stats.maxDifference*1.2)),f=frame(s,xd,[-limit,limit],{xlabel:doc.unit,ylabel:`F_${stats.groups[1]} − F_${stats.groups[0]}`,yformat:probability,bottom:s.h-70,tickOffset:30,labelOffset:48}),points=[{value:xd[0],difference:0},...stats.points,{value:xd[1],difference:0}],g=s.group();reference(s,f);
 const shape=s.path(d3.area().x(d=>f.x(d.value)).y0(f.y(0)).y1(d=>f.y(d.difference)).curve(d3.curveStepAfter)(points),{fill:s.theme.accent,'fill-opacity':.15},g),line=s.path(d3.line().x(d=>f.x(d.value)).y(d=>f.y(d.difference)).curve(d3.curveStepAfter)(points),{stroke:s.theme.accent,'stroke-width':1.6,'data-mark':'ecdf-difference','data-max-difference':stats.maxDifference},g);s.clipReveal(g,f.left,f.top,f.right-f.left,f.bottom-f.top,.05,.78);
 stats.points.forEach(p=>{const mark=s.circle(f.x(p.value),f.y(p.difference),1.8,{fill:s.theme.accent,'data-mark':'ecdf-difference-point','data-value':p.value,'data-difference':p.difference},g);s.tip(mark,`${doc.unit}: ${fmt(p.value)}\n${stats.groups[0]}: ${fmt(p.a*100)}%\n${stats.groups[1]}: ${fmt(p.b*100)}%\nΔ: ${fmt(p.difference*100)} ${t12('百分点','percentage points')}`);});
 stats.groups.forEach((group,i)=>rawRug(s,doc.data.filter(r=>r.group===group),f.x,f.bottom+6+i*6,{color:groupColor(s,group,i),height:4}));label(s,f.left+7,f.top+16,`D = ${fmt(stats.maxDifference,{significantDigits:3})}`,{fill:s.theme.fg,'font-size':s.fs-1},25);s.tip(shape,t12('概率差面积，不是密度或频数','Area of probability differences; not density or counts'));s.tip(line,t12('右连续经验分布差','Right-continuous empirical CDF difference'));
}
function quantiledot(s,doc){
 const points=quantileDots12(doc.data,doc.dotCount),left=s.compact?36:48,right=s.w-20,top=40,bottom=s.h-51,x=d3.scaleLinear(measurementDomain(doc.data.map(d=>d.value),{padding:.05}),[left,right]);
 // Preserve exact quantile X values. Deterministic vertical stacks only avoid overlap.
 let radius=Math.min(s.compact?4.5:7.5,(right-left)/30),placed=[];
 const pack=r=>{const result=[];for(const point of points){const px=x(point.value);let level=0;while(result.some(d=>Math.abs(d.x-px)<r*2.15&&Math.abs(d.level-level)<.5))level++;result.push({...point,x:px,level});}return result;};
 placed=pack(radius);for(let i=0;i<20&&(d3.max(placed,d=>d.level)+1)*radius*2.2>bottom-top;i++){radius*=.85;placed=pack(radius);}
 s.line(left,bottom,right,bottom);x.ticks(s.compact?3:5).forEach(v=>num(s,x(v),bottom+19,fmt(v),{'text-anchor':'middle','font-size':s.fs-2}));label(s,right,s.h-2,doc.unit,{'text-anchor':'end','font-size':s.fs-2},30);
 placed.forEach((p,i)=>{const mark=s.circle(p.x,bottom-radius-p.level*radius*2.2,radius,{fill:s.theme.accent,'fill-opacity':.84,'data-mark':'quantile-dot','data-value':p.value,'data-probability':p.p,'data-mass':p.mass});s.add(progress=>{const q=phase(progress,i/doc.dotCount*.4,.45);mark.setAttribute('cy',bottom-(radius+p.level*radius*2.2)*q);mark.setAttribute('r',radius*Math.sqrt(q));});s.tip(mark,`${t12('派生分位点','Derived quantile')} p=${fmt(p.p)}\n${fmt(p.value)} ${doc.unit}\n${t12('概率质量','Probability mass')}: ${fmt(p.mass*100)}%`);});
 rawRug(s,doc.data,x,bottom+4,{height:5});label(s,left,16,`${t12('每点','Each dot')} ${fmt(100/doc.dotCount)}% · n=${doc.data.length}`,{fill:s.theme.fg,'font-size':s.fs-1},50);label(s,left,31,t12('短线为原始观测 · 堆叠高度仅用于避让','Rug: raw observations · stacking only avoids overlap'),{'font-size':s.fs-3},s.compact?40:80);
}
function scatterRows(s,doc,x,y){doc.data.forEach((row,i)=>{const mark=s.circle(x(row.x),y(row.y),s.compact?1.2:1.6,{fill:s.theme.fg,'fill-opacity':.38,'data-mark':'distribution-xy',...recordAttrs(row),'data-x':row.x,'data-y':row.y});s.reveal(mark,.35+i/doc.data.length*.2,.25);s.edit(mark,row,'x');s.tip(mark,`${row.label}\n${doc.axes.x}: ${String(row.x)}\n${doc.axes.y}: ${String(row.y)}\n${t12('原始坐标；点击编辑 X','Raw coordinates; click to edit X')}`);const yTarget=s.circle(x(row.x),y(row.y),s.compact?3:4,{fill:'none',stroke:'transparent','stroke-width':3,'pointer-events':'stroke','data-mark':'distribution-y-edit',...recordAttrs(row)});s.edit(yTarget,row,'y');s.tip(yTarget,`${row.label}\n${doc.axes.x}: ${String(row.x)}\n${doc.axes.y}: ${String(row.y)}\n${t12('原始坐标；点击编辑 Y','Raw coordinates; click to edit Y')}`);});}
function histogram2d(s,doc){
 const model=bins12(doc.data,doc.binsX,doc.binsY),f=frame(s,model.xd,model.yd,{xlabel:doc.axes.x,ylabel:doc.axes.y,top:48,right:s.w-(s.compact?38:56)}),max=d3.max(model.cells,c=>c.count);
 model.cells.forEach((c,i)=>{const mark=s.rect(f.x(c.x0),f.y(c.y1),f.x(c.x1)-f.x(c.x0),f.y(c.y0)-f.y(c.y1),{fill:shade(s,c.count,max),stroke:s.theme.bg,'stroke-width':.7,'data-mark':'histogram2d-bin','data-count':c.count,'data-record-ids':JSON.stringify(c.rows.map(r=>r._id).filter(Boolean))});s.reveal(mark,(c.ix+c.iy)/(doc.binsX+doc.binsY)*.3,.55);s.tip(mark,`X: [${fmt(c.x0)}, ${fmt(c.x1)}${c.ix===doc.binsX-1?']':')'}\nY: [${fmt(c.y0)}, ${fmt(c.y1)}${c.iy===doc.binsY-1?']':')'}\n${t12('频数','Count')}: ${c.count}`);});
 scatterRows(s,doc,f.x,f.y);const lx=f.right+9,ly=f.top,lh=Math.min(110,f.bottom-f.top);for(let i=0;i<32;i++)s.rect(lx,ly+i*lh/32,7,lh/32+.2,{fill:shade(s,max*(1-i/31),max)});num(s,lx+10,ly+4,max,{'font-size':s.fs-3});num(s,lx+10,ly+lh,0,{'font-size':s.fs-3});label(s,lx-2,ly-9,t12('计数','Count'),{'font-size':s.fs-3},8);label(s,f.left,17,`n=${doc.data.length} · ${doc.binsX}×${doc.binsY} ${t12('箱','bins')}`,{fill:s.theme.fg,'font-size':s.fs-2},45);
}
function density2d(s,doc){
 const model=densityGrid12(doc.data,doc.bandwidthX,doc.bandwidthY),f=frame(s,model.xd,model.yd,{xlabel:doc.axes.x,ylabel:doc.axes.y,top:62}),levels=[.15,.3,.5,.7,.9].map(p=>model.max*p),contours=d3.contours().size([model.nx,model.ny]).thresholds(levels)(model.values),transform=d3.geoTransform({point(px,py){this.stream.point(f.left+px/model.nx*(f.right-f.left),f.bottom-py/model.ny*(f.bottom-f.top));}}),path=d3.geoPath(transform),g=s.group();
 contours.forEach((contour,i)=>{const mark=s.path(path(contour),{fill:shade(s,contour.value,model.max),'fill-opacity':.60,stroke:s.theme.accent,'stroke-width':.7,'stroke-opacity':.55,'data-mark':'density2d-contour','data-density':contour.value},g);s.reveal(mark,i*.085,.5);s.tip(mark,`${t12('密度 ≥','Density ≥')} ${fmt(contour.value)} ${doc.unit}\n${t12('不是概率覆盖区间','Not a probability-coverage interval')}`);});
 scatterRows(s,doc,f.x,f.y);label(s,f.left,14,`${t12('高斯核','Gaussian KDE')} · h=(${fmt(doc.bandwidthX)}, ${fmt(doc.bandwidthY)})`,{fill:s.theme.fg,'font-size':s.fs-2},55);label(s,f.left,28,`${t12('密度层级','Density levels')}: ${levels.map(v=>fmt(v,{significantDigits:2})).join(' / ')} ${doc.unit}`,{'font-size':s.fs-3},s.compact?45:95);
}
function halfeye(s,doc){
 const model=halfeye12(doc.data,doc.bandwidth),left=s.compact?42:60,right=s.w-20,top=38,bottom=s.h-45,step=(bottom-top)/model.curves.length,amp=step*.57,x=d3.scaleLinear(model.domain,[left,right]);
 x.ticks(s.compact?3:5).forEach(v=>{s.line(x(v),top,x(v),bottom,{'stroke-width':.5,'stroke-dasharray':'2 5'});num(s,x(v),bottom+18,fmt(v),{'text-anchor':'middle','font-size':s.fs-2});});label(s,right,s.h-3,doc.unit,{'text-anchor':'end','font-size':s.fs-2},25);
 model.curves.forEach((curve,i)=>{const baseline=top+(i+.82)*step,col=groupColor(s,curve.group,i),g=s.group({'data-group':curve.group}),shape=s.path('',{fill:col,'fill-opacity':.22,stroke:col,'stroke-width':1.1,'data-mark':'halfeye-density','data-max-density':d3.max(curve.points,p=>p.density)},g);s.add(progress=>{const q=phase(progress,i*.065,.65);shape.setAttribute('d',d3.area().x(p=>x(p.value)).y0(baseline).y1(p=>baseline-p.density/model.max*amp*q).curve(d3.curveMonotoneX)(curve.points));});s.tip(shape,`${curve.group} · n=${curve.samples.length}\n${t12('高斯密度；组间共用密度高度尺度','Gaussian density; shared height scale across groups')}\nh=${fmt(doc.bandwidth)} ${doc.unit}`);
  const intervalY=baseline+8;for(const [range,width,name]of[[curve.outer,1.3,'90%'],[curve.inner,4,'50%']]){const mark=s.line(x(range[0]),intervalY,x(range[1]),intervalY,{stroke:col,'stroke-width':width,'stroke-linecap':'round','data-mark':'halfeye-interval','data-coverage':name,'data-low':range[0],'data-high':range[1]},g);s.add(progress=>{const q=phase(progress,.15+i*.06,.55);mark.setAttribute('x1',x(curve.median+(range[0]-curve.median)*q));mark.setAttribute('x2',x(curve.median+(range[1]-curve.median)*q));});s.tip(mark,`${curve.group} · ${name} ${t12('中央分位区间','central quantile interval')}\n[${fmt(range[0])}, ${fmt(range[1])}] ${doc.unit}`);}
  const dot=s.circle(x(curve.median),intervalY,3,{fill:s.theme.bg,stroke:col,'stroke-width':1.6,'data-mark':'halfeye-median','data-value':curve.median},g);s.growCircle(dot,3,.2+i*.05,.45);s.tip(dot,`${curve.group} · ${t12('中位数','Median')}: ${fmt(curve.median)} ${doc.unit}`);rawRug(s,curve.samples,x,baseline+15,{color:col,height:4,parent:g});label(s,left-8,baseline+2,curve.group,{'text-anchor':'end',fill:col,'font-size':s.fs-1},s.compact?4:9);
 });label(s,left,14,t12('粗线 50% · 细线 90% · 点：中位数','Thick 50% · thin 90% · dot: median'),{fill:s.theme.fg,'font-size':s.fs-2},s.compact?40:65);label(s,left,28,t12('中央样本区间，非均值置信区间','Central sample intervals, not mean confidence intervals'),{'font-size':s.fs-3},s.compact?40:75);
}
export const volume12Renderers={lorenz,ppplot,deltaplot,ecdfdiff,quantiledot,histogram2d,density2d,halfeye};
