import * as d3 from 'd3';
import {labelInk} from './chart-readability.js';
import world13 from './datasets/world-110m.json' with {type:'json'};
import {t13,hierarchy13,tornado13,cohorts13,venn13,cyclicFlow13} from './volume13-data.js';
import {phase7 as phase,number7 as fmt,num7 as num,label7 as label} from './volume7-utils.js';
const rowTip=(row,unit,keys)=>keys.map(key=>`${key}: ${String(row[key])}`).join('\n')+(unit?`\n${unit}`:'');
const cat=(s,i)=>s.theme.color(i),caption=(s,text)=>label(s,12,s.h-3,text,{'font-size':s.fs-3},s.compact?47:100);
function arrow(s,name,color){const id=`${s.id}-${name}`,m=s.el('marker',{id,viewBox:'0 0 8 8',refX:6.5,refY:4,markerWidth:5,markerHeight:5,orient:'auto',markerUnits:'userSpaceOnUse'},s.defs);s.path('M0,0L8,4L0,8Z',{fill:color},m);return`url(#${id})`;}
function geoflow(s,doc){
 const projection=d3.geoNaturalEarth1().fitExtent([[12,14],[s.w-12,s.h-30]],{type:'Sphere'}),path=d3.geoPath(projection),base=s.group(),flows=s.group(),max=d3.max(doc.data,d=>d.value),points=new Map();
 s.path(path(d3.geoGraticule10()),{stroke:s.theme.line,'stroke-width':.35,'stroke-opacity':.65},base);
 world13.features.forEach(f=>s.path(path(f),{fill:s.theme.fg,'fill-opacity':.035,stroke:s.theme.line,'stroke-width':.4},base));
 const end=arrow(s,'geo-arrow',s.theme.accent);
 doc.data.forEach((row,i)=>{const from=[row.sourceLongitude,row.sourceLatitude],to=[row.targetLongitude,row.targetLatitude],interpolate=d3.geoInterpolate(from,to),coordinates=Array.from({length:81},(_,j)=>interpolate(j/80)),geometry={type:'LineString',coordinates};
  // Width uses a zero-origin linear magnitude scale, including small flows.
  const mark=s.path(path(geometry),{stroke:s.theme.accent,'stroke-width':4*row.value/max,'stroke-opacity':.7,'stroke-linecap':'round','marker-end':end,'data-mark':'geoflow-link','data-value':row.value,'data-source':row.source,'data-target':row.target},flows);
  s.draw(mark,i/doc.data.length*.25,.6);s.tip(mark,`${row.source} → ${row.target}\n${rowTip(row,doc.unit,['value','sourceLongitude','sourceLatitude','targetLongitude','targetLatitude'])}`);s.edit(mark,row,'value');
  points.set(row.source,from);points.set(row.target,to);
 });
 for(const[name,point]of points){const [x,y]=projection(point);const m=s.circle(x,y,2,{fill:s.theme.bg,stroke:s.theme.accent,'stroke-width':1});s.tip(m,`${name}\n${point[0]}°, ${point[1]}°`);label(s,x+4,y-4,name,{'font-size':s.fs-3,fill:s.theme.secondary},s.compact?6:13);}
 caption(s,t13('线宽 = 流量 · 方向看箭头 · Natural Earth 1:110m','Width = flow · arrows show direction · Natural Earth 1:110m'));
}
function circlehierarchy(s,doc){
 const source=hierarchy13(doc.data),root=d3.hierarchy(source.root,n=>n.children).sum(n=>n.children.length?0:n.row.value).sort((a,b)=>b.value-a.value),size=Math.max(30,Math.min(s.w-30,s.h-34)),packed=d3.pack().size([size,size]).padding(s.compact?2.5:4)(root),ox=(s.w-size)/2,oy=(s.h-24-size)/2;
 packed.descendants().forEach((node,i)=>{const row=node.data.row,leaf=!node.children,branch=node.ancestors().find(n=>n.depth===1),color=cat(s,branch?root.children.indexOf(branch):0),mark=s.circle(ox+node.x,oy+node.y,node.r,{fill:leaf?color:s.theme.fg,'fill-opacity':leaf?.2:.025,stroke:leaf?color:s.theme.line,'stroke-width':leaf?.8:.7,'data-mark':'hierarchy-circle','data-node-id':row.id,'data-leaf':leaf,'data-value':row.value,'data-total':node.value});
  s.growCircle(mark,node.r,node.depth*.055,.55);s.edit(mark,row,'value');s.tip(mark,`${row.label}\nid: ${row.id}\nparent: ${row.parent}\nvalue: ${row.value}\n${t13('叶值合计','Leaf total')}: ${node.value} ${doc.unit}`);
  if(leaf&&node.r>(s.compact?11:14)){const tx=label(s,ox+node.x,oy+node.y-1,row.label,{'text-anchor':'middle','font-size':s.fs-2,fill:labelInk(s.theme.bg,s.theme.fg)},Math.max(2,node.r*1.4/(s.fs-2)));s.reveal(tx,.45+node.depth*.035,.2);if(node.r>17){const n=num(s,ox+node.x,oy+node.y+12,fmt(row.value),{'text-anchor':'middle','font-size':s.fs-3});s.reveal(n,.55,.2);}}
  else if(!leaf&&node.depth===1&&node.r>22){const tx=label(s,ox+node.x,oy+node.y-node.r+12,row.label,{'text-anchor':'middle','font-size':s.fs-3},Math.max(3,node.r/(s.fs-3)));s.reveal(tx,.55,.2);}
 });caption(s,t13('叶圆面积 = 数量；父圆面积包含布局留白','Leaf area = quantity; parent area includes layout padding'));
}
function radialtree(s,doc){
 const source=hierarchy13(doc.data),root=d3.hierarchy(source.root,n=>n.children),radius=Math.max(24,Math.min(s.w-110,s.h-62)/2),cx=s.w/2,cy=(s.h-24)/2,tree=d3.tree().size([2*Math.PI,radius]).separation((a,b)=>(a.parent===b.parent?1:1.5)/a.depth)(root),group=s.group({transform:`translate(${cx},${cy})`}),path=d3.linkRadial().angle(d=>d.x).radius(d=>d.y),max=d3.max(doc.data,d=>d.value);
 for(let level=1;level<=source.depth;level++)s.circle(0,0,radius*level/source.depth,{fill:'none',stroke:s.theme.line,'stroke-width':.4,'stroke-dasharray':'1 5'},group);
 tree.links().forEach(link=>{const p=s.path(path(link),{stroke:s.theme.secondary,'stroke-width':.8,'stroke-opacity':.7,'data-mark':'radialtree-edge','data-parent':link.source.data.row.id,'data-child':link.target.data.row.id},group);s.draw(p,link.source.depth*.075,.52);s.tip(p,`${link.source.data.row.label} → ${link.target.data.row.label}`);});
 tree.descendants().forEach(node=>{const leaf=!node.children,x=Math.sin(node.x)*node.y,y=-Math.cos(node.x)*node.y,row=node.data.row,branch=node.ancestors().find(n=>n.depth===1),color=cat(s,branch?root.children.indexOf(branch):0),r=leaf?6*Math.sqrt(row.value/max):2.3,c=s.circle(x,y,r,{fill:leaf?color:s.theme.bg,stroke:leaf?color:s.theme.secondary,'stroke-width':.75,'data-mark':'radialtree-node','data-node-id':row.id,'data-value':row.value,'data-total':node.data.total},group);s.growCircle(c,r,node.depth*.075,.5);s.edit(c,row,'value');s.tip(c,`${row.label}\nid: ${row.id}\nparent: ${row.parent}\nvalue: ${row.value}\n${t13('叶值合计','Leaf total')}: ${node.data.total} ${doc.unit}`);
  if(leaf||node.depth===0){const right=Math.sin(node.x)>=0,tx=label(s,x+(node.depth===0?0:right?8:-8),y+(node.depth===0?-8:3),row.label,{'text-anchor':node.depth===0?'middle':right?'start':'end','font-size':s.fs-3,fill:s.theme.fg},s.compact?4:8,group);s.reveal(tx,.5+node.depth*.04,.2);}
 });caption(s,t13('枝长与角度仅为布局；叶点面积 = 数量','Branch length / angle are layout only; leaf-marker area = quantity'));
}
function tornado(s,doc){
 const rows=tornado13(doc),left=s.compact?70:108,right=s.w-24,top=38,bottom=s.h-32,x=d3.scaleLinear(s.linearDomain([doc.baseline,...doc.data.flatMap(d=>[d.low,d.high])]),[left,right]).nice(4),y=d3.scaleBand(rows.map(d=>d.row.parameter),[top,bottom]).padding(.25),high=s.theme.accent,low=[...s.theme.colors,s.theme.secondary,s.theme.fg].find(color=>color.toLowerCase()!==high.toLowerCase());
 x.ticks(s.compact?3:5).forEach(v=>{s.line(x(v),top-5,x(v),bottom,{'stroke-width':.5,'stroke-dasharray':'1 5'});num(s,x(v),bottom+16,fmt(v),{'text-anchor':'middle','font-size':s.fs-3});});s.line(x(doc.baseline),top-8,x(doc.baseline),bottom,{stroke:s.theme.fg,'stroke-width':1,'stroke-dasharray':'3 3'});s.legend([{label:t13('低情景','Low scenario'),color:low},{label:t13('高情景','High scenario'),color:high}],left,13);
 rows.forEach(({row},i)=>{const yy=y(row.parameter),bh=y.bandwidth()/2;label(s,left-7,yy+y.bandwidth()/2+3,row.parameter,{'text-anchor':'end','font-size':s.fs-2,fill:s.theme.fg},s.compact?5:10);for(const[field,color,offset]of[['low',low,0],['high',high,bh]]){const b=s.rect(Math.min(x(doc.baseline),x(row[field])),yy+offset,Math.abs(x(row[field])-x(doc.baseline)),Math.max(1,bh-1),{fill:color,'fill-opacity':.68,'data-mark':'tornado-scenario','data-scenario':field,'data-value':row[field]});s.add(p=>{const q=phase(p,i/rows.length*.25,.6),end=x(doc.baseline)+(x(row[field])-x(doc.baseline))*q;b.setAttribute('x',Math.min(x(doc.baseline),end));b.setAttribute('width',Math.abs(end-x(doc.baseline)));});s.edit(b,row,field);s.tip(b,`${row.parameter}\n${field}: ${row[field]} ${doc.unit}\nbaseline: ${doc.baseline}\nΔ: ${row[field]-doc.baseline}`);const dot=s.circle(x(row[field]),yy+offset+(bh-1)/2,1.75,{fill:color,'data-mark':'tornado-endpoint'});s.reveal(dot,.6+i/rows.length*.2,.15);s.edit(dot,row,field);s.tip(dot,`${row.parameter}\n${field}: ${row[field]} ${doc.unit}`);}});
 caption(s,`${t13('基准','Baseline')}: ${fmt(doc.baseline)} ${doc.unit} · ${t13('一次改变一个参数','one parameter at a time')}`);
}
function cohortcurve(s,doc){
 const groups=cohorts13(doc),left=43,right=s.w-22,bottom=s.h-39,legendBottom=s.legend(groups.map((g,i)=>({label:g.cohort,color:s.theme.groupColor?.(g.cohort,cat(s,i))||cat(s,i)})),left,12),top=Math.max(35,legendBottom+10),x=d3.scaleLinear([0,d3.max(doc.data,d=>d.period)],[left,right]),y=d3.scaleLinear([0,1],[bottom,top]);
 for(const v of[0,.25,.5,.75,1]){s.line(left,y(v),right,y(v),{'stroke-width':.5,'stroke-dasharray':'1 5'});num(s,left-7,y(v)+3,`${v*100}%`,{'text-anchor':'end','font-size':s.fs-3});}for(const v of x.ticks(s.compact?4:6).filter(Number.isInteger))num(s,x(v),bottom+16,v,{'text-anchor':'middle','font-size':s.fs-3});
 groups.forEach((group,i)=>{const color=s.theme.groupColor?.(group.cohort,cat(s,i))||cat(s,i),g=s.group({'data-mark':'cohort-series','data-cohort':group.cohort}),line=d3.line().x(d=>x(d.row.period)).y(d=>y(d.rate));s.path(line(group.rows),{stroke:color,'stroke-width':1.6,'data-mark':'cohort-line'},g);group.rows.forEach(({row,rate})=>{const m=s.circle(x(row.period),y(rate),s.compact?1.8:2.5,{fill:s.theme.bg,stroke:color,'stroke-width':1,'data-mark':'cohort-point','data-period':row.period,'data-retained':row.retained,'data-size':row.size,'data-rate':rate},g);s.edit(m,row,'retained');s.tip(m,`${row.cohort}\n${row.period} ${doc.periodUnit}\nretained: ${row.retained}\nsize: ${row.size}\n${rate*100}%`);});s.clipReveal(g,left-4,top-5,right-left+8,bottom-top+10,i/groups.length*.1,.72);});caption(s,`${t13('群龄','Cohort age')} / ${doc.periodUnit} · ${t13('分母为各群起始人数','fixed initial cohort denominators')}`);
}
function venn(s,doc){
 const stats=venn13(doc),r=Math.max(24,Math.min(s.w/3.45,(s.h-66)/2.7)),cx=s.w/2,cy=(s.h-31)/2,centers=[[-.48,-.26],[.48,-.26],[0,.57]],labelPlaces=[[-1.01,-.98],[1.01,-.98],[0,1.64]],positions={1:[-.88,-.39],2:[.88,-.39],4:[0,1.03],3:[0,-.63],5:[-.44,.37],6:[.44,.37],7:[0,.04]};
 centers.forEach(([dx,dy],i)=>{const c=s.circle(cx+dx*r,cy+dy*r,r,{fill:cat(s,i),'fill-opacity':.11,stroke:cat(s,i),'stroke-width':1,'data-mark':'venn-set','data-set':doc.sets[i]});s.growCircle(c,r,i*.06,.55);s.tip(c,`${doc.sets[i]}\n${t13('集合总数','Set total')}: ${stats.setTotals[i]} ${doc.unit}`);const [lx,ly]=labelPlaces[i];label(s,cx+lx*r,cy+ly*r,doc.sets[i],{'text-anchor':'middle','font-size':s.fs-1,fill:cat(s,i)},s.compact?7:12);});
 stats.regions.forEach(({row,mask},i)=>{const [dx,dy]=positions[mask],x=cx+dx*r,y=cy+dy*r,g=s.group({'data-mark':'venn-region','data-mask':mask,'data-count':row.count}),hit=s.rect(x-15,y-12,30,20,{fill:s.theme.bg,'fill-opacity':.001},g),n=num(s,x,y+3,fmt(row.count),{'text-anchor':'middle','font-size':s.fs,fill:s.theme.fg},g);for(const mark of[hit,n]){s.edit(mark,row,'count');s.tip(mark,`${row.members}\n${t13('仅属于这些集合','Exactly these sets')}: ${row.count} ${doc.unit}`);}s.reveal(g,.48+i*.025,.25);});caption(s,t13('七个排他交集；区域面积不编码数量','Seven exclusive intersections; region area does not encode count'));
}
function sankeycycle(s,doc){
 const graph=cyclicFlow13(doc.data,{width:s.w,height:s.h,compact:s.compact}),flows=s.group();
 graph.links.forEach(l=>{const sx=l.source.x+l.source.width,tx=l.target.x,sy=l.y0,ty=l.y1,c=s.theme.groupColor?.(l.source.name,cat(s,l.source.index))||cat(s,l.source.index),bend=s.compact?12:18;
  const d=l.returning?`M${sx},${sy}C${sx+bend},${sy} ${sx+bend},${l.lane} ${sx},${l.lane}H${tx}C${tx-bend},${l.lane} ${tx-bend},${ty} ${tx},${ty}`:`M${sx},${sy}C${(sx+tx)/2},${sy} ${(sx+tx)/2},${ty} ${tx},${ty}`;
  const p=s.path(d,{stroke:c,'stroke-width':l.width,'stroke-opacity':.43,'stroke-linecap':'butt','data-mark':'cycle-link','data-source':l.row.source,'data-target':l.row.target,'data-value':l.row.value,'data-return':l.returning},flows);s.draw(p,l.index/doc.data.length*.16,.66);s.edit(p,l.row,'value');s.tip(p,`${l.row.source} → ${l.row.target}\n${l.row.value} ${doc.unit}${l.returning?'\n'+t13('回流通道','Return channel'):''}`);
  // Direction markers remain legible independently of quantitative link width.
  const a=arrow(s,`flow-${l.index}`,c),direction=s.path(d,{stroke:c,'stroke-width':.6,'stroke-opacity':.65,'marker-end':a,'pointer-events':'none'},flows);s.draw(direction,l.index/doc.data.length*.16,.66);
 });
 graph.nodes.forEach(n=>{const c=s.theme.groupColor?.(n.name,cat(s,n.index))||cat(s,n.index),r=s.rect(n.x,n.y,n.width,n.height,{fill:c,'fill-opacity':.8,'data-mark':'cycle-node','data-node':n.name,'data-incoming':n.incoming,'data-outgoing':n.outgoing,'data-balance':n.balance});s.reveal(r,.05+n.layer*.015,.35);s.tip(r,`${n.name}\n${t13('流入','In')}: ${n.incoming}\n${t13('流出','Out')}: ${n.outgoing}\n${t13('入−出','In−out')}: ${n.balance} ${doc.unit}`);const tx=label(s,n.x+n.width/2,n.y-6,n.name,{'text-anchor':'middle','font-size':s.fs-3,fill:s.theme.fg},s.compact?5:10);s.reveal(tx,.55,.2);});caption(s,t13('线宽 = 流量；节点不平衡保留，回流不等于新增','Width = flow; node imbalance retained; return flow is not new flow'));
}
function adjacency(s,doc){
 const left=s.compact?58:85,top=s.compact?48:60,right=s.w-16,bottom=s.h-30,n=doc.nodes.length,size=Math.max(30,Math.min(right-left,bottom-top)),cw=size/n,x0=left+(right-left-size)/2,y0=top+(bottom-top-size)/2,lookup=new Map(doc.data.map(r=>[JSON.stringify([r.source,r.target]),r])),max=d3.max(doc.data,d=>d.value)||1;
 const color=v=>s.theme.valueColor?.(v,[0,max])??d3.interpolateRgb(s.theme.bg,s.theme.accent)(.04+.86*v/max);
 doc.nodes.forEach((name,i)=>{label(s,x0-6,y0+(i+.5)*cw+3,name,{'text-anchor':'end','font-size':s.fs-3},s.compact?4:7);const tx=label(s,x0+(i+.5)*cw,y0-9,name,{'text-anchor':'start','font-size':s.fs-3,transform:`rotate(-35 ${x0+(i+.5)*cw} ${y0-9})`},s.compact?4:7);for(let j=0;j<n;j++){const row=lookup.get(JSON.stringify([name,doc.nodes[j]])),c=color(row.value),r=s.rect(x0+j*cw,y0+i*cw,cw-1,cw-1,{fill:c,stroke:i===j?s.theme.secondary:'none','stroke-width':.4,'data-mark':'adjacency-cell','data-source':row.source,'data-target':row.target,'data-value':row.value});s.reveal(r,(i+j)/(2*n)*.35,.5);s.edit(r,row,'value');s.tip(r,`${row.source} → ${row.target}\n${row.value} ${doc.unit}`);if(cw>=23){const text=num(s,x0+(j+.5)*cw,y0+(i+.5)*cw+3,fmt(row.value),{'text-anchor':'middle','font-size':s.fs-3,fill:labelInk(c,s.theme.fg)});s.reveal(text,.4+(i+j)/(2*n)*.25,.25);s.edit(text,row,'value');s.tip(text,`${row.source} → ${row.target}\n${row.value} ${doc.unit}`);}}});caption(s,t13('行 → 列 · 共同色阶从 0 开始 · 对角线为自身联系','Row → column · common zero-based color scale · diagonal = self-links'));
}
export const volume13Renderers={geoflow,circlehierarchy,radialtree,tornado,cohortcurve,venn,sankeycycle,adjacency};
