import * as d3 from 'd3';
import {isEnglish} from './locale.js';
import {volume19Catalog,volume19English} from './volume19-catalog.js';
export const t19=(zh,en)=>isEnglish()?en:zh;
const ids=new Set(volume19Catalog.map(t=>t.id));
export const groups19=rows=>[...new Set(rows.map(r=>r.group))];
export function response19(rows){return groups19(rows).map(group=>{let previous;const points=rows.filter(r=>r.group===group).sort((a,b)=>a.frequency-b.frequency).map(row=>{let phase=Math.atan2(row.imag,row.real)*180/Math.PI;if(previous!==undefined)phase+=360*Math.round((previous-phase)/360);previous=phase;const magnitude=Math.hypot(row.real,row.imag);return{row,magnitude,db:20*Math.log10(magnitude),phase};});return{group,points};});}
export function smith19(real,imag,z0){const scale=Math.max(Math.abs(real),Math.abs(imag),z0),r=real/scale,x=imag/scale,z=z0/scale,den=(r+z)**2+x*x;return{real:(r*r+x*x-z*z)/den,imag:2*x*z/den};}
export function windrose19(doc){const n=doc.windSectors,step=360/n,bins=doc.speedBreaks,cells=Array.from({length:n},(_,sector)=>bins.map((low,bin)=>({sector,bin,low,high:bins[bin+1]??null,rows:[],count:0,frequency:0,cumulative:0})));const calm=[];for(const row of doc.data){if(row.speed<doc.calmThreshold){calm.push(row);continue;}const sector=Math.floor((row.direction+step/2)%360/step),bin=Math.min(bins.length-1,d3.bisectRight(bins,row.speed)-1);cells[sector][bin].rows.push(row);cells[sector][bin].count++;}for(const sector of cells){let cumulative=0;for(const cell of sector){cell.frequency=cell.count/doc.data.length;cell.previous=cumulative;cumulative+=cell.frequency;cell.cumulative=cumulative;}}return{cells:cells.flat(),calm,calmFrequency:calm.length/doc.data.length,max:d3.max(cells,a=>a.at(-1).cumulative),step};}
export function polar19(angle,radius){const radians=angle*Math.PI/180;return{x:radius*Math.sin(radians),y:radius*Math.cos(radians)};}
export function phasor19(rows){return{real:d3.sum(rows,r=>r.real),imag:d3.sum(rows,r=>r.imag)};}
export function regular19(values){if(values.length<2)return false;const step=values[1]-values[0];return step>0&&Number.isFinite(step)&&values.every((v,i)=>Number.isFinite(v)&&(i===0||v>values[i-1])&&Math.abs(v-(values[0]+i*step))<=Math.max(step*1e-7,Math.min(step*1e-4,Math.abs(v)*Number.EPSILON*2)));}
export function eye19(doc){const rows=[...doc.data].sort((a,b)=>a.time-b.time),dt=rows[1].time-rows[0].time,samplesPerSymbol=Math.round(doc.symbolPeriod/dt),windowSize=2*samplesPerSymbol,map=new Map(),points=[];const add=(window,p)=>{if(!map.has(window))map.set(window,[]);map.get(window).push(p);};rows.forEach((row,i)=>{const sampleIndex=Math.round((row.time-doc.timeOrigin)/dt),window=Math.floor(sampleIndex/windowSize),offset=sampleIndex-window*windowSize,p={row,phase:offset/samplesPerSymbol,window};points.push(p);add(window,p);if(offset===0&&i>0)add(window-1,{row,phase:2,window:window-1});});return{dt,samplesPerSymbol,points,traces:[...map.entries()].sort((a,b)=>a[0]-b[0]).map(([window,points])=>({window,points}))};}
export function validateVolume19(doc,{fail,count,noDuplicates,warnings}){
 if(!ids.has(doc.template))return;const id=doc.template,rows=doc.data,finite=v=>typeof v==='number'&&Number.isFinite(v),positive=v=>finite(v)&&v>0,unit=v=>typeof v==='string'&&v.trim().length>0&&v.length<=80,bad=(zh,en)=>fail(t19(zh,en));
 const range={bode:[4,480],nyquist:[4,480],nichols:[4,480],polezero:[2,80],smith:[4,480],windrose:[12,1000],polarscatter:[5,400],hodograph:[4,100],phasor:[2,12],eyediagram:[24,1000],constellation:[8,1000],campbell:[4,600]}[id];count(rows.length,...range,t19('输入记录','input records'));
 if(id!=='campbell')noDuplicates(rows.map(r=>r.label),t19('观测编号','Observation labels'));
 const numeric=volume19Catalog.find(t=>t.id===id).fields.filter(f=>f[1]==='number').map(f=>f[0]);if(rows.some(r=>numeric.some(k=>!finite(r[k])))){bad('所有数值字段必须保留有限原值；缺测不补零。','All numeric fields require finite original values; missing measurements are not zero-filled.');return;}
 if(['bode','nyquist','nichols','smith'].includes(id)){
  const groups=groups19(rows);count(groups.length,1,4,t19('曲线','curves'));for(const group of groups){const part=rows.filter(r=>r.group===group);count(part.length,4,160,t19('每曲线采样','samples per curve'));noDuplicates(part.map(r=>r.frequency),t19('同曲线频率','Within-curve frequency'));}
  if(rows.some(r=>r.frequency<=0))bad('频率必须为正；当前图不补造直流或负频率数据。','Frequency must be positive; DC and negative-frequency data are not manufactured.');if(!unit(doc.frequencyUnit))bad('frequencyUnit 必须明确频率的单位。','frequencyUnit must declare the frequency unit.');
  if(['bode','nichols'].includes(id)&&rows.some(r=>!(Math.hypot(r.real,r.imag)>0)))bad('分贝与相位要求非零复响应；零响应不能替换成任意小数。','Decibels and phase require nonzero complex responses; zero responses cannot be replaced with arbitrary small values.');
  if(id==='smith'){if(rows.some(r=>r.real<0))bad('此阻抗史密斯图只支持非负电阻，负电阻不能裁剪进单位圆。','This impedance Smith chart supports nonnegative resistance; negative resistance cannot be clipped into the unit disk.');if(!positive(doc.referenceImpedance))bad('referenceImpedance 必须是正实参考阻抗，单位 Ω。','referenceImpedance must be a positive real reference impedance in ohms.');else if(rows.some(r=>!Object.values(smith19(r.real,r.imag,doc.referenceImpedance)).every(Number.isFinite)))bad('阻抗比例超过可表示精度，请换算参考与输入尺度。','Impedance ratios exceed representable precision; rescale reference and input.');}
 }
 if(id==='polezero'){if(!['continuous','discrete'].includes(doc.systemDomain))bad('systemDomain 必须明确 continuous 或 discrete。','systemDomain must explicitly be continuous or discrete.');if(rows.some(r=>!['pole','zero'].includes(r.kind)))bad('kind 必须为 pole 或 zero，重根需独立编号。','kind must be pole or zero; repeated roots need separate labels.');}
 if(id==='windrose'){
  if(!positive(doc.calmThreshold))bad('calmThreshold 必须为正数；速度低于它才算静风。','calmThreshold must be positive; speeds strictly below it are calm.');
  if(![8,16].includes(doc.windSectors))bad('windSectors 必须为 8 或 16。','windSectors must be 8 or 16.');
  if(!Array.isArray(doc.speedBreaks)||doc.speedBreaks.length<2||doc.speedBreaks.length>6||doc.speedBreaks.some((v,i)=>!positive(v)||i>0&&v<=doc.speedBreaks[i-1])||doc.speedBreaks[0]!==doc.calmThreshold)bad('speedBreaks 需要 2–6 个严格递增正下界，首项等于 calmThreshold；最后一段无上界。','speedBreaks needs 2–6 strictly increasing positive lower bounds, starting at calmThreshold; the final bin is unbounded.');
  if(rows.some(r=>r.speed<0||r.direction!==null&&(!finite(r.direction)||r.direction<0||r.direction>=360)||r.speed>=doc.calmThreshold&&r.direction===null))bad('风速非负；非静风必须有 [0,360) 来向，只有静风允许 direction=null。','Speed must be nonnegative; noncalm observations require a wind-from bearing in [0,360). Only calm observations may have direction=null.');
 }
 if(['polarscatter','constellation'].includes(id)){count(groups19(rows).length,1,id==='polarscatter'?6:8,t19('分组','groups'));if(id==='polarscatter'&&(rows.some(r=>r.angle<0||r.angle>=360||r.radius<0)||!rows.some(r=>r.radius>0)))bad('方位角需在 [0,360)，半径非负且至少一个正值；不接受负半径翻转。','Bearing must be in [0,360), and radii nonnegative with at least one positive value; negative-radius flips are not supported.');}
 if(id==='hodograph'){noDuplicates(rows.map(r=>r.height),t19('测量高度','Measured heights'));if(rows.some(r=>r.height<0))bad('高度不能为负；u/v 允许正、负和零。','Height cannot be negative; u/v may be positive, negative or zero.');if(!unit(doc.heightUnit))bad('heightUnit 必须明确高度单位。','heightUnit must declare the height unit.');}
 if(id==='phasor'){if(!['rms','peak'].includes(doc.phaseConvention))bad('phaseConvention 必须为 rms 或 peak，不能混用幅值约定。','phaseConvention must be rms or peak; amplitude conventions cannot be mixed.');if(!positive(doc.frequency)||!unit(doc.frequencyUnit))bad('相量必须声明同一个正 frequency 及 frequencyUnit。','Phasors must declare one shared positive frequency and frequencyUnit.');}
 if(id==='eyediagram'){
  const times=rows.map(r=>r.time).sort(d3.ascending);noDuplicates(times,t19('采样时刻','Sample times'));if(!regular19(times)){bad('time 必须唯一且严格等间隔，不能用等距眼图隐藏采样空档。','time must be unique and strictly equally spaced; an eye diagram cannot hide sampling gaps.');return;}
  if(!positive(doc.symbolPeriod)||!finite(doc.timeOrigin)||!unit(doc.timeUnit)){bad('symbolPeriod 为正，timeOrigin 有限，timeUnit 明确；这些参数不能自动猜测。','symbolPeriod must be positive, timeOrigin finite and timeUnit declared; none are inferred.');return;}
  const dt=times[1]-times[0],n=doc.symbolPeriod/dt,offset=(times[0]-doc.timeOrigin)/dt;if(!Number.isFinite(n)||n<4||n>128||Math.abs(n-Math.round(n))>1e-7)bad('每符号采样数 symbolPeriod/采样间隔 必须是 4–128 的整数。','symbolPeriod/sample interval must be an integer from 4 to 128.');
  if(!Number.isFinite(offset)||Math.abs(offset)>1e9||Math.abs(offset-Math.round(offset))>1e-6)bad('timeOrigin 必须与原始采样网格对齐，且离输入起点不超过 10⁹ 个采样间隔。','timeOrigin must align with the original sampling grid and lie within 10⁹ sample intervals of the input start.');
  if(times.at(-1)-times[0]<4*doc.symbolPeriod)bad('需要至少四个符号周期的真实采样跨度，形成两个双符号观察窗。','At least four symbol periods of real sample span are required for two two-symbol windows.');
 }
 if(id==='campbell'){
  const modes=[...new Set(rows.map(r=>r.mode))];count(modes.length,1,6,t19('模态分支','mode branches'));for(const mode of modes){const part=rows.filter(r=>r.mode===mode);count(part.length,4,120,t19('每分支采样','samples per branch'));noDuplicates(part.map(r=>r.speed),t19('同分支转速','Within-branch speed'));}
  if(rows.some(r=>r.speed<0||r.frequency<0||r.amplitude<0))bad('转速、频率和幅值必须非负，零幅值保留为十字标记。','Speed, frequency and amplitude must be nonnegative; zero amplitude remains as a cross.');
  if(!Array.isArray(doc.orders)||doc.orders.length<1||doc.orders.length>6||doc.orders.some(v=>!positive(v)||v>1000)||new Set(doc.orders).size!==doc.orders.length)bad('orders 必须含 1–6 个唯一正阶次，每个不超过 1000。','orders must contain 1–6 distinct positive orders, each no greater than 1000.');
 }
 warnings.push(t19('保留所有原始记录和单位，不补缺测、不自动拟合或平滑；动画可倒放定位。','All original records and units are retained without missing-value filling, automatic fitting or smoothing; animation seeks reversibly.'));
 if(['bode','nyquist','nichols','polezero','smith'].includes(id))warnings.push(t19('图只表达输入结果，不验证系统模型完整性，不自动判断稳定性或计算裕度。','The chart displays supplied results without verifying model completeness, judging stability or calculating margins.'));
}
export function volume19Summary(doc,fmt){return ids.has(doc.template)?{value:fmt(doc.data.length),label:t19('输入记录','Input records'),unit:t19('条','rows')}:null;}
export function volume19MethodNotes(id){const response=t19('幅值= hypot(real,imag)，dB=20·log10(幅值)。相位从 atan2(imag,real) 开始，按递增频率选择离上一点最近的 360° 分支；只能展开已采样相位，无法恢复采样间隐藏的多圈变化。','Magnitude=hypot(real,imag), dB=20·log10(magnitude). Starting from atan2(imag,real), select the nearest 360° branch to the previous point in increasing frequency order. This cannot recover unobserved phase turns between samples.');const notes={
 bode:[response+' https://www.mathworks.com/help/control/ref/dynamicsystem.bode.html'],
 nyquist:[t19('横坐标为输入实部、纵坐标为输入虚部，两轴等比例。仅按频率连接原始正频率点，不闭合、不镜像。−1 点只是已知参考；没有完整轮廓与开环极点数时不计算绕数或稳定性。','X and Y are the supplied real and imaginary parts on equal scales. Connect only original positive-frequency points, without closure or mirroring. −1 is a reference only; no winding count or stability conclusion is computed without a complete contour and open-loop pole count.')+' https://www.mathworks.com/help/control/ref/dynamicsystem.nyquist.html'],
 nichols:[response,t19('横轴相位（°），纵轴幅值（dB）；不叠加闭环 M/N 等值线，不由轨迹单独给出稳定裕度。','X is phase in degrees and Y is magnitude in decibels; no closed-loop M/N contours or stability margins are inferred from the locus alone.')+' https://www.mathworks.com/help/control/ref/dynamicsystem.nichols.html'],
 polezero:[t19('极点用 ×、零点用 ○，不进行多项式求根或近似消去。continuous 显示虚轴，discrete 显示单位圆；参考边界不是自动稳定性分类。重根分别保留，重叠位置显示重数。','Poles use × and zeros ○. No polynomial roots or approximate cancellations are calculated. continuous displays the imaginary axis; discrete displays the unit circle. Reference boundaries do not classify stability. Repeated roots remain separate and coincident locations display multiplicity.')+' https://www.mathworks.com/help/control/ref/lti.pzmap.html'],
 smith:[t19('Γ=(Z−Z₀)/(Z+Z₀)，Z=real+j·imag、Z₀=referenceImpedance>0。网格为归一化电阻与电抗；单位圆映射非负电阻半平面。计算先做共同尺度缩放以避免平方溢出；只连接已给频率点。','Γ=(Z−Z₀)/(Z+Z₀), with Z=real+j·imag and positive real Z₀=referenceImpedance. Grid curves are normalized resistance and reactance. The unit disk maps the nonnegative-resistance half-plane. Common scaling prevents square overflow; only supplied frequency points are connected.')+' https://scikit-rf.readthedocs.io/en/latest/api/generated/skrf.tlineFunctions.zl_2_Gamma0.html'],
 windrose:[t19('风来自的方位角以北 0°、顺时针定义。扇区中心在 0,360/N,…；边界左闭右开，速度段也左闭右开且最后一段无上界。静风 speed<calmThreshold 独立计数，所有频率分母均是完整输入行数。半径线性表示频率，外圈短线为非静风原始来向；静风原始记录显示在底部独立短线带。','Wind-from bearing is clockwise from north. Sector centers are 0,360/N,…; direction and speed bins are left-closed/right-open, with the last speed bin unbounded. Calm means speed<calmThreshold. Every frequency denominator is the full row count. Radius linearly encodes frequency. Outer ticks retain original noncalm bearings; calm records appear in a separate bottom rug.')+' https://python-windrose.github.io/windrose/usage-output.html'],
 polarscatter:[t19('x=radius·sin(angle)，y=radius·cos(angle)，angle 使用角度制、北起顺时针。零半径点保留在原点；不进行抖动或将负半径翻转成另一个方向。','x=radius·sin(angle), y=radius·cos(angle), with degrees clockwise from north. Zero-radius points remain at the origin; no jitter or negative-radius reversal is applied.')+' https://matplotlib.org/stable/gallery/pie_and_polar_charts/polar_scatter.html'],
 hodograph:[t19('横轴 u 向东为正，纵轴 v 向北为正，两轴同尺度。按 height 升序仅连接实测层，风速为 hypot(u,v)。线段是观测间的线性连接，不推断中间层观测或气象危险等级。','X=u positive eastward, Y=v positive northward, with equal axis scales. Connect measured levels in increasing height order; speed=hypot(u,v). Segments linearly connect observations without inventing intermediate levels or meteorological hazard classifications.')+' https://unidata.github.io/MetPy/latest/api/generated/metpy.plots.Hodograph.html'],
 phasor:[t19('数学复平面中实轴为 0°，正角逆时针。合成量 Σreal+jΣimag，虚线只表示数学向量和；不执行电路求解。所有输入必须共享频率、物理单位与 RMS/peak 约定。','The real axis is 0° and positive angles are counterclockwise. The resultant is Σreal+jΣimag; a dashed vector shows the mathematical sum without solving a circuit. Inputs must share frequency, physical units and RMS/peak convention.')+' https://www.comsol.com/support/learning-center/article/handling-complex-valued-numbers-and-problems-in-the-frequency-domain-45121'],
 eyediagram:[t19('采样网格与 timeOrigin 对齐，每符号采样数须为整数。每 2·symbolPeriod 分一个观察窗，横坐标为窗内时间/symbolPeriod（0–2）。共享窗边界仅复用该处真实观测；不插值补点、不自动恢复时钟，首尾不完整窗口仍保留。','Align the sample grid with timeOrigin and require an integer samples-per-symbol count. Partition into 2·symbolPeriod windows and plot within-window time/symbolPeriod from 0 to 2. Shared boundaries reuse only an actual observed sample. No crossing samples or clock recovery are synthesized; partial edge windows remain.')+' https://www.mathworks.com/help/comm/ref/eyediagram.html'],
 constellation:[t19('实部 I 为横轴、虚部 Q 为纵轴且两轴等比例；点面积固定。保留输入幅值、相位与全部符号，不添加理想符号位置、不作均衡、判决、EVM 或 BER 估计。','I is horizontal and Q vertical on equal scales; marker area is constant. Keep input amplitude, phase and every symbol. No ideal symbol locations, equalization, decisions, EVM or BER estimates are added.')+' https://www.mathworks.com/help/comm/ref/constellationdiagram.html'],
 campbell:[t19('横轴转速 rpm，纵轴频率 Hz。第 k 阶参考线 f=k·rpm/60；只显示落在当前坐标域的段。点面积正比于输入 amplitude，零幅值使用十字且仍可编辑。分支由输入 mode 声明，不做模态跟踪、FFT 或重采样。','X is speed in rpm, Y frequency in Hz. Order k follows f=k·rpm/60, clipped to the displayed domain. Marker area is proportional to amplitude; zero uses an editable cross. Input mode declares each branch; no modal tracking, FFT or resampling is performed.')+' https://www.mathworks.com/help/signal/ref/rpmfreqmap.html']
 };return notes[id]||[];}
export function guide19(t,guide){if(!ids.has(t.id))return guide;const en=volume19English[t.id],warnings=[];validateVolume19(guide.example,{fail:()=>{},count:()=>{},noDuplicates:()=>{},warnings});const meaning={bode:'一行是一个正频率处的外部复响应，实部和虚部是线性幅值比。',nyquist:'一行是一个正频率处的复响应；不生成负频率共轭点。',nichols:'一行是一个频率响应采样，幅值与展开相位由原复数计算。',polezero:'一行是一个外部计算的零点或极点，重根用不同编号分别输入。',smith:'一行是指定频率处的原始复阻抗，实部与虚部都以 Ω 输入。',windrose:'一行是一次原始风观测；direction 为风来向，静风方向可为空。',polarscatter:'一行是一个完整极坐标观测，角度北起顺时针，半径保留原单位。',hodograph:'一行是一层风观测，包含高度、向东分量 u 和向北分量 v。',phasor:'一行是共享同一频率、单位和幅值约定的原始复相量。',eyediagram:'一行是一个原始实值时域采样；只折叠时间坐标，不改测量幅度。',constellation:'一行是一个符号抽样的原始 I/Q 值及已知来源分组。',campbell:'一行是指定转速下的外部模态频率及幅值，分支名称由输入给定。'};return{...guide,introduction:isEnglish()?en.description:t.description,rowMeaning:isEnglish()?en.rowMeaning:meaning[t.id],use:isEnglish()?en.use:t.use,avoid:isEnglish()?en.avoid:t.avoid,limit:isEnglish()?en.limit:t.limit,notes:[...warnings,...volume19MethodNotes(t.id)],fields:guide.fields.map((f,i)=>({...f,description:isEnglish()?en.fields[i][2]:t.fields[i][2]}))};}
