import {uiText,uiMarkup,uiMessage} from './locale.js';
import {formatDecimal} from './number-format.js';
import * as d3 from 'd3';
import {unique8,classificationCurve,calibrationBins} from './volume8-data.js';
import {axes8 as axes,extent8 as extent,point8 as point,color8 as color,legend8 as legend,label8 as label,annotation8 as annotation,fmt8 as fmt,ref8 as ref} from './volume8-utils.js';

function classifier(s,doc,pr=false){const groups=unique8(doc.data.map(d=>d.model)),curves=groups.map(name=>({name,...classificationCurve(doc.data.filter(d=>d.model===name))})),f=axes(s,{xd:[0,1],yd:[0,1],percentX:true,percentY:true,xTicks:[0,.5,1],yTicks:[0,.5,1],xLabel:pr?uiText('召回率 Recall · AP 见图例'):uiText('假阳性率 FPR · AUC 见图例'),yLabel:`${pr?uiText('精确率 Precision'):uiText('真阳性率 TPR')} · n=${curves[0].n}`});legend(s,curves.map((c,i)=>({label:`${c.name} ${formatDecimal((pr?c.ap:c.auc),3)}`,color:s.theme.groupColor(c.name,color(s,i)),line:true,dash:i===1?'5 3':i===2?'2 3':''})));if(pr){const line=ref(s,f,curves[0].prevalence);s.tip(line,uiMessage`正类比例 ${fmt(curves[0].prevalence*100)}%`);}else{s.line(f.x(0),f.y(0),f.x(1),f.y(1),{stroke:s.theme.secondary,'stroke-width':.8,'stroke-dasharray':'3 4'});}curves.forEach((c,j)=>{const line=d3.line().x(d=>f.x(pr?d.recall:d.fpr)).y(d=>f.y(pr?d.precision:d.tpr)).curve(pr?d3.curveStepBefore:d3.curveLinear),g=s.group(),path=s.path(line(c.points),{stroke:s.theme.groupColor(c.name,color(s,j)),'stroke-width':1.5,'stroke-dasharray':j===1?'5 3':j===2?'2 3':'','data-mark':pr?'pr-curve':'roc-curve','data-group':c.name,'data-metric':pr?c.ap:c.auc},g);s.clipReveal(g,f.left-2,f.top-3,f.right-f.left+4,f.bottom-f.top+6,j*.05,.8);c.points.forEach((d,i)=>{const dot=s.circle(f.x(pr?d.recall:d.fpr),f.y(pr?d.precision:d.tpr),3.5,{fill:'transparent'},g);s.tip(dot,`${c.name} · ${doc.positiveLabel}\n${pr?'AP':'AUC'} ${formatDecimal((pr?c.ap:c.auc),4)} · n=${c.n}\n${d.threshold===null?uiText('尚无预测正类'):uiMessage`得分 ≥ ${fmt(d.threshold)}`}\nTPR ${fmt(d.tpr*100)}% · FPR ${fmt(d.fpr*100)}%\nPrecision ${fmt(d.precision*100)}%`);});});}
const roc=(s,doc)=>classifier(s,doc,false),precisionrecall=(s,doc)=>classifier(s,doc,true);

function calibration(s,doc){const groups=unique8(doc.data.map(d=>d.model)),f=axes(s,{xd:[0,1],yd:[0,1],percentX:true,percentY:true,xTicks:[0,.5,1],yTicks:[0,.5,1],yLabel:uiMessage`实际正类比例 · ${doc.bins} 个等宽箱`,xLabel:uiText('分箱平均预测概率 · n 见提示')});legend(s,groups.map((label,i)=>({label,color:s.theme.groupColor(label,color(s,i))})));s.line(f.x(0),f.y(0),f.x(1),f.y(1),{stroke:s.theme.secondary,'stroke-width':.8,'stroke-dasharray':'3 4'});groups.forEach((name,j)=>{const rows=calibrationBins(doc.data.filter(d=>d.model===name),doc.bins),col=s.theme.groupColor(name,color(s,j)),g=s.group(),path=s.path(d3.line().defined(d=>d!==null).x(d=>f.x(d.probability)).y(d=>f.y(d.frequency))(rows),{stroke:col,'stroke-width':1.3,'stroke-dasharray':j?'4 3':'','data-mark':'calibration-line','data-group':name},g);s.clipReveal(g,f.left-3,f.top-4,f.right-f.left+6,f.bottom-f.top+8,j*.08,.8);rows.forEach(d=>{if(!d)return;const dot=point(s,f.x(d.probability),f.y(d.frequency),{color:col,shape:j,filled:j%2===0,r:3.5,delay:j*.08+d.index/doc.bins*.35,mark:'calibration-bin','data-n':d.n});s.tip(dot,uiMessage`${name} · ${doc.positiveLabel}\n概率分箱 [${fmt(d.lower)}, ${fmt(d.upper)}${d.index===doc.bins-1?']':')'}\nn=${d.n} · 平均预测 ${fmt(d.probability*100)}%\n实际正类 ${fmt(d.frequency*100)}%`);if(groups.length===1||(!s.compact&&j===0)){const txt=s.text(f.x(d.probability)+6,f.y(d.frequency)+12,`n=${d.n}`,{'font-size':s.fs-3,fill:col});s.reveal(txt,.65,.3);}});});}

function confusion(s,doc){const labels=unique8(doc.data.map(d=>d.actual)),count=labels.length,left=s.compact?62:100,top=54,side=Math.min(s.w-left-24,s.h-top-49),right=left+side,bottom=top+side,cell=side/count,max=d3.max(doc.data,d=>d.count),fill=d3.scaleLinear([0,max],[s.theme.soft,s.theme.accent]).interpolate(d3.interpolateLab);label(s,left,13,uiText('行：真实 · 列：预测'),{'font-size':s.fs-2},30);const total=d3.sum(doc.data,d=>d.count),correct=d3.sum(doc.data.filter(d=>d.actual===d.predicted),d=>d.count);label(s,left,33,uiMessage`n=${total} · 准确率 ${fmt(correct/total*100)}%`,{'font-size':s.fs-2},40);labels.forEach((name,i)=>{label(s,left-9,top+(i+.5)*cell+3,name,{'text-anchor':'end','font-size':Math.min(s.fs-1,cell*.27)},s.compact?5:10);label(s,left+(i+.5)*cell,bottom+18,name,{'text-anchor':'middle','font-size':Math.min(s.fs-1,cell*.27)},s.compact?4:8);});doc.data.forEach((d,i)=>{const row=labels.indexOf(d.actual),col=labels.indexOf(d.predicted),x=left+col*cell,y=top+row*cell,c=fill(d.count),rect=s.rect(x+1,y+1,cell-2,cell-2,{fill:c,'data-mark':'confusion-cell','data-actual':d.actual,'data-predicted':d.predicted,'data-count':d.count});s.reveal(rect,(row+col)*.045,.6);const rowTotal=d3.sum(doc.data.filter(r=>r.actual===d.actual),r=>r.count);s.edit(rect,d,'count');s.tip(rect,uiMessage`真实 ${d.actual} → 预测 ${d.predicted}\n${d.count} 个样本 · 行内 ${fmt(d.count/rowTotal*100)}%`);const txt=s.text(x+cell/2,y+cell/2+4,String(d.count),{'text-anchor':'middle',fill:d3.lab(c).l<55?'#f8f7f4':'#262626','font-size':Math.min(s.fs+2,cell*.31),'font-family':'ui-monospace,monospace'});s.edit(txt,d,'count');s.reveal(txt,.35+(row+col)*.045,.35);});const barY=s.h-11,barW=Math.min(88,side*.4),gradient=s.el('linearGradient',{id:`${s.id}-count`},s.defs);[0,1].forEach(v=>s.el('stop',{offset:v,'stop-color':fill(v*max)},gradient));s.rect(left,barY-4,barW,5,{fill:`url(#${s.id}-count)`});s.text(left+barW+8,barY+1,uiMessage`0—${max} 个`,{'font-size':s.fs-3});}

function learning(s,doc){const f=axes(s,{xd:d3.extent(doc.data,d=>d.epoch),yd:extent(doc.data.flatMap(d=>[d.train,d.validation]).filter(Number.isFinite),{zero:true,pad:0}),yLabel:uiMessage`损失 / ${doc.unit}`,xLabel:uiText('训练轮次 Epoch')});legend(s,[{label:uiText('训练集'),line:true},{label:uiText('验证集'),line:true,dash:'5 3'}]);['train','validation'].forEach((key,j)=>{const g=s.group(),line=s.path(d3.line().defined(d=>d[key]!==null).x(d=>f.x(d.epoch)).y(d=>f.y(d[key]))(doc.data),{stroke:color(s,j),'stroke-width':1.5,'stroke-dasharray':j?'5 3':'','data-mark':'learning-line','data-series':key},g);s.clipReveal(g,f.left-2,f.top-3,f.right-f.left+4,f.bottom-f.top+6,j*.08,.8);doc.data.forEach((d,i)=>{if(d[key]===null)return;const dot=s.circle(f.x(d.epoch),f.y(d[key]),3.5,{fill:'transparent'},g);s.edit(dot,d,key);s.tip(dot,uiMessage`${j?uiText('验证'):uiText('训练')} · Epoch ${d.epoch}\n损失 ${fmt(d[key])} ${doc.unit}`);});});}
export const model8Renderers={roc,precisionrecall,calibration,confusion,learning};
