import * as d3 from 'd3';
import {isEnglish} from './locale.js';
import {volume18Catalog,volume18English} from './volume18-catalog.js';
import {hierarchy13} from './volume13-data.js';
import {gains16} from './volume16-data.js';
export const t18=(zh,en)=>isEnglish()?en:zh;
const ids=new Set(volume18Catalog.map(t=>t.id)),unique=a=>[...new Set(a)],pair=(a,b)=>JSON.stringify([a,b]),finite=v=>typeof v==='number'&&Number.isFinite(v)&&Math.abs(v)<=1e15,text=v=>typeof v==='string'&&v.trim().length>0&&v.length<=80;
export function bipartite18(doc){return{left:doc.leftNodes.map(name=>({name,total:d3.sum(doc.data.filter(r=>r.source===name),r=>r.value)})),right:doc.rightNodes.map(name=>({name,total:d3.sum(doc.data.filter(r=>r.target===name),r=>r.value)}))};}
export function ego18(doc){return{neighbors:unique(doc.data.flatMap(r=>[r.source,r.target])).filter(n=>n!==doc.ego),edges:doc.data};}
export function variwide18(rows){let cursor=0;const bars=rows.map(row=>{const start=cursor;cursor+=row.width;return{row,start,end:cursor,amount:row.width*row.rate};});return{bars,totalWidth:cursor,totalAmount:d3.sum(bars,p=>p.amount)};}
export function waterfall18(doc){let balance=doc.baseline;return{steps:doc.stepOrder.map(step=>{const start=balance;let positive=start,negative=start;const parts=doc.components.map(component=>{const row=doc.data.find(r=>r.step===step&&r.component===component),a=row.value>=0?positive:negative,b=a+row.value;if(row.value>=0)positive=b;else negative=b;return{row,start:a,end:b};});balance+=d3.sum(parts,p=>p.row.value);return{step,start,end:balance,positive,negative,parts};}),total:balance};}
export function treeTable18(rows){const m=hierarchy13(rows),ordered=[];function walk(node){ordered.push(node);node.children.forEach(walk);}walk(m.root);return{...m,ordered};}
export function nelson18(rows){return unique(rows.map(r=>r.group)).map(group=>{const input=rows.filter(r=>r.group===group),times=unique(input.map(r=>r.duration)).sort(d3.ascending),points=[{time:0,hazard:0,atRisk:input.length,events:0,records:[]}];let atRisk=input.length,hazard=0;for(const time of times){const records=input.filter(r=>r.duration===time),events=records.filter(r=>r.status==='ended').length;hazard+=events/atRisk;points.push({time,hazard,atRisk,events,records});atRisk-=records.length;}return{group,rows:input,points};});}
export function ks18(rows){const n0=rows.filter(r=>r.actual===0).length,n1=rows.length-n0,sorted=[...rows].sort((a,b)=>a.score-b.score);let c0=0,c1=0;const points=[{score:0,f0:0,f1:0,records:[]}];for(let i=0;i<sorted.length;){let j=i;const records=[];while(j<sorted.length&&sorted[j].score===sorted[i].score){const row=sorted[j++];records.push(row);if(row.actual===0)c0++;else c1++;}points.push({score:sorted[i].score,f0:c0/n0,f1:c1/n1,records});i=j;}const maximum=points.reduce((a,b)=>Math.abs(b.f0-b.f1)>Math.abs(a.f0-a.f1)?b:a,points[0]);points.push({score:1,f0:1,f1:1,records:[]});return{points,maximum,distance:Math.abs(maximum.f0-maximum.f1),n0,n1};}
export function lift18(rows){return gains16(rows).points.slice(1).map(p=>({...p,lift:p.gain/p.fraction}));}
export function nextUp18(v){if(v===0)return Number.MIN_VALUE;const b=new ArrayBuffer(8),d=new DataView(b);d.setFloat64(0,v);d.setBigUint64(0,d.getBigUint64(0)+1n);return d.getFloat64(0);}
export function metrics18(rows,threshold){const p=rows.filter(r=>r.actual===1).length,selected=rows.filter(r=>r.score>=threshold),tp=d3.sum(selected,r=>r.actual),fp=selected.length-tp,fn=p-tp,tn=rows.length-p-fp;return{threshold,tp,fp,fn,tn,precision:tp+fp?tp/(tp+fp):null,recall:tp/p,f1:2*tp/(2*tp+fp+fn)};}
export function thresholds18(doc){const thresholds=unique([0,1,...doc.data.flatMap(r=>[r.score,nextUp18(r.score)])].filter(t=>t>=0&&t<=1)).sort(d3.ascending);return unique(doc.data.map(r=>r.model)).map(model=>{const rows=doc.data.filter(r=>r.model===model),prevalence=d3.mean(rows,r=>r.actual);return{model,rows,prevalence,points:thresholds.map(t=>{const m=metrics18(rows,t);return{...m,cost:doc.template==='costcurve'?(m.fp*doc.falsePositiveCost+m.fn*doc.falseNegativeCost)/rows.length:null};})};});}
export function validateVolume18(doc,{fail,count,noDuplicates,warnings}){
 if(!ids.has(doc.template))return;const id=doc.template,rows=doc.data;
 const array=(key,min,max)=>{const a=doc[key];if(!Array.isArray(a)||a.length<min||a.length>max||a.some(v=>!text(v))||new Set(a).size!==a.length){fail(t18(`${key} 必须包含 ${min}–${max} 个唯一非空名称。`,`${key} requires ${min}–${max} unique nonempty names.`));return false;}return true;};
 if(id==='bipartite'){
  const a=array('leftNodes',2,12),b=array('rightNodes',2,12);if(!a||!b)return;count(rows.length,3,60,t18('已观测联系','observed edges'));if(doc.leftNodes.some(v=>doc.rightNodes.includes(v)))fail(t18('左右两类节点必须互不相交。','The two node partitions must be disjoint.'));noDuplicates(rows.map(r=>pair(r.source,r.target)),t18('联系组合','Edge pairs'));if(rows.some(r=>r.value<=0||!doc.leftNodes.includes(r.source)||!doc.rightNodes.includes(r.target)))fail(t18('每条联系须从 leftNodes 指向 rightNodes 且 value > 0。','Every edge must go from leftNodes to rightNodes with value > 0.'));
 }
 if(id==='egonetwork'){
  if(!text(doc.ego)){fail(t18('ego 必须为非空中心名称。','ego must name the focal node.'));return;}const neighbors=ego18(doc).neighbors;count(neighbors.length,3,16,t18('直接邻居','direct neighbors'));count(rows.length,3,80,t18('已观测联系','observed edges'));noDuplicates(rows.map(r=>pair(...[r.source,r.target].sort())),t18('无向联系组合','Undirected pairs'));if(rows.some(r=>r.value<=0||r.source===r.target))fail(t18('无向联系必须为正值且没有自环。','Undirected links must be positive without self loops.'));if(neighbors.some(n=>!rows.some(r=>(r.source===doc.ego&&r.target===n)||(r.target===doc.ego&&r.source===n))))fail(t18('所有邻居都必须与 ego 有直接的观测联系。','Every alter must have a directly observed edge to ego.'));
 }
 if(id==='radialheatmap'){
  const a=array('sectors',4,16),b=array('rings',2,8);if(!a||!b)return;noDuplicates(rows.map(r=>pair(r.sector,r.ring)),t18('扇区与圆环组合','Sector-ring pairs'));if(rows.length!==doc.sectors.length*doc.rings.length||rows.some(r=>!doc.sectors.includes(r.sector)||!doc.rings.includes(r.ring)))fail(t18('必须完整列出 sectors × rings 的所有单元；缺失值填 null。','Supply the complete sectors × rings grid; missing values must be explicit null.'));if(!rows.some(r=>r.value!==null))fail(t18('至少需要一个已观测值。','At least one observed value is required.'));
 }
 if(id==='spiralheatmap'){
  if(!Number.isInteger(doc.cycleLength)||doc.cycleLength<6||doc.cycleLength>24){fail(t18('cycleLength 必须是 6–24 的整数。','cycleLength must be an integer from 6 to 24.'));return;}count(rows.length,doc.cycleLength*2,doc.cycleLength*6,t18('等间隔时期','equal intervals'));noDuplicates(rows.map(r=>r.period),t18('时期','Periods'));if(!rows.some(r=>r.value!==null))fail(t18('至少需要一个已观测值。','At least one observed value is required.'));
 }
 if(id==='variwide'){
  count(rows.length,3,16,t18('类别','categories'));noDuplicates(rows.map(r=>r.label),t18('类别名称','Category names'));if(!doc.axes||!text(doc.axes.x)||!text(doc.axes.y))fail(t18('axes.x 与 axes.y 必须标明数量和率的含义及单位。','axes.x and axes.y must name the quantity and rate with units.'));if(rows.some(r=>r.width<=0||r.rate<0))fail(t18('width 必须为正，rate 必须非负。','width must be positive and rate nonnegative.'));const m=variwide18(rows);if(!Number.isFinite(m.totalAmount)||!Number.isFinite(m.totalWidth)||m.bars.some(p=>p.end===p.start||!Number.isFinite(p.amount)||(p.row.rate>0&&p.amount===0)))fail(t18('宽度或乘积在当前单位下不可表示；请换算单位。','Widths or products are unrepresentable in these units; rescale the measurements.'));
 }
 if(id==='stackedwaterfall'){
  const a=array('stepOrder',2,8),b=array('components',2,6);if(!a||!b)return;if(!finite(doc.baseline)||!finite(doc.finalTotal)){fail(t18('baseline 与 finalTotal 必须为有限总量且绝对值 ≤10¹⁵。','baseline and finalTotal must be finite totals with magnitude ≤10¹⁵.'));return;}noDuplicates(rows.map(r=>pair(r.step,r.component)),t18('步骤与分量组合','Step-component pairs'));if(rows.length!==doc.stepOrder.length*doc.components.length||rows.some(r=>!doc.stepOrder.includes(r.step)||!doc.components.includes(r.component))||new Set(rows.map(r=>pair(r.step,r.component))).size!==rows.length){fail(t18('必须完整提供 stepOrder × components；零也需显式填写。','Supply every stepOrder × components pair, including explicit zero.'));return;}const total=doc.baseline+d3.sum(rows,r=>r.value),scale=Math.max(Math.abs(doc.baseline),Math.abs(doc.finalTotal),d3.sum(rows,r=>Math.abs(r.value)),Number.MIN_VALUE);if(Math.abs(total-doc.finalTotal)>scale*1e-10)fail(t18('finalTotal 必须等于 baseline 加全部变化；相对容差为 10⁻¹⁰。','finalTotal must equal baseline plus all changes, within relative tolerance 10⁻¹⁰.'));const m=waterfall18(doc);if(m.steps.some(p=>![p.start,p.end,p.positive,p.negative].every(Number.isFinite)||p.parts.some(q=>q.row.value!==0&&q.start===q.end)))fail(t18('变化在当前总量单位下无法分辨；请换算单位或调整基准。','A change is numerically indistinguishable from its balance; rescale units or revise the baseline.'));
 }
 if(id==='treetable'){count(rows.length,3,24,t18('层级节点','hierarchy nodes'));try{const m=treeTable18(rows);count(m.depth,1,6,t18('层级深度','hierarchy depth'));if(!Number.isFinite(m.total))fail(t18('叶值合计必须为有限值。','The leaf sum must be finite.'));}catch(error){fail(error.message);}}
 if(id==='nelsonaalen'){
  const groups=unique(rows.map(r=>r.group));count(groups.length,1,4,t18('组','groups'));groups.forEach(g=>count(rows.filter(r=>r.group===g).length,4,120,g));noDuplicates(rows.map(r=>r.label),t18('观测编号','Observation identifiers'));if(rows.some(r=>r.duration<0||!['ended','censored'].includes(r.status)))fail(t18('duration 必须非负，status 仅接受 ended/censored。','duration must be nonnegative and status ended or censored.'));
 }
 if(['ksplot','liftcurve','thresholdmetrics','costcurve'].includes(id)){
  const models=unique(rows.map(r=>r.model)),labels=unique(rows.map(r=>r.label));count(models.length,1,2,t18('模型','models'));count(labels.length,8,300,t18('每模型样本','samples per model'));noDuplicates(rows.map(r=>pair(r.model,r.label)),t18('模型与样本组合','Model-sample pairs'));if(rows.length!==models.length*labels.length)fail(t18('每个模型都必须提供同一批完整测试样本。','Every model must provide the same complete test population.'));if(rows.some(r=>![0,1].includes(r.actual)||r.score<0||r.score>1))fail(t18('actual 只能为 0/1，score 必须在 [0,1]。','actual must be 0/1 and score within [0,1].'));if(labels.some(l=>unique(rows.filter(r=>r.label===l).map(r=>r.actual)).length!==1))fail(t18('同一样本跨模型的实际类别必须相同。','Actual outcomes must agree across models for each sample.'));if(models.some(m=>new Set(rows.filter(r=>r.model===m).map(r=>r.actual)).size!==2))fail(t18('每个模型必须同时有正负类别。','Every model requires both actual classes.'));if(!text(doc.positiveLabel))fail(t18('positiveLabel 必须说明正类事件。','positiveLabel must describe the positive event.'));if(id==='costcurve'&&(!finite(doc.falsePositiveCost)||!finite(doc.falseNegativeCost)||doc.falsePositiveCost<0||doc.falseNegativeCost<0||doc.falsePositiveCost+doc.falseNegativeCost<=0))fail(t18('误报与漏报代价必须非负、有限且至少一项为正。','False-positive and false-negative costs must be finite, nonnegative and at least one positive.'));
 }
 if(['bipartite','egonetwork'].includes(id))warnings.push(t18('只显示已观测联系；未列边不用于推断零。几何位置为结构布局，不是额外测量；线宽与原强度成比例。','Only observed links are drawn; unlisted links are not measured zeros. Position is structural layout, not a measurement; line width is proportional to supplied strength.'));
 if(['ksplot','liftcurve','thresholdmetrics','costcurve'].includes(id))warnings.push(t18('使用同一独立测试集；所有相同得分整体处理，不通过排序顺序创造更细阈值，不自动推荐最优阈值。','Use one held-out test population. Ties enter together, without invented finer thresholds or automatic optimal-threshold advice.'));
}
const refs={bipartite:'https://networkx.org/documentation/stable/reference/algorithms/bipartite.html',egonetwork:'https://networkx.org/documentation/stable/reference/generated/networkx.generators.ego.ego_graph.html',variwide:'https://api.highcharts.com/highcharts/plotOptions.variwide',treetable:'https://d3js.org/d3-hierarchy/hierarchy',nelsonaalen:'https://lifelines.readthedocs.io/en/latest/Survival%20analysis%20with%20lifelines.html',ksplot:'https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html',liftcurve:'https://scikit-plot.readthedocs.io/en/stable/metrics.html#scikitplot.metrics.plot_lift_curve',thresholdmetrics:'https://scikit-learn.org/stable/auto_examples/model_selection/plot_precision_recall.html',costcurve:'https://scikit-learn.org/stable/auto_examples/model_selection/plot_cost_sensitive_learning.html'};
export function volume18MethodNotes(id){const notes={
 bipartite:t18('左右按显式数组固定顺序。节点圆点面积与其已观测联系合计成比例；孤立节点只显示空心位置标记。','Explicit arrays order both sides. Node marker area is proportional to the sum of observed incident weights; isolated nodes use hollow position markers.'),
 egonetwork:t18('中心固定，邻居按首次出现等角排列；邻居间边为弦。距离与角度不作度量，节点圆点大小固定。','The focal node is central and alters follow first appearance at equal angles. Alter-to-alter links are chords. Distance and angle are not metrics; nodes have fixed marker size.'),
 radialheatmap:t18('扇区角度相等、环带厚度相等，只有颜色编码原值；不同半径单元面积不相等。null 使用纹理，零参与共同色标。','Sectors have equal angles and rings equal thickness. Color alone encodes value; cell areas differ by radius. Null cells are textured and numeric zero participates in the shared color scale.'),
 spiralheatmap:t18('阿基米德螺旋：r=a+bθ；每期占相同角度，每 cycleLength 期一圈。输入顺序是等时间间隔顺序，空值保留完整纹理单元；面积不是数据通道。','Archimedean spiral r=a+bθ: equal angular steps, one revolution per cycleLength intervals. Input order is equally spaced time order; null retains a full textured cell. Area is not a data channel.'),
 variwide:t18('横轴累计 width，高度为 rate，面积=width×rate；相邻柱无间隙。rate=0 用基线标记保留，不能创造正面积。','X accumulates width, height is rate and area=width×rate; neighboring columns have no gap. A zero rate retains a baseline marker without inventing positive area.'),
 stackedwaterfall:t18('每步正分量从原净额向上累计，负分量另从同一原净额向下累计；下一步从原净额+正负合计开始。起终总量独立从零表示；容差为最大绝对总量/变化量的 10⁻¹⁰。','In each step, positive components stack upward and negative components downward from the previous net balance. The next step begins at that balance plus all signed changes. Initial/final totals start at zero. Reconciliation tolerance is 10⁻¹⁰ times the largest absolute total or absolute-change sum.'),
 treetable:t18('内部节点总量递归相加叶值；原表内部 value 保持 0。条形共用根总量尺度；父子汇总有重叠，不能再次相加。点击内部标签编辑名称，点击叶条编辑原叶值。','Internal totals recursively sum leaves; original internal value stays zero. All bars share the root-total scale. Parent and child totals overlap and cannot be added again. Internal labels edit their names; leaf bars edit original values.'),
 nelsonaalen:t18('H(t)=Σ(tⱼ≤t)dⱼ/nⱼ。nⱼ 为时刻之前在险人数，同刻删失者仍在分母；先累加 d/n，再移除该时刻事件和删失。假设独立、非信息性右删失；使用未平滑的并列 d/n，不用调和数平滑；不外推尾部，不估计区间。','H(t)=Σ(tⱼ≤t)dⱼ/nⱼ. The risk set immediately before tⱼ includes same-time censoring; add d/n, then remove all events and censoring at that time. Assume independent, non-informative right censoring. Use unsmoothed tied-event d/n, not harmonic smoothing; no tail extrapolation or uncertainty interval.'),
 ksplot:t18('F₀/F₁ 分别为真实类别 0/1 得分的右连续经验 CDF，D=max|F₀−F₁|。相同得分同时计入；仅报告描述性距离，不调用连续分布 KS 检验的 p 值。','F₀/F₁ are right-continuous empirical score CDFs for actual classes 0/1. D=max|F₀−F₁|, with all tied scores included together. Report descriptive distance only, without continuous-distribution KS p-values.'),
 liftcurve:t18('降序完整同分块纳入；lift=(已选正类/已选人数)/(全部正类/n)=gain/selectedShare。只在实际同分块端点计算；连线仅为视觉指引，零份额没有定义。','Enter complete score ties in descending order. lift=(selected positives/selected population)/(all positives/n)=gain/selectedShare. Only complete tie-block endpoints are calculated; connectors are visual guides, and zero share is undefined.'),
 thresholdmetrics:t18('规则 score≥t；P=TP/(TP+FP)，R=TP/(TP+FN)，F1=2TP/(2TP+FP+FN)。未选中记录时 P=null，保留断口。每个 score 与其下一可表示浮点值组成真实阈值跳跃，端点是 0/1。','Select score≥t. P=TP/(TP+FP), R=TP/(TP+FN), F1=2TP/(2TP+FP+FN). With no selected records P=null and the line breaks. Each observed score and its next representable float preserve threshold jumps, bounded by 0/1.'),
 costcurve:t18('每记录期望代价=(FP×falsePositiveCost+FN×falseNegativeCost)/n。全部判正=(1−正类比例)×误报代价，全部判负=正类比例×漏报代价。成本为显式固定输入；该图不是决策曲线的阈值赔率净获益。','Expected cost per record=(FP×falsePositiveCost+FN×falseNegativeCost)/n. Predict-all-positive cost=(1−prevalence)×false-positive cost; all-negative=prevalence×false-negative cost. Costs are fixed supplied values, not decision-curve threshold odds.')
};return ids.has(id)?[notes[id],...(refs[id]?[t18('方法参考：','Method reference: ')+refs[id]]:[])]:[];}
export function volume18Summary(doc,fmt){if(!ids.has(doc.template))return null;if(doc.template==='variwide')return{value:fmt(variwide18(doc.data).totalAmount),label:t18('数量×率合计','Total quantity × rate'),unit:doc.unit};return{value:fmt(doc.data.length),label:t18('原始记录','Original records'),unit:t18('条','rows')};}
export function guide18(t,guide){if(!ids.has(t.id))return guide;const en=volume18English[t.id],warnings=[];validateVolume18(guide.example,{fail:()=>{},count:()=>{},noDuplicates:()=>{},warnings});return{...guide,introduction:isEnglish()?en.description:t.description,rowMeaning:isEnglish()?en.rowMeaning:t.fields.map(([k,,d])=>`${k}: ${d}`).join('；'),use:isEnglish()?en.use:t.use,avoid:isEnglish()?en.avoid:t.avoid,limit:isEnglish()?en.limit:t.limit,notes:[...warnings,...volume18MethodNotes(t.id)],fields:guide.fields.map((f,i)=>({...f,description:isEnglish()?en.fields[i][2]:t.fields[i][2]}))};}
