const str=(k,l)=>[k,'string',l],num=(k,l)=>[k,'number',l];
const predictions=[str('label','测试样本唯一编号'),str('model','预测模型'),num('actual','真实类别：0 或 1'),num('score','正类预测概率：0–1')];
const specs=[
 ['radviz','多变量径向投影','RadViz','research',[str('sample','样本唯一编号'),str('variable','变量名称及原始单位'),str('group','样本分组'),num('value','原始测量值')],'将完整样本的多变量分别归一化后，以圆周锚点的加权平衡位置展示结构。','多变量模式、样本分群、属性偏向','把二维距离当原始距离；比较归一化范围不同的两张图','3–8 个非恒定变量，5–100 完整样本，1–6 组；不接受全零归一化权重样本'],
 ['hiveplot','分组轴蜂巢网络','Hive plot','flow',[str('source','端点 A'),str('target','端点 B'),str('sourceGroup','A 所属轴'),str('targetGroup','B 所属轴'),num('sourcePosition','A 在轴上位置：0–1'),num('targetPosition','B 在轴上位置：0–1'),num('value','无向联系强度')],'节点按明确分组放到三条轴上，沿轴位置和跨轴连线呈现网络结构。','系统依赖、跨组协作、网络结构','让边宽冒充方向；按屏幕位置猜测节点属性','3 个轴，3–60 条跨轴无向正联系；节点分组与位置固定'],
 ['cumulativegains','累计增益曲线','Cumulative gains','research',predictions,'按预测概率降序逐批纳入同分样本，展示筛选人群份额与捕获正类份额。','排序效果、目标发现、测试集模型比较','对同分样本任意排序；把训练集效果当泛化表现','1–3 模型，每模型 8–300 个相同测试样本，包含正负类别'],
 ['decisioncurve','决策净获益曲线','Decision curve','research',predictions,'比较不同概率阈值下的模型净获益，并明确展示全部处理与均不处理的基线。','决策阈值敏感性、二分类策略比较','把净获益当准确率；从演示曲线推导未经验证的应用建议','1–3 模型，每模型 8–300 完整共同测试样本；0 < thresholdMin < thresholdMax < 1'],
 ['rankclock','时序排名时钟','Rank clock','trend',[str('period','时期：按首次出现排序'),str('label','对象名称'),num('value','原始指标值')],'时间沿圆周推进，半径表示每期按同一规则计算的竞争排名。','周期排行、名次变化、相对表现','将名次距离当数值差距；把首尾自动连成未观测的周期','3–8 个对象、4–16 完整时期；rankOrder 为 ascending 或 descending；并列采用 1,1,3'],
 ['funnelcontrol','比例控制漏斗','Proportion control funnel','research',[str('label','单位或批次名称'),num('events','事件个数'),num('total','完整观察样本量')],'以样本量为横轴比较事件比例，已知基准概率形成二项正态近似控制漏斗。','跨单位质量监控、不同样本量的比例比较','与元分析漏斗混淆；把控制界限当规格限或精确二项区间','5–100 个整数计数；0 < targetRate < 1；每单位 np 与 n(1−p) 均 ≥ 5'],
 ['labbe','双组事件比例图','L’Abbé plot','research',[str('label','研究或实验名称'),num('controlEvents','对照组事件数'),num('controlTotal','对照组总人数'),num('treatmentEvents','处理组事件数'),num('treatmentTotal','处理组总人数')],'每项研究同时展示对照和处理组事件比例，气泡面积对应两组合计样本量。','双组事件率比较、研究异质性、实验结果概览','将气泡面积当逆方差权重；把事件增减直接等同获益','3–60 项研究；两组计数完整，分母为正整数；事件数不超过分母'],
 ['nomogram','线性评分列线图','Linear scoring nomogram','research',[str('variable','变量名称及单位'),num('minimum','输入范围下界'),num('maximum','输入范围上界'),num('coefficient','线性系数'),num('reference','参考输入值'),num('value','当前输入值')],'把每个原值映射到共同的线性贡献刻度，再显示加总评分。','透明评分规则、线性模型解释、情景计算','将未经验证的线性分数转换成风险概率；忽略输入范围','3–7 个变量；minimum < maximum；参考与当前值在范围内；显式 intercept']
];
export const volume16Catalog=specs.map(([id,name,en,category,fields,description,use,avoid,limit],i)=>({id,no:String(161+i),name,en,type:name,category,fields,description,use,avoid,limit,motion:'结构展开 / 原值定位 / 统计轨迹推进',keywords:`${name} ${en} ${use}`,edition:16,research:category==='research',dataMode:'observations',duration:8}));
const predictionRows=['A','B'].flatMap((model,j)=>Array.from({length:64},(_,i)=>{const actual=(i*17%29)<11?1:0;return{label:`S${i+1}`,model,actual,score:Math.round(Math.max(.02,Math.min(.98,.24+actual*.40+Math.sin(i*2.13+j)*(.22+j*.1)))*20)/20};}));
const variables=['Speed / s','Quality / %','Capacity / GB','Cost / USD','Stability / %'];
const nodeGroups=['Research','Design','Engineering'];const hiveNodes=Array.from({length:15},(_,i)=>({name:`N${i+1}`,group:nodeGroups[i%3],position:.14+Math.floor(i/3)*.19}));
export const volume16Contents={
 radviz:{title:'多指标样本结构',subtitle:'确定性合成原始值 · 每变量 min–max · 二维距离不代表原始距离',unit:'按变量',data:Array.from({length:36},(_,i)=>variables.map((variable,j)=>({sample:`S${i+1}`,variable,group:['A','B','C'][Math.floor(i/12)],value:+(30+22*Math.sin(i*.7+j*1.1)+18*(Math.floor(i/12)===j%3)+i*.3+j*8).toFixed(4)}))).flat()},
 hiveplot:{title:'跨组系统关系',subtitle:'确定性合成网络 · 轴上位置为显式标准化属性 · 无向联系',unit:'次',axisOrder:nodeGroups,data:Array.from({length:23},(_,i)=>{const a=hiveNodes[i%15],b=hiveNodes[(i*4+1)%15];return{source:a.name,target:b.name,sourceGroup:a.group,targetGroup:b.group,sourcePosition:a.position,targetPosition:b.position,value:8+(i*7)%31};}).filter((r,i,a)=>r.sourceGroup!==r.targetGroup&&a.findIndex(x=>[x.source,x.target].sort().join('|')===[r.source,r.target].sort().join('|'))===i)},
 cumulativegains:{title:'优先筛选能覆盖多少目标',subtitle:'确定性合成测试集 · 同分样本共同纳入',unit:'比例',positiveLabel:'目标事件',data:predictionRows},
 decisioncurve:{title:'阈值变化下的策略净获益',subtitle:'确定性合成概率 · 完整共同测试集 · 未估计不确定区间',unit:'净获益 / 个体',positiveLabel:'目标事件',thresholdMin:.05,thresholdMax:.70,data:predictionRows},
 rankclock:{title:'全年产品竞争排名',subtitle:'确定性合成指标 · 外圈为第 1 名 · 并列采用竞争排名',unit:'分',rankOrder:'descending',data:Array.from({length:12},(_,p)=>['A','B','C','D','E'].map((label,i)=>({period:`${p+1}月`,label,value:Math.round(65+Math.sin(p*.65+i*1.24)*18+Math.cos(p*.34-i)*7)}))).flat()},
 funnelcontrol:{title:'不同规模单位的事件比例',subtitle:'确定性合成计数 · 已知基准 12% · 二项正态近似 ±3σ',unit:'%',targetRate:.12,limitSigma:3,data:Array.from({length:24},(_,i)=>{const total=60+i*32;return{label:`Site ${i+1}`,events:Math.round(total*(.12+Math.sin(i*1.9)*.033+(i===17?.09:0))),total};})},
 labbe:{title:'研究间双组事件比例',subtitle:'确定性合成计数 · 面积为总样本量 · 对角线表示比例相等',unit:'%',data:Array.from({length:16},(_,i)=>{const controlTotal=70+i*19,treatmentTotal=78+i*17,p=.12+i*.034;return{label:`Study ${i+1}`,controlEvents:Math.round(controlTotal*p),controlTotal,treatmentEvents:Math.round(treatmentTotal*(p*.74+Math.sin(i)*.035)),treatmentTotal};})},
 nomogram:{title:'透明线性评分计算',subtitle:'确定性合成评分规则 · 未拟合模型 · 分数不代表风险概率',unit:'分',intercept:50,data:[['Quality / %',50,100,.6,75,88],['Delivery / day',1,20,-1.8,10,7],['Capacity / GB',16,128,.22,64,96],['Support / hour',0,24,.8,8,14]].map(([variable,minimum,maximum,coefficient,reference,value])=>({variable,minimum,maximum,coefficient,reference,value}))}
};
const enSpecs={
 radviz:['Variable-normalized observations find equilibrium among equally spaced circular anchors.','Multivariate patterns and attribute bias','Treating projected distance as original distance or comparing differently normalized datasets','3–8 nonconstant variables, 5–100 complete samples and 1–6 groups; each sample needs positive total normalized weight.','One row is one original measurement of a variable for a sample. Supply every sample × variable and keep its group consistent.'],
 hiveplot:['Three explicit group axes organize a network; supplied normalized positions locate nodes and line widths encode undirected strength.','Cross-group networks and structural comparison','Reading direction into undirected links or inferring unsupplied node attributes','Exactly 3 named axes, 3–60 positive cross-axis edges; every node has a consistent group and position in [0,1].','One row is one undirected relation. Provide both node names, groups, normalized positions and positive weight.'],
 cumulativegains:['Samples enter in descending predicted probability, with complete tied-score blocks entering together.','Target discovery and held-out ranking comparisons','Breaking ties arbitrarily or using training-set performance as generalization','1–3 models; 8–300 identical held-out samples per model with both actual classes.','Each row is one sample, model, true binary outcome and predicted positive-class probability.'],
 decisioncurve:['Net benefit varies with threshold and is compared against act-on-all and act-on-none strategies.','Threshold sensitivity and binary decision strategy evaluation','Confusing net benefit with accuracy or interpreting a demo as validated decision guidance','1–3 models, 8–300 common test samples each; 0 < thresholdMin < thresholdMax < 1.','Each row is a held-out outcome and predicted probability, with the same labeled population under every model.'],
 rankclock:['Time advances around a circle while radius encodes competition rank in each complete period.','Ranking shifts and relative performance','Reading rank distance as value distance or inventing a closing time transition','3–8 objects × 4–16 complete periods; rankOrder ascending or descending; ties use 1,1,3.','One row is one object in one period with its original value. Period order follows first appearance.'],
 funnelcontrol:['Sample size versus event proportion is compared with a known binomial reference and approximate normal control limits.','Proportion monitoring across units with different sample sizes','Confusing this with a meta-analysis funnel, exact binomial limits or specification limits','5–100 complete integer counts; 0 < targetRate < 1; n×p and n×(1−p) must both be at least 5.','One row is one unit with events and its full observed denominator; targetRate is an independently specified reference.'],
 labbe:['Paired control and treatment event proportions locate each study, with bubble area representing combined sample size.','Two-arm event rates and study heterogeneity','Calling bubble size inverse-variance weight or assuming more events means benefit','3–60 studies; positive integer denominators and integer event counts within each denominator.','One row supplies both event counts and denominators from the same two-arm study.'],
 nomogram:['Aligned predictor rulers express linear contributions on a shared score scale and sum to a total score.','Transparent additive scoring and scenario explanation','Turning unvalidated scores into risk probabilities or ignoring declared input ranges','3–7 variables; minimum < maximum; reference and current values within range; finite intercept.','One row is one numeric predictor, range, coefficient, reference value and current input. No model is fitted.']
};
const fieldEN={sample:'Sample identifier',variable:'Variable name with original measurement unit',group:'Consistent sample group',value:'Original value',source:'First node name',target:'Second node name',sourceGroup:'First node axis',targetGroup:'Second node axis',sourcePosition:'First node normalized axis position [0,1]',targetPosition:'Second node normalized axis position [0,1]',label:'Original sample, object or study identifier',model:'Prediction model',actual:'Observed binary outcome: 0 or 1',score:'Predicted probability for class 1, in [0,1]',period:'Period ordered by first appearance',events:'Observed integer event count',total:'Complete positive integer denominator',controlEvents:'Control-arm integer event count',controlTotal:'Control-arm positive integer denominator',treatmentEvents:'Treatment-arm integer event count',treatmentTotal:'Treatment-arm positive integer denominator',minimum:'Declared minimum input',maximum:'Declared maximum input',coefficient:'Linear coefficient in score per input unit',reference:'Reference input, within declared range'};
export const volume16English=Object.fromEntries(volume16Catalog.map(t=>{const [description,use,avoid,limit,rowMeaning]=enSpecs[t.id];return[t.id,{description,use,avoid,limit,rowMeaning,fields:t.fields.map(([k,type])=>[k,type,fieldEN[k]])}];}));
