// Deterministic synthetic inputs. Diagnostics are calculated from one declared synthetic OLS fit.
const str=(key,label)=>[key,'string',label],num=(key,label)=>[key,'number',label];
const observation=[str('label','原始观测唯一编号'),str('group','观测分组'),num('value','原始测量值')],diagnostic=[str('label','拟合观测唯一编号'),num('leverage','同一 OLS 拟合的帽子矩阵对角元 h'),num('stdResidual','内部标准化残差 e/(s√(1−h))')];
const specs=[
 ['boxen','嵌套分位箱图','Letter-value boxen plot','distribution',observation,'用逐层尾部分位区间展示大样本分布，保留每条原始观测。','比较群体分布、长尾和尾部分位变化','把分位区间当均值置信区间；从箱宽推断频数密度','1–5 组，每组 16–240 个完整观测；Type 7 分位数，最深尾部至少 4 个样本'],
 ['sina','密度抖动散点','Sina density scatter','distribution',observation,'原始观测沿数值轴准确定位，横向按局部密度确定抖动范围。','兼顾原值、样本量和分布形态的组间比较','将横向距离当测量变量；把固定抖动当聚类结果','1–5 组，每组 8–200 个观测；明确正 bandwidth；不抖动数值轴'],
 ['rootogram','悬挂根图','Hanging rootogram','research',[str('label','按输入顺序排列的箱或计数类别'),num('observed','真实观察频数，非负整数'),num('expected','外部模型给出的非负期望频数')],'频数开平方后从期望曲线向下悬挂观察柱，柱底相对零线暴露模型失配。','检查计数模型、过多零值和分布尾部失配','自动把观察频数拟合成期望；把平方根差当 Pearson 残差','4–32 个有序箱；observed 整数、expected 可为小数；明确 modelName'],
 ['ecdfband','经验分布置信带','ECDF with DKW band','research',[str('label','独立原始观测唯一编号'),num('value','原始测量值')],'右连续经验分布外围绘制 DKW 同时置信带，覆盖整个总体分布函数。','独立同分布样本的分布不确定性展示','当作均值区间或点态区间；用于相关时间序列而不调整假设','8–600 个独立同分布观测；alpha 在 0.001–0.5；重复值完整计入'],
 ['qqcompare','双样本Q-Q图','Two-sample Q–Q plot','research',observation,'在共同概率网格上比较两组样本分位数，以等单位对角线显示分布差异。','比较位置、尺度和尾部差异；样本量可以不同','把分位点当成真实配对观测；把对角线当拟合回归线','恰好 2 组，每组 8–300 个同单位观测；groupOrder 明确横纵方向'],
 ['worm','去趋势Q-Q图','Worm plot','research',[str('label','模型残差唯一编号'),str('group','预先定义的诊断分层'),num('stdResidual','外部计算的正态标准化或分位残差')],'各层残差的正态 Q-Q 图减去理论分位数，偏移围绕零线形成诊断曲线。','检查模型残差的偏移、尺度或尾部失配','把相关残差的示意包络当精确区间；自动把原值当标准化残差','1–4 层，每层 8–180 个已标准化残差；固定标准正态参考，不重新拟合'],
 ['spreadlevel','离散度水平图','Spread–level plot','research',observation,'在双对数轴上比较各组中位数与四分位距，观察离散度随水平的变化。','正值组间异方差探索和尺度效应','把 IQR 当标准差；把描述性斜率当方差齐性检验','3–10 组，每组 8–100 个正原值；组内 IQR > 0，组间中位数不全相同'],
 ['scalelocation','尺度位置诊断','Scale–location plot','research',[str('label','拟合观测唯一编号'),num('fitted','外部模型拟合值'),num('stdResidual','同一 OLS 拟合的内部标准化残差')],'以拟合值为横轴、标准化残差绝对值的平方根为纵轴，检查残差尺度模式。','检查线性模型残差的尺度变化','把图形趋势当显著性检验；混合不同拟合或外部学生化残差','8–300 个完整诊断记录；明确 modelName；不重新拟合原模型'],
 ['residualleverage','残差杠杆诊断','Residuals versus leverage','research',diagnostic,'标准化残差与杠杆值共同定位观测，叠加同一 OLS 模型的 Cook 距离等值线。','联合定位高杠杆与较大残差的影响点','将 Cook 等值线当删除阈值；混用外部学生化残差或不同模型','8–300 个完整 OLS 诊断；0 ≤ h < 1；parameterCount 含截距，帽子迹与参数数一致'],
 ['cooksdistance','Cook影响距离','Cook influence distance','research',diagnostic,'按原始观测顺序展示删除单点对整体拟合的 Cook 距离，保留高影响点身份。','定位需要核实的影响观测，比较影响集中度','自动删除超过 4/n 的点；将 Cook 距离当误差或概率','8–300 个完整 OLS 诊断；与残差杠杆图相同的参数数和标准化约定'],
 ['addedvariable','偏回归图','Added-variable plot','research',[str('label','原始观测唯一编号'),num('xResidual','目标解释变量对其余协变量回归后的残差'),num('yResidual','响应变量对同一批其余协变量回归后的残差')],'同时去掉其余协变量后，展示目标变量与响应的剩余关系及残差平面的 OLS 直线。','解释多元线性回归的单个变量贡献','把未调整的原始 X/Y 填作残差；将条件斜率当因果效应','8–300 个同样本 OLS 残差对；明确 modelName 和两个轴的原单位；X 残差有变化'],
 ['componentresidual','成分残差图','Component-plus-residual plot','research',[str('label','原始观测唯一编号'),num('x','目标数值解释变量原值'),num('residual','外部完整 OLS 模型的普通残差')],'把已知线性成分 βx 加回完整模型残差，与该变量的线性成分对照。','检查单一数值项的线性形式是否合理','用于含该变量交互项的模型而不调整定义；把部分残差当预测值','8–300 个完整观测；明确 coefficient、modelName 和轴单位；仅线性无交互数值项']
];
export const volume17Catalog=specs.map(([id,name,en,category,fields,description,use,avoid,limit],i)=>({id,no:String(169+i),name,en,type:name,category,fields,description,use,avoid,limit,motion:'原生轨迹展开 / 原值显现 / 诊断结构推进',keywords:`${name} ${en} ${use}`,edition:17,research:category==='research',dataMode:['boxen','sina','ecdfband','qqcompare','spreadlevel'].includes(id)?'observations':'analysis',duration:8}));
const normalish=(i,j)=>Math.sin(i*1.713+j)*.82+Math.sin(i*.731+j*.8)*.63+Math.cos(i*.391-j)*.39;
const grouped=(groups,n,fn)=>groups.flatMap((group,j)=>Array.from({length:n},(_,i)=>({label:`${group}-${i+1}`,group,value:fn(i,j)})));
const distribution=grouped(['A','B','C','D'],128,(i,j)=>+(25+j*9+normalish(i,j)*(3+j*.5)+Math.exp((i%17)/9)*(j===2?1.7:.35)).toFixed(5));
// Gram–Schmidt constructs the design [intercept, x, z]. Projecting a synthetic
// response into its orthogonal complement gives coherent complete OLS diagnostics.
function syntheticOLS(){const n=60,x=Array.from({length:n},(_,i)=>(i-(n-1)/2)/12),z=x.map((v,i)=>Math.sin(i*.49)+v*.16),sum=a=>a.reduce((a,b)=>a+b,0),dot=(a,b)=>sum(a.map((v,i)=>v*b[i])),mean=a=>sum(a)/n,center=a=>a.map(v=>v-mean(a)),normalize=a=>{const norm=Math.sqrt(dot(a,a));return a.map(v=>v/norm);},q0=Array(n).fill(1/Math.sqrt(n)),q1=normalize(center(x)),z1=center(z),q2=normalize(z1.map((v,i)=>v-dot(z1,q1)*q1[i])),raw=x.map((v,i)=>normalish(i,0)*(1+.24*v*v)+(i===51?4:0)),projected=raw.map((v,i)=>v-dot(raw,q0)*q0[i]-dot(raw,q1)*q1[i]-dot(raw,q2)*q2[i]),mse=dot(projected,projected)/(n-3),fitted=x.map((v,i)=>45+5*v+2*z[i]),y=fitted.map((v,i)=>v+projected[i]),zc=center(z),xc=center(x),yc=center(y),bx=dot(xc,zc)/dot(zc,zc),by=dot(yc,zc)/dot(zc,zc);return x.map((value,i)=>{const leverage=q0[i]**2+q1[i]**2+q2[i]**2;return{label:`S${i+1}`,x:value,residual:projected[i],fitted:fitted[i],leverage,stdResidual:projected[i]/Math.sqrt(mse*(1-leverage)),xResidual:xc[i]-bx*zc[i],yResidual:yc[i]-by*zc[i]};});}
const ols=syntheticOLS(),pick=(keys)=>ols.map(row=>Object.fromEntries(['label',...keys].map(k=>[k,row[k]]))),modelName='Synthetic OLS: y ~ 1 + x + z';
export const volume17Contents={
 boxen:{title:'把长尾分布展开看',subtitle:'确定性合成原值 · 嵌套 Type 7 分位区间 · 细点保留全部样本',unit:'ms',data:distribution},
 sina:{title:'每个原值都有位置',subtitle:'确定性合成原值 · 数值轴不抖动 · 宽度共用密度尺度',unit:'ms',bandwidth:2.4,data:distribution.filter(r=>r.group!=='D').filter((_,i)=>i%2===0)},
 rootogram:{title:'模型漏掉了哪些计数',subtitle:'确定性合成计数与外部期望 · 柱底为 √期望−√观察',unit:'次',modelName:'Synthetic fitted count distribution',data:[['0',49,28.4],['1',45,49.7],['2',57,61.1],['3',52,53.5],['4',33,35.1],['5',22,18.4],['6',10,8.1],['7',5,3.0],['8+',2,.7]].map(([label,observed,expected])=>({label,observed,expected}))},
 ecdfband:{title:'样本分布还有多少不确定性',subtitle:'确定性合成独立样本 · DKW 同时置信带，置信水平 95%',unit:'ms',alpha:.05,data:distribution.filter(r=>r.group==='B').map(({label,value})=>({label,value}))},
 qqcompare:{title:'两组分布的形状差异',subtitle:'确定性合成原值 · 共同分位概率网格 · 原始样本数可不同',unit:'ms',groupOrder:['A','C'],data:distribution.filter(r=>['A','C'].includes(r.group)).filter((r,i)=>r.group==='A'||i%2===0)},
 worm:{title:'分层检查残差分布',subtitle:'确定性合成分析残差 · 固定标准正态参考 · 无拟合或置信包络',unit:'标准化残差',modelName:'Synthetic standardized residual diagnostic',data:['A','B','C','D'].flatMap((group,j)=>Array.from({length:36},(_,i)=>{const p=(i+.5)/36,t=Math.log(p/(1-p))/.56/3;return{label:`${group}-${i+1}`,group,stdResidual:t*(1+j*.11)+[0,.25,-.2,0][j]+(j===3?.14*t*t:0)};}))},
 spreadlevel:{title:'数值越高波动是否越大',subtitle:'确定性合成正原值 · 中位数与 IQR 的 log₁₀ 比较',unit:'ms',data:grouped(['A','B','C','D','E','F'],40,(i,j)=>+(18+j*16+normalish(i,j)*(1.4+j*1.35)).toFixed(5))},
 scalelocation:{title:'残差尺度随拟合值变化',subtitle:'同一个确定性合成 OLS 拟合 · 纵轴 √|内部标准化残差|',unit:'诊断值',modelName,data:pick(['fitted','stdResidual'])},
 residualleverage:{title:'哪些观测同时有杠杆和残差',subtitle:'同一个确定性合成 OLS 拟合 · Cook 等值线不是删除规则',unit:'诊断值',modelName,parameterCount:3,data:pick(['leverage','stdResidual'])},
 cooksdistance:{title:'定位影响整体拟合的观测',subtitle:'同一个确定性合成 OLS 拟合 · 原始观测顺序 · 4/n 仅作参考',unit:'Cook D',modelName,parameterCount:3,data:pick(['leverage','stdResidual'])},
 addedvariable:{title:'控制其余变量后的关系',subtitle:'同一个确定性合成 OLS 拟合 · 残差平面直线，未重复拟合原模型',unit:'残差单位',modelName,axes:{x:'X residual / units',y:'Y residual / units'},data:pick(['xResidual','yResidual'])},
 componentresidual:{title:'检查变量的线性成分',subtitle:'同一个确定性合成 OLS 拟合 · 部分残差 = e + βx · 无交互项',unit:'响应单位',modelName,coefficient:5,axes:{x:'Predictor X / units',y:'Component + residual / units'},data:pick(['x','residual'])}
};
const en={
 boxen:['Nested tail-quantile boxes expose large-sample distribution structure while retaining every original observation.','Group distributions, long tails and tail-quantile patterns','Reading quantile intervals as mean confidence intervals or box width as density','1–5 groups of 16–240 complete observations. Type 7 quantiles; deepest tail retains at least four observations.','One row is one original measurement with a unique label and group.'],
 sina:['Values keep their exact vertical coordinate; local density determines deterministic horizontal jitter width.','Comparing original observations, sample size and distribution shape','Reading horizontal offsets as a measured variable or interpreting jitter as clusters','1–5 groups of 8–200 observations; declare positive bandwidth. The value axis is never jittered.','One row is an original value and group. Horizontal placement is derived solely for display.'],
 rootogram:['Observed square-root bars hang from the expected square-root curve; their bottoms show lack of fit against zero.','Count models, excess zeros and tail discrepancies','Silently fitting expected counts or calling square-root differences Pearson residuals','4–32 ordered bins; observed is a nonnegative integer and expected a nonnegative external expectation; modelName is required.','One row is a declared bin with its observed frequency and externally calculated expected frequency.'],
 ecdfband:['A right-continuous empirical CDF is enclosed by a DKW simultaneous confidence band for the entire population CDF.','Distribution uncertainty for independent identically distributed samples','Calling the band a mean interval or pointwise interval, or applying IID assumptions to dependent time series','8–600 IID observations; alpha is 0.001–0.5 and ties retain their full mass.','One row is one original IID observation, including all repeated values.'],
 qqcompare:['A common probability grid compares sample quantiles, with an equal-unit identity line and original-data rugs.','Comparing distribution location, scale and tails with unequal sample sizes','Treating derived quantile points as observed pairs or the identity line as a regression fit','Exactly 2 groups of 8–300 same-unit observations; groupOrder specifies horizontal then vertical group.','One row is one original measurement from one of the two declared groups; observations need not be paired.'],
 worm:['Normal Q–Q deviations are plotted around zero within each supplied stratum using a fixed standard-normal reference.','Inspecting residual location, scale and tail patterns by stratum','Inventing confidence envelopes or passing raw outcomes as standardized residuals','1–4 strata of 8–180 precomputed standardized or normal quantile residuals; no reference fit is estimated.','One row is an external standardized residual and its predeclared diagnostic stratum.'],
 spreadlevel:['Group medians and interquartile ranges are compared on log10 axes to inspect how spread changes with level.','Exploring heteroscedasticity and scale effects in positive grouped data','Calling IQR a standard deviation or a descriptive slope a variance test','3–10 groups of 8–100 positive values, positive group IQRs and nonconstant group medians.','One row is one original positive observation. Median and Type 7 IQR are calculated within its group.'],
 scalelocation:['Fitted values versus square-root absolute internally standardized residuals expose patterns in residual scale.','Inspecting residual scale variation in a linear model','Treating patterns as a significance test or mixing models and externally studentized residuals','8–300 complete diagnostic records with modelName; the original model is not refitted.','One row is one observation’s external fitted value and internal standardized residual from the same OLS model.'],
 residualleverage:['Internally standardized residual and leverage jointly locate observations, with equal-Cook-distance contours from the same OLS model.','Investigating observations with high leverage and large residuals','Using contour crossings as automatic deletion rules or mixing residual conventions','8–300 complete OLS records; 0 ≤ leverage < 1; parameterCount includes the intercept and equals the hat-matrix trace.','One row supplies a complete-case OLS leverage and internal residual e/(s√(1−h)); retain every fitted observation.'],
 cooksdistance:['Cook distance by original observation order shows the influence of removing one observation on the overall fitted model.','Finding influential observations to investigate and retaining their identities','Automatically deleting points beyond 4/n or treating distance as an error or probability','8–300 complete OLS records with the same parameter count and internal-residual convention as residual–leverage diagnostics.','One row supplies the leverage and internally standardized residual from one complete OLS fit. Cook distance is derived.'],
 addedvariable:['Residualizing both variables against the other covariates exposes their remaining relation and an OLS line in residual space.','Explaining a predictor’s contribution within a multiple linear regression','Passing unadjusted X/Y as residuals or treating a conditional slope as causal','8–300 residual pairs from the same OLS sample; declare modelName and both axis units; X residuals must vary.','One row supplies X and Y residuals after separate regressions on the same remaining covariates and intercept.'],
 componentresidual:['The supplied linear component βx is added to each full-model residual and compared with the component line.','Inspecting the linear form of one numeric predictor','Applying this simple definition to interactions or treating partial residuals as predictions','8–300 complete observations; declare coefficient, modelName and axes; one linear numeric term without interactions.','One row is a predictor’s original value and the ordinary residual from the complete OLS model; coefficient comes from that fit.']
};
const fieldEN={label:'Unique original observation or bin identifier',group:'Observation group or predeclared diagnostic stratum',value:'Original measured value',observed:'Observed nonnegative integer count',expected:'Externally calculated nonnegative expected count',stdResidual:'Internally standardized or declared normal quantile residual',fitted:'External model fitted value',leverage:'External OLS hat-matrix diagonal h, in [0,1)',xResidual:'Residual of X after adjustment for the other covariates',yResidual:'Residual of Y after adjustment for the same other covariates',x:'Original numeric predictor value',residual:'Ordinary residual from the complete external OLS model'};
export const volume17English=Object.fromEntries(volume17Catalog.map(t=>{const [description,use,avoid,limit,rowMeaning]=en[t.id];return[t.id,{description,use,avoid,limit,rowMeaning,fields:t.fields.map(([key,type])=>[key,type,fieldEN[key]])}];}));
