// Deterministic synthetic examples; frequency responses and model roots are supplied results, never fitted here.
const str=(k,d)=>[k,'string',d],num=(k,d)=>[k,'number',d],nullable=(k,d)=>[k,'number | null',d];
const response=[str('label','采样点唯一编号'),str('group','同一响应曲线名称'),num('frequency','正采样频率，单位见 frequencyUnit'),num('real','复响应实部，线性幅值比'),num('imag','复响应虚部，线性幅值比')];
const specs=[
 ['bode','波特幅相图','Bode magnitude and phase','research',response,'同一组复频响同时呈现对数频率下的分贝幅值和展开相位。','频率响应测量、控制器比较、滤波器分析','从稀疏相位采样推断真实多圈相位；由部分响应判定稳定性','每组 4–160 点、1–4 组，总计 ≤480；频率正且组内唯一；复响应不能为零'],
 ['nyquist','奈奎斯特图','Nyquist response locus','research',response,'按频率顺序连接输入复响应，在等比例实虚坐标中呈现轨迹。','频域响应轨迹、控制模型结果、阻抗比观察','把只输入的正频率轨迹当完整 Nyquist 轮廓；自动镜像或宣称稳定','每组 4–160 点、1–4 组，总计 ≤480；只画提供的正频率点，不补负频率'],
 ['nichols','尼科尔斯图','Nichols response plot','research',response,'以展开相位为横轴、分贝幅值为纵轴，把频率响应压缩成一条轨迹。','增益与相位联合观察、频率响应结果对比','把图当闭环等值线图；没有极点信息时作稳定性判断','每组 4–160 点、1–4 组，总计 ≤480；正频率、非零复响应；不计算稳定裕度'],
 ['polezero','零极点图','Pole-zero map','research',[str('label','根的唯一编号，重根分别输入'),str('kind','pole 表示极点，zero 表示零点'),num('real','根的实部'),num('imag','根的虚部')],'十字与空心圆在等比例复平面上标记外部给定的极点和零点。','系统根分布、滤波器结构、模型结果说明','把不完整根表当完整系统；自动消去相近根或给出稳定结论','2–80 个根；systemDomain 明确 continuous 或 discrete；重根不合并删除'],
 ['smith','史密斯阻抗图','Smith impedance chart','research',[str('label','阻抗点唯一编号'),str('group','同一阻抗曲线名称'),num('frequency','正采样频率'),num('real','阻抗电阻分量 / Ω'),num('imag','阻抗电抗分量 / Ω')],'把输入阻抗按指定参考阻抗映射到反射系数平面，以阻抗网格辅助读数。','射频阻抗测量、匹配路径、网络分析仪结果','将阻抗误当反射系数；把圆内轨迹当已证明的系统稳定性','每组 4–160 点、1–4 组，总计 ≤480；电阻非负，参考阻抗为正实数'],
 ['windrose','风向频率玫瑰图','Wind-frequency rose','distribution',[str('label','原始风观测唯一编号'),nullable('direction','风来自的方向，北为 0° 顺时针；静风可为 null'),num('speed','非负原始风速')],'按风向扇区与风速段统计全部原始观测，径向长度表示占完整样本的频率。','风向分布、气象站观测、环境监测','把扇区面积当频率；去除静风后偷偷改变分母','12–1000 条观测；8/16 个扇区；2–6 速度段；静风计入完整样本分母'],
 ['polarscatter','极坐标散点图','Polar scatterplot','research',[str('label','原始点唯一编号'),str('group','点的分组'),num('angle','方向角：北为 0°，顺时针，范围 [0,360)'),num('radius','非负原始径向量')],'方向角与原始径向量共同定位观测点，分组颜色保持一致。','方向性测量、传感器观测、极坐标样本比较','把半径平方当原始量；把顺时针方位角与数学角混淆','5–400 个完整点、1–6 组；角度 [0,360)，半径非负且并非全零'],
 ['hodograph','风矢量廓线图','Wind hodograph','research',[str('label','测量层唯一编号'),num('height','非负测量高度'),num('u','向东为正的风分量'),num('v','向北为正的风分量')],'在等比例风分量坐标中按高度连接测量层，色深显示原始高度。','高空风廓线、垂直风切变、风矢量结构','把连线长度当高度间距；把风去向分量当风来向角','4–100 个唯一高度；heightUnit 明确高度单位；u/v 使用同一风速单位'],
 ['phasor','相量图','Phasor diagram','research',[str('label','相量唯一名称'),num('real','同相实分量'),num('imag','正交虚分量')],'同一原点的复向量展示各相量，虚线向量表示复数和。','交流同频相量、复幅值合成、相位关系','混用 RMS 与峰值；混合不同频率或不同物理单位相量','2–12 个同单位相量；phaseConvention 明确 rms 或 peak；频率必须一致并声明'],
 ['eyediagram','眼图','Eye diagram','research',[str('label','原始时域采样点唯一编号'),num('time','原始等间隔采样时刻'),num('value','原始实值信号幅度')],'按显式符号周期把真实采样分成双符号窗口叠加，保留每个原始值。','数字信号波形、时序抖动观察、通信链路演示','自动恢复时钟或补造交点；把图形直接当误码率测量','24–1000 个等间隔点；每符号 4–128 个采样；显式 symbolPeriod、timeOrigin、timeUnit'],
 ['constellation','通信星座图','IQ constellation','research',[str('label','符号观测唯一编号'),str('group','符号来源或已知分组'),num('real','原始同相分量 I'),num('imag','原始正交分量 Q')],'等比例 I/Q 坐标保留原始符号观测，展示分组与散布，不自动吸附理想点。','解调符号、I/Q 采样、调制质量探索','将任意波形采样当符号抽样；未给参考星座时计算误差向量幅度','8–1000 个完整符号、1–8 组；I/Q 同单位；不自动归一化、旋转或判决'],
 ['campbell','转速频率图','Campbell mode diagram','research',[str('mode','外部识别的分支或模态名称'),num('speed','非负转速 / rpm'),num('frequency','非负模态频率 / Hz'),num('amplitude','非负响应幅值，点面积表示幅值')],'按转速连接外部给定的模态频率，幅值决定点面积，阶次参考线由显式阶次数组给定。','旋转机械模态、转速扫频、共振交叉点观察','将参考线交叉直接当共振证明；由稀疏分支伪造完整功率谱','1–6 分支，每支 4–120 个唯一转速，总计 ≤600；orders 为 1–6 个正阶次']
];
export const volume19Catalog=specs.map(([id,name,en,category,fields,description,use,avoid,limit],i)=>({id,no:String(193+i),name,en,type:name,category,fields,description,use,avoid,limit,motion:'原始复向量定位 / 频率轨迹描绘 / 样本逐层显现',keywords:`${name} ${en} ${use}`,edition:19,research:category==='research',dataMode:['windrose','polarscatter','hodograph','eyediagram','constellation'].includes(id)?'observations':'analysis',duration:8}));
const responses=['A','B'].flatMap((group,j)=>Array.from({length:48},(_,i)=>{const frequency=10**(-1+i*3/47),q=frequency/(4+j*1.2),denR=1-q*q,denI=(.5+j*.22)*q,den=denR*denR+denI*denI;return{label:`${group}-${i+1}`,group,frequency:+frequency.toPrecision(8),real:+(denR/den).toPrecision(9),imag:+(-denI/den).toPrecision(9)};}));
const iq=Array.from({length:224},(_,i)=>{const group=['A','B','C','D'][i%4],a=[-1,1,-1,1][i%4],b=[-1,-1,1,1][i%4];return{label:`Q${i+1}`,group,real:+(a+.12*Math.sin(i*2.37)+.055*Math.cos(i*.9)).toFixed(5),imag:+(b+.11*Math.cos(i*1.73)+.045*Math.sin(i*.4)).toFixed(5)};});
const symbols=[-1,1,1,-1,1,-1,-1,1,1,1,-1,-1,1,-1,1,1,-1,1,-1,-1,1];
export const volume19Contents={
 bode:{title:'两组系统的幅值与相位',subtitle:'确定性合成复频响 · 不拟合系统，不计算稳定裕度',unit:'gain ratio',frequencyUnit:'Hz',data:responses},
 nyquist:{title:'复频响如何随频率移动',subtitle:'确定性合成复频响 · 仅正频率输入轨迹，非完整稳定性轮廓',unit:'gain ratio',frequencyUnit:'Hz',data:responses},
 nichols:{title:'增益与相位的联合轨迹',subtitle:'确定性合成复频响 · 相位按相邻采样展开，不计算闭环等值线',unit:'gain ratio',frequencyUnit:'Hz',data:responses},
 polezero:{title:'系统根在复平面的位置',subtitle:'确定性合成根表 · 十字为极点，空心圆为零点，不推断稳定性',unit:'s⁻¹',systemDomain:'continuous',data:[['P1','pole',-.55,2.5],['P2','pole',-.55,-2.5],['P3','pole',-1.7,4.2],['P4','pole',-1.7,-4.2],['P5','pole',-4,0],['Z1','zero',-2.7,1.1],['Z2','zero',-2.7,-1.1],['Z3','zero',-.9,0]].map(([label,kind,real,imag])=>({label,kind,real,imag}))},
 smith:{title:'射频阻抗的匹配轨迹',subtitle:'确定性合成阻抗 · 参考阻抗 50 Ω，曲线按频率推进',unit:'Ω',frequencyUnit:'GHz',referenceImpedance:50,data:['A','B'].flatMap((group,j)=>Array.from({length:36},(_,i)=>{const f=1+i*.05;return{label:`${group}-${i+1}`,group,frequency:+f.toFixed(3),real:+(25+j*16+18*Math.sin(i*.1)**2).toFixed(5),imag:+((f-(1.8+j*.12))*110+18*Math.sin(i*.18)).toFixed(5)};}))},
 windrose:{title:'风从哪里来、通常有多强',subtitle:'确定性合成风观测 · 所有观测含静风作为百分比分母',unit:'m/s',calmThreshold:.5,windSectors:16,speedBreaks:[.5,2,5,8,12],data:Array.from({length:320},(_,i)=>{const speed=i%17===0?.2:+(.7+(i*13%145)/10).toFixed(2);return{label:`W${i+1}`,direction:speed<.5?null:+((i*137.508+(i%3)*23)%360).toFixed(5),speed};})},
 polarscatter:{title:'观测方向与径向量',subtitle:'确定性合成观测 · 北为 0° 顺时针，半径保持原单位',unit:'m',data:Array.from({length:84},(_,i)=>({label:`R${i+1}`,group:['A','B','C'][i%3],angle:+((i*137.508)%360).toFixed(5),radius:+(20+(i%3)*17+13*Math.sin(i*.73)).toFixed(4)}))},
 hodograph:{title:'随高度变化的风矢量',subtitle:'确定性合成风廓线 · u 向东为正，v 向北为正，色深为高度',unit:'m/s',heightUnit:'m',data:Array.from({length:19},(_,i)=>({label:`H${i+1}`,height:i*350,u:+(3+i*.93+4*Math.sin(i*.2)).toFixed(5),v:+(-4+10*Math.sin(i*.14)+i*.38).toFixed(5)}))},
 phasor:{title:'同频相量与复数合成',subtitle:'确定性合成 RMS 相量 · 虚线为复数和，实轴为 0°',unit:'V',frequency:50,frequencyUnit:'Hz',phaseConvention:'rms',data:[['A',115,0],['B',-47,81.4064],['C',-33,-57.1577]].map(([label,real,imag])=>({label,real,imag}))},
 eyediagram:{title:'真实时域采样的双符号叠加',subtitle:'确定性合成波形 · 只折叠原始点，不恢复时钟，不补造交点',unit:'V',symbolPeriod:1,timeOrigin:0,timeUnit:'ns',data:Array.from({length:321},(_,i)=>{const time=i/16,k=Math.min(19,Math.floor(time)),fraction=time-k,from=symbols[Math.max(0,k-1)],to=symbols[k],blend=Math.min(1,fraction/.3),value=from+(to-from)*(1-Math.cos(blend*Math.PI))/2+.04*Math.sin(i*1.9);return{label:`S${i+1}`,time,value:+value.toFixed(6)};})},
 constellation:{title:'I/Q 符号的真实散布',subtitle:'确定性合成符号 · 不吸附理想点，不自动计算 EVM 或误码率',unit:'V',data:iq},
 campbell:{title:'转速扫频中的模态与阶次',subtitle:'确定性合成模态结果 · 点面积为幅值，虚线仅为阶次参考',unit:'mm/s',orders:[1,2,3],data:['Mode A','Mode B','Mode C'].flatMap((mode,j)=>Array.from({length:25},(_,i)=>{const speed=300+i*175,frequency=[26+speed*.003,68-speed*.003,105+speed*.006][j],amplitude=.15+2.4*Math.exp(-(((frequency-speed*(j+1)/60)/13)**2));return{mode,speed,frequency:+frequency.toFixed(4),amplitude:+amplitude.toFixed(6)};}))}
};
const en={
 bode:['The same complex response becomes log-frequency magnitude in decibels and unwrapped phase.','Frequency-response measurements, filter analysis and controller comparisons','Inferring unsampled phase turns or stability from incomplete response data','1–4 curves, 4–160 points each, at most 480 total; positive unique within-group frequency and nonzero complex response.','One row is a supplied complex response at one positive frequency; real and imaginary parts are linear gain ratios.'],
 nyquist:['Supplied complex responses trace an equal-scale real-imaginary locus in increasing frequency order.','Frequency-response loci and control-model results','Treating a supplied positive-frequency locus as a full Nyquist contour or making stability claims','1–4 curves, 4–160 points each, at most 480 total; only supplied positive-frequency samples are drawn, without mirroring.','One row is an original complex response. Frequency orders the locus; no negative-frequency response is manufactured.'],
 nichols:['Unwrapped phase versus decibel magnitude jointly represents the supplied frequency response.','Joint phase/gain inspection and response comparison','Assuming closed-loop contour grids or stability margins are calculated','1–4 curves, 4–160 points each, at most 480 total; positive frequency and nonzero complex response.','One row is a supplied frequency-response sample, transformed to magnitude and adjacent-sample unwrapped phase.'],
 polezero:['Crosses and hollow circles mark externally supplied poles and zeros on an equal-scale complex plane.','System roots, filter structure and model-result communication','Treating an incomplete root table as a complete system or automatically cancelling nearby roots','2–80 roots; systemDomain must be continuous or discrete. Repeated roots are separate retained records.','One row is one externally calculated root. kind is pole or zero; repeated roots retain distinct labels.'],
 smith:['Supplied impedances map to reflection coefficients using an explicit real reference impedance.','RF impedance measurements and matching trajectories','Supplying reflection coefficients as impedances or inferring system stability from the unit disk','1–4 curves, 4–160 points each, at most 480 total; nonnegative resistance and positive real referenceImpedance.','One row is measured or externally calculated impedance in ohms at one positive frequency.'],
 windrose:['Direction sectors stack speed-bin frequencies using the complete observation count, including calm records.','Wind direction, meteorological observations and environmental monitoring','Reading wedge area as frequency or removing calm observations from the denominator','12–1000 observations, 8 or 16 sectors, 2–6 speed bins; calm observations remain in the denominator.','One row is an original wind observation. direction is the bearing the wind comes from; calm records may have null direction.'],
 polarscatter:['Compass bearing and original radial magnitude locate each observation, with consistent group colors.','Directional measurements and polar-coordinate samples','Confusing squared radius with the measured quantity or using mathematical-angle orientation','5–400 points, 1–6 groups; angle in [0,360), nonnegative radius with at least one positive value.','One row is one original polar observation. Bearing is clockwise from north, and radius retains its declared unit.'],
 hodograph:['Equal-scale eastward and northward wind components connect in increasing height order. Color encodes height.','Vertical wind profiles and vector structure','Reading line length as height difference or interpreting component direction as wind-from bearing','4–100 distinct nonnegative heights; explicit heightUnit, with u and v in one common wind-speed unit.','One row is one measured level, its height, eastward-positive u and northward-positive v.'],
 phasor:['Complex vectors share one origin and a dashed vector displays their complex sum.','Same-frequency AC phasors and phase relationships','Mixing RMS with peak conventions, different frequencies or physical units','2–12 same-unit phasors; phaseConvention is rms or peak; one positive common frequency is explicitly declared.','One row is one complex phasor with real and imaginary components under the shared frequency and amplitude convention.'],
 eyediagram:['Explicit two-symbol windows overlay original equally spaced waveform samples without synthesizing crossing points.','Digital waveforms, timing patterns and communications demonstrations','Assuming clock recovery, reconstructed crossing samples or measured bit-error rate','24–1000 equally spaced samples, 4–128 samples per symbol; explicit symbolPeriod, timeOrigin and timeUnit.','One row is one original real-valued time-domain sample. Only time coordinates are folded; measured amplitudes are retained.'],
 constellation:['Equal-scale I/Q coordinates retain original symbol observations without snapping to ideal constellation points.','Demodulated symbols, IQ observations and modulation-pattern inspection','Treating arbitrary waveform samples as symbol decisions or calculating EVM without references','8–1000 complete symbols, 1–8 groups; I and Q share one unit. No normalization, rotation or decision rule is applied.','One row is one complex symbol observation with known source/group, real in-phase and imaginary quadrature components.'],
 campbell:['Externally identified modal frequencies connect across rotation speed, with amplitude-proportional marker area and explicit order references.','Rotating-machine modes and speed-sweep analysis','Treating a line intersection as proof of resonance or sparse branches as a complete power spectrum','1–6 branches with 4–120 unique speeds each, at most 600 total; orders contains 1–6 unique positive orders.','One row is one supplied modal frequency and response amplitude at a rotation speed in rpm.']
};
const fields={bode:['Unique response-sample label','Response curve','Positive frequency in frequencyUnit','Linear complex-response real part','Linear complex-response imaginary part'],nyquist:null,nichols:null,polezero:['Unique root label; repeated roots remain separate','pole or zero','Root real component','Root imaginary component'],smith:['Unique impedance-sample label','Impedance curve','Positive frequency in frequencyUnit','Resistance / Ω','Reactance / Ω'],windrose:['Unique original wind-observation label','Wind-from compass bearing [0,360); null allowed for calm','Original nonnegative speed'],polarscatter:['Unique original observation label','Observation group','Compass bearing [0,360), clockwise from north','Original nonnegative radial quantity'],hodograph:['Unique measured-level label','Original nonnegative height in heightUnit','Original eastward-positive wind component','Original northward-positive wind component'],phasor:['Unique phasor label','Original in-phase real component','Original quadrature imaginary component'],eyediagram:['Unique original sample label','Original equally spaced sample time','Original real-valued signal amplitude'],constellation:['Unique original symbol label','Known source or group','Original in-phase component I','Original quadrature component Q'],campbell:['Externally identified mode or branch','Original nonnegative speed / rpm','Original nonnegative mode frequency / Hz','Original nonnegative response amplitude; marker area encodes amplitude']};fields.nyquist=fields.bode;fields.nichols=fields.bode;
export const volume19English=Object.fromEntries(volume19Catalog.map(t=>{const [description,use,avoid,limit,rowMeaning]=en[t.id];return[t.id,{description,use,avoid,limit,rowMeaning,fields:t.fields.map(([k,type],i)=>[k,type,fields[t.id][i]])}];}));
