import {drawSectorLabels} from './chart-readability.js';
import {uiText,uiMarkup,uiMessage} from './locale.js';
import * as d3 from 'd3';
import {unique7 as unique,table7,horizonSamples} from './volume7-data.js';
import {phase7 as phase,short7 as short,number7 as fmt,num7 as num,texture7 as texture,label7 as label,frame7,spatialScale7,spatialAxes7} from './volume7-utils.js';
import {relation7Renderers} from './volume7-relations.js';
import {stat7Renderers} from './volume7-statistics.js';

function pie(s,doc){
  const {w,h,theme:t}=s,total=d3.sum(doc.data,d=>d.value),cx=w/2,cy=h/2-4,r=Math.min(w*.24,(h-76)/2),g=s.group({transform:`translate(${cx},${cy})`}),arc=d3.arc().innerRadius(0).outerRadius(r),sectors=d3.pie().sort(null).value(d=>d.value)(doc.data),marks=[];
  sectors.forEach((a,i)=>{const col=t.objectColor(a.data,t.colors[i%t.colors.length]),filled=i<2||t.categorical||t.custom,path=s.path('',{fill:filled?col:texture(s,`pie-${i}`,col),stroke:filled?t.bg:col,'stroke-width':.7,'data-mark':'pie-sector','data-angle':a.endAngle-a.startAngle,'data-value':a.data.value},g);s.edit(path,a.data);s.tip(path,`${a.data.label}\n${a.data.value} ${doc.unit} · ${fmt(a.data.value/(total||1)*100)}%`);s.add(p=>path.setAttribute('d',arc({...a,endAngle:a.startAngle+(a.endAngle-a.startAngle)*phase(p,i*.025,.65)})));marks.push({index:i,value:a.data.value,geometry:{cx,cy,r1:r,a0:a.startAngle-Math.PI/2,a1:a.endAngle-Math.PI/2},label:{visible:false}});});
  drawSectorLabels(s,marks,doc,{x:14,y:18,w:w-28,h:h-54});label(s,cx,h-4,uiMessage`合计 ${fmt(total)} ${doc.unit}`,{'text-anchor':'middle','font-size':s.fs-1},60);
}
function polarline(s,doc){
  const {w,h,theme:t}=s,cx=w/2,cy=h/2,r=Math.min(w*.3,(h-92)/2),scale=d3.scaleLinear([0,d3.max(doc.data,d=>d.value)],[0,r]).nice(3),g=s.group({transform:`translate(${cx},${cy})`}),halo={stroke:t.bg,'stroke-width':3.5,'paint-order':'stroke','stroke-linejoin':'round'};
  scale.ticks(3).filter(v=>v>0).forEach(v=>{s.circle(0,0,scale(v),{fill:'none',stroke:t.line,'stroke-width':.65,'stroke-dasharray':'1 4'},g);num(s,-r-58,-scale(v)+4,fmt(v),{'text-anchor':'end','font-size':s.fs-1,...halo},g);s.line(-r-48,-scale(v),-r-16,-scale(v),{'stroke-width':.6},g);});
  const pts=doc.data.map((d,i)=>{const a=i/doc.data.length*Math.PI*2-Math.PI/2,point=[Math.cos(a)*scale(d.value),Math.sin(a)*scale(d.value)];if(i%Math.ceil(doc.data.length/12)===0){const x=Math.cos(a),y=Math.sin(a),attrs={'text-anchor':x>.3?'start':x<-.3?'end':'middle','font-size':s.fs-1,...halo};s.line(x*3,y*3,x*r,y*r,{'stroke-width':.5},g);label(s,x*(r+24),y*(r+24)-3,d.period,attrs,16,g);num(s,x*(r+24),y*(r+24)+12,fmt(d.value),attrs,g);}return point;});
  const p=s.path(d3.line().curve(d3.curveLinearClosed)(pts),{stroke:t.accent,'stroke-width':1.6},g);s.draw(p,.08,.74);pts.forEach(([x,y],i)=>{const dot=s.circle(x,y,2.8,{fill:t.bg,stroke:t.accent,'stroke-width':1.2},g);s.tip(dot,`${doc.data[i].period}\n${doc.data[i].value} ${doc.unit}`);s.growCircle(dot,2.8,i/pts.length*.65,.25);});label(s,14,h-4,uiMessage`半径从零量起 · ${doc.unit}`,{'font-size':s.fs-1},48);
}

function stackedcolumn(s,doc){
  const {w,h,theme:t}=s,table=table7(doc.data),left=44,right=w-12,top=35,bottom=h-34,x=d3.scaleBand(table.columns,[left,right]).padding(.3),layers=d3.stack().keys(table.groups).value((r,k)=>r.values[k])(table.rows),y=d3.scaleLinear([0,d3.max(table.rows,r=>d3.sum(table.groups,k=>r.values[k]))],[bottom,top]).nice(4);
  s.legend(table.groups.map((n,i)=>({label:short(n,6),color:t.groupColor(n,t.color(i))})),left,12);y.ticks(4).forEach(v=>{s.line(left,y(v),right,y(v),{'stroke-width':.6,'stroke-dasharray':'1 5'});num(s,left-6,y(v)+3,fmt(v),{'text-anchor':'end'});});
  layers.forEach((layer,j)=>layer.forEach((d,i)=>{const col=t.groupColor(layer.key,t.colors[j%t.colors.length]),rect=s.rect(x(table.columns[i]),y(d[1]),x.bandwidth(),y(d[0])-y(d[1]),{fill:j<2?col:texture(s,`column-${j}`,col),stroke:col,'stroke-width':.6,'data-mark':'stacked-column','data-low':d[0],'data-high':d[1]});s.tip(rect,`${table.columns[i]} · ${layer.key}\n${d[1]-d[0]} ${doc.unit}`);s.add(p=>{const q=phase(p,i/table.columns.length*.3,.65);rect.setAttribute('y',y(d[1]*q));rect.setAttribute('height',y(d[0]*q)-y(d[1]*q));});}));table.columns.forEach((v,i)=>{if(i%Math.ceil(table.columns.length/(w<450?4:8))===0)label(s,x(v)+x.bandwidth()/2,bottom+19,v,{'text-anchor':'middle','font-size':s.fs-2},8);});
}
function streamgraph(s,doc){
  const {w,h,theme:t}=s,tab=table7(doc.data,'period','series',true),layers=d3.stack().keys(tab.groups).value((r,k)=>r.values[k]).offset(d3.stackOffsetSilhouette)(tab.rows),x=d3.scaleUtc(d3.extent(tab.columns,d=>new Date(d)),[18,w-18]),y=d3.scaleLinear(d3.extent(layers.flat(2)),[h-33,34]);
  s.legend(tab.groups.map((n,i)=>({label:short(n,6),color:t.color(i)})),18,12);const area=d3.area().x((d,i)=>x(new Date(tab.columns[i]))).y0(d=>y(d[0])).y1(d=>y(d[1])),g=s.group();
  layers.forEach((l,i)=>{const col=t.color(i),p=s.path(area(l),{fill:i<2?col:texture(s,`stream-${i}`,col),stroke:col,'stroke-width':.7,'fill-opacity':i<2?.78:1,'data-mark':'stream-band'},g);s.tip(p,uiMessage`${l.key}\n带宽表示 ${doc.unit}`);});s.clipReveal(g,18,28,w-36,h-61,.08,.8);
  tab.rows.forEach((r,i)=>{const hit=s.line(x(new Date(r.key)),32,x(new Date(r.key)),h-33,{stroke:'transparent','stroke-width':Math.max(6,(w-36)/tab.rows.length)});s.tip(hit,`${r.key}\n${tab.groups.map(k=>`${k}：${r.values[k]} ${doc.unit}`).join('\n')}`);});x.ticks(4).forEach(v=>num(s,x(v),h-13,d3.utcFormat('%m.%d')(v),{'text-anchor':'middle','font-size':s.fs-2}));
}
function horizon(s,doc){
  const {w,h,theme:t}=s,tab=table7(doc.data,'period','series',true),band=d3.max(doc.data,d=>Math.abs(d.value||0))/3,left=64,right=w-15,top=39,bottom=h-28,rowH=(bottom-top)/tab.groups.length,x=d3.scaleUtc(d3.extent(tab.columns,d=>new Date(d)),[left,right]);
  label(s,14,13,uiMessage`每层 ${fmt(band)} ${doc.unit}`,{'font-size':s.fs-2},s.compact?22:40);s.legend([{label:uiText('增加'),color:t.accent},{label:uiText('减少'),color:t.fg}],w-116,13);
  tab.groups.forEach((g,j)=>{const y=top+j*rowH,base=y+rowH-7,layer=s.group({'data-horizon-series':g}),samples=horizonSamples(tab.rows,g,band);label(s,left-9,y+rowH/2,g,{'text-anchor':'end','font-size':s.fs-2},5);s.line(left,base,right,base,{'stroke-width':.7});for(const sign of [-1,1])for(let b=0;b<3;b++){const area=d3.area().defined(d=>d.value!==null).x(d=>x(new Date(d.time))).y0(base).y1(d=>base-Math.min(band,Math.max(0,sign*d.value-b*band))/band*(rowH-12));s.path(area(samples),{fill:sign>0?t.accent:t.fg,'fill-opacity':[.18,.38,.72][b],'data-mark':'horizon-band','data-band':band,'data-sign':sign},layer);}s.clipReveal(layer,left,y,right-left,rowH,j*.035,.76);tab.rows.forEach(d=>{const tip=s.rect(x(new Date(d.key))-3,y,6,rowH-7,{fill:'transparent'});s.tip(tip,`${g} · ${d.key}\n${d.values[g]===null?uiText('缺失'):d.values[g]+' '+doc.unit}`);});});x.ticks(3).forEach(v=>num(s,x(v),h-8,d3.utcFormat('%m.%d')(v),{'text-anchor':'middle','font-size':s.fs-2}));
}
function cycleplot(s,doc){
  const {w,h,theme:t}=s,tab=table7(doc.data,'cycle','season'),left=42,right=w-12,top=32,bottom=h-40,slot=(right-left)/tab.groups.length,y=d3.scaleLinear(s.linearDomain(doc.data.map(d=>d.value),true),[bottom,top]).nice(3);
  y.ticks(3).forEach(v=>{s.line(left,y(v),right,y(v),{'stroke-dasharray':'1 5','stroke-width':.6});num(s,left-6,y(v)+3,fmt(v),{'text-anchor':'end'});});
  tab.groups.forEach((g,j)=>{const x=d3.scalePoint(tab.columns,[left+j*slot+slot*.12,left+(j+1)*slot-slot*.12]),col=j===0?t.accent:t.fg,values=tab.rows.map(r=>({cycle:r.key,value:r.values[g]})),avg=d3.mean(values,d=>d.value),path=s.path(d3.line().defined(d=>d.value!==null).x(d=>x(d.cycle)).y(d=>y(d.value))(values),{stroke:col,'stroke-width':1.2});s.draw(path,j*.045,.68);s.line(x(tab.columns[0]),y(avg),x(tab.columns.at(-1)),y(avg),{stroke:col,'stroke-dasharray':'3 3','stroke-opacity':.35});values.filter(d=>d.value!==null).forEach((d,i)=>{const point=s.circle(x(d.cycle),y(d.value),2,{fill:t.bg,stroke:col});s.tip(point,`${g} · ${d.cycle}\n${d.value} ${doc.unit}`);s.growCircle(point,2,.1+j*.045+i*.025,.5);});label(s,left+(j+.5)*slot,15,g,{'text-anchor':'middle','font-size':s.fs-2},Math.max(2,Math.floor(slot/10)));if(j<tab.groups.length-1)s.line(left+(j+1)*slot,top,left+(j+1)*slot,bottom,{'stroke-width':.5});});label(s,right,h-7,uiMessage`${tab.columns[0]} → ${tab.columns.at(-1)} · 虚线为各季均值`,{'text-anchor':'end','font-size':s.fs-2},45);
}
function eventline(s,doc){
  const {w,h,theme:t}=s,groups=unique(doc.data.map(d=>d.group)),left=56,right=w-28,top=30,bottom=h-32,dates=doc.data.map(d=>new Date(d.date)),ext=d3.extent(dates),x=d3.scaleUtc(ext[0].getTime()===ext[1].getTime()?[+ext[0]-864e5,+ext[1]+864e5]:ext,[left,right]),slot=(bottom-top)/groups.length;
  groups.forEach((g,j)=>{const y=top+(j+.5)*slot,col=t.color(j),own=doc.data.filter(d=>d.group===g).sort((a,b)=>a.date.localeCompare(b.date));label(s,left-10,y+3,g,{'text-anchor':'end',fill:t.fg,'font-size':s.fs-2},4);s.line(left,y,right,y,{'stroke-width':.8});let ends=[-Infinity,-Infinity];own.forEach((r,i)=>{const px=x(new Date(r.date)),lane=ends[0]<=px-14?0:1,maxchars=Math.max(2,Math.min(s.compact?3:6,Math.floor((right-left)/own.length/(s.fs-2)))),txt=short(r.label,maxchars),tw=[...txt].length*(s.fs-2),tx=Math.max(left+tw/2,Math.min(right-tw/2,px));ends[lane]=tx+tw/2+4;const dot=s.circle(px,y,3.3,{fill:t.bg,stroke:col,'stroke-width':1.2});s.tip(dot,`${g} · ${r.label}\n${r.date}`);s.growCircle(dot,3.3,i/own.length*.45+j*.04,.4);const ly=y+(lane?20:-13);s.line(px,y+(lane?5:-5),tx,ly+(lane?-9:3),{stroke:col,'stroke-opacity':.35,'stroke-width':.6});const text=label(s,tx,ly,r.label,{'text-anchor':'middle','font-size':s.fs-2},maxchars);s.reveal(text,.25+i*.05,.4);});});x.ticks(3).forEach(v=>num(s,x(v),h-9,d3.utcFormat('%m.%d')(v),{'text-anchor':'middle','font-size':s.fs-2}));
}
function vectorfield(s,doc){
  const {theme:t}=s,f=spatialScale7(s,doc.data,{top:36,bottom:s.h-64});spatialAxes7(s,doc,f);const max=d3.max(doc.data,d=>Math.hypot(d.u,d.v));let nearest=Infinity;for(let i=0;i<doc.data.length;i++)for(let j=i+1;j<doc.data.length;j++)nearest=Math.min(nearest,Math.hypot(doc.data[i].x-doc.data[j].x,doc.data[i].y-doc.data[j].y)*f.scale);const length=Math.min(nearest*.58,Math.min(f.right-f.left,f.bottom-f.top)*.13),factor=max?length/max:0;
  doc.data.forEach((d,i)=>{const x=f.x(d.x),y=f.y(d.y),mag=Math.hypot(d.u,d.v),dx=d.u*factor,dy=-d.v*factor,col=d.v>=0?t.accent:t.fg,g=s.group({'data-mark':'vector','data-magnitude':mag,'data-scale':factor}),path=s.path('',{stroke:col,'stroke-width':1.15,'stroke-linecap':'round'},g);s.tip(g,uiMessage`(${d.x}, ${d.y})\n水平 ${d.u} · 竖直 ${d.v} ${doc.unit}\n大小 ${fmt(mag)} ${doc.unit}`);if(!mag)s.circle(x,y,1.5,{fill:t.secondary},g);s.add(p=>{const q=phase(p,i/doc.data.length*.25,.65),ex=x+dx*q,ey=y+dy*q,head=Math.min(4,mag*factor*.3)*q,a=Math.atan2(dy,dx);path.setAttribute('d',`M${x},${y}L${ex},${ey}M${ex-head*Math.cos(a-.5)},${ey-head*Math.sin(a-.5)}L${ex},${ey}L${ex-head*Math.cos(a+.5)},${ey-head*Math.sin(a+.5)}`);});});label(s,48,s.h-22,uiMessage`最长箭头 ${fmt(max)} ${doc.unit}`,{'font-size':s.fs-3},40);
}
function voronoi(s,doc){
  const {theme:t}=s,f=spatialScale7(s,doc.data),groups=unique(doc.data.map(d=>d.group)),delaunay=d3.Delaunay.from(doc.data,d=>f.x(d.x),d=>f.y(d.y)),v=delaunay.voronoi([f.left,f.top,f.right,f.bottom]);spatialAxes7(s,doc,f);
  doc.data.forEach((d,i)=>{const col=t.color(groups.indexOf(d.group)),cell=s.path(v.renderCell(i)||'',{fill:col,'fill-opacity':.1,stroke:col,'stroke-opacity':.45,'stroke-width':.7,'data-mark':'voronoi-cell'});s.tip(cell,uiMessage`${d.label} · ${d.group}\n(${d.x}, ${d.y})\n区域为最近邻分区`);s.reveal(cell,i/doc.data.length*.22,.65);const point=s.circle(f.x(d.x),f.y(d.y),2.7,{fill:t.bg,stroke:col,'stroke-width':1.1});s.tip(point,`${d.label}\n${doc.axes.x}：${d.x}\n${doc.axes.y}：${d.y}`);s.growCircle(point,2.7,i/doc.data.length*.25,.6);});
}
function gauge(s,doc){
  const {w,h,theme:t}=s,d=doc.data[0],cx=w/2,cy=h*.71,r=Math.min(w*.36,h*.54),g=s.group({transform:`translate(${cx},${cy})`}),start=-Math.PI/2,end=Math.PI/2,ratio=(d.value-d.min)/(d.max-d.min),target=(d.target-d.min)/(d.max-d.min),arc=d3.arc().innerRadius(r*.88).outerRadius(r);
  s.path(arc({startAngle:start,endAngle:end}),{fill:texture(s,'gauge',t.secondary),stroke:t.line,'stroke-width':.65},g);const active=s.path('',{fill:t.accent},g);s.add(p=>active.setAttribute('d',arc({startAngle:start,endAngle:start+Math.PI*ratio*phase(p,.02,.8)})));
  for(let i=0;i<=4;i++){const a=start+i/4*Math.PI,x=Math.sin(a),y=-Math.cos(a);s.line(x*r*1.04,y*r*1.04,x*r*1.09,y*r*1.09,{stroke:t.secondary,'stroke-width':.8},g);num(s,x*r*1.2,y*r*1.2+4,fmt(d.min+(d.max-d.min)*i/4),{'text-anchor':'middle','font-size':s.fs-2},g);}
  const a=start+target*Math.PI;s.line(Math.sin(a)*r*.84,-Math.cos(a)*r*.84,Math.sin(a)*r*1.04,-Math.cos(a)*r*1.04,{stroke:t.fg,'stroke-width':1.4},g);
  const needle=s.path('',{fill:t.fg,'data-mark':'gauge-needle','data-ratio':ratio},g);s.tip(needle,uiMessage`${d.label}\n${d.value} ${doc.unit}\n目标 ${d.target} · 量程 ${d.min}–${d.max}`);s.add(p=>{const a=start+ratio*Math.PI*phase(p,.04,.8),x=Math.sin(a),y=-Math.cos(a);needle.setAttribute('d',`M${-y*2.8},${x*2.8}L${x*r*.76},${y*r*.76}L${y*2.8},${-x*2.8}Z`);});s.circle(0,0,4,{fill:t.bg,stroke:t.fg,'stroke-width':1.3},g);num(s,cx,cy+26,`${fmt(d.value)} ${short(doc.unit,5)}`,{'text-anchor':'middle','font-size':s.compact?24:34,fill:t.fg});label(s,cx,h-4,uiMessage`目标 ${fmt(d.target)} ${doc.unit}`,{'text-anchor':'middle','font-size':s.fs-2},30);
}
export const volume7Renderers={pie,polarline,stackedcolumn,streamgraph,horizon,cycleplot,eventline,vectorfield,voronoi,gauge,...relation7Renderers,...stat7Renderers};
