// All values below are deterministic synthetic examples, never real business observations.
const str=(key,label)=>[key,'string',label],num=(key,label)=>[key,'number',label];
const hierarchy=[str('id','节点唯一标识'),str('parent','父节点标识；根节点填 ROOT'),str('label','节点显示名称'),num('value','叶节点数量；内部节点填 0')];
const specs=[
 ['geoflow','地理流向图','Geographic flows','flow',[str('source','起点名称'),str('target','终点名称'),num('sourceLongitude','起点经度 / °'),num('sourceLatitude','起点纬度 / °'),num('targetLongitude','终点经度 / °'),num('targetLatitude','终点纬度 / °'),num('value','正流量')],'大圆弧表示两地之间的有向联系，线宽按同一比例映射流量。','跨地区订单、物流和迁移联系','把大圆弧当实际运输轨迹；把两地总流量当净流量','2–40 条有向边；同名地点坐标一致；端点不能重合或对跖'],
 ['circlehierarchy','多层嵌套圆','Nested circle packing','composition',hierarchy,'圆的包含关系表达多层归属，叶圆面积表示数量；父圆是布局包络。','预算归属、目录资产、产品组合','将父圆的包络面积当成准确总量；在父节点重复填总数','3–80 个节点；唯一根；最多 7 层；叶值 > 0，内部值为 0'],
 ['radialtree','多层径向树','Radial hierarchy tree','flow',hierarchy,'以径向树呈现任意多级的父子关系，叶点面积对应叶节点数量。','分类体系、组织树、产品架构','把角度和枝长当成数据距离；把共享子节点重复计数','3–80 个节点；唯一根；最多 7 层；一个节点只能有一个父节点'],
 ['tornado','敏感性龙卷风图','Sensitivity tornado','comparison',[str('parameter','参数名称'),num('low','低情景下的输出值'),num('high','高情景下的输出值')],'参数的低、高情景结果相对同一基准显示，按最大绝对影响排序。','模型敏感性、预算情景、成本分析','把 low/high 当置信区间；强制认为低情景输出更低','3–16 个参数；baseline 为同量纲有限基准值'],
 ['cohortcurve','同期群留存曲线','Cohort retention curves','trend',[str('cohort','同期群名称'),num('period','距起始时点的整数期数'),num('retained','当期仍活跃人数'),num('size','同期群起始人数')],'每个同期群以自己的起始人数为分母，比较相同群龄的活跃比例。','产品留存、订阅活跃、用户回访','把未到达的群龄补成零；混用起始人数；把回访留存当生存率','2–8 个同期群，最多 36 期；每群从第 0 期连续输入；允许回访反弹'],
 ['venn','三集合交集图','Three-set Venn diagram','composition',[str('members','排他成员集合，用 | 分隔'),num('count','排他交集非负整数计数')],'七个互斥区域显示三个集合的交集计数；区域面积不编码数量。','三组受众、类别交集、集合关系说明','将包含式交集填入排他区域；从圆面积比较集合规模','sets 必须含 3 个不含 | 的唯一集合名；全部 7 个非空组合都要填写'],
 ['sankeycycle','循环桑基图','Cyclic Sankey','flow',[str('source','起点节点'),str('target','终点节点'),num('value','正流量')],'流带宽度统一编码流量；循环和自环由回流通道呈现，节点单独显示流入与流出。','循环经济、材料返工、客户状态转移','把流入与流出不平衡隐藏为守恒；把循环流量求和当独立人数','2–16 个节点、2–40 条有向边；支持自环，禁止同向重复边'],
 ['adjacency','网络邻接矩阵','Directed adjacency matrix','flow',[str('source','起点节点 / 行'),str('target','终点节点 / 列'),num('value','非负有向联系权重')],'矩阵行是起点、列是终点，色深与数字对应有向联系权重。','团队交互、服务调用、部门协作','把有向矩阵当成对称关系；把缺测自动补零','nodes 明确 2–12 个唯一节点；完整方阵，零联系必须显式填 0']
];
export const volume13Catalog=specs.map(([id,name,en,category,fields,description,use,avoid,limit],i)=>({id,no:String(137+i),name,en,type:name,category,fields,description,use,avoid,limit,motion:'结构展开 / 原值标记显现 / 动画可往返定位',keywords:`${name} ${en} ${use}`,edition:13,dataMode:'observations',duration:8}));
const hierarchyData=[['portfolio','ROOT','产品组合',0],['core','portfolio','核心产品',0],['growth','portfolio','增长业务',0],['services','portfolio','专业服务',0],['workspace','core','协作工具',0],['analysis','core','分析工具',0],['editor','workspace','在线编辑',35],['review','workspace','团队审阅',22],['charts','analysis','数据图表',31],['reports','analysis','自动报告',19],['education','growth','教育版',24],['mobile','growth','移动端',16],['consulting','services','咨询',18],['training','services','培训',12]].map(([id,parent,label,value])=>({id,parent,label,value}));
const locations={Shanghai:[121.47,31.23],Singapore:[103.82,1.35],London:[-.13,51.51],NewYork:[-74.01,40.71],Tokyo:[139.69,35.68],Sydney:[151.21,-33.87],SanFrancisco:[-122.42,37.77]};
const flowRows=[['Shanghai','Singapore',84],['Shanghai','London',56],['Singapore','Sydney',42],['London','NewYork',68],['Tokyo','SanFrancisco',62],['NewYork','Shanghai',37],['Shanghai','Tokyo',75]].map(([source,target,value])=>({source,target,sourceLongitude:locations[source][0],sourceLatitude:locations[source][1],targetLongitude:locations[target][0],targetLatitude:locations[target][1],value}));
const nodes=['研究','产品','设计','工程','市场','支持'];
export const volume13Contents={
 geoflow:{title:'跨区域业务流向',subtitle:'确定性合成数据 · 大圆弧为关系示意，并非实测航线',unit:'千单',data:flowRows},
 circlehierarchy:{title:'产品组合的多层结构',subtitle:'确定性合成数据 · 仅叶圆面积表示数量',unit:'项目',data:hierarchyData},
 radialtree:{title:'产品能力分层结构',subtitle:'确定性合成数据 · 连线表示父子归属',unit:'项目',data:hierarchyData},
 tornado:{title:'利润模型参数敏感性',subtitle:'确定性合成情景 · 每次仅改变一个参数',unit:'万元',baseline:100,data:[['需求量',68,137],['单位售价',78,129],['材料成本',121,82],['转化率',87,118],['人力成本',114,91],['退货率',108,94]].map(([parameter,low,high])=>({parameter,low,high}))},
 cohortcurve:{title:'各月同期群留存',subtitle:'确定性合成数据 · 相同群龄比较，未成熟期间不补零',unit:'%',periodUnit:'周',data:['一月','二月','三月','四月'].flatMap((cohort,j)=>Array.from({length:11-j*2},(_,period)=>{const size=480+j*80;return{cohort,period,size,retained:period===0?size:Math.round(size*(.33+j*.055+.52*Math.exp(-period/2.3)+Math.sin(period*1.3+j)*.017))};}))},
 venn:{title:'三类用户兴趣交集',subtitle:'确定性合成计数 · 区域面积不表示数量',unit:'人',sets:['设计','分析','开发'],data:[['设计',42],['分析',38],['开发',34],['设计|分析',25],['设计|开发',18],['分析|开发',22],['设计|分析|开发',16]].map(([members,count])=>({members,count}))},
 sankeycycle:{title:'材料回收与再利用',subtitle:'确定性合成流量 · 回流与外部净流入分别保留',unit:'吨',data:[['原料','制造',100],['制造','使用',86],['制造','回收',14],['使用','回收',55],['使用','处置',31],['回收','制造',48],['回收','处置',21]].map(([source,target,value])=>({source,target,value}))},
 adjacency:{title:'团队之间的协作联系',subtitle:'确定性合成数据 · 行为起点，列为终点；零值显式展示',unit:'次',nodes,data:nodes.flatMap((source,i)=>nodes.map((target,j)=>({source,target,value:i===j?0:12+(i*7+j*13)%41+(i===3||j===3?18:0)})))}
};
export const volume13English={
 geoflow:{description:'Great-circle arcs show directed connections, with a common linear width scale for magnitude.',use:'Regional orders, logistics and migration connections',avoid:'Interpreting arcs as recorded routes or gross flows as net movements',limit:'2–40 directed edges; each location keeps consistent coordinates; endpoints must not coincide or be antipodal.',rowMeaning:'One row is a directed connection, with decimal-degree coordinates for both endpoints and positive flow.'},
 circlehierarchy:{description:'Nested containment shows hierarchy; leaf-circle area encodes quantity. Parent circles enclose their children with layout padding.',use:'Budget ownership, asset folders and product portfolios',avoid:'Reading parent enclosing area as an exact subtotal or entering subtotals twice',limit:'3–80 unique nodes, one root, up to 7 levels. Leaves have positive values; internal nodes have zero input values.',rowMeaning:'One row is one node with a unique id, parent id and display label. Root parent is ROOT; only leaves carry quantities.'},
 radialtree:{description:'A radial tree shows multilevel parent-child relationships; leaf-marker area represents leaf quantity.',use:'Classification, organizational structure and product architecture',avoid:'Reading angles or branch lengths as measured distance or repeating shared subtrees',limit:'3–80 nodes, one root, up to 7 levels; each node has exactly one parent.',rowMeaning:'One row is a unique node. Use ROOT as the single root parent, zero for internal values and positive leaf quantities.'},
 tornado:{description:'Low- and high-input scenario outputs extend from one baseline. Parameters sort by maximum absolute departure.',use:'Model sensitivity, budget scenarios and cost analysis',avoid:'Treating scenario outputs as confidence limits or assuming a low input gives a lower output',limit:'3–16 parameters; baseline is a required finite output value in the same unit.',rowMeaning:'One row is one parameter and the two model outputs when that parameter alone takes its declared low/high scenario.'},
 cohortcurve:{description:'Each cohort divides active counts by its own initial size; curves compare cohorts at the same age.',use:'Product retention, active subscriptions and return visits',avoid:'Zero-filling future periods, changing denominators or treating returning-user retention as survival',limit:'2–8 cohorts, up to 36 periods; each cohort starts at age zero with contiguous integer ages. Returning users may cause increases.',rowMeaning:'One row is a cohort at one age. size is its fixed initial population; retained is the active count at that age.'},
 venn:{description:'Seven mutually exclusive regions label the exact three-set intersections. Region area does not encode count.',use:'Audience overlaps and three-category set relationships',avoid:'Entering inclusive intersections in exclusive regions or comparing areas as quantities',limit:'sets contains three unique names without |. Supply all seven nonempty exclusive combinations, including zeros.',rowMeaning:'One row is one exact membership combination, separated by |, and its nonnegative integer count.'},
 sankeycycle:{description:'A common width scale represents flow. Return channels preserve cycles and self-loops; nodes retain separate incoming and outgoing totals.',use:'Circular material flows, rework and customer-state transitions',avoid:'Hiding imbalance as conservation or counting recirculating flow as unique people',limit:'2–16 nodes, 2–40 directed edges. Self-loops are supported; duplicate directed pairs are rejected.',rowMeaning:'One row is a directed flow with a positive quantity. Opposite-direction links are separate observations.'},
 adjacency:{description:'Rows are sources and columns are targets; color intensity and labels encode directed connection weight.',use:'Team interaction, service calls and department collaboration',avoid:'Treating a directed matrix as symmetric or silently converting missing values to zero',limit:'nodes specifies 2–12 unique nodes. Supply every directed pair, including explicit zeros on the diagonal.',rowMeaning:'One row is one source-target matrix cell with a nonnegative weight. Every node pair is explicitly provided.'}
};
const englishLabels={geoflow:['Source location','Target location','Source longitude / °','Source latitude / °','Target longitude / °','Target latitude / °','Positive flow'],circlehierarchy:['Stable unique ASCII node id','Parent id; use ROOT for the root','Display label','Leaf quantity; zero for internal nodes'],radialtree:['Stable unique ASCII node id','Parent id; use ROOT for the root','Display label','Leaf quantity; zero for internal nodes'],tornado:['Parameter','Output under low-input scenario','Output under high-input scenario'],cohortcurve:['Cohort','Integer age since cohort start','Active count at this age','Fixed initial cohort size'],venn:['Exact set membership, separated by |','Nonnegative exclusive-intersection count'],sankeycycle:['Source node','Target node','Positive directed flow'],adjacency:['Source node / row','Target node / column','Nonnegative directed connection weight']};
for(const t of volume13Catalog)volume13English[t.id].fields=t.fields.map(([key,type],i)=>[key,type,englishLabels[t.id][i]]);
