import {uiText,uiMarkup,uiMessage} from './locale.js';
import {equalUnitDomains} from './axis-policy.js';
import * as d3 from 'd3';
import {unique8,upsetLayout,manhattanLayout} from './volume8-data.js';
import {axes8 as axes,extent8 as extent,point8 as point,color8 as color,legend8 as legend,label8 as label,annotation8 as annotation,fmt8 as fmt,phase8 as phase,ref8 as ref} from './volume8-utils.js';

function volcano(s,doc){const cutoff=-Math.log10(doc.qThreshold),maxX=Math.max(doc.fcThreshold*1.4,d3.max(doc.data,d=>Math.abs(d.log2FC))*1.08),maxY=Math.max(cutoff*1.2,d3.max(doc.data,d=>-Math.log10(d.padj)))*1.09,f=axes(s,{xd:[-maxX,maxX],yd:[0,maxY],yLabel:uiText('−log₁₀ 校正 p 值'),xLabel:uiText('log₂ 倍数变化')});annotation(s,`padj ≤ ${fmt(doc.qThreshold)} · |log₂FC| ≥ ${fmt(doc.fcThreshold)}`);ref(s,f,cutoff);[-doc.fcThreshold,doc.fcThreshold].forEach(v=>ref(s,f,v,{vertical:true}));doc.data.forEach((d,i)=>{const hit=d.padj<=doc.qThreshold&&Math.abs(d.log2FC)>=doc.fcThreshold,col=hit?(d.log2FC>0?s.theme.accent:s.theme.fg):s.theme.secondary,p=point(s,f.x(d.log2FC),f.y(-Math.log10(d.padj)),{color:col,shape:hit?d.log2FC>0?2:1:0,r:hit?3:1.65,filled:hit,delay:i/doc.data.length*.28,mark:'volcano-point','data-selected':String(hit),'data-padj':d.padj});s.edit(p,d);s.tip(p,`${d.label}\nlog₂FC ${fmt(d.log2FC)} · padj ${fmt(d.padj)}\n${hit?uiText('通过预设阈值'):uiText('未通过预设阈值')}`);});}

function ma(s,doc){const means=d3.extent(doc.data,d=>d.mean),f=axes(s,{xd:[means[0]*.8,means[1]*1.25],yd:extent(doc.data.map(d=>d.log2FC),{zero:true}),logX:true,yLabel:uiText('log₂ 倍数变化'),xLabel:uiText('标准化平均表达量 · 对数轴')});annotation(s,uiMessage`实心方块：padj ≤ ${fmt(doc.qThreshold)}`);ref(s,f,0,{color:s.theme.fg});doc.data.forEach((d,i)=>{const hit=d.padj<=doc.qThreshold,p=point(s,f.x(d.mean),f.y(d.log2FC),{color:hit?s.theme.accent:s.theme.secondary,shape:hit?1:0,filled:hit,r:hit?2.8:1.7,delay:i/doc.data.length*.3});s.edit(p,d);s.tip(p,uiMessage`${d.label}\n平均表达 ${fmt(d.mean)}\nlog₂FC ${fmt(d.log2FC)} · padj ${fmt(d.padj)}`);});}

function pca(s,doc){const groups=unique8(doc.data.map(d=>d.group)),domains=equalUnitDomains(doc.data,{width:s.w-72,height:s.h-100,padding:.09,xKey:'pc1',yKey:'pc2'}),{x:xd,y:yd}=domains;const f=axes(s,{xd,yd,yLabel:uiMessage`PC2 · 解释方差 ${fmt(doc.pc2Variance)}%`,xLabel:uiMessage`PC1 · 解释方差 ${fmt(doc.pc1Variance)}%`});legend(s,groups.map(label=>({label})));if(xd[0]<=0&&xd[1]>=0)ref(s,f,0,{vertical:true,color:s.theme.line});if(yd[0]<=0&&yd[1]>=0)ref(s,f,0,{color:s.theme.line});doc.data.forEach((d,i)=>{const j=groups.indexOf(d.group),p=point(s,f.x(d.pc1),f.y(d.pc2),{color:color(s,j),shape:j,filled:j%2===0,r:3.4,delay:j*.06+i/doc.data.length*.2,mark:'pca-score','data-pc1':d.pc1,'data-pc2':d.pc2});s.edit(p,d);s.tip(p,`${d.label} · ${d.group}\nPC1 ${fmt(d.pc1)} · PC2 ${fmt(d.pc2)}`);});}

function scree(s,doc){const total=d3.sum(doc.data,d=>d.eigenvalue),rows=doc.data.map(d=>({...d,share:d.eigenvalue/total})),f=axes(s,{xd:[-.6,rows.length-.4],yd:[0,d3.max(rows,d=>d.share)*1.13],xTicks:[],percentY:true,yLabel:uiText('解释方差比例'),xLabel:uiText('全部主成分 · 输入特征值归一化')});annotation(s,uiMessage`${rows.length} 个主成分 · 合计 100%`);const bw=(f.right-f.left)/(rows.length+.2)*.55;rows.forEach((d,i)=>{const x=f.x(i),y=f.y(d.share),bar=s.rect(x-bw/2,y,bw,f.bottom-y,{fill:i===0?s.theme.accent:s.theme.fg,'fill-opacity':i===0?.78:.13,'data-mark':'scree-bar','data-share':d.share});s.add(p=>{const q=phase(p,i*.025,.7);bar.setAttribute('y',f.bottom-(f.bottom-y)*q);bar.setAttribute('height',(f.bottom-y)*q);});s.edit(bar,d,'eigenvalue');s.tip(bar,uiMessage`${d.component}\n特征值 ${fmt(d.eigenvalue)} · 解释方差 ${fmt(d.share*100)}%`);if(rows.length<=10||i%2===0||i===rows.length-1)label(s,x,f.bottom+18,d.component,{'text-anchor':'middle','font-size':s.fs-2},s.compact?4:8);});const line=s.path(d3.line().x((_,i)=>f.x(i)).y(d=>f.y(d.share))(rows),{stroke:s.theme.fg,'stroke-width':1.2});s.draw(line,.2,.65);rows.forEach((d,i)=>point(s,f.x(i),f.y(d.share),{color:i===0?s.theme.accent:s.theme.fg,r:2.6,filled:false,delay:.35+i*.02}));}

function enrichment(s,doc){const rows=[...doc.data].sort((a,b)=>b.count/b.total-a.count/a.total),left=s.compact?78:128,right=s.w-26,top=58,bottom=s.h-61,slot=(bottom-top)/rows.length,max=d3.max(rows,d=>d.count),x=d3.scaleLinear([0,d3.max(rows,d=>d.count/d.total)*1.22],[left,right]),maxQ=d3.max(rows,d=>-Math.log10(d.padj))||1,minQ=d3.min(rows,d=>-Math.log10(d.padj)),qColor=d3.scaleLinear([Math.min(0,minQ),maxQ],[s.theme.soft,s.theme.accent]).interpolate(d3.interpolateLab),r=d3.scaleSqrt([0,max],[0,Math.min(10,slot*.39)]);label(s,left,13,uiText('GeneRatio · 命中数 / 输入基因数'),{'font-size':s.fs-2},s.compact?24:50);[Math.max(1,Math.round(max/3)),max].forEach((v,i)=>{s.circle(left+i*76+8,32,r(v),{fill:s.theme.secondary,'fill-opacity':.35,stroke:s.theme.secondary,'stroke-width':.7});s.text(left+i*76+23,35,String(v),{'font-size':s.fs-2});});
  x.ticks(s.w<390?3:4).forEach(v=>{s.line(x(v),top-5,x(v),bottom,{'stroke-width':.5,'stroke-dasharray':'1 5'});s.text(x(v),bottom+17,`${fmt(v*100)}%`,{'text-anchor':'middle','font-size':s.fs-2});});rows.forEach((d,i)=>{const cy=top+(i+.5)*slot,c=qColor(-Math.log10(d.padj));label(s,left-10,cy+3,d.label,{'text-anchor':'end','font-size':Math.min(s.fs-1,slot*.65),fill:s.theme.fg},s.compact?6:13);s.line(left,cy,right,cy,{'stroke-width':.5});const dot=s.circle(x(d.count/d.total),cy,r(d.count),{fill:c,stroke:s.theme.accent,'stroke-width':.6,'data-mark':'enrichment-bubble','data-count':d.count});s.growCircle(dot,r(d.count),i*.04,.7);s.edit(dot,d);s.tip(dot,uiMessage`${d.label}\nGeneRatio ${d.count}/${d.total} = ${fmt(d.count/d.total*100)}%\n命中 ${d.count} · padj ${fmt(d.padj)}`);});const y=s.h-14,gradient=s.el('linearGradient',{id:`${s.id}-q`},s.defs);[0,1].forEach(v=>s.el('stop',{offset:v,'stop-color':qColor(v*maxQ)},gradient));const barWidth=Math.min(85,(s.w-left-15)*.38);s.rect(left,y-5,barWidth,5,{fill:`url(#${s.id}-q)`});s.text(left,y+9,'0',{'font-size':s.fs-3});s.text(left+barWidth,y+9,fmt(maxQ),{'text-anchor':'end','font-size':s.fs-3});s.text(left+barWidth+12,y+1,'−log₁₀ padj',{'font-size':s.fs-3});}

function upset(s,doc){const layout=upsetLayout(doc),rows=layout.intersections,left=s.compact?66:100,right=s.w-16,top=38,barBottom=Math.max(88,s.h*.51),matrixTop=barBottom+27,matrixBottom=s.h-20,slot=(matrixBottom-matrixTop)/doc.sets.length,x=d3.scaleBand(rows.map((_,i)=>i),[left,right]).padding(.34),y=d3.scaleLinear([0,d3.max(rows,d=>d.count)*1.2],[barBottom,top]);label(s,left,12,uiText('排他交集大小'),{'font-size':s.fs-2},30);s.text(right,12,uiMessage`共 ${fmt(layout.total)}`,{'text-anchor':'end','font-size':s.fs-2});y.ticks(3).forEach(v=>{s.line(left,y(v),right,y(v),{'stroke-width':.6,'stroke-dasharray':'1 5'});s.text(left-8,y(v)+3,fmt(v),{'text-anchor':'end','font-size':s.fs-2});});layout.sets.forEach((d,j)=>{const cy=matrixTop+(j+.5)*slot;if(j%2===0)s.rect(left,cy-slot/2,right-left,slot,{fill:s.theme.soft,'fill-opacity':.65});label(s,left-8,cy+3,d.name,{'text-anchor':'end','font-size':Math.min(s.fs-2,slot*.65)},s.compact?5:10);});rows.forEach((d,i)=>{const cx=x(i)+x.bandwidth()/2,col=s.theme.objectColor(d,d.members.length===doc.sets.length?s.theme.accent:s.theme.fg),bar=s.rect(x(i),y(d.count),x.bandwidth(),barBottom-y(d.count),{fill:col,'data-mark':'upset-bar','data-count':d.count});s.add(p=>{const q=phase(p,i*.023,.64);bar.setAttribute('y',barBottom-(barBottom-y(d.count))*q);bar.setAttribute('height',(barBottom-y(d.count))*q);});s.edit(bar,d,'count');s.tip(bar,uiMessage`${d.members.join(' ∩ ')}\n排他交集 ${d.count} ${doc.unit}\n不属于其余声明集合`);if(x.bandwidth()>12){const txt=s.text(cx,y(d.count)-6,String(d.count),{'text-anchor':'middle','font-size':s.fs-3});s.reveal(txt,.65,.3);}const indices=d.members.map(name=>doc.sets.indexOf(name)),ys=indices.map(j=>matrixTop+(j+.5)*slot);const line=s.line(cx,d3.min(ys),cx,d3.max(ys),{stroke:col,'stroke-width':1.25});s.reveal(line,.3+i*.02,.5);doc.sets.forEach((name,j)=>{const active=d.members.includes(name),circle=s.circle(cx,matrixTop+(j+.5)*slot,Math.min(3.4,x.bandwidth()/2,slot*.23),{fill:active?col:s.theme.line,'data-mark':'upset-member','data-active':String(active)});s.reveal(circle,.24+i*.02,.5);s.edit(circle,d,'members');s.tip(circle,`${d.members.join(' ∩ ')} · ${d.count}\n${name}：${active?uiText('包含'):uiText('排除')}`);});});label(s,right,s.h-3,uiText('● 所属集合 · 每列一个排他组合'),{'text-anchor':'end','font-size':s.fs-3},50);}

function manhattan(s,doc){const layout=manhattanLayout(doc),threshold=-Math.log10(doc.threshold),f=axes(s,{xd:[0,layout.total],yd:[0,Math.max(threshold*1.1,d3.max(layout.points,d=>d.y)*1.12)],xTicks:[],yLabel:uiText('−log₁₀ p 值'),xLabel:uiText('染色体物理位置 / bp')});annotation(s,uiMessage`预设阈值 p=${fmt(doc.threshold)} · ${doc.data.length} 个位点`);layout.chromosomes.forEach((c,i)=>{if(i%2===0)s.rect(f.x(c.start),f.top,f.x(c.end)-f.x(c.start),f.bottom-f.top,{fill:s.theme.soft,'fill-opacity':.4});label(s,f.x((c.start+c.end)/2),f.bottom+18,c.name,{'text-anchor':'middle','font-size':s.fs-2},5);});ref(s,f,threshold,{color:s.theme.accent});layout.points.forEach((d,i)=>{const hit=d.pvalue<=doc.threshold,j=doc.chromosomes.findIndex(c=>c.name===d.chromosome),dot=point(s,f.x(d.x),f.y(d.y),{color:hit?s.theme.accent:j%2===0?s.theme.fg:s.theme.secondary,shape:hit?3:0,r:hit?3:1.9,delay:d.x/layout.total*.35,mark:'manhattan-point','data-position':d.position});s.edit(dot,d);s.tip(dot,uiMessage`${d.label}\n染色体 ${d.chromosome} · ${d.position.toLocaleString('en-US')} bp\np=${fmt(d.pvalue)}`);});}
export const omics8Renderers={volcano,ma,pca,scree,enrichment,upset,manhattan};
