import {labelInk} from './chart-readability.js';
import * as d3 from 'd3';
import {withEntityIds} from './entity-identity.js';
import {multivariateVariables,multivariateSelectedPair,multivariateBounds} from './multivariate-rules.js';
import {padded} from './scientific-geometry.js';
import world10 from './datasets/world-110m.json' with {type:'json'};
import {t10,autocorrelation10,pacf10,imr10,cluster10,matrix10} from './volume10-data.js';
import {phase7 as phase,number7 as fmt,num7 as num,label7 as label,texture7 as texture} from './volume7-utils.js';
const color=(s,v,domain)=>s.theme.valueColor?.(v,domain)??d3.interpolateRgb(s.theme.bg,s.theme.accent)(.13+.82*(domain[0]===domain[1]?.5:(v-domain[0])/(domain[1]-domain[0])));
function scaleLegend(s,domain,{x=18,y=s.h-11,width=90}={}){const n=32;for(let i=0;i<n;i++)s.rect(x+i*width/n,y-5,width/n+.2,5,{fill:color(s,domain[0]+i/(n-1)*(domain[1]-domain[0]),domain)});num(s,x,y+12,fmt(domain[0]),{'font-size':s.fs-3});num(s,x+width,y+12,fmt(domain[1]),{'font-size':s.fs-3,'text-anchor':'end'});}
function baseMap(s){const extent=[[12,12],[s.w-12,Math.min(s.h-44,s.w*.58+18)]],projection=d3.geoNaturalEarth1().fitExtent(extent,{type:'Sphere'}),path=d3.geoPath(projection),clip=s.el('clipPath',{id:`${s.id}-map-frame`},s.defs);s.rect(extent[0][0],extent[0][1],extent[1][0]-extent[0][0],extent[1][1]-extent[0][1],{},clip);const g=s.group({'clip-path':`url(#${s.id}-map-frame)`});
 s.path(path(d3.geoGraticule10()),{stroke:s.theme.line,'stroke-width':.3,'stroke-opacity':.6},g);
 return{projection,path,g};}
function mapDetails(s,doc){if(s.h<s.w*1.1)return;const top=s.w*.58+54,bottom=s.h-66,rows=doc.data.filter(d=>d.value!==null).sort((a,b)=>b.value-a.value).slice(0,6),gap=Math.min(40,(bottom-top)/Math.max(1,rows.length));label(s,18,top-16,t10('数值最高的 6 个地区 / 地点','Top 6 measured regions / sites'),{'font-size':s.fs-2},45);rows.forEach((d,i)=>{const y=top+i*gap;label(s,18,y,d.label,{'font-size':s.fs-1,fill:s.theme.fg},25);num(s,s.w-18,y,`${fmt(d.value)} ${doc.unit}`,{'text-anchor':'end','font-size':s.fs-1});s.line(18,y+9,s.w-18,y+9,{'stroke-width':.5});});}
function attribution(s){label(s,s.w-12,s.h-4,'Natural Earth · 1:110m',{'font-size':s.fs-3,'text-anchor':'end'},32);}
function choropleth(s,doc){
 const {path,g}=baseMap(s),lookup=new Map(doc.data.map(d=>[d.code,d])),domain=d3.extent(doc.data.filter(d=>d.value!==null),d=>d.value);
 world10.features.forEach((feature,i)=>{const d=lookup.get(feature.properties.code),missing=!d||d.value===null,shape=s.path(path(feature),{fill:missing?s.theme.line:color(s,d.value,domain),stroke:s.theme.bg,'stroke-width':.55,'data-mark':'geo-region','data-code':feature.properties.code,'data-missing':missing,'data-value':d?.value??''},g);s.reveal(shape,missing?0:.12+i/world10.features.length*.25,.45);s.tip(shape,`${d?.label||feature.properties.name}\n${missing?t10('未提供观测','No observation'):`${fmt(d.value)} ${doc.unit}`}\n${feature.properties.code}`);if(d)s.edit(shape,d,'value');});
 scaleLegend(s,domain,{y:s.h-18});label(s,128,s.h-13,doc.unit,{'font-size':s.fs-2},12);s.rect(18,s.h-44,6,6,{fill:s.theme.line});label(s,30,s.h-38,t10('缺测','Unmeasured'),{'font-size':s.fs-3},18);mapDetails(s,doc);attribution(s);
}
function geomap(s,doc){
 const {projection,path,g}=baseMap(s);world10.features.forEach(f=>s.path(path(f),{fill:s.theme.fg,'fill-opacity':.04,stroke:s.theme.line,'stroke-width':.5},g));
 const max=d3.max(doc.data,d=>d.value)||1,rMax=Math.min(22,s.w*.035,s.h*.07),sorted=[...doc.data].sort((a,b)=>b.value-a.value);
 sorted.forEach(d=>{const [cx,cy]=projection([d.longitude,d.latitude]),r=d.value===0?2:rMax*Math.sqrt(d.value/max),mark=s.circle(cx,cy,r,{fill:d.value===0?s.theme.bg:s.theme.objectColor(d,s.theme.accent),'fill-opacity':d.value===0?1:.3,stroke:s.theme.objectColor(d,s.theme.accent),'stroke-width':.8,'data-mark':'geo-bubble','data-value':d.value,'data-longitude':d.longitude,'data-latitude':d.latitude},g);s.growCircle(mark,r,doc.data.indexOf(d)/doc.data.length*.3,.55);s.edit(mark,d,'value');s.tip(mark,`${d.label}\n${fmt(d.value)} ${doc.unit}\n${d.longitude}°, ${d.latitude}°`);});
 label(s,18,s.h-15,t10('面积 = 数量','Area = magnitude'),{'font-size':s.fs-3},25);num(s,18,s.h-1,`${fmt(max)} ${doc.unit}`,{'font-size':s.fs-2});mapDetails(s,doc);attribution(s);
}
function splom(s,input){
 const doc=withEntityIds({...input,data:input.data.map((r,i)=>({...r,_nativeRow:i}))},{legacyNamespace:'unmigrated-multivariate'}),variables=multivariateVariables(doc),pair=multivariateSelectedPair(doc),m=matrix10(doc.data,'_sampleId','_variableId'),samples=doc.sampleEntities.items.filter(sample=>m.rowNames.includes(sample.id)),n=variables.length,left=s.compact?38:62,top=28,bottom=s.h-28,right=s.w-14,gap=6,cw=(right-left)/n,ch=(bottom-top)/n,groups=[...new Set(doc.data.map(d=>d.group))],bounds=multivariateBounds(doc),domains=variables.map(v=>padded(bounds[v.id]));
 variables.forEach((v,j)=>{label(s,left+(j+.5)*cw,bottom+15,v.label,{'text-anchor':'middle','font-size':s.fs-3},Math.max(3,cw/(s.fs-3)));label(s,left-6,top+(j+.5)*ch,v.label,{'text-anchor':'end','font-size':s.fs-3},s.compact?4:8);});
 for(let r=0;r<n;r++)for(let c=0;c<n;c++){
  const vx=variables[c],vy=variables[r],selected=pair[0]===vx.id&&pair[1]===vy.id,x0=left+c*cw+gap,y0=top+r*ch+gap,x=d3.scaleLinear(domains[c],[x0+5,x0+cw-gap-6]),y=d3.scaleLinear(domains[r],[y0+ch-gap-6,y0+5]),panel=s.group({'data-variable-x':vx.id,'data-variable-y':vy.id,'data-selected-facet':selected});
  s.rect(x0,y0,cw-gap,ch-gap,{...(s.options.multivariateNavigation&&r!==c?{'data-multivariate-facet':'','data-variable-x':vx.id,'data-variable-y':vy.id,'aria-label':`X: ${vx.label} · Y: ${vy.label}`,role:'button',tabindex:selected?0:-1}:{}),fill:selected?s.theme.accent:s.theme.fg,'fill-opacity':selected?.035:.015,stroke:selected?s.theme.accent:s.theme.line,'stroke-width':selected?1:.55},panel);
  if(r===c){label(s,x0+(cw-gap)/2,y0+ch*.43,vy.label,{'text-anchor':'middle','font-size':s.fs-2,fill:s.theme.fg},Math.max(3,(cw-gap)/(s.fs-2)),panel);num(s,x0+(cw-gap)/2,y0+ch*.66,`${fmt(domains[r][0])}–${fmt(domains[r][1])}`,{'text-anchor':'middle','font-size':s.fs-3},panel);continue;}
  samples.forEach((sample,i)=>{const xr=m.lookup.get(JSON.stringify([sample.id,vx.id])),yr=m.lookup.get(JSON.stringify([sample.id,vy.id])),col=s.theme.groupColor?.(yr.group,s.theme.color(groups.indexOf(yr.group)))||s.theme.color(groups.indexOf(yr.group)),p=s.circle(x(xr.value),y(yr.value),s.compact?1.45:2.1,{fill:col,'fill-opacity':.58,'data-mark':'splom-point','data-sample-id':sample.id,'data-sample':sample.name,'data-record-label':`${sample.name} · ${yr.group}`,'data-morph-key':JSON.stringify(['multivariate-sample',sample.id,vx.id,vy.id]),'data-variable-x':vx.id,'data-variable-y':vy.id,'data-record-ids':JSON.stringify([xr._id,yr._id]),'data-x':xr.value,'data-y':yr.value},panel);s.growCircle(p,s.compact?1.45:2.1,(r*n+c)/(n*n)*.2+i/samples.length*.13,.45);s.tip(p,`${sample.name} · ${yr.group}\n${vx.label}: ${fmt(xr.value)}\n${vy.label}: ${fmt(yr.value)}`);});
 }
 s.legend(groups.map((g,i)=>({label:g,color:s.theme.groupColor?.(g,s.theme.color(i))||s.theme.color(i)})),left,13);
}

function clusterheatmap(s,doc){
 const m=matrix10(doc.data),rowTree=cluster10(m.values),colTree=cluster10(m.columnNames.map((_,j)=>m.values.map(v=>v[j]))),rowOrder=rowTree.indices,colOrder=colTree.indices,left=s.compact?66:102,top=s.compact?43:57,right=s.w-18,bottom=s.h-42,cw=(right-left)/colOrder.length,ch=(bottom-top)/rowOrder.length,domain=d3.extent(doc.data,d=>d.value);
 rowOrder.forEach((ri,i)=>{label(s,left-5,top+(i+.5)*ch+3,m.rowNames[ri],{'text-anchor':'end','font-size':s.fs-3},s.compact?3:6);colOrder.forEach((cj,j)=>{const d=m.lookup.get(JSON.stringify([m.rowNames[ri],m.columnNames[cj]])),r=s.rect(left+j*cw,top+i*ch,cw-1,ch-1,{fill:color(s,d.value,domain),'data-mark':'cluster-cell','data-value':d.value});s.reveal(r,(i+j)/(rowOrder.length+colOrder.length)*.28,.5);s.edit(r,d,'value');s.tip(r,`${d.row} · ${d.column}\n${fmt(d.value)} ${doc.unit}`);if(cw>43&&ch>24&&!s.compact){const c=color(s,d.value,domain);num(s,left+(j+.5)*cw,top+(i+.5)*ch+3,fmt(d.value),{'text-anchor':'middle','font-size':s.fs-3,fill:labelInk(c,s.theme.fg)});}});});
 colOrder.forEach((cj,j)=>label(s,left+(j+.5)*cw,bottom+14,m.columnNames[cj],{'text-anchor':'middle','font-size':s.fs-3},Math.max(3,cw/(s.fs-3))));
 function tree(node,horizontal){const order=horizontal?rowOrder:colOrder,span=horizontal?left-45:top-13,max=(horizontal?rowTree:colTree).distance||1,pos=index=>order.indexOf(index),center=d=>d3.mean(d.indices,pos),depth=d=>span*d.distance/max;
  if(!node.children)return;const [a,b]=node.children;if(horizontal){const xx=left-30-depth(node),ay=top+(center(a)+.5)*ch,by=top+(center(b)+.5)*ch;const p=s.path(`M${left-30-depth(a)},${ay}H${xx}V${by}H${left-30-depth(b)}`,{stroke:s.theme.secondary,'stroke-width':.75,'data-mark':'cluster-branch','data-distance':node.distance});s.draw(p,.05,.65);}else{const yy=top-6-depth(node),ax=left+(center(a)+.5)*cw,bx=left+(center(b)+.5)*cw;const p=s.path(`M${ax},${top-6-depth(a)}V${yy}H${bx}V${top-6-depth(b)}`,{stroke:s.theme.secondary,'stroke-width':.75,'data-mark':'cluster-branch','data-distance':node.distance});s.draw(p,.05,.65);}node.children.forEach(c=>tree(c,horizontal));
 }tree(rowTree,true);tree(colTree,false);scaleLegend(s,domain,{x:left,y:s.h-15,width:Math.min(90,s.w-left-30)});label(s,right,s.h-2,t10('欧氏 · 平均连接','Euclidean · Average'),{'font-size':s.fs-3,'text-anchor':'end'},30);
}
function pcaloadings(s,doc){
 const left=39,right=s.w-39,top=24,bottom=s.h-33,r=Math.max(20,Math.min(right-left,bottom-top)/2),cx=(left+right)/2,cy=(top+bottom)/2,x=v=>cx+v*r,y=v=>cy-v*r;
 s.circle(cx,cy,r,{fill:'none',stroke:s.theme.line,'stroke-width':.8});s.line(cx-r,cy,cx+r,cy,{stroke:s.theme.line});s.line(cx,cy-r,cx,cy+r,{stroke:s.theme.line});for(const v of[-1,1]){num(s,x(v),cy+14,v,{'text-anchor':'middle','font-size':s.fs-3});num(s,cx-6,y(v)+3,v,{'text-anchor':'end','font-size':s.fs-3});}
 label(s,cx+r+9,cy-6,'PC1',{'font-size':s.fs-2},6);label(s,cx+7,cy-r+4,'PC2',{'font-size':s.fs-2},6);
 const marker=s.el('marker',{id:`${s.id}-loading-arrow`,viewBox:'0 0 10 10',refX:8,refY:5,markerWidth:5,markerHeight:5,orient:'auto'},s.defs);s.path('M0,1L9,5L0,9Z',{fill:s.theme.accent},marker);
 doc.data.forEach((d,i)=>{const line=s.line(cx,cy,x(d.loading1),y(d.loading2),{stroke:s.theme.accent,'stroke-width':1.2,'marker-end':`url(#${s.id}-loading-arrow)`,'data-mark':'pca-loading','data-pc1':d.loading1,'data-pc2':d.loading2});s.add(p=>{const q=phase(p,i/doc.data.length*.2,.6);line.setAttribute('x2',x(d.loading1*q));line.setAttribute('y2',y(d.loading2*q));});s.edit(line,d,'loading1');s.tip(line,`${d.variable}\nPC1: ${fmt(d.loading1)}\nPC2: ${fmt(d.loading2)}`);const tx=label(s,x(d.loading1)+(d.loading1>=0?5:-5),y(d.loading2)-6,d.variable,{'text-anchor':d.loading1>=0?'start':'end','font-size':s.fs-2,fill:s.theme.fg},s.compact?6:14);s.reveal(tx,.5+i/doc.data.length*.2,.2);});
 label(s,16,s.h-3,t10('相关载荷 · 非样本得分','Correlation loadings · not scores'),{'font-size':s.fs-3},45);
}
function autocorrelation(s,doc,partial=false){
 const values=doc.data.map(d=>d.value),coeff=(partial?pacf10:autocorrelation10)(values,doc.maxLag),left=42,right=s.w-19,top=25,bottom=s.h-41,x=d3.scalePoint(d3.range(1,doc.maxLag+1),[left+8,right-8]),y=d3.scaleLinear([-1,1],[bottom,top]),band=1.96/Math.sqrt(values.length),g=s.group();
 s.rect(left,y(band),right-left,y(-band)-y(band),{fill:s.theme.accent,'fill-opacity':.065},g);
 for(const v of[-1,-.5,0,.5,1]){s.line(left,y(v),right,y(v),{'stroke-width':v===0?1:.5,'stroke-dasharray':v===0?'':'1 5'},g);num(s,left-7,y(v)+3,fmt(v),{'font-size':s.fs-3,'text-anchor':'end'});}
 for(const v of[-band,band])s.line(left,y(v),right,y(v),{stroke:s.theme.accent,'stroke-width':.65,'stroke-dasharray':'3 4'},g);
 coeff.slice(1).forEach((v,i)=>{const lag=i+1,px=x(lag),mark=s.line(px,y(0),px,y(v),{stroke:s.theme.fg,'stroke-width':2,'data-mark':partial?'pacf-lag':'acf-lag','data-lag':lag,'data-value':v});s.add(p=>mark.setAttribute('y2',y(v*phase(p,i/doc.maxLag*.3,.55))));const point=s.circle(px,y(v),2.2,{fill:s.theme.accent});s.add(p=>{const q=phase(p,i/doc.maxLag*.3,.55);point.setAttribute('cy',y(v*q));point.setAttribute('opacity',q);});s.tip(mark,`${partial?'PACF':'ACF'} · ${t10('滞后','Lag')} ${lag}\n${fmt(v)}\nn = ${values.length}`);if(doc.maxLag<=16||i%Math.ceil(doc.maxLag/10)===0||lag===doc.maxLag)num(s,px,bottom+16,lag,{'font-size':s.fs-3,'text-anchor':'middle'});});
 label(s,left,13,partial?'PACF · Yule–Walker':'ACF',{'font-size':s.fs-2},28);label(s,right,s.h-3,`±1.96/√n = ±${fmt(band,{significantDigits:3})}`,{'text-anchor':'end','font-size':s.fs-3},40);label(s,left,s.h-3,t10('滞后','Lag'),{'font-size':s.fs-3},10);
}
function imr(s,doc){
 const stats=imr10(doc.data),left=s.compact?38:47,right=s.w-(s.compact?68:80),top=22,bottom=s.h-28,gap=34,ph=(bottom-top-gap)/2,x=d3.scalePoint(doc.data.map(d=>d.period),[left,right]);
 const panels=[{name:'I',values:doc.data.map(d=>d.value),low:stats.low,high:stats.high,mean:stats.mean,zero:false},{name:'MR',values:stats.moving,low:0,high:stats.mrHigh,mean:stats.mrMean,zero:true}];
 panels.forEach((p,j)=>{const py=top+j*(ph+gap),pb=py+ph,vals=p.values.filter(v=>v!==null),domain=s.linearDomain([...vals,p.low,p.high],p.zero),y=d3.scaleLinear(domain,[pb,py]).nice(3),g=s.group();
  y.ticks(3).forEach(v=>{s.line(left,y(v),right,y(v),{'stroke-width':.5,'stroke-dasharray':'1 5'});num(s,left-7,y(v)+3,fmt(v),{'text-anchor':'end','font-size':s.fs-3});});
  for(const [name,v]of [['LCL',p.low],['CL',p.mean],['UCL',p.high]]){s.line(left,y(v),right,y(v),{stroke:name==='CL'?s.theme.secondary:s.theme.accent,'stroke-width':.7,'stroke-dasharray':name==='CL'?'':'3 4'});label(s,right+5,y(v)+3,`${name} ${fmt(v,{significantDigits:4})}`,{'font-size':s.fs-3,fill:s.theme.secondary},20);}
  const line=d3.line().defined((v)=>v!==null).x((_,i)=>x(doc.data[i].period)).y(v=>y(v));s.path(line(p.values),{stroke:s.theme.fg,'stroke-width':1.1,'data-mark':`imr-${p.name}-line`},g);
  p.values.forEach((v,i)=>{if(v===null)return;const outside=v<p.low||v>p.high,mark=s.circle(x(doc.data[i].period),y(v),outside?3.2:2.2,{fill:outside?s.theme.accent:s.theme.bg,stroke:outside?s.theme.accent:s.theme.fg,'stroke-width':.85,'data-mark':`imr-${p.name}-point`,'data-value':v,'data-outside':outside},g);s.edit(mark,doc.data[i],'value');s.tip(mark,`${p.name} · ${doc.data[i].period}\n${fmt(v)} ${doc.unit}${outside?'\n'+t10('超出控制限','Outside control limits'):''}`);});s.clipReveal(g,left-5,py-6,right-left+10,ph+12,j*.07,.73);label(s,left,py-9,`${p.name} · ${doc.unit}`,{'font-size':s.fs-2},35);
 });
 doc.data.forEach((d,i)=>{if(i===0||i===doc.data.length-1||i%Math.ceil(doc.data.length/6)===0)label(s,x(d.period),bottom+17,d.period,{'text-anchor':'middle','font-size':s.fs-3},9);});
}
export const volume10Renderers={choropleth,geomap,splom,clusterheatmap,pcaloadings,acf:(s,d)=>autocorrelation(s,d),pacf:(s,d)=>autocorrelation(s,d,true),imr};
