import {populationId} from './data-identity.js';
import * as d3 from 'd3';
import {measurementDomain} from './axis-policy.js';
import {phase7 as phase,number7 as fmt,num7 as num,label7 as label} from './volume7-utils.js';
import {t15,weibull15,meanExcess15,ttt15,recurrence15,spectrum15} from './volume15-data.js';
const attrs=row=>({'data-record-id':row._id,'data-record-label':row.label});
const color=(s,g,i)=>s.theme.groupColor?.(g,s.theme.color(i))||s.theme.color(i);
const percent=x=>`${fmt(x*100,{significantDigits:3})}%`;
function frame(s,xd,yd,{left=s.compact?43:59,right=s.w-22,top=38,bottom=s.h-44,xlabel='',ylabel='',xformat=fmt,yformat=fmt}={}){const x=d3.scaleLinear(xd,[left,right]),y=d3.scaleLinear(yd,[bottom,top]);for(const v of y.ticks(s.compact?3:4)){s.line(left,y(v),right,y(v),{'stroke-width':.5,'stroke-dasharray':'2 4'});num(s,left-7,y(v)+3,yformat(v),{'text-anchor':'end','font-size':s.fs-2});}for(const v of x.ticks(s.compact?3:5)){s.line(x(v),bottom,x(v),bottom+4,{'stroke-width':.6});num(s,x(v),bottom+18,xformat(v),{'text-anchor':'middle','font-size':s.fs-2});}s.line(left,bottom,right,bottom);label(s,left,top-15,ylabel,{'font-size':s.fs-2},s.compact?30:70);label(s,right,bottom+35,xlabel,{'text-anchor':'end','font-size':s.fs-2},s.compact?35:70);return{x,y,left,right,top,bottom};}
function legend(s,groups,y=13,{state=false}={}){const width=(s.w-70)/groups.length;groups.forEach((group,i)=>{const x=45+i*width,col=state?s.theme.color(i):color(s,group,i);s.circle(x,y-3,3,{fill:col});label(s,x+8,y,group,{fill:col,'font-size':s.fs-2},Math.max(3,Math.floor(width/7)-2));});}
function rawRug(s,doc,x,y){doc.data.forEach((row,i)=>{const px=x(row.value),mark=s.line(px,y,px,y+6,{stroke:s.theme.secondary,'stroke-opacity':.55,'data-mark':'reliability-raw',...attrs(row),'data-value':row.value});s.reveal(mark,.2+i/doc.data.length*.3,.35);s.edit(mark,row,'value');s.tip(mark,`${row.label}: ${String(row.value)} ${doc.unit}\n${t15('原始观测','Original observation')}`);});}
function lexis(s,doc){const groups=[...new Set(doc.data.map(r=>r.group))],xd=measurementDomain(doc.data.flatMap(r=>[r.entryPeriod,r.exitPeriod]),{padding:.05}),yd=measurementDomain(doc.data.flatMap(r=>[r.entryAge,r.entryAge+r.exitPeriod-r.entryPeriod]),{padding:.08}),f=frame(s,xd,yd,{top:49,xlabel:t15('日历年','Calendar year'),ylabel:t15('年龄 / 年','Age / years'),xformat:v=>String(+v.toFixed(2))});legend(s,groups);
 doc.data.forEach((row,i)=>{const col=color(s,row.group,groups.indexOf(row.group)),exitAge=row.entryAge+row.exitPeriod-row.entryPeriod,line=s.line(f.x(row.entryPeriod),f.y(row.entryAge),f.x(row.exitPeriod),f.y(exitAge),{stroke:col,'stroke-width':s.compact?1.5:2.2,'stroke-opacity':.78,'data-mark':'lexis-lifeline',...attrs(row),'data-birth-year':row.entryPeriod-row.entryAge});s.add(p=>{const q=phase(p,i/doc.data.length*.28,.6);line.setAttribute('x2',f.x(row.entryPeriod+(row.exitPeriod-row.entryPeriod)*q));line.setAttribute('y2',f.y(row.entryAge+(exitAge-row.entryAge)*q));});s.edit(line,row,'entryAge');const start=s.circle(f.x(row.entryPeriod),f.y(row.entryAge),2,{fill:s.theme.bg,stroke:col,'stroke-width':1,...attrs(row)}),end=s.circle(f.x(row.exitPeriod),f.y(exitAge),2.6,{fill:col,...attrs(row)});s.growCircle(start,2,i/doc.data.length*.28,.3);s.growCircle(end,2.6,.45+i/doc.data.length*.28,.25);s.edit(start,row,'entryPeriod');s.edit(end,row,'exitPeriod');const tip=`${row.label} · ${row.group}\n${t15('进入','Entry')}: ${String(row.entryPeriod)} · ${String(row.entryAge)} ${doc.unit}\n${t15('退出','Exit')}: ${String(row.exitPeriod)} · ${fmt(exitAge)} ${doc.unit}\n${t15('出生年','Birth year')}: ${fmt(row.entryPeriod-row.entryAge)}`;[line,start,end].forEach(mark=>s.tip(mark,tip));});
}
function lanes(s,domain,labels,{top=41,left=s.compact?43:66,bottom=s.h-45}={}){const right=s.w-20,x=d3.scaleLinear(domain,[left,right]),y=d3.scaleBand(labels,[top,bottom]).padding(.3);x.ticks(s.compact?3:5).forEach(v=>{s.line(x(v),top,x(v),bottom,{'stroke-width':.5,'stroke-dasharray':'2 5'});num(s,x(v),bottom+18,fmt(v),{'text-anchor':'middle','font-size':s.fs-2});});labels.forEach(value=>label(s,left-7,y(value)+y.bandwidth()/2+3,value,{'text-anchor':'end','font-size':s.fs-2},s.compact?5:9));label(s,right,s.h-4,s.doc.unit,{'text-anchor':'end','font-size':s.fs-2},28);return{x,y,left,right,top,bottom};}
function swimmer(s,doc){const rows=[...doc.data].sort((a,b)=>(b.end-b.start)-(a.end-a.start)),groups=[...new Set(doc.data.map(r=>r.group))],f=lanes(s,measurementDomain(rows.flatMap(r=>[r.start,r.end]),{padding:.04}),rows.map(r=>r.label),{top:60});legend(s,groups);label(s,f.left,34,t15('◇ 首次响应 · → 仍在观察','◇ first response · → observation ongoing'),{'font-size':s.fs-3},s.compact?40:70);
 rows.forEach((row,i)=>{const cy=f.y(row.label)+f.y.bandwidth()/2,h=Math.min(13,f.y.bandwidth()),col=color(s,row.group,groups.indexOf(row.group)),bar=s.rect(f.x(row.start),cy-h/2,f.x(row.end)-f.x(row.start),h,{fill:col,'fill-opacity':.24,'data-mark':'swimmer-window',...attrs(row),'data-start':row.start,'data-end':row.end});s.add(p=>bar.setAttribute('width',(f.x(row.end)-f.x(row.start))*phase(p,i/rows.length*.3,.56)));s.edit(bar,row,'end');const center=s.line(f.x(row.start),cy,f.x(row.end),cy,{stroke:col,'stroke-width':1.3});s.draw(center,i/rows.length*.3,.56);const start=s.circle(f.x(row.start),cy,2,{fill:col,...attrs(row)});s.edit(start,row,'start');s.growCircle(start,2,i/rows.length*.3,.4);const tip=`${row.label} · ${row.group}\n${String(row.start)} – ${String(row.end)} ${doc.unit}\n${t15('首次响应','First response')}: ${row.response===null?t15('无记录','not recorded'):String(row.response)+' '+doc.unit}\n${t15('仍在观察','Ongoing')}: ${row.ongoing}`;[bar,center,start].forEach(mark=>s.tip(mark,tip));
  if(row.response!==null){const px=f.x(row.response),r=3.7,diamond=s.path(`M${px} ${cy-r}L${px+r} ${cy}L${px} ${cy+r}L${px-r} ${cy}Z`,{fill:s.theme.bg,stroke:col,'stroke-width':1.4,'data-mark':'swimmer-response',...attrs(row),'data-response':row.response});s.reveal(diamond,.38+i/rows.length*.3,.24);s.edit(diamond,row,'response');s.tip(diamond,tip);}
  if(row.ongoing){const px=f.x(row.end),arrow=s.path(`M${px-5} ${cy-4}L${px} ${cy}L${px-5} ${cy+4}`,{stroke:col,'stroke-width':1.5,'data-mark':'swimmer-ongoing',...attrs(row)});s.reveal(arrow,.55+i/rows.length*.2,.23);s.edit(arrow,row,'ongoing');s.tip(arrow,tip);}
 });
}
function eventhistory(s,doc){const subjects=[...new Set(doc.data.map(r=>r.subject))],states=[...new Set(doc.data.map(r=>r.state))],f=lanes(s,measurementDomain(doc.data.flatMap(r=>[r.start,r.end]),{padding:.025}),subjects,{top:44});legend(s,states,13,{state:true});doc.data.forEach((row,i)=>{const cy=f.y(row.subject)+f.y.bandwidth()/2,h=Math.min(22,f.y.bandwidth()),col=s.theme.color(states.indexOf(row.state)),mark=s.rect(f.x(row.start),cy-h/2,f.x(row.end)-f.x(row.start),h,{fill:col,'fill-opacity':.73,'data-mark':'event-history-interval',...attrs(row),'data-state':row.state,'data-start':row.start,'data-end':row.end});s.add(p=>mark.setAttribute('width',(f.x(row.end)-f.x(row.start))*phase(p,.05+(f.x(row.start)-f.left)/(f.right-f.left)*.36,.55)));s.edit(mark,row,'end');const edge=s.line(f.x(row.start),cy-h/2,f.x(row.start),cy+h/2,{stroke:s.theme.bg,'stroke-width':2,'data-mark':'event-history-start',...attrs(row)});s.reveal(edge,i/doc.data.length*.32,.45);s.edit(edge,row,'start');const tip=`${row.label} · ${row.subject}\n${row.state}\n[${String(row.start)}, ${String(row.end)}) ${doc.unit}`;s.tip(mark,tip);s.tip(edge,tip);});label(s,f.left,s.h-4,t15('空白保留未记录区间','Blank = unrecorded interval'),{'font-size':s.fs-3},s.compact?25:55);}
function recurrence(s,doc){const model=recurrence15(doc.data,doc.threshold),rows=model.rows,dt=rows[1].time-rows[0].time,xd=[rows[0].time-dt/2,rows.at(-1).time+dt/2],side=Math.min(s.w-(s.compact?68:92),s.h-111),left=(s.w-side)/2,top=70,f=frame(s,xd,xd,{left,right:left+side,top,bottom:top+side,xlabel:`${t15('时间','Time')} / ${doc.timeUnit}`,ylabel:`${t15('时间','Time')} / ${doc.timeUnit}`});
 s.rect(f.left,f.top,side,side,{fill:s.theme.bg,stroke:s.theme.rule,'stroke-width':.6,'data-mark':'recurrence-background'});const cell=side/rows.length,g=s.group();model.cells.filter(c=>c.recurrent).forEach(c=>{const mark=s.rect(f.x(c.a.time)-cell/2,f.y(c.b.time)-cell/2,cell+.03,cell+.03,{fill:s.theme.accent,'fill-opacity':c.i===c.j?.9:.68,'data-mark':'recurrence-cell','data-i':c.i,'data-j':c.j,'data-distance':c.distance,'data-record-ids':JSON.stringify([c.a._id,c.b._id].filter(Boolean))},g);s.tip(mark,`${t15('时间对','Time pair')}: ${String(c.a.time)}, ${String(c.b.time)} ${doc.timeUnit}\n${String(c.a.value)}, ${String(c.b.value)} ${doc.unit}\n|Δ|=${fmt(c.distance)} ≤ ${String(doc.threshold)}`);});s.clipReveal(g,f.left,f.top,side,side,.13,.78);
 const ry=d3.scaleLinear(measurementDomain(rows.map(r=>r.value),{padding:.05}),[47,22]),path=s.path(d3.line().x(r=>f.x(r.time)).y(r=>ry(r.value))(rows),{stroke:s.theme.fg,'stroke-width':1,'data-mark':'recurrence-original-signal'});s.draw(path,.02,.5);rows.forEach((row,i)=>{const mark=s.circle(f.x(row.time),ry(row.value),1.6,{fill:s.theme.fg,'data-mark':'recurrence-raw',...attrs(row)});s.growCircle(mark,1.6,i/rows.length*.28,.4);s.edit(mark,row,'value');s.tip(mark,`${row.label}\n${String(row.time)} ${doc.timeUnit}: ${String(row.value)} ${doc.unit}`);});label(s,f.left,12,`ε=${String(doc.threshold)} ${doc.unit} · m=1`,{fill:s.theme.fg,'font-size':s.fs-2},45);
}
function weibull(s,doc){const populationColor=s.theme.objectColor(populationId('sample-group',doc.data),s.theme.accent);const points=weibull15(doc.data),f=frame(s,measurementDomain(points.map(p=>p.x),{padding:.07}),measurementDomain(points.map(p=>p.y),{padding:.07}),{xlabel:`${t15('寿命（对数轴）','Lifetime (log scale)')} / ${doc.unit}`,ylabel:t15('Weibull 累计概率','Weibull cumulative probability'),xformat:x=>fmt(Math.exp(x)),yformat:y=>percent(-Math.expm1(-Math.exp(y)))});points.forEach((p,i)=>{const r=s.compact?2.4:3.2,mark=s.circle(f.x(p.x),f.y(p.y),r,{fill:populationColor,'fill-opacity':.75,'data-mark':'weibull-point',...attrs(p.row),'data-probability':p.p,'data-log-time':p.x});s.growCircle(mark,r,i/points.length*.43,.4);s.edit(mark,p.row,'value');s.tip(mark,`${p.row.label}: ${String(p.row.value)} ${doc.unit}\np=${fmt(p.p)}\nln(t)=${fmt(p.x)} · ln(−ln(1−p))=${fmt(p.y)}`);});label(s,f.left+6,f.top+14,t15('完整寿命 · 不自动拟合','Complete lifetimes · no fitted line'),{'font-size':s.fs-2},s.compact?32:65);}
function meanexcess(s,doc){const populationColor=s.theme.objectColor(populationId('sample-group',doc.data),s.theme.accent);const points=meanExcess15(doc.data,doc.minExceedances),f=frame(s,measurementDomain(doc.data.map(r=>r.value),{padding:.045}),measurementDomain([0,...points.map(p=>p.mean)],{padding:.08}),{top:43,bottom:s.h-90,xlabel:`${t15('阈值','Threshold')} / ${doc.unit}`,ylabel:`${t15('平均超额','Mean excess')} / ${doc.unit}`}),line=s.path(d3.line().x(p=>f.x(p.threshold)).y(p=>f.y(p.mean))(points),{stroke:populationColor,'stroke-width':1.8,'data-mark':'mean-excess-line'});s.draw(line,.05,.73);points.forEach((p,i)=>{const r=s.compact?1.8:2.5,mark=s.circle(f.x(p.threshold),f.y(p.mean),r,{fill:populationColor,'data-mark':'mean-excess-point','data-threshold':p.threshold,'data-count':p.count,'data-mean':p.mean});s.growCircle(mark,r,i/points.length*.35,.45);s.tip(mark,`${t15('阈值','Threshold')}: ${String(p.threshold)} ${doc.unit}\ne(u)=${fmt(p.mean)} ${doc.unit}\nn(x>u)=${p.count}`);});
 const cy=s.h-48,scale=d3.scaleLinear([0,doc.data.length],[cy+14,cy-5]);points.forEach((p,i)=>{const mark=s.line(f.x(p.threshold),cy+14,f.x(p.threshold),scale(p.count),{stroke:s.theme.secondary,'stroke-width':Math.max(1,(f.right-f.left)/points.length*.6),'stroke-opacity':.45,'data-mark':'mean-excess-count','data-count':p.count});s.reveal(mark,.12+i/points.length*.35,.45);});label(s,f.left,cy-9,t15('超额样本量','Exceedance count'),{'font-size':s.fs-3},30);rawRug(s,doc,f.x,s.h-19);label(s,f.right,s.h-3,t15('底部短线：全部原始观测','Bottom rug: all original observations'),{'text-anchor':'end','font-size':s.fs-3},s.compact?37:70);label(s,f.left+4,f.top+12,`n ≥ ${doc.minExceedances}`,{'font-size':s.fs-2},20);
}
function ttt(s,doc){const populationColor=s.theme.objectColor(populationId('sample-group',doc.data),s.theme.accent);const points=ttt15(doc.data),f=frame(s,[0,1],[0,1],{xlabel:t15('累计失效份额 i/n','Cumulative failure fraction i/n'),ylabel:t15('总试验时间份额','Total time-on-test share'),xformat:percent,yformat:percent});s.line(f.x(0),f.y(0),f.x(1),f.y(1),{stroke:s.theme.secondary,'stroke-dasharray':'4 4','data-mark':'ttt-reference'});const shape=s.path(d3.area().x(p=>f.x(p.fraction)).y0(p=>f.y(p.fraction)).y1(p=>f.y(p.total))(points),{fill:populationColor,'fill-opacity':.09}),line=s.path(d3.line().x(p=>f.x(p.fraction)).y(p=>f.y(p.total))(points),{stroke:populationColor,'stroke-width':1.8,'data-mark':'ttt-curve'});s.reveal(shape,.08,.72);s.draw(line,.06,.76);points.slice(1).forEach((p,i)=>{const r=s.compact?1.9:2.6,mark=s.circle(f.x(p.fraction),f.y(p.total),r,{fill:populationColor,'data-mark':'ttt-point',...attrs(p.row),'data-fraction':p.fraction,'data-total-time':p.total});s.growCircle(mark,r,i/doc.data.length*.4,.4);s.edit(mark,p.row,'value');s.tip(mark,`${p.row.label}: ${String(p.row.value)} ${doc.unit}\ni/n=${fmt(p.fraction)}\nTTT=${fmt(p.total)}`);});label(s,f.left+8,f.bottom-13,t15('虚线：指数分布参考','Dashed: exponential reference'),{'font-size':s.fs-2},s.compact?31:65);}
function spectrogram(s,doc){const model=spectrum15(doc.data),xd=[model.times[0]-model.dt/2,model.times.at(-1)+model.dt/2],yd=[Math.max(0,model.frequencies[0]-model.df/2),model.frequencies.at(-1)+model.df/2],f=frame(s,xd,yd,{top:34,right:s.w-(s.compact?56:79),xlabel:doc.axes.x,ylabel:doc.axes.y}),max=model.max||1,shade=v=>s.theme.valueColor?.(v,[0,max])??d3.interpolateRgb(s.theme.bg,s.theme.accent)(.04+.93*v/max);doc.data.forEach(row=>{const x0=f.x(row.time-model.dt/2),x1=f.x(row.time+model.dt/2),y0=f.y(row.frequency+model.df/2),y1=f.y(Math.max(0,row.frequency-model.df/2)),mark=s.rect(x0,y0,x1-x0+.04,y1-y0+.04,{fill:shade(row.power),'data-mark':'spectrogram-cell',...attrs(row),'data-time':row.time,'data-frequency':row.frequency,'data-power':row.power});s.reveal(mark,(row.time-model.times[0])/(model.times.at(-1)-model.times[0])*.4,.5);s.edit(mark,row,'power');s.tip(mark,`${doc.axes.x}: ${String(row.time)}\n${doc.axes.y}: ${String(row.frequency)}\n${String(row.power)} ${doc.unit}`);});const lx=f.right+13,h=Math.min(115,f.bottom-f.top);for(let i=0;i<40;i++)s.rect(lx,f.top+i*h/40,8,h/40+.3,{fill:shade(model.max*(1-i/39))});num(s,lx+12,f.top+4,fmt(model.max),{'font-size':s.fs-3});num(s,lx+12,f.top+h,0,{'font-size':s.fs-3});label(s,lx-3,f.top+h+17,doc.unit,{'font-size':s.fs-3},s.compact?8:16);}
export const volume15Renderers={lexis,swimmer,eventhistory,recurrence,weibull,meanexcess,ttt,spectrogram};
