import * as d3 from 'd3';
import {measurementDomain} from './axis-policy.js';
import {engineeringWindKey} from './engineering-series-rules.js';
import {phase7 as phase,number7 as fmt,num7 as num,label7 as label,short7 as short} from './volume7-utils.js';
import {t19,groups19,response19,smith19,windrose19,polar19,phasor19,eye19} from './volume19-data.js';
const attrs=row=>({'data-record-id':row._id,'data-record-label':row.label});
const color=(s,group,i)=>s.theme.groupColor?.(group,s.theme.color(i))||s.theme.color(i);
const pct=v=>`${fmt(v*100,{significantDigits:3})}%`;
const tipComplex=(row,doc)=>`${row.label}${row.group?' · '+row.group:''}\nRe: ${String(row.real)} · Im: ${String(row.imag)} ${doc.unit}${row.frequency!==undefined?'\nf: '+String(row.frequency)+' '+doc.frequencyUnit:''}`;
function frame(s,xd,yd,{left=s.compact?44:62,right=s.w-23,top=39,bottom=s.h-43,xlabel='',ylabel='',xf=fmt,yf=fmt,xticks=true}={}){const x=d3.scaleLinear(xd,[left,right]),y=d3.scaleLinear(yd,[bottom,top]);for(const v of y.ticks(s.compact?3:4)){s.line(left,y(v),right,y(v),{'stroke-width':.5,'stroke-dasharray':'2 5'});num(s,left-7,y(v)+3,yf(v),{'text-anchor':'end','font-size':s.fs-2});}if(xticks)for(const v of x.ticks(s.compact?3:5)){s.line(x(v),bottom,x(v),bottom+4,{'stroke-width':.65});num(s,x(v),bottom+17,xf(v),{'text-anchor':'middle','font-size':s.fs-2});}s.line(left,bottom,right,bottom);label(s,left,top-12,ylabel,{'font-size':s.fs-2},s.compact?31:65);if(xlabel)label(s,right,bottom+34,xlabel,{'text-anchor':'end','font-size':s.fs-2},s.compact?35:70);return{x,y,left,right,top,bottom};}
function equalFrame(s,points,{left=s.compact?42:60,right=s.w-22,top=42,bottom=s.h-43,xlabel='',ylabel='',minExtent=0}={}){const width=right-left,height=bottom-top,maxX=Math.max(minExtent,d3.max(points,p=>Math.abs(p[0]))||0),maxY=Math.max(minExtent,d3.max(points,p=>Math.abs(p[1]))||0),extent=Math.max(maxX,maxY)||1;let yd=extent*1.14,xd=yd*width/height;if(xd<maxX*1.14){xd=maxX*1.14;yd=xd*height/width;}const f=frame(s,[-xd,xd],[-yd,yd],{left,right,top,bottom,xlabel,ylabel});s.line(f.x(0),top,f.x(0),bottom,{stroke:s.theme.secondary,'stroke-width':.8});s.line(left,f.y(0),right,f.y(0),{stroke:s.theme.secondary,'stroke-width':.8});return f;}
function legend(s,groups,y=13){s.legend(groups.map((g,i)=>({label:short(g,s.compact?7:18),color:color(s,g,i)})),s.compact?18:34,y);}
function groupTop(s,groups){const start=s.compact?18:34;let cursor=start,y=13;for(const group of groups){const text=short(group,s.compact?7:18),size=[...String(text)].reduce((n,c)=>n+(/[\u2e80-\uffff]/.test(c)?1:.58),0)*s.fs+29;if(cursor>start&&cursor+size>s.w-12){cursor=start;y+=s.fs+8;}cursor+=size;}return Math.max(39,y+23);}
function editableComplex(s,row,doc,x,y,col,{radius=s.compact?2.1:3,delay=0,mark='complex-sample'}={}){const core=s.circle(x,y,radius,{fill:col,'fill-opacity':.76,'data-mark':mark,...attrs(row),'data-real':row.real,'data-imag':row.imag});s.growCircle(core,radius,delay,.4);s.edit(core,row,'real');s.tip(core,tipComplex(row,doc)+'\n'+t19('点击编辑实部','Click to edit the real part'));const ring=s.circle(x,y,radius+2,{fill:'none',stroke:'transparent','stroke-width':2.5,'pointer-events':'stroke','data-mark':'complex-imag-edit',...attrs(row)});s.edit(ring,row,'imag');s.tip(ring,tipComplex(row,doc)+'\n'+t19('点击编辑虚部','Click to edit the imaginary part'));return core;}
function arrow(s,x1,y1,x2,y2,col,{dashed=false,mark='phasor-vector',width=1.8}={}){const dx=x2-x1,dy=y2-y1,length=Math.hypot(dx,dy),angle=Math.atan2(dy,dx),h=Math.min(8,length*.25),head=length?`M${x2-h*Math.cos(angle-.45)} ${y2-h*Math.sin(angle-.45)}L${x2} ${y2}L${x2-h*Math.cos(angle+.45)} ${y2-h*Math.sin(angle+.45)}`:'';return{line:s.line(x1,y1,x2,y2,{stroke:col,'stroke-width':width,'stroke-dasharray':dashed?'5 4':'','data-mark':mark}),head:s.path(head,{stroke:col,'stroke-width':width})};}
function bode(s,doc){const curves=response19(doc.data),all=curves.flatMap(c=>c.points),xd=measurementDomain(doc.data.map(r=>Math.log10(r.frequency)),{padding:.025}),split=Math.round(s.h*.48),f=frame(s,xd,measurementDomain(all.map(p=>p.db),{padding:.1}),{top:groupTop(s,curves.map(c=>c.group)),bottom:split-16,ylabel:t19('幅值 / dB','Magnitude / dB'),xf:v=>fmt(10**v),xticks:false}),g=frame(s,xd,measurementDomain(all.map(p=>p.phase),{padding:.1}),{top:split+25,bottom:s.h-43,ylabel:t19('展开相位 / °','Unwrapped phase / °'),xlabel:`f / ${doc.frequencyUnit}`,xf:v=>fmt(10**v)});legend(s,curves.map(c=>c.group));curves.forEach((curve,j)=>{const col=color(s,curve.group,j);for(const [panel,field]of[[f,'db'],[g,'phase']]){const path=s.path(d3.line().x(p=>panel.x(Math.log10(p.row.frequency))).y(p=>panel.y(p[field]))(curve.points),{stroke:col,'stroke-width':1.6,'data-mark':`bode-${field}-curve`});s.draw(path,j*.07,.74);}curve.points.forEach((p,i)=>{for(const [panel,field,edit]of[[f,'db','real'],[g,'phase','imag']]){const mark=s.circle(panel.x(Math.log10(p.row.frequency)),panel.y(p[field]),s.compact?1.5:2.2,{fill:col,'data-mark':`bode-${field}-sample`,...attrs(p.row),'data-value':p[field]});s.growCircle(mark,s.compact?1.5:2.2,i/curve.points.length*.35,.43);s.edit(mark,p.row,edit);s.tip(mark,`${tipComplex(p.row,doc)}\n${fmt(p.db)} dB · ${fmt(p.phase)}°`);}});});}
function nyquist(s,doc){const curves=response19(doc.data),f=equalFrame(s,[[-1,0],...doc.data.map(r=>[r.real,r.imag])],{top:groupTop(s,curves.map(c=>c.group)),xlabel:`Re / ${doc.unit}`,ylabel:`Im / ${doc.unit}`});legend(s,curves.map(c=>c.group));const ref=s.circle(f.x(-1),f.y(0),4,{fill:'none',stroke:s.theme.secondary,'stroke-width':1.1});s.tip(ref,t19('−1 + j0 参考点，不计算稳定性','−1 + j0 reference; stability is not computed'));curves.forEach((c,j)=>{const col=color(s,c.group,j),path=s.path(d3.line().x(p=>f.x(p.row.real)).y(p=>f.y(p.row.imag))(c.points),{stroke:col,'stroke-width':1.6,'data-mark':'nyquist-locus'});s.draw(path,j*.05,.79);c.points.forEach((p,i)=>editableComplex(s,p.row,doc,f.x(p.row.real),f.y(p.row.imag),col,{delay:i/c.points.length*.32,mark:'nyquist-sample'}));const k=Math.floor(c.points.length*.45),a=c.points[k-1].row,b=c.points[k].row,head=arrow(s,f.x(a.real),f.y(a.imag),f.x(b.real),f.y(b.imag),col);s.reveal(head.line,.5,.3);s.reveal(head.head,.5,.3);});}
function nichols(s,doc){const curves=response19(doc.data),points=curves.flatMap(c=>c.points),f=frame(s,measurementDomain(points.map(p=>p.phase),{padding:.08}),measurementDomain(points.map(p=>p.db),{padding:.1}),{top:groupTop(s,curves.map(c=>c.group)),xlabel:t19('展开相位 / °','Unwrapped phase / °'),ylabel:t19('幅值 / dB','Magnitude / dB')});legend(s,curves.map(c=>c.group));curves.forEach((c,j)=>{const col=color(s,c.group,j),path=s.path(d3.line().x(p=>f.x(p.phase)).y(p=>f.y(p.db))(c.points),{stroke:col,'stroke-width':1.7,'data-mark':'nichols-locus'});s.draw(path,j*.07,.76);c.points.forEach((p,i)=>{const mark=editableComplex(s,p.row,doc,f.x(p.phase),f.y(p.db),col,{delay:i/c.points.length*.35,mark:'nichols-sample'});s.tip(mark,`${tipComplex(p.row,doc)}\n${fmt(p.phase)}° · ${fmt(p.db)} dB`);});});}
function polezero(s,doc){const f=equalFrame(s,doc.data.map(r=>[r.real,r.imag]),{minExtent:doc.systemDomain==='discrete'?1:0,xlabel:`Re / ${doc.unit}`,ylabel:`Im / ${doc.unit}`});label(s,f.left,13,t19('× 极点 · ○ 零点','× poles · ○ zeros'),{'font-size':s.fs-2},45);if(doc.systemDomain==='discrete')s.circle(f.x(0),f.y(0),Math.abs(f.x(1)-f.x(0)),{fill:'none',stroke:s.theme.secondary,'stroke-dasharray':'4 4','data-mark':'polezero-unit-circle'});const locations=d3.group(doc.data,r=>`${r.real}|${r.imag}|${r.kind}`);doc.data.forEach((row,i)=>{const x=f.x(row.real),y=f.y(row.imag),r=s.compact?3.3:5,col=s.theme.groupColor(row.kind,row.kind==='pole'?s.theme.accent:s.theme.fg),mark=row.kind==='pole'?s.path(`M${x-r} ${y-r}L${x+r} ${y+r}M${x-r} ${y+r}L${x+r} ${y-r}`,{stroke:col,'stroke-width':1.6,'data-mark':'polezero-root',...attrs(row),'data-kind':row.kind}):s.circle(x,y,r,{fill:s.theme.bg,stroke:col,'stroke-width':1.6,'data-mark':'polezero-root',...attrs(row),'data-kind':row.kind});s.reveal(mark,i/doc.data.length*.38,.43);s.edit(mark,row,'real');s.tip(mark,`${tipComplex(row,doc)}\n${row.kind}`);const target=s.circle(x,y,r+3,{fill:'none',stroke:'transparent','stroke-width':3,'pointer-events':'stroke',...attrs(row)});s.edit(target,row,'imag');s.tip(target,tipComplex(row,doc));});for(const rows of locations.values())if(rows.length>1)label(s,f.x(rows[0].real)+8,f.y(rows[0].imag)-7,`×${rows.length}`,{'font-size':s.fs-2},8);}
function smith(s,doc){const f=equalFrame(s,[[-1,-1],[1,1]],{xlabel:'Re Γ',ylabel:'Im Γ',top:groupTop(s,groups19(doc.data)),minExtent:1}),cx=f.x(0),cy=f.y(0),r=Math.abs(f.x(1)-cx);legend(s,groups19(doc.data));s.circle(cx,cy,r,{fill:'none',stroke:s.theme.secondary,'stroke-width':1,'data-mark':'smith-unit-circle'});const drawGrid=points=>s.path(d3.line().x(p=>f.x(p.real)).y(p=>f.y(p.imag))(points),{stroke:s.theme.line,'stroke-width':.65});for(const resistance of[0,.2,.5,1,2,5]){const pts=Array.from({length:181},(_,i)=>{const a=-Math.PI+i*Math.PI/90;return{real:resistance/(1+resistance)+Math.cos(a)/(1+resistance),imag:Math.sin(a)/(1+resistance)};});drawGrid(pts);label(s,f.x((resistance-1)/(resistance+1))+3,cy-4,String(resistance),{'font-size':s.fs-3},5);}for(const reactance of[-5,-2,-1,-.5,-.2,.2,.5,1,2,5])drawGrid(Array.from({length:150},(_,i)=>smith19(Math.expm1(i/149*Math.log(1001)),reactance,1)));response19(doc.data).forEach((curve,j)=>{const col=color(s,curve.group,j),points=curve.points.map(p=>({...smith19(p.row.real,p.row.imag,doc.referenceImpedance),row:p.row})),path=s.path(d3.line().x(p=>f.x(p.real)).y(p=>f.y(p.imag))(points),{stroke:col,'stroke-width':1.8,'data-mark':'smith-locus'});s.draw(path,j*.07,.78);points.forEach((p,i)=>{const mark=editableComplex(s,p.row,doc,f.x(p.real),f.y(p.imag),col,{delay:i/points.length*.36,mark:'smith-sample'});s.tip(mark,`${tipComplex(p.row,doc)}\nΓ: ${fmt(p.real)} + j(${fmt(p.imag)})\nZ₀: ${String(doc.referenceImpedance)} Ω`);});});label(s,f.right,f.top-12,`Z₀=${String(doc.referenceImpedance)} Ω`,{'text-anchor':'end','font-size':s.fs-2},30);}
function polarFrame(s,max,{top=31,bottom=s.h-35,format=fmt}={}){const radius=Math.max(20,Math.min(s.w-87,bottom-top)/2),cx=s.w/2,cy=(top+bottom)/2,scale=d3.scaleLinear([0,max],[0,radius]);for(const v of d3.ticks(0,max,3).filter(v=>v>0)){s.circle(cx,cy,scale(v),{fill:'none',stroke:s.theme.line,'stroke-width':.7});num(s,cx+4,cy-scale(v)+10,format(v),{'font-size':s.fs-3});}for(let a=0;a<360;a+=45){const p=polar19(a,radius);s.line(cx,cy,cx+p.x,cy-p.y,{'stroke-width':.5});const q=polar19(a,radius+13);label(s,cx+q.x,cy-q.y+3,['N','NE','E','SE','S','SW','W','NW'][a/45],{'text-anchor':'middle','font-size':s.fs-2},3);}return{cx,cy,radius,scale};}
function polarscatter(s,doc){const groups=groups19(doc.data),max=d3.max(doc.data,r=>r.radius)*1.1,f=polarFrame(s,max,{top:groupTop(s,groups),bottom:s.h-24});legend(s,groups);doc.data.forEach((row,i)=>{const p=polar19(row.angle,f.scale(row.radius)),col=color(s,row.group,groups.indexOf(row.group)),r=s.compact?2.2:3,mark=s.circle(f.cx+p.x,f.cy-p.y,r,{fill:col,'fill-opacity':.7,'data-mark':'polar-observation',...attrs(row),'data-angle':row.angle,'data-radius':row.radius});s.add(progress=>{const q=phase(progress,i/doc.data.length*.35,.5);mark.setAttribute('cx',f.cx+p.x*q);mark.setAttribute('cy',f.cy-p.y*q);mark.setAttribute('r',r*Math.sqrt(q));});s.edit(mark,row,'radius');s.tip(mark,`${row.label} · ${row.group}\n${String(row.angle)}° · ${String(row.radius)} ${doc.unit}`);const ring=s.circle(f.cx+p.x,f.cy-p.y,r+2,{fill:'none',stroke:'transparent','stroke-width':2.5,'pointer-events':'stroke',...attrs(row)});s.edit(ring,row,'angle');s.tip(ring,`${row.label}\n${String(row.angle)}° · ${String(row.radius)} ${doc.unit}`);});label(s,s.w-12,s.h-3,doc.unit,{'text-anchor':'end','font-size':s.fs-2},25);}
function windrose(s,doc){const m=windrose19(doc),max=Math.max(m.max,.01)*1.12,f=polarFrame(s,max,{top:46,bottom:s.h-40,format:pct}),arc=d3.arc(),bins=doc.speedBreaks;s.legend(bins.map((low,i)=>({label:short(`${low}–${bins[i+1]??'∞'}`,s.compact?8:14),color:s.theme.objectColor(engineeringWindKey(doc,i),s.theme.color(i))})),12,12);m.cells.filter(c=>c.count).forEach(c=>{const start=(c.sector*m.step-m.step/2+1)*Math.PI/180,end=(c.sector*m.step+m.step/2-1)*Math.PI/180,mark=s.path('',{fill:s.theme.objectColor(engineeringWindKey(doc,c.bin),s.theme.color(c.bin)),'fill-opacity':.8,stroke:s.theme.bg,'stroke-width':.7,transform:`translate(${f.cx},${f.cy})`,'data-mark':'wind-frequency-bin','data-count':c.count,'data-frequency':c.frequency,'data-sector':c.sector,'data-bin':c.bin,'data-record-ids':JSON.stringify(c.rows.map(r=>r._id).filter(Boolean))});s.add(p=>{const q=phase(p,c.sector/doc.windSectors*.3,.56);mark.setAttribute('d',arc({startAngle:start,endAngle:end,innerRadius:f.scale(c.previous)*q,outerRadius:f.scale(c.cumulative)*q}));});s.tip(mark,`${t19('来向中心','Bearing center')}: ${c.sector*m.step}°\n${c.low}–${c.high??'∞'} ${doc.unit}\nn=${c.count} / ${doc.data.length} · ${pct(c.frequency)}`);});
 doc.data.forEach((row,i)=>{const calm=row.speed<doc.calmThreshold;let x1,y1,x2,y2;if(calm){x1=18+(s.w-36)*m.calm.indexOf(row)/Math.max(1,m.calm.length-1);y1=s.h-25;x2=x1;y2=y1+4;}else{const a=polar19(row.direction,f.radius+5),b=polar19(row.direction,f.radius+8);x1=f.cx+a.x;y1=f.cy-a.y;x2=f.cx+b.x;y2=f.cy-b.y;}const bin=calm?-1:Math.min(bins.length-1,d3.bisectRight(bins,row.speed)-1),mark=s.line(x1,y1,x2,y2,{stroke:s.theme.objectColor(engineeringWindKey(doc,bin),s.theme.fg),'stroke-width':.9,'stroke-opacity':.35,'data-mark':'wind-raw-observation',...attrs(row),'data-speed':row.speed});s.reveal(mark,.24+i/doc.data.length*.27,.35);s.edit(mark,row,'speed');s.tip(mark,`${row.label}\n${row.direction===null?t19('静风，来向未定义','Calm; bearing undefined'):String(row.direction)+'°'} · ${String(row.speed)} ${doc.unit}`);});
 label(s,f.cx,f.cy-2,`${t19('静风','Calm')} ${pct(m.calmFrequency)}`,{'text-anchor':'middle',fill:s.theme.fg,'font-size':s.fs-2},30);label(s,f.cx,s.h-5,`${t19('半径：全样本频率','Radius: full-sample frequency')} · n=${doc.data.length}`,{'text-anchor':'middle','font-size':s.fs-3},s.compact?47:85);
}
function hodograph(s,doc){const rows=[...doc.data].sort((a,b)=>a.height-b.height),f=equalFrame(s,rows.map(r=>[r.u,r.v]),{xlabel:`u / ${doc.unit}`,ylabel:`v / ${doc.unit}`,right:s.w-(s.compact?57:78)}),domain=d3.extent(rows,r=>r.height),shade=h=>s.theme.valueColor?.(h,domain)??d3.interpolateRgb(s.theme.bg,s.theme.accent)(.24+.7*(h-domain[0])/(domain[1]-domain[0]));rows.slice(1).forEach((row,i)=>{const previous=rows[i],path=s.line(f.x(previous.u),f.y(previous.v),f.x(row.u),f.y(row.v),{stroke:shade((row.height+previous.height)/2),'stroke-width':2.1,'data-mark':'hodograph-segment'});s.draw(path,i/rows.length*.35,.46);});rows.forEach((row,i)=>{const mark=s.circle(f.x(row.u),f.y(row.v),s.compact?2.6:3.7,{fill:shade(row.height),'data-mark':'hodograph-level',...attrs(row),'data-height':row.height});s.growCircle(mark,s.compact?2.6:3.7,i/rows.length*.38,.45);s.edit(mark,row,'u');const ring=s.circle(f.x(row.u),f.y(row.v),s.compact?5:6,{fill:'none',stroke:'transparent','stroke-width':2.5,'pointer-events':'stroke',...attrs(row)});s.edit(ring,row,'v');const tip=`${row.label}\nh: ${String(row.height)} ${doc.heightUnit}\nu: ${String(row.u)} · v: ${String(row.v)} ${doc.unit}\n|V|: ${fmt(Math.hypot(row.u,row.v))} ${doc.unit}`;s.tip(mark,tip);s.tip(ring,tip);});
 // Two height callouts keep dense wind profiles readable; leaders identify
 // the exact measured endpoint, while every level retains its raw tooltip.
 const callouts=[],font=s.fs-3;
 for(const [i,row]of[rows[0],rows.at(-1)].entries()){
  const text=`h ${fmt(row.height)}`,width=text.length*font*.62,px=f.x(row.u),py=f.y(row.v),x=Math.max(f.left+5,Math.min(f.right-width-5,px+8));
  let y=Math.max(f.top+font+4,Math.min(f.bottom-5,py+(i?18:-10)));
  const previous=callouts[0];
  if(previous&&x<previous.x+previous.width+5&&x+width+5>previous.x&&Math.abs(y-previous.y)<font+7)y=previous.y+font+9<=f.bottom-5?previous.y+font+9:previous.y-font-9;
  callouts.push({x,y,width});
  const leader=s.line(px,py,x-2,y-font*.4,{stroke:s.theme.secondary,'stroke-width':.65,'data-mark':'hodograph-height-leader',...attrs(row)});
  s.reveal(leader,.4,.35);
  label(s,x,y,text,{'font-size':font,'data-mark':'hodograph-height-label','data-height':row.height,...attrs(row)},22);
 }
 const lx=f.right+12,h=Math.min(100,f.bottom-f.top);for(let i=0;i<32;i++)s.rect(lx,f.top+i*h/32,7,h/32+.2,{fill:shade(domain[1]-(domain[1]-domain[0])*i/31)});num(s,lx+10,f.top+4,fmt(domain[1]),{'font-size':s.fs-3});num(s,lx+10,f.top+h,fmt(domain[0]),{'font-size':s.fs-3});label(s,lx-2,f.top+h+15,doc.heightUnit,{'font-size':s.fs-3},10);}
function phasor(s,doc){const sum=phasor19(doc.data),f=equalFrame(s,[...doc.data.map(r=>[r.real,r.imag]),[sum.real,sum.imag]],{xlabel:`Re / ${doc.unit}`,ylabel:`Im / ${doc.unit}`});label(s,f.left,13,`${String(doc.frequency)} ${doc.frequencyUnit} · ${doc.phaseConvention.toUpperCase()}`,{'font-size':s.fs-2},55);doc.data.forEach((row,i)=>{const col=s.theme.objectColor(row,s.theme.color(i)),a=arrow(s,f.x(0),f.y(0),f.x(row.real),f.y(row.imag),col);s.add(p=>{const q=phase(p,i/doc.data.length*.3,.58);a.line.setAttribute('x2',f.x(row.real*q));a.line.setAttribute('y2',f.y(row.imag*q));});s.reveal(a.head,.48+i/doc.data.length*.26,.24);s.edit(a.line,row,'real');s.tip(a.line,tipComplex(row,doc));editableComplex(s,row,doc,f.x(row.real),f.y(row.imag),col,{delay:.35+i/doc.data.length*.2,mark:'phasor-endpoint'});label(s,f.x(row.real)+7,f.y(row.imag)-7,row.label,{fill:col,'font-size':s.fs-1},s.compact?10:24);});const result=arrow(s,f.x(0),f.y(0),f.x(sum.real),f.y(sum.imag),s.theme.accent,{dashed:true,mark:'phasor-resultant',width:2.1});s.add(p=>{const q=phase(p,.44,.46);result.line.setAttribute('x2',f.x(sum.real*q));result.line.setAttribute('y2',f.y(sum.imag*q));});s.reveal(result.head,.74,.2);s.tip(result.line,`ΣRe=${fmt(sum.real)}\nΣIm=${fmt(sum.imag)}\n|Σ|=${fmt(Math.hypot(sum.real,sum.imag))} ${doc.unit}`);label(s,f.x(sum.real)+7,f.y(sum.imag)+15,'Σ',{fill:s.theme.accent,'font-size':s.fs+2},2);}
function eyediagram(s,doc){const model=eye19(doc),f=frame(s,[0,2],measurementDomain(doc.data.map(r=>r.value),{padding:.12}),{xlabel:t19('窗内时间 / 符号周期','Within-window time / symbol period'),ylabel:doc.unit});s.line(f.x(1),f.top,f.x(1),f.bottom,{stroke:s.theme.secondary,'stroke-dasharray':'4 4'});model.traces.forEach((trace,i)=>{const path=s.path(d3.line().x(p=>f.x(p.phase)).y(p=>f.y(p.row.value))(trace.points),{stroke:s.theme.accent,'stroke-width':s.compact?.9:1.15,'stroke-opacity':.34,'data-mark':'eye-observed-trace','data-window':trace.window,'data-record-ids':JSON.stringify(trace.points.map(p=>p.row._id).filter(Boolean))});s.draw(path,i/model.traces.length*.38,.55);});model.points.forEach((p,i)=>{const mark=s.circle(f.x(p.phase),f.y(p.row.value),s.compact?1:1.4,{fill:s.theme.accent,'fill-opacity':.35,'data-mark':'eye-original-sample',...attrs(p.row),'data-original-time':p.row.time,'data-phase':p.phase});s.growCircle(mark,s.compact?1:1.4,i/model.points.length*.4,.48);s.edit(mark,p.row,'value');s.tip(mark,`${p.row.label}\nt: ${String(p.row.time)} ${doc.timeUnit}\n${String(p.row.value)} ${doc.unit}\nτ/T: ${fmt(p.phase)}`);});label(s,f.left,13,`T=${String(doc.symbolPeriod)} ${doc.timeUnit} · ${model.samplesPerSymbol} ${t19('采样/符号','samples/symbol')}`,{'font-size':s.fs-2},60);}
function constellation(s,doc){const groups=groups19(doc.data),f=equalFrame(s,doc.data.map(r=>[r.real,r.imag]),{top:groupTop(s,groups),xlabel:`I / ${doc.unit}`,ylabel:`Q / ${doc.unit}`});legend(s,groups);doc.data.forEach((row,i)=>editableComplex(s,row,doc,f.x(row.real),f.y(row.imag),color(s,row.group,groups.indexOf(row.group)),{delay:i/doc.data.length*.39,radius:s.compact?1.8:2.5,mark:'constellation-symbol'}));}
function campbell(s,doc){const modes=[...new Set(doc.data.map(r=>r.mode))],maxA=d3.max(doc.data,r=>r.amplitude)||1,xd=measurementDomain([0,...doc.data.map(r=>r.speed)],{padding:.03}),yd=measurementDomain([0,...doc.data.map(r=>r.frequency)],{padding:.08}),f=frame(s,[0,xd[1]],[0,yd[1]],{xlabel:'rpm',ylabel:'Hz'});s.legend(modes.map((m,i)=>({label:short(m,s.compact?9:22),color:color(s,m,i)})),s.compact?15:35,13);for(const order of doc.orders){const xmax=Math.min(xd[1],yd[1]*60/order),x1=f.x(0),x2=f.x(xmax),y1=f.y(0),y2=f.y(order*xmax/60);s.line(x1,y1,x2,y2,{stroke:s.theme.secondary,'stroke-dasharray':'4 5','stroke-width':.7,'data-mark':'campbell-order','data-order':order});label(s,x2-4,y2+12,`${order}×`,{'text-anchor':'end','font-size':s.fs-3},8);}modes.forEach((mode,j)=>{const rows=doc.data.filter(r=>r.mode===mode).sort((a,b)=>a.speed-b.speed),col=color(s,mode,j),path=s.path(d3.line().x(r=>f.x(r.speed)).y(r=>f.y(r.frequency))(rows),{stroke:col,'stroke-width':1.1,'stroke-opacity':.6,'data-mark':'campbell-branch'});s.draw(path,j*.06,.8);rows.forEach((row,i)=>{const x=f.x(row.speed),y=f.y(row.frequency),r=(s.compact?6:10)*Math.sqrt(row.amplitude/maxA),mark=row.amplitude===0?s.path(`M${x-2} ${y-2}L${x+2} ${y+2}M${x-2} ${y+2}L${x+2} ${y-2}`,{stroke:col,'stroke-width':1,'data-mark':'campbell-zero',...attrs(row)}):s.circle(x,y,r,{fill:col,'fill-opacity':.45,'data-mark':'campbell-amplitude',...attrs(row),'data-amplitude':row.amplitude});if(row.amplitude===0)s.reveal(mark,i/rows.length*.4,.4);else s.growCircle(mark,r,i/rows.length*.4,.45);s.edit(mark,row,'amplitude');s.tip(mark,`${row.mode}\n${String(row.speed)} rpm · ${String(row.frequency)} Hz\n${String(row.amplitude)} ${doc.unit}`);const point=s.circle(x,y,1.4,{fill:col,'data-mark':'campbell-frequency',...attrs(row)});s.growCircle(point,1.4,i/rows.length*.4,.45);s.edit(point,row,'frequency');s.tip(point,`${row.mode}\n${String(row.speed)} rpm · ${String(row.frequency)} Hz\n${String(row.amplitude)} ${doc.unit}`);});});}
export const volume19Renderers={bode,nyquist,nichols,polezero,smith,windrose,polarscatter,hodograph,phasor,eyediagram,constellation,campbell};
