// All examples are explicitly synthetic. Geography is separately attributed.
const str=(key,label)=>[key,'string',label],num=(key,label)=>[key,'number',label];
const time=[str('period','等间隔观测顺序'),num('value','原始测量值')];
const specs=[
 ['choropleth','地区填色地图','Country choropleth','comparison',[str('code','地图地区代码'),str('label','地区显示名称'),['value','number | null','比率或密度；null 保留缺测']],'用颜色深浅比较国家级比率或密度，未填地区保持缺测色。','地区渗透率、人口密度、跨国指标','用国土面积暗示数量；缺测补零','2–176 个地图覆盖地区；code 使用帮助中的 Natural Earth ADM0_A3 代码'],
 ['geomap','地区气泡地图','Geographic bubble map','comparison',[str('label','位置名称'),num('longitude','经度 / °'),num('latitude','纬度 / °'),num('value','非负规模值')],'地点由经纬度定位，气泡面积对应数量，共用世界底图。','地区销售规模、站点访问量、采样规模','用气泡半径代表数量；用偏移后的坐标冒充真实地点','1–120 个地点；经度 −180–180，纬度 −85–85，value ≥ 0'],
 ['splom','散点矩阵','Scatterplot matrix','distribution',[str('sample','样本标识'),str('variable','变量名称及单位'),num('value','原始测量值'),str('group','样本分组')],'同一批样本的多个变量两两配对，每个分面共用对应变量的尺度。','多变量探索、特征关系、实验指标检查','将相关当因果；混淆样本；逐格删除缺测造成样本不一致','2–5 个变量，3–80 个完整样本；每个样本 × 变量填写一行'],
 ['clusterheatmap','聚类热力图','Clustered heatmap','distribution',[str('row','行对象'),str('column','列指标'),num('value','同量纲测量值')],'用欧氏距离与平均连接聚类排列完整矩阵，树枝展示合并距离。','表达模式、同量纲指标比较、样本结构探索','不同量纲直接比较；把聚类看作显著性检验','2–24 行对象、2–12 列指标；矩阵完整，不自动标准化'],
 ['pcaloadings','PCA 载荷图','PCA correlation loadings','distribution',[str('variable','变量名称'),num('loading1','变量与 PC1 的相关系数'),num('loading2','变量与 PC2 的相关系数')],'箭头展示原变量与两个主成分的相关载荷；单位圆为相关系数边界。','已完成 PCA 的变量解释、变量方向与关联','输入样本得分或旋转矩阵；把箭头长短当解释方差','2–24 个变量；使用同一次 PCA 的相关载荷，每项平方和 ≤ 1'],
 ['acf','自相关图 ACF','Autocorrelation (ACF)','trend',time,'从等间隔原始序列计算各滞后相关，显示白噪声假设下的近似参考带。','时序依赖、周期探索、残差检查','非等间隔数据；有趋势却直接判定平稳；将参考带当模型区间','8–500 个非恒定连续观测；无缺测；最大滞后为 1–60 且小于样本数'],
 ['pacf','偏自相关图 PACF','Partial autocorrelation (PACF)','trend',time,'用未调整自协方差的 Yule–Walker 递推计算偏自相关。','自回归阶数探索、残差检查、时序依赖','混用不同 PACF 估计器；仅凭一张图选择模型','8–500 个非恒定连续观测；无缺测；最大滞后为 1–60 且小于样本数'],
 ['imr','单值移动极差图','Individuals & moving range','trend',[str('period','采集顺序'),num('value','原始测量值')],'上图显示原始观测，下图显示相邻差的绝对值；控制限由整段基线样本估计。','单次测量的过程监控、批次质量、设备稳定性','将控制限当规格限；混入不同过程；忽略时间依赖','4–300 个按顺序采集的单值；无缺测；移动极差至少有一个非零值']
];
export const volume10Catalog=specs.map(([id,name,en,category,fields,description,use,avoid,limit],i)=>({id,no:String(113+i),name,en,type:name,category:i>=2?'research':category,fields,description,use,avoid,limit,motion:'尺度建立 / 数据逐步展开 / 标记停留',keywords:`${name} ${en} ${use}`,edition:10,research:i>=2,dataMode:i===4?'analysis':'observations',duration:8}));
const timeData=Array.from({length:48},(_,i)=>({period:`${i+1}`,value:+(50+3*Math.sin(i*.57)+Math.cos(i*1.93)*1.7).toFixed(3)}));
const variables=['Length / mm','Mass / g','Width / mm'];
export const volume10Contents={
 choropleth:{title:'地区指标比较',subtitle:'合成比率数据 · 灰色地区未提供观测',unit:'%',data:[['USA','美国',68],['CAN','加拿大',74],['BRA','巴西',42],['GBR','英国',78],['FRA','法国',71],['DEU','德国',76],['IND','印度',38],['CHN','中国',65],['JPN','日本',81],['AUS','澳大利亚',73],['ZAF','南非',46]].map(([code,label,value])=>({code,label,value}))},
 geomap:{title:'站点访问规模',subtitle:'合成站点数据 · 气泡面积表示数量',unit:'千次',data:[['New York',-74.006,40.7128,68],['London',-.1276,51.5072,54],['Tokyo',139.6917,35.6895,82],['Sydney',151.2093,-33.8688,37],['Paris',2.3522,48.8566,45],['Singapore',103.8198,1.3521,63],['Cape Town',18.4241,-33.9249,24],['São Paulo',-46.6333,-23.5505,42]].map(([label,longitude,latitude,value])=>({label,longitude,latitude,value}))},
 splom:{title:'样本多变量关系',subtitle:'同一样本的原始观测 · 每个变量保留自己的单位',unit:'按变量',data:Array.from({length:26},(_,i)=>variables.map((variable,j)=>({sample:`S${String(i+1).padStart(2,'0')}`,variable,value:+([25+i*.65+Math.sin(i)*2,120+i*3+Math.cos(i*.8)*18,8+i*.13+Math.sin(i*.5)][j]).toFixed(2),group:i<13?'A':'B'}))).flat()},
 clusterheatmap:{title:'样本指标聚类',subtitle:'原始值 · 欧氏距离 · 平均连接 · 不标准化',unit:'mg/L',data:Array.from({length:10},(_,i)=>Array.from({length:6},(_,j)=>({row:`S${i+1}`,column:`M${j+1}`,value:+(4+(i<5?Math.sin(j*.7):Math.cos(j*.7))*2+Math.sin(i+j)*.55).toFixed(2)}))).flat()},
 pcaloadings:{title:'主成分变量载荷',subtitle:'输入已计算的相关载荷 · 非样本得分',unit:'相关系数',data:[['Length',.86,.25],['Mass',.78,.38],['Width',.65,-.54],['Density',-.38,.77],['Ratio',-.64,-.49]].map(([variable,loading1,loading2])=>({variable,loading1,loading2}))},
 acf:{title:'序列自相关',subtitle:'未调整自协方差 · 参考带 ±1.96/√n',unit:'原始测量单位',maxLag:16,data:timeData},
 pacf:{title:'序列偏自相关',subtitle:'Yule–Walker · 未调整自协方差',unit:'原始测量单位',maxLag:16,data:timeData},
 imr:{title:'过程单值与移动极差',subtitle:'整段样本估计基线 · 控制限不等于规格限',unit:'mL/min',data:Array.from({length:28},(_,i)=>({period:`${i+1}`,value:+(50+Math.sin(i*2.1)*2+Math.cos(i*.87)*1.1+(i===21?7:0)).toFixed(2)}))}
};
export const volume10English={
 choropleth:{description:'Country-level rates or densities use a continuous color scale. Regions without observations remain explicitly unmeasured.',use:'Regional penetration, population density and country comparisons',avoid:'Encoding totals with country area; replacing missing data with zero',limit:'2–176 supported regions. Join with the documented Natural Earth ADM0_A3 code.',rowMeaning:'Each row is one supported country code, its display name and the observed rate or density. A null value remains missing.'},
 geomap:{description:'Longitude and latitude locate each site; bubble area represents its nonnegative magnitude.',use:'Regional sales, site traffic and sampling scale',avoid:'Encoding quantity by radius or silently moving geographic coordinates',limit:'1–120 locations; longitude −180–180°, latitude −85–85°, value ≥ 0.',rowMeaning:'Each row is one location with decimal-degree longitude and latitude and its original magnitude.'},
 splom:{description:'Every variable pair shows the same complete samples; each variable retains one common domain across its panels.',use:'Multivariate exploration, feature relationships and experimental measurements',avoid:'Treating association as causation or silently deleting incomplete samples',limit:'2–5 variables, 3–80 complete samples; one row per sample × variable.',rowMeaning:'Each row is one sample measured on one variable. Repeat its sample identifier and group across every variable.'},
 clusterheatmap:{description:'An average-linkage hierarchy with Euclidean distance orders both axes. Original values are never standardized automatically.',use:'Expression patterns and comparable measurement profiles',avoid:'Combining incomparable units or treating clustering as a significance test',limit:'2–24 row objects and 2–12 column variables; complete numeric matrix required.',rowMeaning:'Each row is one row-object × column-variable cell. All cells must be explicitly supplied in a comparable unit.'},
 pcaloadings:{description:'Arrows encode correlations of original variables with PC1 and PC2. The unit circle bounds the correlations.',use:'Interpreting variables after a completed PCA',avoid:'Supplying sample scores, eigenvectors or loadings from different PCA fits',limit:'2–24 variables; squared correlation loadings sum to at most 1 for each variable.',rowMeaning:'Each row is one original variable and its correlations with PC1 and PC2 from the same fitted PCA.'},
 acf:{description:'Autocorrelations are computed from the centered, equally spaced raw sequence using one unadjusted covariance denominator.',use:'Serial dependence, periodicity and residual diagnostics',avoid:'Irregular sampling, unreported trends or interpreting reference bands as model intervals',limit:'8–500 nonconstant complete observations. maxLag is 1–60 and less than n.',rowMeaning:'Each row is one original, equally spaced observation, in acquisition order. Supply no aggregate correlation results.'},
 pacf:{description:'Yule–Walker recursion using unadjusted autocovariances calculates the partial autocorrelations.',use:'Exploring autoregressive order and residual serial dependence',avoid:'Mixing PACF estimators or choosing a model from this plot alone',limit:'8–500 nonconstant complete observations. maxLag is 1–60 and less than n.',rowMeaning:'Each row is one original, equally spaced observation, in acquisition order. Supply no aggregate correlation results.'},
 imr:{description:'The upper panel shows individuals and the lower panel successive absolute differences. All supplied observations estimate one baseline.',use:'Single-measurement process monitoring and batch quality',avoid:'Confusing control and specification limits or mixing different processes',limit:'4–300 complete ordered measurements; at least one nonzero successive difference.',rowMeaning:'Each row is one individual process measurement in acquisition order. The first moving range is undefined and is not replaced with zero.'}
};
