const field=(key,type,label)=>[key,type,label];
const xy=[field('x','number','横轴坐标'),field('y','number','纵轴坐标')];
const scalar=[field('label','string','类别'),field('value','number','非负数量')];
export const volume6Catalog=[
  {id:'donut',no:'49',name:'环形图',en:'Donut chart',type:'环形占比图',category:'composition',fields:scalar,description:'同一整体中的份额，以扇区角度表示。',use:'预算、来源、类别份额',avoid:'总量无意义；类别太多；使用负数',motion:'内环建立 / 扇区展开 / 份额标注',keywords:'环形 饼 占比 donut pie share',limit:'3–10 个唯一类别，非负且总量大于零'},
  {id:'circlepack',no:'50',name:'圆形打包图',en:'Packed circles',type:'等比例圆形打包图',category:'composition',fields:scalar,description:'圆面积对应数量，紧凑排列显示规模差异。',use:'类别规模、资产组成、对象数量',avoid:'需要按坐标读取数值；把圆间距离当成关系',motion:'圆心落位 / 面积展开 / 数值显现',keywords:'圆形 打包 气泡 面积 circle pack bubble',limit:'4–16 个唯一类别，数值大于零'},
  {id:'dendrogram',no:'51',name:'树状关系图',en:'Hierarchy tree',type:'两级树状关系图',category:'flow',fields:[field('parent','string','一级分类'),...scalar],description:'连线呈现分类归属，末端圆点面积表示子项数量。',use:'目录结构、组织分类、资源归属',avoid:'把分支距离当成相似度；多父节点网络',motion:'主干展开 / 分支延伸 / 叶节点显现',keywords:'树状 层级 目录 分支 tree dendrogram hierarchy',limit:'2–5 个父分类，每类 2–5 个子项，总计 6–18 个子项'},
  {id:'ternary',no:'52',name:'三元散点图',en:'Ternary plot',type:'三成分占比散点图',category:'distribution',fields:[field('label','string','对象'),field('group','string','分组'),field('a','number','第一成分占比'),field('b','number','第二成分占比'),field('c','number','第三成分占比')],description:'三角形内的位置同时表示三个成分，每条记录合计 100%。',use:'三部分构成、混合方案、成分分布',avoid:'三个指标不能相加；不同的分母',motion:'三角坐标建立 / 观测点落位 / 分组显现',keywords:'三元 三角 配比 成分 ternary composition',limit:'6–80 个对象，1–4 组；a+b+c=100；axes.a/b/c 注明三个成分'},
  {id:'contour',no:'53',name:'等值线图',en:'Contour field',type:'规则网格等值线图',category:'distribution',fields:[...xy,field('value','number','网格观测值')],description:'在完整规则网格上，以等值线呈现数值区域。',use:'空间强度、实验响应、连续数值场',avoid:'离散分类；缺失网格；把插值区域当成原始观测',motion:'网格建立 / 等值区域显现 / 原始采样点显现',keywords:'等值线 地形 场 强度 contour isoline surface',limit:'6–20 × 6–20 的完整等距网格；axes.x/y 注明坐标及单位'},
  {id:'hexbin',no:'54',name:'六边形分箱图',en:'Hexbin density',type:'原始样本六边形分箱图',category:'distribution',fields:[field('label','string','样本编号'),...xy],description:'将原始二维观测汇入固定六边形网格，色阶表示每格样本数。',use:'大量二维观测、重叠散点、样本密度',avoid:'把分箱中心当成每个样本的精确位置',motion:'坐标建立 / 六边形按频数显现 / 计数标注',keywords:'六边形 分箱 密度 hexbin density binning',limit:'20–600 个唯一样本；axes.x/y；binRadius 为 8–24 的固定分箱半径'},
  {id:'step',no:'55',name:'阶梯折线图',en:'Step series',type:'右连续阶梯折线图',category:'trend',fields:[field('period','YYYY-MM-DD','变更日期'),field('value','number | null','变更后数值')],description:'每次记录生效后保持数值，直到下次变更；缺失保留断点。',use:'库存、容量、状态量、分段固定价格',avoid:'本来连续变化的观测；应插值的数据',motion:'时间轴建立 / 阶梯展开 / 变更节点显现',keywords:'阶梯 变更 库存 step staircase',limit:'6–48 个唯一日期，至少两个有效观测；null 为缺失'},
  {id:'difference',no:'56',name:'差异面积图',en:'Difference area',type:'双序列差异面积图',category:'trend',fields:[field('period','YYYY-MM-DD','观测日期'),field('a','number','第一序列值'),field('b','number','第二序列值')],description:'两条折线之间的区域区分正负差异；交叉位置按线性插值计算。',use:'实际与基准、两组走势、差距变化',avoid:'两序列单位不同；不同统计口径',motion:'两条线同步展开 / 差异区域显现 / 末值标注',keywords:'差异 面积 基准 difference area comparison',limit:'6–48 个唯一日期；seriesLabels 为两个不同序列名称'},
  {id:'scatter3d',no:'57',name:'3D 散点图',en:'Spatial scatter',type:'三维坐标散点图',category:'spatial',dimension:'3d',fields:[field('label','string','对象'),field('group','string','分组'),...xy,field('z','number','第三维坐标')],description:'用三个实际坐标定位对象，可旋转观察遮挡关系。',use:'三指标关系、实验空间、三维观测',avoid:'把投影距离当成原始距离；第四指标未经说明映射球体',motion:'坐标框架建立 / 点位显现 / 视角落定',keywords:'3d 三维 空间 散点 spatial scatter',limit:'6–80 个唯一对象，1–4 组；axes.x/y/z 分别注明指标与单位'},
  {id:'bars3d',no:'58',name:'3D 网格柱图',en:'Spatial columns',type:'三维分类网格柱图',category:'spatial',dimension:'3d',fields:[field('row','string','行分类'),field('column','string','列分类'),field('value','number','非负数量')],description:'两组分类组成底面网格，所有柱高使用共同零基线。',use:'双分类数量、渠道与时期、区域与产品',avoid:'负值；需要极精确的平面长度比较',motion:'底面网格建立 / 柱体逐行生长 / 视角落定',keywords:'3d 三维 柱状 网格 bar column',limit:'3–6 行 × 3–6 列完整矩阵，非负且总量大于零'},
  {id:'surface3d',no:'59',name:'3D 曲面图',en:'Measured surface',type:'规则采样三维曲面图',category:'spatial',dimension:'3d',fields:[...xy,field('value','number','高度观测值')],description:'高度来自规则网格观测，三角面只在相邻采样点间线性连接。',use:'实验响应面、地形采样、空间数值场',avoid:'缺失采样；把面内插值当成实测值',motion:'采样网格展开 / 高度升起 / 曲面落定',keywords:'3d 三维 曲面 地形 surface mesh',limit:'4–16 × 4–16 的完整等距网格；axes.x/y/z 注明三个坐标含义'},
  {id:'trajectory3d',no:'60',name:'3D 轨迹图',en:'Spatial trajectory',type:'时间连接三维轨迹图',category:'spatial',dimension:'3d',fields:[field('period','YYYY-MM-DD','观测日期'),...xy,field('z','number','第三维坐标')],description:'按日期连接同一对象的三维观测，末端强调最新位置。',use:'三指标共同变化、空间运动记录、实验过程',avoid:'连线不代表回归关系；混入不同对象',motion:'坐标建立 / 路径按时间延伸 / 最新位置显现',keywords:'3d 三维 轨迹 路径 trajectory spatial',limit:'6–60 个唯一日期；axes.x/y/z 分别注明指标与单位'}
].map(t=>({...t,edition:6,duration:8}));

const date=i=>new Date(Date.UTC(2025,0,1+i*7)).toISOString().slice(0,10);
const round=v=>Math.round(v*10)/10;
const fieldGrid=(n,m)=>Array.from({length:n*m},(_,i)=>{const x=i%n,y=Math.floor(i/n);return{x,y,value:round(18+62*Math.exp(-((x-n*.37)**2+(y-m*.42)**2)/(n*.9))+32*Math.exp(-((x-n*.79)**2+(y-m*.72)**2)/(n*.6)))};});
const categories=['研究','写作','设计','拍摄','剪辑','发行'];
const values=[28,22,18,14,10,8];
export const volume6Contents={
  donut:{title:'内容制作预算占比',subtitle:'六类支出 · 合计 100 万元',unit:'万元',data:categories.map((label,i)=>({label,value:values[i]}))},
  circlepack:{title:'各类内容资料数量',subtitle:'圆面积表示资料份数',unit:'份',data:['研究','写作','设计','拍摄','剪辑','发行','翻译','访谈','归档'].map((label,i)=>({label,value:[128,96,84,67,52,43,34,27,18][i]}))},
  dendrogram:{title:'项目分类与子项数量',subtitle:'连线表示归属 · 圆面积表示子项数量',unit:'项',data:[['调研','文献',24],['调研','访谈',18],['调研','问卷',12],['制作','脚本',22],['制作','图形',16],['制作','影像',14],['交付','排版',8],['交付','校对',6],['交付','归档',5]].map(([parent,label,value])=>({parent,label,value}))},
  ternary:{title:'各项目的三类工时占比',subtitle:'每个项目合计 100%',unit:'%',axes:{a:'研究',b:'制作',c:'发行'},data:Array.from({length:30},(_,i)=>{const a=18+(i*17%49),b=12+(i*11%Math.max(15,80-a));return {label:`项目 ${i+1}`,group:['长文','影像','课程'][i%3],a,b,c:100-a-b};})},
  contour:{title:'展区采样声强分布',subtitle:'规则采样 · 等值区域由线性插值生成',unit:'dB',axes:{x:'横向距离 / 米',y:'纵向距离 / 米'},data:fieldGrid(14,10)},
  hexbin:{title:'阅读时长与完成率分布',subtitle:'360 个原始样本 · 固定分箱',unit:'人',axes:{x:'阅读时长 / 分钟',y:'完成阅读率 / %'},binRadius:14,data:Array.from({length:360},(_,i)=>{const a=i*2.3999632,rad=Math.sqrt(((i*67)%359+1)/360),g=i%3;return {label:`读者 ${i+1}`,x:round(4+g*3.8+Math.cos(a)*rad*2.7),y:round(35+g*18+Math.sin(a)*rad*24)};})},
  step:{title:'每周可用席位变更',subtitle:'变更后保持数值 · 缺失处断开',unit:'个',data:[32,32,48,48,40,40,64,64,52,52,52,72,72,60,60,80].map((value,i)=>({period:date(i),value}))},
  difference:{title:'实际阅读量与计划差距',subtitle:'两序列使用同一时间与数值尺度',unit:'千次',seriesLabels:['实际','计划'],data:Array.from({length:18},(_,i)=>({period:date(i),a:round(47+i*2.1+Math.sin(i*.63)*16),b:round(50+i*2+Math.sin(i*.3)*4)}))},
  scatter3d:{title:'内容项目三指标分布',subtitle:'每个点代表一个项目',unit:'原始量纲',axes:{x:'制作工时 / 小时',y:'阅读次数 / 千次',z:'完成阅读率 / %'},data:Array.from({length:36},(_,i)=>{const g=i%3,angle=i*2.3999632,r=Math.sqrt((i*11%35+1)/36);return {label:`项目 ${i+1}`,group:['长文','影像','课程'][g],x:round(20+g*17+Math.cos(angle)*r*13),y:round(25+g*18+Math.sin(angle)*r*22),z:round(42+g*14+Math.cos(angle*.73)*r*14)};})},
  bars3d:{title:'渠道与内容类型阅读量',subtitle:'柱高使用共同零点 · 底面表示两组分类',unit:'千次',data:['搜索','推荐','订阅','分享'].flatMap((row,i)=>['长文','教程','访谈','影像','课程'].map((column,j)=>({row,column,value:[[36,55,41,28,62],[52,79,46,64,43],[68,47,58,39,71],[29,38,22,56,34]][i][j]})))},
  surface3d:{title:'展区采样声强曲面',subtitle:'高度为实测点的模拟示例 · 面内为线性插值',unit:'dB',axes:{x:'横向距离 / 米',y:'纵向距离 / 米',z:'声强 / dB'},data:fieldGrid(12,10)},
  trajectory3d:{title:'内容指标的每周变化',subtitle:'同一内容系列 · 按日期连接观测点',unit:'原始量纲',axes:{x:'阅读时长 / 分钟',y:'完成阅读率 / %',z:'再次阅读率 / %'},data:Array.from({length:28},(_,i)=>({period:date(i),x:round(5+i*.2+Math.cos(i*.32)*2),y:round(45+i*.9+Math.sin(i*.32)*13),z:round(14+i*.65+Math.sin(i*.16)*7)}))}
};
