// These examples are deterministic synthetic observations, not actual subjects or measurements.
const str=(k,d)=>[k,'string',d],num=(k,d)=>[k,'number',d],nullable=(k,d)=>[k,'number | null',d];
const sample=[str('label','完整观测的唯一编号'),num('value','原始测量值；保留原单位')];
const specs=[
 ['lexis','Lexis年龄历时图','Lexis lifelines','research',[str('label','个体唯一编号'),str('group','个体分组'),num('entryPeriod','进入观察的日历年，可含小数'),num('entryAge','进入观察的年龄 / 年'),num('exitPeriod','离开观察的日历年')],'在日历时间与年龄坐标中保留每个个体的观察生命线，出生同期群对应平行斜线。','人群随访、年龄与时期结构、队列观察窗口','把端点当死亡事件；从线条数量直接推断风险率','3–60 个个体；进入年龄非负，退出晚于进入；时间与年龄均以年计'],
 ['swimmer','个体随访泳道图','Swimmer plot','research',[str('label','个体唯一编号'),str('group','个体分组'),num('start','开始时间'),num('end','最后已观察时间'),nullable('response','首次响应时间；没有响应时填 null'),num('ongoing','观察是否仍在继续：1 是，0 否')],'每条泳道保留一个个体的观察时长，菱形标记首次响应，箭头标记观察仍在继续。','试验随访、客户响应过程、个体项目历程','把继续箭头当未来时长预测；用空值伪造响应时间','3–24 个个体；结束晚于开始，响应必须在观察区间内'],
 ['eventhistory','多状态事件历程图','Event-history sequences','research',[str('label','状态区间的唯一编号'),str('subject','个体编号'),str('state','该区间的状态名称'),num('start','状态区间开始时间'),num('end','状态区间结束时间')],'以独立状态段呈现各个个体的过程历史，空档保留为空白，不自动连接或填补。','设备运行状态、客户旅程、个体多状态随访','将空档理解为某个状态；将同时发生的事件塞进互斥状态轨道','2–20 个体、最多 160 段、2–8 种状态；同一个体区间不能重叠'],
 ['recurrence','标量递归图','Scalar recurrence plot','research',[str('label','采样点唯一编号'),num('time','等间隔采样时间'),num('value','原始标量测量值')],'比较各时间点的原值距离，以阈值判定相似状态，展示周期结构及其改变。','信号重复结构、周期漂移、时间序列探索','将标量近邻等同于完整系统状态；据此直接声称混沌或因果关系','12–80 个等间隔采样点；threshold 是原值单位的非负距离；不做延迟嵌入'],
 ['weibull','Weibull概率图','Weibull probability plot','research',sample,'完整正寿命样本在对数寿命与 Weibull 概率坐标中展开，用于观察分布形状。','完整故障寿命、材料可靠性、分布诊断','输入删失寿命或零寿命；把视觉直线当参数估计或适配检验','5–300 条完整、未删失正观测；不拟合形状或尺度参数'],
 ['meanexcess','平均超额图','Mean-excess plot','research',sample,'展示超过不同阈值的观测还会平均超出多少，并显示每个阈值的有效超额样本量。','极端损失、峰值负荷、尾部分布探索','把少量尾部点当可靠外推；将探索曲线当分布拟合或置信区间','5–300 条有限观测；minExceedances 至少 2 且小于样本量'],
 ['ttt','总试验时间变换图','Total time on test','research',sample,'将完整寿命样本转为累计总试验时间份额，与累计失效份额比较。','可靠性寿命形状、风险率趋势探索','把经验曲线当风险率估计；混入删失记录或带权观测','5–300 条完整未删失正寿命；样本等权；对角线仅是指数分布参考'],
 ['spectrogram','时频功率谱图','Time-frequency spectrogram','research',[num('time','分析窗中心时间'),num('frequency','频率箱中心频率'),num('power','该时频单元的非负功率或功率谱密度')],'用同一连续色标显示预先计算的时间—频率功率矩阵，保留输入尺度与物理单位。','音频频率变化、设备振动、时频分析结果','把原始时域采样冒充功率矩阵；把功率与功率谱密度混用','3–48 个等距时间窗、3–32 个等距频率箱；完整矩阵最多 1500 单元，非负功率，缺测不能补零']
];
export const volume15Catalog=specs.map(([id,name,en,category,fields,description,use,avoid,limit],i)=>({id,no:String(153+i),name,en,type:name,category,fields,description,use,avoid,limit,motion:'生命线推进 / 状态段展开 / 概率路径描绘 / 时频单元显现',keywords:`${name} ${en} ${use}`,edition:15,dataMode:id==='spectrogram'?'analysis':'observations',research:true,duration:8}));
const lifetimes=Array.from({length:42},(_,i)=>({label:`L${String(i+1).padStart(2,'0')}`,value:+(85*Math.pow(-Math.log(1-(i+.7)/42.4),1/1.65)*(1+.025*Math.sin(i*2.2))).toFixed(3)}));
const sequences=['待机','运行','维护','运行','停机'];
export const volume15Contents={
 lexis:{title:'年龄与日历年的观察轨迹',subtitle:'确定性合成数据 · 每条线表示一个个体的实际观察窗口',unit:'年',data:Array.from({length:22},(_,i)=>({label:`P${String(i+1).padStart(2,'0')}`,group:['A','B','C'][i%3],entryPeriod:2012+(i%7)*.8,entryAge:18+(i*7)%37,exitPeriod:2020+(i%5)*.75}))},
 swimmer:{title:'每个个体的响应与随访',subtitle:'确定性合成数据 · 菱形为首次响应，箭头为仍在观察',unit:'月',data:Array.from({length:13},(_,i)=>{const start=i%3*.4,end=6.5+(12-i)*1.23;return{label:`P${String(i+1).padStart(2,'0')}`,group:i<7?'A':'B',start,end:+end.toFixed(2),response:i%4===0?null:+(start+2.1+i*.21).toFixed(2),ongoing:i%3===0?1:0};})},
 eventhistory:{title:'个体状态的完整历程',subtitle:'确定性合成数据 · 空白区间为没有输入记录的观察空档',unit:'小时',data:Array.from({length:9},(_,j)=>{let cursor=(j%3)*.6;return sequences.map((state,k)=>{const start=cursor,end=start+2.5+(j*3+k*5)%8*.55;cursor=end+(j===3&&k===1?2:0);return{label:`E${j+1}-${k+1}`,subject:`D${String(j+1).padStart(2,'0')}`,state,start:+start.toFixed(2),end:+end.toFixed(2)};});}).flat()},
 recurrence:{title:'信号中重复出现的状态',subtitle:'确定性合成信号 · 标量距离阈值，不做延迟嵌入',unit:'V',timeUnit:'s',threshold:.23,data:Array.from({length:60},(_,i)=>({label:`S${i+1}`,time:i*.2,value:+(Math.sin(i*.48)+.24*Math.sin(i*.15)+(i>36?.35:0)).toFixed(5)}))},
 weibull:{title:'完整寿命样本的 Weibull 诊断',subtitle:'确定性合成数据 · 未删失样本，只展示概率位置，不自动拟合',unit:'小时',data:lifetimes},
 meanexcess:{title:'超过阈值后还会超出多少',subtitle:'确定性合成数据 · 尾部样本量与平均超额共同展示',unit:'万元',minExceedances:5,data:Array.from({length:64},(_,i)=>({label:`C${i+1}`,value:+(18*Math.pow(1-(i+.5)/64.5,-.43)+2*Math.sin(i*.71)).toFixed(3)}))},
 ttt:{title:'寿命中的总试验时间份额',subtitle:'确定性合成数据 · 经验 TTT 变换，未删失且等权',unit:'小时',data:lifetimes},
 spectrogram:{title:'能量如何在时间与频率间移动',subtitle:'确定性合成功率矩阵 · 展示预计算结果，不从时域伪造频谱',unit:'V²/Hz',axes:{x:'时间 / s',y:'频率 / Hz'},data:Array.from({length:30},(_,i)=>Array.from({length:20},(_,j)=>{const time=i*.25,frequency=(j+1)*5,power=.03+1.3*Math.exp(-(((frequency-(18+i*1.8))/6)**2))+.75*Math.exp(-(((frequency-(78-i*.95))/9)**2))*(.6+.4*Math.cos(i*.2)**2);return{time,frequency,power:+power.toFixed(5)};})).flat()}
};
export const volume15English={
 lexis:{description:'Individual observed lifelines retain calendar period and attained age; equal birth cohorts follow parallel diagonals.',use:'Population follow-up, age-period structure and cohort observation windows',avoid:'Interpreting endpoints as deaths or line counts as incidence rates',limit:'3–60 individuals; nonnegative entry age, exit after entry. Calendar time and age both use years.',rowMeaning:'One row is one complete observed lifeline. Exit age equals entryAge + exitPeriod − entryPeriod.'},
 swimmer:{description:'Each lane preserves one individual’s observed duration, first-response diamond and continuation arrow.',use:'Trial follow-up, customer response and individual project trajectories',avoid:'Reading continuation arrows as future-duration predictions or inventing response dates',limit:'3–24 individuals; end > start. A response is null or lies within the observed interval; ongoing is 0 or 1.',rowMeaning:'One row is an individual with an observation window, optional first response and a continuation flag.'},
 eventhistory:{description:'Independent colored intervals retain each individual’s state history. Gaps stay blank without interpolation.',use:'Machine states, customer journeys and individual multistate follow-up',avoid:'Treating gaps as a state or putting simultaneous states on an exclusive-state track',limit:'2–20 individuals, up to 160 intervals and 2–8 states. Intervals for one individual cannot overlap.',rowMeaning:'One row is an observed state interval [start,end) for one individual; label identifies that interval.'},
 recurrence:{description:'A distance threshold compares original scalar values across sample times to expose repeated patterns and changes.',use:'Repeated signal patterns, periodic drift and time-series exploration',avoid:'Equating scalar neighbors with complete system states or inferring chaos or causality',limit:'12–80 equally spaced samples; threshold is a nonnegative distance in measurement units. No delay embedding is applied.',rowMeaning:'One row is one original scalar observation at a unique equally spaced sample time.'},
 weibull:{description:'Complete positive lifetimes unfold on log-lifetime and Weibull probability coordinates for shape inspection.',use:'Complete failure lifetimes, material reliability and distribution diagnostics',avoid:'Using censored or zero lifetimes, or treating apparent straightness as parameter estimation or a fit test',limit:'5–300 complete, uncensored positive observations. No shape or scale parameters are fitted.',rowMeaning:'One row is one original complete lifetime. Every observation is retained, including ties.'},
 meanexcess:{description:'At each threshold, show the mean excess among strictly exceeding observations and the number of exceedances.',use:'Extreme losses, peak loads and exploratory tail analysis',avoid:'Extrapolating sparse tails or treating the curve as a fitted distribution or confidence interval',limit:'5–300 finite observations. minExceedances must be at least 2 and below the sample size.',rowMeaning:'One row is one complete original observation. Threshold means are derived from the full sample.'},
 ttt:{description:'Complete lifetimes become normalized total time on test, plotted against the cumulative failure fraction.',use:'Lifetime shape and exploratory hazard-trend inspection',avoid:'Treating the curve as a hazard-rate estimate or mixing censored or weighted observations',limit:'5–300 complete uncensored positive lifetimes with equal weights. The diagonal is an exponential-distribution reference.',rowMeaning:'One row is one original complete lifetime. All lifetimes contribute to the total-time denominator.'},
 spectrogram:{description:'A single continuous color scale displays precomputed time-frequency power while preserving physical units.',use:'Audio frequency changes, machine vibrations and time-frequency analysis results',avoid:'Presenting time-domain samples as spectral power or mixing power with power spectral density',limit:'3–48 equally spaced time centers and 3–32 equally spaced frequency centers; complete nonnegative power matrix with at most 1500 cells. Missing cells cannot be zero-filled.',rowMeaning:'One row is one time-frequency bin, with center coordinates and externally calculated power or power spectral density.'}
};
const englishFields={lexis:['Unique individual label','Individual group','Calendar entry year, including fractions','Age at entry / years','Calendar exit year'],swimmer:['Unique individual label','Individual group','Observed start time','Last observed time','First response time; null means no recorded response','Observation continues: 1 yes, 0 no'],eventhistory:['Unique observed interval label','Individual identifier','State during this interval','Observed interval start','Observed interval end'],recurrence:['Unique original sample label','Equally spaced sampling time','Original scalar measurement'],weibull:['Unique complete observation label','Original positive complete lifetime'],meanexcess:['Unique complete observation label','Original measurement in its declared unit'],ttt:['Unique complete observation label','Original positive complete lifetime'],spectrogram:['Analysis-window center time','Frequency-bin center','Nonnegative precomputed power or power spectral density']};
for(const t of volume15Catalog)volume15English[t.id].fields=t.fields.map(([k,type],i)=>[k,type,englishFields[t.id][i]]);
