import {populationId} from './data-identity.js';
import * as d3 from 'd3';
import {measurementDomain} from './axis-policy.js';
import {phase7 as phase,number7 as fmt,num7 as num,label7 as label,short7 as short} from './volume7-utils.js';
import {t17,groups17,boxen17,sina17,rootogram17,ecdfBand17,qqCompare17,worm17,spreadLevel17,scaleLocation17,cook17,addedVariable17,componentResidual17} from './volume17-data.js';
const col=(s,name,i)=>s.theme.groupColor?.(name,s.theme.color(i))??s.theme.color(i),record=row=>({'data-record-id':row._id}),pct=v=>`${fmt(v*100)}%`;
function axes(s,xd,yd,{left=s.compact?42:56,right=s.w-20,top=39,bottom=s.h-43,xlabel='',ylabel='',xf=fmt,yf=fmt,square=false,parent}={}){
 if(square){const side=Math.min(right-left,bottom-top),cx=(left+right)/2,cy=(top+bottom)/2;left=cx-side/2;right=cx+side/2;top=cy-side/2;bottom=cy+side/2;}
 const x=d3.scaleLinear(xd,[left,right]),y=d3.scaleLinear(yd,[bottom,top]);
 for(const v of x.ticks(s.compact?3:5)){s.line(x(v),bottom,x(v),bottom+4,{'stroke-width':.65},parent);num(s,x(v),bottom+17,xf(v),{'text-anchor':'middle','font-size':s.fs-2},parent);}
 for(const v of y.ticks(s.compact?3:4)){s.line(left,y(v),right,y(v),{'stroke-width':.55,'stroke-dasharray':'2 5'},parent);num(s,left-7,y(v)+3,yf(v),{'text-anchor':'end','font-size':s.fs-2},parent);}
 s.line(left,bottom,right,bottom,{'stroke-width':.7},parent);label(s,left,top-12,ylabel,{'font-size':s.fs-2},s.compact?31:70,parent);label(s,right,bottom+33,xlabel,{'text-anchor':'end','font-size':s.fs-2},s.compact?32:70,parent);return{x,y,left,right,top,bottom};
}
function zeros(s,f){if(f.x.domain()[0]<=0&&f.x.domain()[1]>=0)s.line(f.x(0),f.top,f.x(0),f.bottom,{stroke:s.theme.secondary,'stroke-width':.7});if(f.y.domain()[0]<=0&&f.y.domain()[1]>=0)s.line(f.left,f.y(0),f.right,f.y(0),{stroke:s.theme.secondary,'stroke-width':.8});}
function dot(s,row,x,y,{color=s.theme.accent,field='value',r=s.compact?2.6:3.5,delay=0,mark='',tip='',attrs={},parent}={}){const m=s.circle(x,y,r,{fill:color,'fill-opacity':.76,stroke:s.theme.bg,'stroke-width':.65,'data-mark':mark,...record(row),...attrs},parent);s.growCircle(m,r,delay,.55);s.edit(m,row,field);s.tip(m,tip);return m;}
function caption(s,value){label(s,12,s.h-2,value,{'font-size':s.fs-3},s.compact?47:105);}
function rawRug(s,rows,x,y,{color=s.theme.fg,field='value',vertical=false,delay=.3,parent}={}){rows.forEach((row,i)=>{const px=x(row[field]),m=vertical?s.line(y,px,y+4,px,{stroke:color,'stroke-width':1,'stroke-opacity':.5,'data-mark':'diagnostic-raw',...record(row)},parent):s.line(px,y,px,y+4,{stroke:color,'stroke-width':1,'stroke-opacity':.5,'data-mark':'diagnostic-raw',...record(row)},parent);s.reveal(m,delay+i/rows.length*.2,.3);s.edit(m,row,field);s.tip(m,`${row.label}${row.group?' · '+row.group:''}\n${field}: ${String(row[field])} ${s.doc.unit}`);});}
function boxen(s,doc){
 const model=boxen17(doc.data),left=s.compact?43:56,right=s.w-17,top=38,bottom=s.h-34,y=d3.scaleLinear(measurementDomain(doc.data.map(r=>r.value),{padding:.08}),[bottom,top]),step=(right-left)/model.length;
 y.ticks(4).forEach(v=>{s.line(left,y(v),right,y(v),{'stroke-width':.6,'stroke-dasharray':'2 5'});num(s,left-7,y(v)+3,fmt(v),{'text-anchor':'end','font-size':s.fs-2});});
 model.forEach((g,i)=>{const cx=left+(i+.5)*step,color=col(s,g.group,i),maxW=Math.min(step*.58,s.compact?42:68);[...g.intervals].reverse().forEach((level,j)=>{const width=maxW*level.width,lo=y(level.low),hi=y(level.high),m=s.rect(cx-width/2,hi,width,lo-hi,{fill:d3.interpolateRgb(s.theme.bg,color)(.18+(g.intervals.length-level.level)*.15),stroke:color,'stroke-width':.8,'data-mark':'boxen-interval','data-low':level.low,'data-high':level.high,'data-tail-probability':level.p,'data-group':g.group});s.add(p=>{const q=phase(p,i*.045+j*.055,.62);m.setAttribute('height',(lo-hi)*q);m.setAttribute('y',y(g.median)+(hi-y(g.median))*q);});s.tip(m,`${g.group}\n${pct(level.p)} – ${pct(1-level.p)}\n[${fmt(level.low)}, ${fmt(level.high)}] ${doc.unit}\nn=${g.samples.length}\n${t17('样本分位区间，非置信区间','Sample quantile interval, not a confidence interval')}`);});
  const median=s.line(cx-maxW/2,y(g.median),cx+maxW/2,y(g.median),{stroke:color,'stroke-width':2,'data-mark':'boxen-median','data-value':g.median});s.reveal(median,.38+i*.06,.4);s.tip(median,`${g.group} · ${t17('中位数','Median')}: ${fmt(g.median)} ${doc.unit}`);
  g.samples.forEach((row,j)=>dot(s,row,cx+step*.36+(j%3-1)*1.5,y(row.value),{color,field:'value',r:s.compact?1.05:1.4,delay:.12+j/g.samples.length*.4,mark:'boxen-raw',tip:`${row.label} · ${g.group}\n${String(row.value)} ${doc.unit}`}));label(s,cx,bottom+18,g.group,{'text-anchor':'middle',fill:color,'font-size':s.fs-1},s.compact?8:18);
 });label(s,left,14,`${t17('逐层尾部分位 · 全部原值','Nested tail quantiles · all observations')} / ${doc.unit}`,{'font-size':s.fs-2},s.compact?44:90);
}
function sina(s,doc){
 const model=sina17(doc),left=s.compact?44:58,right=s.w-17,top=38,bottom=s.h-35,step=(right-left)/model.curves.length,y=d3.scaleLinear(measurementDomain(doc.data.map(r=>r.value),{padding:.08}),[bottom,top]),width=step*.34;
 y.ticks(4).forEach(v=>{s.line(left,y(v),right,y(v),{'stroke-width':.55,'stroke-dasharray':'2 5'});num(s,left-7,y(v)+3,fmt(v),{'text-anchor':'end','font-size':s.fs-2});});
 model.curves.forEach((g,i)=>{const cx=left+(i+.5)*step,color=col(s,g.group,i),sorted=[...g.points].sort((a,b)=>a.row.value-b.row.value),shape=s.path(d3.area().y(p=>y(p.row.value)).x0(p=>cx-p.density/model.max*width).x1(p=>cx+p.density/model.max*width).curve(d3.curveMonotoneY)(sorted),{fill:color,'fill-opacity':.065,stroke:color,'stroke-width':.7,'stroke-opacity':.22,'data-mark':'sina-envelope'});s.reveal(shape,i*.07,.7);
  g.points.forEach((p,j)=>{const px=cx+p.jitter*p.density/model.max*width,m=dot(s,p.row,px,y(p.row.value),{color,delay:.06+j/g.points.length*.4,mark:'sina-observation',attrs:{'data-value':p.row.value,'data-density':p.density},tip:`${p.row.label} · ${g.group}\n${String(p.row.value)} ${doc.unit}\n${t17('密度','Density')}: ${fmt(p.density)}\nh=${String(doc.bandwidth)}`});s.add(progress=>m.setAttribute('cx',cx+(px-cx)*phase(progress,.08+i*.03,.65)));});label(s,cx,bottom+18,`${g.group} · n=${g.samples.length}`,{'text-anchor':'middle',fill:color,'font-size':s.fs-2},s.compact?13:24);
 });label(s,left,14,`${t17('原值不动 · 共享密度宽度','Exact values · shared density width')} · h=${fmt(doc.bandwidth)}`,{'font-size':s.fs-2},s.compact?47:95);
}
function rootogram(s,doc){
 const model=rootogram17(doc),yd=measurementDomain([0,...model.flatMap(m=>[m.expectedRoot,m.difference])],{padding:.12}),left=s.compact?43:56,right=s.w-17,top=39,bottom=s.h-43,step=(right-left)/model.length,y=d3.scaleLinear(yd,[bottom,top]),x=i=>left+(i+.5)*step;
 y.ticks(4).forEach(v=>{s.line(left,y(v),right,y(v),{'stroke-width':.55,'stroke-dasharray':'2 5'});num(s,left-7,y(v)+3,fmt(v),{'text-anchor':'end','font-size':s.fs-2});});s.line(left,y(0),right,y(0),{stroke:s.theme.fg,'stroke-width':1.1});
 model.forEach((m,i)=>{const color=s.theme.objectColor(m.row._id,s.theme.accent),xx=x(i)-step*.37,yy=y(m.expectedRoot),height=y(m.difference)-yy,bar=s.rect(xx,yy,step*.74,height,{fill:color,'fill-opacity':.27,stroke:color,'stroke-width':.8,'data-mark':'rootogram-observed','data-observed':m.row.observed,'data-expected':m.row.expected,'data-difference':m.difference});s.add(p=>bar.setAttribute('height',height*phase(p,i/model.length*.25,.6)));s.edit(bar,m.row,'observed');s.tip(bar,`${m.row.label}\n${t17('观察','Observed')}: ${String(m.row.observed)}\n${t17('期望','Expected')}: ${String(m.row.expected)}\n√E−√O: ${fmt(m.difference)}`);const expected=dot(s,m.row,x(i),yy,{color:s.theme.fg,field:'expected',r:2.1,delay:.2+i/model.length*.25,mark:'rootogram-expected',tip:`${m.row.label}\nexpected: ${String(m.row.expected)}\n${doc.modelName}`});if(m.row.observed===0){const zero=s.line(xx,yy,xx+step*.74,yy,{stroke:color,'stroke-width':3,'data-mark':'rootogram-zero'});s.edit(zero,m.row,'observed');s.tip(zero,`${m.row.label}\nobserved: 0`);s.reveal(zero,.2,.6);}if(model.length<=12||i%Math.ceil(model.length/10)===0)label(s,x(i),bottom+18,m.row.label,{'text-anchor':'middle','font-size':s.fs-2},s.compact?5:10);});
 const curve=s.path(d3.line().x(m=>x(m.index)).y(m=>y(m.expectedRoot))(model),{stroke:s.theme.fg,'stroke-width':1.5,'data-mark':'rootogram-curve'});s.draw(curve,.08,.72);label(s,left,14,t17('柱底=√期望−√观察 · 零线为完全匹配','Bar bottom = √expected−√observed · zero = exact match'),{'font-size':s.fs-2},s.compact?49:98);caption(s,t17('悬挂柱高=√观察频数 · 外部模型期望','Hanging height = √observed count · external model expectations'));
}
function ecdfband(s,doc){const populationColor=s.theme.objectColor(populationId('sample-group',doc.data),s.theme.accent);
 const model=ecdfBand17(doc),xd=measurementDomain(doc.data.map(r=>r.value),{padding:.06}),points=[{value:xd[0],p:0,low:0,high:Math.min(1,model.epsilon)},...model.points,{value:xd[1],p:1,low:Math.max(0,1-model.epsilon),high:1}],f=axes(s,xd,[0,1],{bottom:s.h-59,xlabel:doc.unit,ylabel:t17('累计概率','Cumulative probability'),yf:pct}),g=s.group();
 const area=s.path(d3.area().x(p=>f.x(p.value)).y0(p=>f.y(p.low)).y1(p=>f.y(p.high)).curve(d3.curveStepAfter)(points),{fill:populationColor,'fill-opacity':.13,'data-mark':'dkw-band','data-epsilon':model.epsilon},g);s.tip(area,`${t17('DKW 同时置信带','DKW simultaneous confidence band')}\n1−α=${pct(1-doc.alpha)}\nε=${fmt(model.epsilon)}\nn=${model.n}`);for(const key of['low','high'])s.path(d3.line().x(p=>f.x(p.value)).y(p=>f.y(p[key])).curve(d3.curveStepAfter)(points),{stroke:populationColor,'stroke-width':.8,'stroke-dasharray':'3 3'},g);const line=s.path(d3.line().x(p=>f.x(p.value)).y(p=>f.y(p.p)).curve(d3.curveStepAfter)(points),{stroke:s.theme.fg,'stroke-width':1.8,'data-mark':'dkw-ecdf'},g);s.clipReveal(g,f.left-1,f.top-1,f.right-f.left+2,f.bottom-f.top+2,.05,.78);
 model.points.forEach(p=>{const dot=s.circle(f.x(p.value),f.y(p.p),2,{fill:s.theme.fg,'data-mark':'dkw-step','data-value':p.value,'data-cdf':p.p},g);s.tip(dot,`${String(p.value)} ${doc.unit}\nFn: ${fmt(p.p)}\n[${fmt(p.low)}, ${fmt(p.high)}]`);});rawRug(s,doc.data,f.x,f.bottom+5);label(s,f.right,14,`${pct(1-doc.alpha)} DKW · n=${model.n}`,{'text-anchor':'end',fill:s.theme.fg,'font-size':s.fs-2},40);caption(s,t17('独立同分布假设 · 整条分布的同时带','IID assumption · simultaneous band for the entire CDF'));
}
function qqcompare(s,doc){
 const model=qqCompare17(doc),domain=measurementDomain(doc.data.map(r=>r.value),{padding:.10}),f=axes(s,domain,domain,{square:true,top:41,right:s.w-28,bottom:s.h-44,xlabel:`${model.groups[0]} / ${doc.unit}`,ylabel:`${model.groups[1]} / ${doc.unit}`});s.line(f.left,f.bottom,f.right,f.top,{stroke:s.theme.secondary,'stroke-dasharray':'4 4'});
 const path=s.path(d3.line().x(p=>f.x(p.x)).y(p=>f.y(p.y))(model.points),{stroke:s.theme.accent,'stroke-width':1.4,'stroke-opacity':.65,'data-mark':'two-sample-qq-line'});s.draw(path,.06,.75);model.points.forEach((p,i)=>{const mark=s.circle(f.x(p.x),f.y(p.y),s.compact?2.2:3,{fill:s.theme.accent,'data-mark':'two-sample-qq-point','data-quantile':p.p,'data-x':p.x,'data-y':p.y});s.growCircle(mark,s.compact?2.2:3,i/model.points.length*.38,.45);s.tip(mark,`p=${pct(p.p)}\n${model.groups[0]}: ${fmt(p.x)} ${doc.unit}\n${model.groups[1]}: ${fmt(p.y)} ${doc.unit}\n${t17('派生分位点，非观测配对','Derived quantiles, not observed pairs')}`);});rawRug(s,model.samples[0],f.x,f.bottom+4,{color:col(s,model.groups[0],0)});rawRug(s,model.samples[1],f.y,f.right+4,{color:col(s,model.groups[1],1),vertical:true});label(s,s.w-15,14,`n=${model.samples[0].length} / ${model.samples[1].length} · y=x`,{'text-anchor':'end','font-size':s.fs-2},45);
}
function worm(s,doc){
 const groups=worm17(doc),cols=groups.length===1?1:2,nrows=Math.ceil(groups.length/cols),outer=11,gap=15,tw=(s.w-outer*2-gap*(cols-1))/cols,th=(s.h-35-gap*(nrows-1))/nrows,xmax=Math.max(1,d3.max(groups,g=>d3.max(g.points,p=>Math.abs(p.theoretical))))*1.06,ymax=Math.max(.15,d3.max(groups,g=>d3.max(g.points,p=>Math.abs(p.deviation))))*1.15;
 groups.forEach((g,i)=>{const xx=outer+(i%cols)*(tw+gap),yy=18+Math.floor(i/cols)*(th+gap),left=xx+(s.compact?29:37),right=xx+tw-6,top=yy+16,bottom=yy+th-24,x=d3.scaleLinear([-xmax,xmax],[left,right]),y=d3.scaleLinear([-ymax,ymax],[bottom,top]),color=col(s,g.group,i);s.rect(xx,yy-2,tw,th,{fill:'none',stroke:s.theme.line,'stroke-width':.65});label(s,xx+6,yy+9,`${g.group} · n=${g.points.length}`,{fill:color,'font-size':s.fs-2},s.compact?18:30);for(const v of y.ticks(3)){s.line(left,y(v),right,y(v),{'stroke-width':.5,'stroke-dasharray':'2 4'});num(s,left-4,y(v)+3,fmt(v),{'text-anchor':'end','font-size':s.fs-3});}for(const v of[-2,0,2].filter(v=>Math.abs(v)<=xmax))num(s,x(v),bottom+14,v,{'text-anchor':'middle','font-size':s.fs-3});s.line(left,y(0),right,y(0),{stroke:s.theme.secondary,'stroke-width':.9});const line=s.path(d3.line().x(p=>x(p.theoretical)).y(p=>y(p.deviation))(g.points),{stroke:color,'stroke-width':1.1,'stroke-opacity':.55,'data-mark':'worm-curve','data-group':g.group});s.draw(line,i*.06,.73);
  g.points.forEach((p,j)=>dot(s,p.row,x(p.theoretical),y(p.deviation),{color,field:'stdResidual',r:s.compact?1.8:2.6,delay:i*.035+j/g.points.length*.28,mark:'worm-residual',attrs:{'data-theoretical':p.theoretical,'data-deviation':p.deviation},tip:`${p.row.label} · ${g.group}\nr: ${String(p.row.stdResidual)}\nΦ⁻¹(p): ${fmt(p.theoretical)}\nΔ: ${fmt(p.deviation)}`}));
 });label(s,12,10,t17('X：正态分位 · Y：残差−正态分位','X: normal quantile · Y: residual minus normal quantile'),{'font-size':s.fs-3},s.compact?48:100);
}
function spreadlevel(s,doc){
 const model=spreadLevel17(doc),groups=model.points.map(p=>p.group),rugHeight=groups.length*5+16,f=axes(s,measurementDomain(model.points.map(p=>p.x),{padding:.15}),measurementDomain(model.points.map(p=>p.y),{padding:.2}),{top:42,bottom:s.h-51-rugHeight,xlabel:t17('log₁₀ 中位数','log₁₀ median'),ylabel:t17('log₁₀ IQR','log₁₀ IQR')}),xd=f.x.domain(),g=s.group(),clip=s.el('clipPath',{id:`${s.id}-spread-clip`},s.defs);s.rect(f.left,f.top,f.right-f.left,f.bottom-f.top,{},clip);g.setAttribute('clip-path',`url(#${s.id}-spread-clip)`);
 const fit=s.line(f.x(xd[0]),f.y(model.fit.predict(xd[0])),f.x(xd[1]),f.y(model.fit.predict(xd[1])),{stroke:s.theme.secondary,'stroke-width':1.2,'stroke-dasharray':'4 4','data-mark':'spread-level-fit','data-slope':model.fit.slope},g);s.reveal(fit,.15,.55);
 model.points.forEach((p,i)=>{const color=col(s,p.group,i),mark=s.circle(f.x(p.x),f.y(p.y),s.compact?4:5,{fill:color,'data-mark':'spread-level-group','data-median':p.median,'data-iqr':p.iqr,'data-group':p.group});s.growCircle(mark,s.compact?4:5,i*.06,.55);s.tip(mark,`${p.group}\n${t17('中位数','Median')}: ${fmt(p.median)} ${doc.unit}\nIQR: ${fmt(p.iqr)} ${doc.unit}\nn=${p.rows.length}\n${t17('组摘要，非单个观测','Group summary, not one observation')}`);const name=label(s,f.x(p.x)+6,f.y(p.y)-6,p.group,{fill:color,'font-size':s.fs-2},s.compact?8:14);s.reveal(name,.2+i*.04,.4);});
 const rugX=d3.scaleLinear(measurementDomain(doc.data.map(r=>r.value)),[f.left,f.right]),base=s.h-rugHeight;model.points.forEach((g,i)=>rawRug(s,g.rows,rugX,base+i*5,{color:col(s,g.group,i)}));label(s,f.left,s.h-3,`${t17('短线：全部原始值，独立横轴','Rugs: all original values, separate X axis')} / ${doc.unit}`,{'font-size':s.fs-3},s.compact?47:95);label(s,s.w-15,14,`${t17('描述性 OLS 斜率','Descriptive OLS slope')} = ${fmt(model.fit.slope,{significantDigits:3})}`,{'text-anchor':'end','font-size':s.fs-2},55);
}
function scalelocation(s,doc){
 const population=populationId('sample-group',doc.data),populationColor=fallback=>s.theme.objectColor(population,fallback);
 const points=scaleLocation17(doc),yd=measurementDomain([0,...points.map(p=>p.y)],{zero:true,padding:0}),f=axes(s,measurementDomain(points.map(p=>p.x)),[0,yd[1]*1.13||1],{xlabel:t17('模型拟合值','Model fitted value'),ylabel:'√|r|'});
 points.forEach((p,i)=>dot(s,p.row,f.x(p.x),f.y(p.y),{color:populationColor(s.theme.accent),field:'stdResidual',delay:i/points.length*.4,mark:'scale-location-point',attrs:{'data-fitted':p.x,'data-sqrt-absolute':p.y},tip:`${p.row.label}\nfitted: ${String(p.row.fitted)}\nr: ${String(p.row.stdResidual)}\n√|r|: ${fmt(p.y)}\n${doc.modelName}`}));label(s,s.w-15,14,t17('内部标准化残差 · 未添加平滑拟合','Internal standardized residuals · no smoother'),{'text-anchor':'end','font-size':s.fs-3},s.compact?48:85);
}
function residualleverage(s,doc){
 const population=populationId('sample-group',doc.data),populationColor=fallback=>s.theme.objectColor(population,fallback);
 const hmax=Math.min(1-Number.EPSILON/2,Math.max(.08,d3.max(doc.data,r=>r.leverage)*1.16)),rmax=Math.max(2.5,d3.max(doc.data,r=>Math.abs(r.stdResidual))*1.2),f=axes(s,[0,hmax],[-rmax,rmax],{xlabel:t17('杠杆 h','Leverage h'),ylabel:t17('内部标准化残差 r','Internal standardized residual r')}),clip=s.el('clipPath',{id:`${s.id}-cook-contours`},s.defs);s.rect(f.left,f.top,f.right-f.left,f.bottom-f.top,{},clip);const g=s.group({'clip-path':`url(#${s.id}-cook-contours)`});zeros(s,f);
 for(const D of[.5,1])for(const sign of[-1,1]){const start=D*doc.parameterCount/(rmax*rmax+D*doc.parameterCount);if(start>=hmax)continue;const pts=Array.from({length:81},(_,i)=>{const h=start+(hmax-start)*i/80;return{h,r:sign*Math.sqrt(D*doc.parameterCount*(1-h)/h)};});const line=s.path(d3.line().x(p=>f.x(p.h)).y(p=>f.y(p.r))(pts),{stroke:s.theme.accent,'stroke-width':.8,'stroke-opacity':.55,'stroke-dasharray':'4 4','data-mark':'cook-contour','data-distance':D},g);s.reveal(line,.05,.55);label(s,f.right-4,f.y(pts.at(-1).r)+(sign>0?-5:11),`D=${D}`,{'text-anchor':'end',fill:s.theme.accent,'font-size':s.fs-3},12,g);}
 doc.data.forEach((row,i)=>{const D=cook17(row,doc.parameterCount);dot(s,row,f.x(row.leverage),f.y(row.stdResidual),{field:'stdResidual',color:populationColor(D>4/doc.data.length?s.theme.accent:s.theme.fg),r:s.compact?2.8:3.6,delay:i/doc.data.length*.4,mark:'residual-leverage-point',attrs:{'data-leverage':row.leverage,'data-cook':D},tip:`${row.label}\nh: ${String(row.leverage)}\nr: ${String(row.stdResidual)}\nCook D: ${fmt(D)}\np=${doc.parameterCount}`});});label(s,s.w-15,14,`n=${doc.data.length} · p=${doc.parameterCount} · ${t17('Cook 等值线','Cook contours')}`,{'text-anchor':'end','font-size':s.fs-2},55);
}
function cooksdistance(s,doc){
 const population=populationId('sample-group',doc.data),populationColor=fallback=>s.theme.objectColor(population,fallback);
 const values=doc.data.map((row,index)=>({row,index:index+1,D:cook17(row,doc.parameterCount)})),threshold=4/doc.data.length,max=Math.max(threshold,d3.max(values,p=>p.D))*1.18,f=axes(s,[.4,values.length+.6],[0,max],{xlabel:t17('原始观测序号','Original observation index'),ylabel:'Cook D',xf:v=>Number.isInteger(v)?String(v):''}),topLabels=[...values].sort((a,b)=>b.D-a.D).slice(0,3);
 s.line(f.left,f.y(threshold),f.right,f.y(threshold),{stroke:s.theme.secondary,'stroke-width':.9,'stroke-dasharray':'4 4','data-mark':'cook-reference','data-reference':threshold});label(s,f.right,f.y(threshold)-5,'4/n',{'text-anchor':'end','font-size':s.fs-3},10);
 values.forEach((p,i)=>{const color=populationColor(p.D>threshold?s.theme.accent:s.theme.fg),stem=s.line(f.x(p.index),f.y(0),f.x(p.index),f.y(p.D),{stroke:color,'stroke-width':s.compact?1.1:1.4,'data-mark':'cook-stem','data-distance':p.D});s.add(progress=>stem.setAttribute('y2',f.y(p.D*phase(progress,i/values.length*.3,.6))));s.edit(stem,p.row,'stdResidual');s.tip(stem,`${p.row.label}\nh: ${String(p.row.leverage)}\nr: ${String(p.row.stdResidual)}\nCook D: ${fmt(p.D)}`);const mark=dot(s,p.row,f.x(p.index),f.y(p.D),{color,field:'leverage',r:2.1,delay:.1+i/values.length*.3,mark:'cook-observation',tip:`${p.row.label}\nh: ${String(p.row.leverage)}\nr: ${String(p.row.stdResidual)}\nD=${fmt(p.D)}`});if(topLabels.includes(p)){const name=label(s,f.x(p.index),f.y(p.D)-8,p.row.label,{'text-anchor':'middle',fill:color,'font-size':s.fs-3},s.compact?7:12);s.reveal(name,.3+i/values.length*.25,.4);}});caption(s,t17('4/n 为探索参考 · 超过参考不代表必须删除','4/n is exploratory · exceeding it does not require deletion'));
}
function addedvariable(s,doc){
 const population=populationId('sample-group',doc.data),populationColor=fallback=>s.theme.objectColor(population,fallback);
 const model=addedVariable17(doc),f=axes(s,measurementDomain(model.points.map(p=>p.x),{padding:.08}),measurementDomain(model.points.map(p=>p.y),{padding:.1}),{xlabel:doc.axes.x,ylabel:doc.axes.y}),xd=f.x.domain(),g=s.group(),clip=s.el('clipPath',{id:`${s.id}-partial-fit`},s.defs);s.rect(f.left,f.top,f.right-f.left,f.bottom-f.top,{},clip);g.setAttribute('clip-path',`url(#${s.id}-partial-fit)`);zeros(s,f);
 const fit=s.line(f.x(xd[0]),f.y(model.fit.predict(xd[0])),f.x(xd[1]),f.y(model.fit.predict(xd[1])),{stroke:s.theme.fg,'stroke-width':1.35,'data-mark':'added-variable-fit','data-slope':model.fit.slope},g);s.reveal(fit,.12,.55);model.points.forEach((p,i)=>dot(s,p.row,f.x(p.x),f.y(p.y),{color:populationColor(s.theme.accent),field:'xResidual',delay:i/model.points.length*.4,mark:'added-variable-point',tip:`${p.row.label}\nxResidual: ${String(p.row.xResidual)}\nyResidual: ${String(p.row.yResidual)}\n${doc.modelName}`}));label(s,s.w-15,14,`${t17('残差平面 OLS 斜率','Residual-plane OLS slope')} = ${fmt(model.fit.slope,{significantDigits:4})}`,{'text-anchor':'end','font-size':s.fs-2},s.compact?46:90);
}
function componentresidual(s,doc){
 const population=populationId('sample-group',doc.data),populationColor=fallback=>s.theme.objectColor(population,fallback);
 const points=componentResidual17(doc),xd=measurementDomain(points.map(p=>p.x)),f=axes(s,xd,measurementDomain(points.flatMap(p=>[p.y,p.component]),{padding:.1}),{xlabel:doc.axes.x,ylabel:doc.axes.y}),fit=s.line(f.x(xd[0]),f.y(doc.coefficient*xd[0]),f.x(xd[1]),f.y(doc.coefficient*xd[1]),{stroke:s.theme.fg,'stroke-width':1.25,'stroke-dasharray':'4 4','data-mark':'component-line','data-coefficient':doc.coefficient});s.reveal(fit,.06,.62);
 points.forEach((p,i)=>{const stem=s.line(f.x(p.x),f.y(p.component),f.x(p.x),f.y(p.y),{stroke:populationColor(s.theme.accent),'stroke-width':.6,'stroke-opacity':.18});s.add(progress=>stem.setAttribute('y2',f.y(p.component+p.row.residual*phase(progress,i/points.length*.2,.65))));dot(s,p.row,f.x(p.x),f.y(p.y),{color:populationColor(s.theme.accent),field:'residual',delay:i/points.length*.38,mark:'component-residual-point',attrs:{'data-component':p.component,'data-partial-residual':p.y},tip:`${p.row.label}\nx: ${String(p.row.x)}\ne: ${String(p.row.residual)}\nβ: ${String(doc.coefficient)}\ne+βx: ${fmt(p.y)}\n${doc.modelName}`});});label(s,s.w-15,14,`e + βx · β=${String(doc.coefficient)}`,{'text-anchor':'end','font-size':s.fs-2},45);caption(s,t17('虚线：原模型线性成分 · 无交互数值项','Dashed: original linear component · numeric term without interactions'));
}
export const volume17Renderers={boxen,sina,rootogram,ecdfband,qqcompare,worm,spreadlevel,scalelocation,residualleverage,cooksdistance,addedvariable,componentresidual};
