import * as d3 from 'd3';
import {isEnglish} from './locale.js';
import {volume12Catalog,volume12English} from './volume12-catalog.js';
export const t12=(zh,en)=>isEnglish()?en:zh;
const ids=new Set(volume12Catalog.map(t=>t.id));
export const groups12=rows=>[...new Set(rows.map(r=>r.group))];
export const sorted12=rows=>[...rows].sort((a,b)=>a.value-b.value);
export function lorenz12(rows){const ordered=sorted12(rows),max=d3.max(ordered,d=>d.value),total=d3.sum(ordered,d=>d.value/max);let cumulative=0;const points=[{population:0,share:0,row:null},...ordered.map((row,i)=>({population:(i+1)/rows.length,share:(cumulative+=row.value/max)/total,row}))];const area=d3.sum(points.slice(1),(p,i)=>(p.share+points[i].share)*(p.population-points[i].population)/2);return{points,gini:Math.max(0,1-2*area)};}
// Abramowitz–Stegun 26.2.17; absolute CDF error < 7.5e-8. At zero return exactly 1/2.
export function normalCDF12(z){if(z===0)return .5;const a=Math.abs(z),t=1/(1+.2316419*a),tail=Math.exp(-a*a/2)/Math.sqrt(2*Math.PI)*t*(.319381530+t*(-.356563782+t*(1.781477937+t*(-1.821255978+t*1.330274429))));return z>0?1-tail:tail;}
export function pp12(rows,mean,sd){const ordered=sorted12(rows),values=ordered.map(d=>d.value);return ordered.map(row=>({row,theoretical:normalCDF12((row.value-mean)/sd),empirical:d3.bisectRight(values,row.value)/values.length}));}
export function quantile12(rows,p){return d3.quantileSorted(sorted12(rows).map(d=>d.value),p);}
export function delta12(rows){const groups=groups12(rows),samples=groups.map(group=>rows.filter(r=>r.group===group));return{groups,points:Array.from({length:19},(_,i)=>{const p=(i+1)/20,a=quantile12(samples[0],p),b=quantile12(samples[1],p);return{p,a,b,difference:b-a};})};}
export function ecdfDifference12(rows){const groups=groups12(rows),samples=groups.map(g=>rows.filter(r=>r.group===g).map(r=>r.value).sort(d3.ascending)),values=[...new Set(rows.map(r=>r.value))].sort(d3.ascending);const points=values.map(value=>{const a=d3.bisectRight(samples[0],value)/samples[0].length,b=d3.bisectRight(samples[1],value)/samples[1].length;return{value,a,b,difference:b-a};});return{groups,points,maxDifference:d3.max(points,d=>Math.abs(d.difference))};}
export function quantileDots12(rows,count){return Array.from({length:count},(_,i)=>({p:(i+.5)/count,value:quantile12(rows,(i+.5)/count),mass:1/count}));}
export function bins12(rows,binsX,binsY){const xd=d3.extent(rows,d=>d.x),yd=d3.extent(rows,d=>d.y),dx=(xd[1]-xd[0])/binsX,dy=(yd[1]-yd[0])/binsY,cells=Array.from({length:binsX*binsY},(_,i)=>{const ix=i%binsX,iy=Math.floor(i/binsX);return{ix,iy,x0:xd[0]+ix*dx,x1:xd[0]+(ix+1)*dx,y0:yd[0]+iy*dy,y1:yd[0]+(iy+1)*dy,rows:[],count:0};});for(const row of rows){const ix=Math.min(binsX-1,Math.floor((row.x-xd[0])/dx)),iy=Math.min(binsY-1,Math.floor((row.y-yd[0])/dy)),cell=cells[iy*binsX+ix];cell.rows.push(row);cell.count++;}return{xd,yd,cells};}
export function gaussianDensity12(values,x,bandwidth){return d3.mean(values,v=>Math.exp(-.5*((x-v)/bandwidth)**2))/bandwidth/Math.sqrt(2*Math.PI);}
export function bivariateDensity12(rows,x,y,hx,hy){return d3.mean(rows,r=>Math.exp(-.5*(((x-r.x)/hx)**2+((y-r.y)/hy)**2)))/hx/hy/(2*Math.PI);}
export function densityGrid12(rows,hx,hy,nx=64,ny=48){const xe=d3.extent(rows,d=>d.x),ye=d3.extent(rows,d=>d.y),xd=[xe[0]-3*hx,xe[1]+3*hx],yd=[ye[0]-3*hy,ye[1]+3*hy],dx=(xd[1]-xd[0])/nx,dy=(yd[1]-yd[0])/ny,values=Array.from({length:nx*ny},(_,i)=>bivariateDensity12(rows,xd[0]+(i%nx+.5)*dx,yd[0]+(Math.floor(i/nx)+.5)*dy,hx,hy));return{xd,yd,nx,ny,values,max:d3.max(values)};}
export function halfeye12(rows,bandwidth){const groups=groups12(rows),extent=d3.extent(rows,d=>d.value),domain=[extent[0]-3*bandwidth,extent[1]+3*bandwidth],curves=groups.map(group=>{const samples=rows.filter(r=>r.group===group),values=samples.map(r=>r.value),points=Array.from({length:129},(_,i)=>{const value=domain[0]+i/128*(domain[1]-domain[0]);return{value,density:gaussianDensity12(values,value,bandwidth)};});return{group,samples,points,median:quantile12(samples,.5),inner:[quantile12(samples,.25),quantile12(samples,.75)],outer:[quantile12(samples,.05),quantile12(samples,.95)]};});return{domain,curves,max:d3.max(curves,c=>d3.max(c.points,p=>p.density))};}
export function validateVolume12(doc,{fail,count,noDuplicates,warnings}){
 if(!ids.has(doc.template))return;const id=doc.template,rows=doc.data,finite=v=>typeof v==='number'&&Number.isFinite(v),positive=v=>finite(v)&&v>0,span=key=>d3.max(rows,r=>r[key])-d3.min(rows,r=>r[key]);
 noDuplicates(rows.map(r=>r.label),t12('观测编号','Observation labels'));
 const max=id==='density2d'?400:['halfeye','deltaplot','ecdfdiff'].includes(id)?1000:['quantiledot','histogram2d'].includes(id)?500:300;count(rows.length,id==='lorenz'?3:5,max,t12('原始观测','raw observations'));
 if(rows.some(r=>['histogram2d','density2d'].includes(id)?!finite(r.x)||!finite(r.y):!finite(r.value))){fail(t12('每条观测必须为完整有限原值，缺测不删除、不补零。','Every observation must be complete and finite; missing values are neither deleted nor zero-filled.'));return;}
 if(id==='lorenz'&&(rows.some(r=>r.value<0)||!rows.some(r=>r.value>0)))fail(t12('洛伦兹曲线需要非负观测且总量为正；不接受负值或全零。','Lorenz curves require nonnegative observations with a positive total; negative or all-zero values are invalid.'));
 if(id==='ppplot'&&(!finite(doc.referenceMean)||!positive(doc.referenceSD)))fail(t12('referenceMean 必须为有限数，referenceSD 必须大于零；不自动从样本拟合。','referenceMean must be finite and referenceSD positive; no automatic sample fit is performed.'));
 if(['deltaplot','ecdfdiff','halfeye'].includes(id)){const groups=groups12(rows);if(id!=='halfeye'&&groups.length!==2)fail(t12('必须恰好提供两组，差值方向为第二组减第一组。','Exactly two groups are required; differences are second minus first.'));count(groups.length,id==='halfeye'?1:2,id==='halfeye'?5:2,t12('分组','groups'));for(const group of groups)count(rows.filter(r=>r.group===group).length,id==='halfeye'?8:5,id==='halfeye'?200:300,t12('每组观测','observations per group'));}
 if(id==='quantiledot'&&(!Number.isInteger(doc.dotCount)||doc.dotCount<20||doc.dotCount>100))fail(t12('dotCount 必须为 20–100 的整数；摘要点数量不等于原始样本量。','dotCount must be an integer from 20 to 100; summary dot count is not raw sample size.'));
 if(['histogram2d','density2d'].includes(id)){
  if(![doc.axes?.x,doc.axes?.y].every(v=>typeof v==='string'&&v.trim()&&v.length<=80))fail(t12('axes.x 和 axes.y 必须分别写明变量名称及单位。','axes.x and axes.y must name each variable and its measurement unit.'));
  if(!(span('x')>0&&span('y')>0))fail(t12('两个坐标轴都需要至少两个不同原值。','Each axis requires at least two distinct original values.'));
  if(id==='histogram2d'&&[doc.binsX,doc.binsY].every(v=>Number.isInteger(v)&&v>=3&&v<=20)&&!(span('x')/doc.binsX>0&&span('y')/doc.binsY>0))fail(t12('原坐标跨度不足以表示非零箱宽，请先换算单位。','The coordinate span cannot represent nonzero bin widths; convert measurement units.'));
  if(id==='histogram2d'&&![doc.binsX,doc.binsY].every(v=>Number.isInteger(v)&&v>=3&&v<=20))fail(t12('binsX 和 binsY 必须为 3–20 的整数。','binsX and binsY must be integers from 3 to 20.'));
  if(id==='density2d'&&(!positive(doc.bandwidthX)||!positive(doc.bandwidthY)||doc.bandwidthX<span('x')/32||doc.bandwidthY<span('y')/24||doc.bandwidthX>span('x')*4||doc.bandwidthY>span('y')*4))fail(t12('二维密度带宽须为正且在各轴跨度的 1/32（X）、1/24（Y）至 4 倍之间，避免网格分辨率无法表达窄核。','Positive density bandwidths must be between 1/32 (X), 1/24 (Y) and 4 times the respective axis span so the evaluation grid resolves the kernels.'));
 }
 if(id==='density2d'&&positive(doc.bandwidthX)&&positive(doc.bandwidthY)&&!Number.isFinite(1/doc.bandwidthX/doc.bandwidthY))fail(t12('带宽乘积过小，密度无法用有限数表示；请换算坐标单位。','Bandwidth product is too small to represent density as a finite number; convert coordinate units.'));
 if(id==='halfeye'&&(!positive(doc.bandwidth)||span('value')>0&&(doc.bandwidth<span('value')/64||doc.bandwidth>span('value')*4)))fail(t12('bandwidth 须为正且在全部样本跨度的 1/64–4 倍之间；常量样本接受任意正常正带宽。','bandwidth must be positive and 1/64–4 times the full sample span; constant samples accept a positive bandwidth.'));
 if(id==='halfeye'&&positive(doc.bandwidth)){const low=d3.min(rows,r=>r.value)-3*doc.bandwidth,high=d3.max(rows,r=>r.value)+3*doc.bandwidth;if(!Number.isFinite(low)||!Number.isFinite(high)||!Number.isFinite(high-low)||!(high>low))fail(t12('当前值和带宽无法构成有限、可分辨的密度横轴；请先换算单位。','The values and bandwidth do not form a finite, distinguishable density axis; convert measurement units.'));}
 if((id==='halfeye'&&positive(doc.bandwidth)&&!Number.isFinite(1/doc.bandwidth))||(id==='ppplot'&&positive(doc.referenceSD)&&!Number.isFinite(1/doc.referenceSD)))fail(t12('尺度过小，请先换算单位以保证数值可表示。','Scale is too small; convert measurement units to retain finite numeric precision.'));
 warnings.push(t12('所有观测等权；不删除缺测、不补零、不自动去除离群值。图中摘要均由完整输入计算。','All observations have equal weight. Missing observations are not removed or zero-filled, and outliers are not trimmed. Summaries use the complete input.'));
 if(['density2d','halfeye'].includes(id))warnings.push(t12('高斯核延伸到观测范围外；显示范围向外延伸三个带宽，不做边界修正或截断再归一化。','Gaussian kernels extend beyond the observations; display extends by three bandwidths without boundary correction or truncation renormalization.'));
}
export function volume12Summary(doc,fmt){return ids.has(doc.template)?{value:fmt(doc.data.length),label:t12('原始观测','Raw observations'),unit:t12('条','rows')}:null;}
const sources={lorenz:'https://databank.worldbank.org/metadataglossary/gender-statistics/series/SI.POV.GINI',quantile:'https://stat.ethz.ch/R-manual/R-devel/library/stats/html/quantile.html',ecdf:'https://stat.ethz.ch/R-manual/R-devel/library/stats/html/ecdf.html',normal:'https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.ndtr.html',density:'https://search.r-project.org/R/refmans/stats/html/density.html',contours:'https://d3js.org/d3-contour/contours',halfeye:'https://mjskay.github.io/ggdist/reference/stat_halfeye.html',dots:'https://mjskay.github.io/ggdist/articles/slabinterval.html'};
export function volume12MethodNotes(id){const q=t12('所有分位数使用 Type 7：h=(n−1)p，在线性排序位置 floor(h) 与 ceil(h) 间插值。','All quantiles use Type 7: h=(n−1)p, linearly interpolated between sorted positions floor(h) and ceil(h).')+' '+sources.quantile;const notes={
 lorenz:[t12('将等权非负原值升序排列；点 (i/n, Σ前i项/Σ全部) 含 (0,0)。Gini=1−2×折线下梯形面积，不做 n/(n−1) 样本校正；常量正值 Gini=0。','Sort equal-weight nonnegative observations. Plot (i/n, cumulative sum/total), including (0,0). Gini=1−2×trapezoidal area, with no n/(n−1) correction; a positive constant sample has Gini=0.')+' '+sources.lorenz],
 ppplot:[t12('横轴 Φ((value−referenceMean)/referenceSD)，纵轴 #{样本≤value}/n。重复值共用同一累计概率，保留所有原始记录。均值与标准差由输入指定，不拟合；CDF 数值近似最大绝对误差约 7.5×10⁻⁸。两轴固定 [0,1]，对角线仅为参考。','X=Φ((value−referenceMean)/referenceSD); Y=#{sample≤value}/n. Ties share one cumulative probability while all rows remain. Reference parameters are supplied, never fitted. CDF approximation absolute error is about 7.5×10⁻⁸. Both axes are [0,1]; the diagonal is only a reference.')+' '+sources.normal+' '+sources.ecdf],
 deltaplot:[q,t12('计算 p=0.05,0.10,…,0.95 的 Q_B(p)−Q_A(p)。A/B 为分组首次出现顺序；纵轴保留原始单位，零线表示分位数相等。原始观测带独立使用原值横轴，不能将差异曲线当成配对个体变化。','Plot Q_B(p)−Q_A(p) at p=0.05,0.10,…,0.95. A/B follow first group appearance. Y retains the original unit; zero means equal quantiles. A separate raw-observation strip uses a measurement-unit X axis. Differences are not paired individual changes.')],
 ecdfdiff:[t12('F_g(x)=#{组g值≤x}/n_g，在合并样本的每个不同原值绘制 F_B(x)−F_A(x) 的右连续阶梯；不平滑。D=max|差| 是描述性最大差，不计算检验 p 值。','F_g(x)=#{group g values≤x}/n_g. Plot the right-continuous step F_B(x)−F_A(x) at every distinct pooled value without smoothing. D=max|difference| is descriptive; no test p-value is calculated.')+' '+sources.ecdf],
 quantiledot:[q,t12('点 i 位于 Q((i+0.5)/dotCount)，每点表示 1/dotCount 概率质量。垂直堆叠只为避让，不编码另一变量；原始观测保留为下方短线。','Dot i is Q((i+0.5)/dotCount), representing 1/dotCount probability mass. Vertical stacking only avoids overlap; it is not another variable. Raw observations remain as a separate rug.')+' '+sources.dots],
 histogram2d:[t12('两轴均以完整观测最小值到最大值等宽分箱。普通箱左闭右开，最后一箱包含最大值；每条记录只计一次。空箱显示真实零频数，非缺测；总频数恒等于原始样本量。','Both axes use equal-width bins over the complete observed min–max. Bins are left-closed/right-open except the last, which includes the maximum. Count every row once. Empty bins are genuine zero counts, not missing observations; total count equals sample size.')],
 density2d:[t12('使用 f(x,y)=Σ exp(−0.5[((x−xi)/hx)²+((y−yi)/hy)²])/(n·2π·hx·hy)，带宽是原坐标单位的核标准差。64×48 网格上的 marching squares 生成等高线；层级为峰值的 15%、30%、50%、70%、90%，表示密度值而非覆盖概率。','Use f(x,y)=Σ exp(−0.5[((x−xi)/hx)²+((y−yi)/hy)²])/(n·2π·hx·hy), with bandwidths as kernel standard deviations in original units. Marching squares on a 64×48 grid generates levels at 15%,30%,50%,70%,90% of peak density. These are density values, not coverage probabilities.')+' '+sources.contours+' '+sources.density],
 halfeye:[q,t12('每组 f(x)=Σ exp(−0.5((x−xi)/h)²)/(n·h·√(2π))，所有组共用带宽和密度高度尺度。点为中位数；粗线 Q25–Q75，细线 Q05–Q95，分别为中央 50%/90% 样本区间，非均值置信区间。','For each group f(x)=Σ exp(−0.5((x−xi)/h)²)/(n·h·√(2π)). Groups share bandwidth and density-height scale. Dot=median; thick interval=Q25–Q75, thin=Q05–Q95: central 50%/90% sample intervals, not confidence intervals for the mean.')+' '+sources.density+' '+sources.halfeye]
 };return notes[id]||[];}
export function guide12(t,guide){if(!ids.has(t.id))return guide;const en=volume12English[t.id],warnings=[];validateVolume12(guide.example,{fail:()=>{},count:()=>{},noDuplicates:()=>{},warnings});return{...guide,introduction:isEnglish()?en.description:t.description,rowMeaning:isEnglish()?en.rowMeaning:t12(['deltaplot','ecdfdiff','halfeye'].includes(t.id)?'一行是一条原始观测，label 唯一，group 表示组别，value 保留测量单位。':['histogram2d','density2d'].includes(t.id)?'一行是一条完整的原始 X、Y 配对观测；label 唯一，两轴单位分别注明。':'一行是一条等权原始观测；label 唯一，value 不是预计算的密度、概率或分位数。',''),use:isEnglish()?en.use:t.use,avoid:isEnglish()?en.avoid:t.avoid,limit:isEnglish()?en.limit:t.limit,notes:[...warnings,...volume12MethodNotes(t.id)],fields:guide.fields.map((f,i)=>({...f,description:isEnglish()?en.fields[i][2]:t.fields[i][2]}))};}
