import {uiText,uiMarkup,uiMessage} from './locale.js';
import {morphReady,stepView} from './work-model.js';
import {isScientificView} from './scientific-rules.js';
import {isSeriesView} from './series-rules.js';
import {isPairedView,isHierarchyView} from './relational-rules.js';

export function workRendererFamily(step){
  if(!morphReady(step))return 'native';
  const v=stepView(step);
  return isScientificView(v)?'scientific':isSeriesView(v)?'series':isPairedView(v)?'paired':isHierarchyView(v)?'hierarchy':'single';
}
export function selectWorkRuntime(work,profiles=[]){
  const families=new Set(work.steps.map(workRendererFamily));
  return profiles.filter(p=>p.families&&[...families].every(f=>p.families.includes(f))).sort((a,b)=>a.bytes-b.bytes)[0]||{file:'work-player.js',families:['native','single','series','paired','hierarchy','scientific']};
}
export async function loadWorkRuntime(work,{base=import.meta.env?.BASE_URL||'/',fetcher=globalThis.fetch,signal}={}){
  const prefix=`${base}forma/`;let profile;
  try{const response=await fetcher(`${prefix}work-runtimes.json`,{signal,cache:'no-cache'});if(response.ok)profile=selectWorkRuntime(work,(await response.json()).profiles);}
  catch(error){if(signal?.aborted)throw error;}
  const file=profile?.file||'work-player.js';
  // The manifest is generated by our build. It cannot redirect data to another origin.
  if(!/^work-player(?:-[a-z-]+)?\.js$/.test(file))throw new Error(uiText('作品引擎清单无效，请刷新后重试。'));
  let response=await fetcher(prefix+file,{signal,cache:'no-cache'});
  if(!response.ok&&file!=='work-player.js')response=await fetcher(prefix+'work-player.js',{signal,cache:'no-cache'});
  if(!response.ok)throw new Error(uiText('作品导出引擎尚未就绪，请刷新后重试。'));
  return response.text();
}
