import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {getExample} from '../../src/forma/catalog.js';
import {withRecordIds,recordId} from '../../src/forma/data-identity.js';
import {setLocale} from '../../src/forma/locale.js';
import {advancedRelationsViews,advancedRelationsViewMap,advancedRelationsDocument,advancedRelationsEligibility,advancedRelationsCompatibility,advancedRelationsBounds,advancedRelationsColorKeys,advancedRelationsColorSubjects,advancedRelationsNodes,advancedRelationsGuide,advancedRelationsAgentGuide} from '../../src/forma/advanced-relations-rules.js';
import {layoutAdvancedRelations,interpolateAdvancedRelationsMark} from '../../src/forma/advanced-relations-morph.js';
import {advancedRelationsPresets,advancedRelationsRecords} from '../../src/forma/advanced-relations-presets.js';
const raw=id=>withRecordIds(getExample(id),{legacyNamespace:'relationx-test'}),doc=id=>advancedRelationsDocument(raw(id));
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8*Math.max(1,Math.abs(a),Math.abs(b)),`${a} != ${b}`),primary=m=>['relationx-cell','relationx-edge','relationx-path','relationx-intersection'].includes(m.role);
function finite(layout){assert.ok(layout.plot.w>0&&layout.plot.h>0);const seen=new Set();for(const m of layout.marks){assert.equal(m.points.length,128,m.key);assert.ok(m.points.flat().every(Number.isFinite),m.key);assert.ok(m.anchor.every(Number.isFinite));assert.ok(!seen.has(m.key),m.key);seen.add(m.key);}for(const label of layout.labels)assert.ok(Number.isFinite(label.x)&&Number.isFinite(label.y));}
function paired(template){const d=doc(template);return advancedRelationsViews.filter(v=>v.family===d.family&&advancedRelationsEligibility(d,v.id).valid).map(v=>v.id);}

test('eight native relation contracts preserve every raw field, record identity, unit and provenance across all fifteen views',()=>{
 assert.equal(Object.keys(advancedRelationsViewMap).length,8);assert.equal(advancedRelationsViews.length,15);
 for(const [template,view]of Object.entries(advancedRelationsViewMap)){const original=raw(template),before=structuredClone(original),d=advancedRelationsDocument(original);assert.deepEqual(original,before);assert.deepEqual(d.data,original.data.map((r,inputIndex)=>({...r,inputIndex})));assert.equal(d.unit,original.unit);assert.deepEqual(d.source,original.source);assert.equal(advancedRelationsEligibility(d,view).valid,true,template);
  for(const target of paired(template))for(const [w,h]of[[300,240],[800,440],[1280,720]]){const l=layoutAdvancedRelations(d,target,w,h);finite(l);const observed=l.marks.filter(primary);assert.equal(observed.length,d.data.length);assert.deepEqual(observed.map(m=>m.identity).sort(),d.data.map(recordId).sort());for(const mark of observed){const row=d.data[mark.row],field=d.family==='relationx-intersections'?'count':'value';assert.equal(mark.value,row[field]);assert.equal(mark.editable,field);assert.ok(mark.opacity>0);assert.ok(!mark.recordIds);}}
 }
});

test('directed adjacency retains every zero, diagonal and orientation with a shared original color scale',()=>{
 const d=doc('adjacency');d.data[0].value=13;d.data[1].value=5;d.data.find(r=>r.source===d.data[1].target&&r.target===d.data[1].source).value=90;for(const view of paired('adjacency')){const layout=layoutAdvancedRelations(d,view,800,440,{domain:{value:[0,200]}});assert.deepEqual(layout.valueDomain,[0,200]);assert.equal(layout.marks.length,d.nodes.length**2);for(const m of layout.marks){assert.equal(m.value,d.data[m.row].value);near(m.tone,m.value/200);assert.deepEqual(m.valueDomain,[0,200]);assert.equal(m.source,d.data[m.row].source);assert.equal(m.target,d.data[m.row].target);}}
 const zero=structuredClone(d);zero.data.forEach(r=>r.value=0);for(const view of paired('adjacency'))finite(layoutAdvancedRelations(zero,view));const missing=structuredClone(d);missing.data.pop();assert.equal(advancedRelationsEligibility(missing,'relationx-adjacency').valid,false);assert.deepEqual(advancedRelationsColorSubjects(d),[]);
});

test('bipartite nodes include isolated declarations and node area is proportional to incident totals',()=>{
 const d=doc('bipartite');d.leftNodes.push('Isolated');for(const view of paired('bipartite')){assert.equal(advancedRelationsEligibility(d,view).valid,true);const l=layoutAdvancedRelations(d,view),nodes=l.marks.filter(m=>m.role==='relationx-node'),isolated=nodes.find(m=>m.group==='Isolated');assert.ok(isolated);assert.equal(isolated.value,0);assert.equal(isolated.paper,true);const positive=nodes.filter(m=>m.value>0);for(const node of positive)near(node.radius**2/positive[0].radius**2,node.value/positive[0].value);assert.equal(l.marks.filter(primary).length,d.data.length);}
 const reversed=structuredClone(d);[reversed.data[0].source,reversed.data[0].target]=[reversed.data[0].target,reversed.data[0].source];assert.equal(advancedRelationsEligibility(reversed,'relationx-bipartite').valid,false);
});

test('ego and hierarchy bundles keep all original edges and source/target attachments while changing geometry',()=>{
 for(const template of['egonetwork','edgebundle']){const d=doc(template),[a,b]=paired(template).map(v=>layoutAdvancedRelations(d,v));assert.deepEqual(a.marks.map(m=>m.key).sort(),b.marks.map(m=>m.key).sort());assert.ok(a.marks.filter(primary).some(m=>JSON.stringify(m.points)!==JSON.stringify(b.marks.find(n=>n.key===m.key).points)));for(const l of[a,b])for(const m of l.marks.filter(primary)){const row=d.data[m.row],node=l.marks.find(n=>n.role==='relationx-node'&&n.group===row.source),target=l.marks.find(n=>n.role==='relationx-node'&&n.group===row.target);for(const k of[0,1]){near((m.points[0][k]+m.points[127][k])/2,node.point[k]);near((m.points[63][k]+m.points[64][k])/2,target.point[k]);}}}
 const d=doc('egonetwork'),changed=structuredClone(d);changed.ego=d.data[0].target;assert.notEqual(advancedRelationsCompatibility(d,changed),'');
});

test('hive preserves supplied positions and the axis order without ranking by weight',()=>{
 const d=doc('hiveplot');for(const view of paired('hiveplot')){const l=layoutAdvancedRelations(d,view);for(const node of l.marks.filter(m=>m.role==='relationx-node')){const row=d.data.find(r=>r.source===node.group||r.target===node.group),side=row.source===node.group?'source':'target';assert.equal(node.position,row[side+'Position']);assert.equal(node.originalGroup,row[side+'Group']);}const changed=structuredClone(d);changed.data.forEach(r=>r.value*=1e-10);const other=layoutAdvancedRelations(changed,view);for(const node of l.marks.filter(m=>m.role==='relationx-node'))assert.deepEqual(node.point,other.marks.find(m=>m.key===node.key).point);}
 const invalid=structuredClone(d);invalid.data[0].sourcePosition=1.1;assert.equal(advancedRelationsEligibility(invalid,'relationx-hive').valid,false);
});

test('parallel sets preserve complete paths, independent identities and proportional native band thickness',()=>{
 const d=doc('parallelsets');for(const view of paired('parallelsets')){const l=layoutAdvancedRelations(d,view);assert.equal(l.statistics.total,d.data.reduce((s,r)=>s+r.value,0));for(const m of l.marks.filter(primary)){const row=d.data[m.row];assert.deepEqual(m.path,[row.a,row.b,row.c]);near(m.thickness,row.value*l.statistics.scale);}assert.equal(l.marks.filter(m=>m.role==='relationx-category').reduce((s,m)=>s+m.value,0),l.statistics.total*3);}
 const changed=structuredClone(d);changed.data[0].b=d.data.find(r=>r.b!==d.data[0].b).b;assert.notEqual(advancedRelationsCompatibility(d,changed),'');
});

test('UpSet and Venn keep exclusive memberships, exact set totals and zero regions without fake native compatibility',()=>{
 for(const template of['upset','venn']){const d=doc(template);for(const view of paired(template)){const l=layoutAdvancedRelations(d,view);assert.equal(l.statistics.total,d.data.reduce((s,r)=>s+r.count,0));for(const set of l.statistics.sets)assert.equal(set.total,d.data.filter(r=>r.members.split('|').includes(set.name)).reduce((s,r)=>s+r.count,0));for(const m of l.marks.filter(primary)){assert.deepEqual(m.members,d.data[m.row].members.split('|'));assert.equal(m.count,d.data[m.row].count);}}}
 const venn=doc('venn');venn.data[0].count=0;assert.equal(advancedRelationsEligibility(venn,'relationx-venn').valid,true);assert.equal(advancedRelationsEligibility(venn,'relationx-intersections').valid,true);assert.equal(advancedRelationsEligibility(venn,'relationx-upset').valid,false);const l=layoutAdvancedRelations(venn,'relationx-intersections'),zero=l.marks.find(m=>primary(m)&&m.identity===recordId(venn.data[0]));assert.equal(zero.value,0);assert.equal(new Set(zero.points.map(p=>p[0])).size,1);assert.ok(zero.stroke>0);assert.equal(advancedRelationsEligibility(doc('upset'),'relationx-venn').valid,false);
});

test('full renaming and sorting preserve incidence identities; source, membership and declared order changes remain incompatible',()=>{
 for(const template of Object.keys(advancedRelationsViewMap)){const d=doc(template),changed=structuredClone(d);changed.data.reverse();assert.equal(advancedRelationsCompatibility(d,changed),'',template);assert.deepEqual(advancedRelationsColorKeys(d).sort(),advancedRelationsColorKeys(changed).sort());
  const renamed=structuredClone(d),rename=s=>`New ${s}`;if(d.family==='relationx-intersections'){renamed.sets=renamed.sets.map(rename);renamed.data.forEach(r=>r.members=r.members.split('|').map(rename).join('|'));}else if(d.family==='relationx-paths'){renamed.data.forEach(r=>{for(const k of['a','b','c'])r[k]=rename(r[k]);});}else{renamed.data.forEach(r=>{r.source=rename(r.source);r.target=rename(r.target);});for(const k of['nodes','leftNodes','rightNodes'])if(renamed[k])renamed[k]=renamed[k].map(rename);if(renamed.ego)renamed.ego=rename(renamed.ego);}assert.equal(advancedRelationsEligibility(renamed,advancedRelationsViewMap[template]).valid,true,template);assert.equal(advancedRelationsCompatibility(d,renamed),'',template);
  for(const mutate of[x=>x.unit+=' changed',x=>x.source={...x.source,name:'Other'},x=>x.data[0]._id+=' changed']){const bad=structuredClone(d);mutate(bad);assert.notEqual(advancedRelationsCompatibility(d,bad),'');}
 }
});

test('malformed metadata rejects safely and color/bounds readers do not crash',()=>{
 const fields={adjacency:['nodes'],bipartite:['leftNodes','rightNodes'],egonetwork:['ego'],hiveplot:['axisOrder'],parallelsets:['axes'],upset:['sets'],venn:['sets']};for(const[template,keys]of Object.entries(fields))for(const field of keys)for(const value of[null,[],{},'']){const d=doc(template);d[field]=value;assert.equal(advancedRelationsEligibility(d,advancedRelationsViewMap[template]).valid,false,`${template}/${field}`);assert.doesNotThrow(()=>advancedRelationsColorSubjects(d));assert.doesNotThrow(()=>advancedRelationsColorKeys(d));assert.ok(Object.values(advancedRelationsBounds(d)).flat().every(Number.isFinite));}
 for(const template of Object.keys(advancedRelationsViewMap)){const d=doc(template);d.data[0][d.family==='relationx-intersections'?'count':'value']=null;assert.equal(advancedRelationsEligibility(d,advancedRelationsViewMap[template]).valid,false);}
});

test('thin-link interpolation preserves endpoint attachments and exact endpoints across scales and interruptions',()=>{
 for(const template of['bipartite','egonetwork','edgebundle','hiveplot']){const d=doc(template),[a,b]=paired(template).map(v=>layoutAdvancedRelations(d,v)),byKey=new Map(b.marks.map(m=>[m.key,m]));for(const old of a.marks.filter(primary)){const next=byKey.get(old.key);assert.deepEqual(interpolateAdvancedRelationsMark(old.points,old,next,0),old.points);assert.deepEqual(interpolateAdvancedRelationsMark(old.points,old,next,1),next.points);for(const q of[.1,.3,.5,.7,.9]){const points=interpolateAdvancedRelationsMark(old.points,old,next,q);assert.ok(points.flat().every(Number.isFinite));for(const[k,index]of[[0,0],[1,63]])for(const dim of[0,1])near((points[index][dim]+points[127-index][dim])/2,mix(old.endpoints[k][dim],next.endpoints[k][dim],q));const resumed=interpolateAdvancedRelationsMark(points,next,old,0);assert.deepEqual(resumed,points);}}}
 function mix(a,b,q){return a+(b-a)*q;}
});

test('eight regular presets clone original rows and expose bilingual view and Agent contracts',()=>{
 assert.equal(advancedRelationsPresets.length,8);assert.equal(advancedRelationsRecords('missing'),null);for(const p of advancedRelationsPresets){const steps=advancedRelationsRecords(p.id,'coral');assert.equal(p.category,'regular');assert.deepEqual(steps.map(s=>s.view),p.views);for(const s of steps){assert.deepEqual(s.doc.data,steps[0].doc.data);assert.equal(s.options.palette,'coral');assert.equal(advancedRelationsEligibility(advancedRelationsDocument(s.doc),s.view).valid,true);}steps[0].doc.data[0].sentinel=true;assert.equal(steps[1].doc.data[0].sentinel,undefined);}try{setLocale('en');for(const v of advancedRelationsViews){assert.equal(v.name,v.en);assert.doesNotMatch(v.note,/\p{Script=Han}/u);}for(const p of advancedRelationsPresets)assert.doesNotMatch(p.name+p.description+p.dataNote+p.relation,/\p{Script=Han}/u);assert.doesNotMatch(advancedRelationsAgentGuide(true),/\p{Script=Han}/u);assert.doesNotMatch(advancedRelationsGuide(doc('hiveplot'),'relationx-hive').join(' '),/\p{Script=Han}/u);}finally{setLocale('zh-CN');}
});

test('twenty directed native transitions preserve SVG nodes through reverse, seek, interrupted resume and saved export',async()=>{
 const [{ScientificMorphChart},{newWork,cleanWork,transitionPlan,stepReport},{stepSVG}]=await Promise.all([import('../../src/forma/scientific-morph.js'),import('../../src/forma/work-model.js'),import('../../src/forma/work-export.js')]),win=new Window(),old=new Map();for(const[k,v]of Object.entries({document:win.document,XMLSerializer:win.XMLSerializer})){old.set(k,Object.getOwnPropertyDescriptor(globalThis,k));Object.defineProperty(globalThis,k,{value:v,configurable:true,writable:true});}let directions=0;
 try{for(const template of Object.keys(advancedRelationsViewMap)){const original=raw(template),d=advancedRelationsDocument(original),views=paired(template);for(const from of views)for(const to of views){if(from===to)continue;directions++;const chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:from,width:800,height:440,editable:true});try{const nodes=new Map([...chart.nodes].map(([k,n])=>[k,n.shape])),seek=chart.setDocument(d,to,{manual:true,effect:'guided',recipe:'relationx-unfold'});seek(.37);const captured=structuredClone([...chart.current]),back=chart.setDocument(d,from,{manual:true,resume:true,effect:'guided',recipe:'relationx-unfold'});back(0);assert.deepEqual([...chart.current],captured);back(1);const again=chart.setDocument(d,to,{manual:true,effect:'guided',recipe:'relationx-unfold'});again(.5);const half=structuredClone([...chart.current]);again(1);again(.5);assert.deepEqual([...chart.current],half);again(1);for(const m of chart.layout.marks){assert.deepEqual(chart.current.get(m.key),m.points);if(primary(m)){assert.equal(chart.nodes.get(m.key).group.dataset.editField,m.editable);assert.equal(Number(chart.nodes.get(m.key).group.dataset.editRow),m.row);}}for(const[k,node]of nodes)assert.equal(chart.nodes.get(k).shape,node);assert.doesNotMatch(chart.svg.outerHTML,/NaN|Infinity|undefined/);}finally{chart.destroy();}}
  const work=newWork(views.map(view=>({doc:structuredClone(original),view,dataGroup:`relationx-${template}`,options:{palette:'ink'}})));assert.deepEqual(cleanWork(JSON.parse(JSON.stringify(work))),work);for(const a of work.steps){assert.equal(stepReport(a).valid,true);for(const b of work.steps)if(a!==b)assert.equal(transitionPlan(a,b,{steps:work.steps}).mode,'morph');const svg=stepSVG(a,work.steps);assert.doesNotMatch(svg.replace(/<style>[\s\S]*?<\/style>/g,''),/NaN|Infinity|undefined/);assert.match(svg,/data-science-role="relationx-/);}
 }
 assert.equal(directions,20);
 }finally{for(const[k,v]of old){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];}await win.happyDOM.close();}
});

test('maximum native relation populations remain finite at compact sizes and all record contours remain present',()=>{
 const cases=[];
 let d=raw('adjacency');d.nodes=Array.from({length:12},(_,i)=>`N${i}`);d.data=d.nodes.flatMap((source,i)=>d.nodes.map((target,j)=>({source,target,value:i===j?0:(i+j+1)*1e12})));cases.push(d);
 d=raw('bipartite');d.leftNodes=Array.from({length:12},(_,i)=>`L${i}`);d.rightNodes=Array.from({length:12},(_,i)=>`R${i}`);d.data=Array.from({length:60},(_,i)=>({source:d.leftNodes[i%12],target:d.rightNodes[Math.floor(i/12)],value:(i+1)*1e-12}));cases.push(d);
 d=raw('egonetwork');const neighbors=Array.from({length:16},(_,i)=>`N${i}`);d.data=neighbors.map(target=>({source:d.ego,target,value:2}));for(let i=0;i<16;i++)for(let j=i+1;j<16&&d.data.length<80;j++)d.data.push({source:neighbors[i],target:neighbors[j],value:i+j+1});cases.push(d);
 d=raw('edgebundle');const bundleNodes=Array.from({length:32},(_,i)=>`N${i}`),owner=n=>`G${Number(n.slice(1))%5}`;d.data=[];for(let gap=1;gap<32&&d.data.length<50;gap++)for(let i=0;i<32&&d.data.length<50;i++){const source=bundleNodes[i],target=bundleNodes[(i+gap)%32];d.data.push({source,target,sourceGroup:owner(source),targetGroup:owner(target),value:(i+1)*1e-12});}cases.push(d);
 d=raw('hiveplot');d.axisOrder=['A','B','C'];d.data=[];const pair=(i,j)=>({source:`N${i}`,target:`N${j}`,sourceGroup:d.axisOrder[i%3],targetGroup:d.axisOrder[j%3],sourcePosition:i/49,targetPosition:j/49,value:i+j+1});for(let i=0;i<50;i++)d.data.push(pair(i,(i+1)%50));for(let i=0;i<10;i++)d.data.push(pair(i,i+2));cases.push(d);
 d=raw('parallelsets');d.data=Array.from({length:36},(_,i)=>({a:`A${i%6}`,b:`B${Math.floor(i/6)}`,c:`C${(i+Math.floor(i/6))%6}`,value:(i+1)*1e-12}));cases.push(d);
 d=raw('upset');d.sets=['A','B','C','D','E'];d.data=Array.from({length:20},(_,i)=>({members:d.sets.filter((_,j)=>(i+1)&1<<j).join('|'),count:i+1}));cases.push(d);
 d=raw('venn');d.data.forEach(r=>r.count=0);cases.push(d);
 for(const original of cases){const identified=withRecordIds(original,{legacyNamespace:`maximum:${original.template}`}),adapted=advancedRelationsDocument(identified);for(const v of advancedRelationsViews.filter(v=>v.family===adapted.family)){if(!advancedRelationsEligibility(adapted,v.id).valid)continue;const l=layoutAdvancedRelations(adapted,v.id,300,240);finite(l);assert.equal(l.marks.filter(primary).length,adapted.data.length);}assert.equal(advancedRelationsEligibility(adapted,advancedRelationsViewMap[original.template]).valid,true,original.template);}
});

test('changing continuous relation units preserves normalized primary geometry without absolute epsilon thresholds',()=>{
 for(const template of['adjacency','bipartite','egonetwork','edgebundle','hiveplot','parallelsets']){const d=doc(template);for(const v of paired(template)){const original=layoutAdvancedRelations(d,v),byKey=new Map(original.marks.filter(primary).map(m=>[m.key,m]));for(const factor of[1e-12,1e12]){const scaled=structuredClone(d);scaled.data.forEach(r=>r.value*=factor);assert.equal(advancedRelationsEligibility(scaled,v).valid,true);const l=layoutAdvancedRelations(scaled,v);for(const m of l.marks.filter(primary)){const before=byKey.get(m.key);for(let i=0;i<128;i++)for(let k=0;k<2;k++)near(m.points[i][k],before.points[i][k]);}}}}
});

test('native and morph colors follow original identities after row sorting and saved-work edits; SVG labels escape markup',async()=>{
 const [{ChartScene},{ScientificMorphChart},{colorSubjects}]=await Promise.all([import('../../src/forma/charts.js'),import('../../src/forma/scientific-morph.js'),import('../../src/forma/color-semantics.js')]),win=new Window(),priorDocument=Object.getOwnPropertyDescriptor(globalThis,'document');Object.defineProperty(globalThis,'document',{value:win.document,configurable:true,writable:true});
 try{for(const template of['bipartite','egonetwork','edgebundle','hiveplot','parallelsets','upset']){const original=raw(template),bindings=colorSubjects(original).map((s,i)=>({id:s.id,color:'#'+(0x137501+i*617).toString(16)}));assert.equal(bindings.length,original.data.length);original.data.reverse();original.data[0][template==='upset'?'count':'value']+=1;const d=advancedRelationsDocument(original),options={width:800,height:440,editable:true,colorBindings:bindings,palette:'ink'},native=new ChartScene(win.document.createElement('div'),original,options);try{native.render(1);const colors=new Set([...native.svg.querySelectorAll('path,rect,circle,line')].filter(n=>!n.closest('defs')).flatMap(n=>[n.getAttribute('fill'),n.getAttribute('stroke')]));for(const b of bindings)assert.ok(colors.has(b.color),`${template} native ${b.id}`);}finally{native.destroy();}for(const v of paired(template)){const chart=new ScientificMorphChart(win.document.createElement('div'),d,{...options,view:v});try{for(const mark of chart.layout.marks.filter(primary))assert.equal(chart.nodes.get(mark.key).shape.getAttribute('fill'),bindings.find(b=>b.id===mark.identity).color);}finally{chart.destroy();}}}
 const d=doc('adjacency'),name='<script>&"',old=d.nodes[0];d.nodes[0]=name;d.data.forEach(r=>{if(r.source===old)r.source=name;if(r.target===old)r.target=name;});const chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:'relationx-adjacency',editable:true});assert.equal(chart.svg.querySelectorAll('script').length,0);assert.match(chart.svg.outerHTML,/&lt;script&gt;/);chart.destroy();
 }finally{if(priorDocument)Object.defineProperty(globalThis,'document',priorDocument);else delete globalThis.document;await win.happyDOM.close();}
});

test('matrix-to-ring cells and wrapping category ribbons keep simple contours through intermediate frames',()=>{
 const crossed=points=>{const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);for(let i=0;i<points.length;i++)for(let j=i+2;j<points.length;j++){if(i===0&&j===points.length-1)continue;const a=points[i],b=points[(i+1)%points.length],c=points[j],d=points[(j+1)%points.length];if(cross(a,b,c)*cross(a,b,d)<-1e-12&&cross(c,d,a)*cross(c,d,b)<-1e-12)return true;}return false;};
 for(const template of['adjacency','parallelsets']){const d=doc(template),[a,b]=paired(template).map(v=>layoutAdvancedRelations(d,v));for(const old of a.marks.filter(primary)){const next=b.marks.find(m=>m.key===old.key);for(const q of[0,.1,.25,.5,.75,.9,1]){const points=interpolateAdvancedRelationsMark(old.points,old,next,q)||old.points.map((p,i)=>p.map((v,k)=>v+(next.points[i][k]-v)*q));assert.equal(crossed(points),false,`${template} ${old.row} at ${q}`);}}}
});
