import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {createServer} from 'vite';
import {IDBFactory} from 'fake-indexeddb';
import {newAnnotation,cleanAnnotations,annotationStatus,applyAnnotation,removeAnnotation,undoAnnotation,annotationOpacity} from '../../src/forma/annotations.js';
import {presetWork,cleanWork,makeStep,newWork,transitionPlan} from '../../src/forma/work-model.js';
import {getExample} from '../../src/forma/catalog.js';
import {previewDataSync,applyDataSync,undoDataSync} from '../../src/forma/work-data-sync.js';
import {annotationAnchor,annotationCaption,renderAnnotations,assertAnnotationLayout} from '../../src/forma/annotation-view.js';
import {openWorkStore} from '../../src/forma/work-store.js';
let win,server,editorModule,sceneModule,frameModule,exportModule,videoModule,actionsModule;const old=new Map();
before(async()=>{
  win=new Window({url:'http://localhost:4207/'});for(const [k,v]of Object.entries({window:win,document:win.document,XMLSerializer:win.XMLSerializer,ResizeObserver:win.ResizeObserver,requestAnimationFrame:win.requestAnimationFrame.bind(win),cancelAnimationFrame:win.cancelAnimationFrame.bind(win)})){old.set(k,Object.getOwnPropertyDescriptor(globalThis,k));Object.defineProperty(globalThis,k,{value:v,writable:true,configurable:true});}
  server=await createServer({server:{middlewareMode:true,hmr:false},appType:'custom'});
  editorModule=await server.ssrLoadModule('/src/forma/work-editor.js');sceneModule=await server.ssrLoadModule('/src/forma/work-scene.js');frameModule=await server.ssrLoadModule('/src/forma/work-frame.js');exportModule=await server.ssrLoadModule('/src/forma/work-export.js');videoModule=await server.ssrLoadModule('/src/forma/work-video.js');actionsModule=await server.ssrLoadModule('/src/forma/library-actions.js');
});
after(async()=>{await server?.close();await win?.happyDOM.close();for(const [k,v]of old){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];}});
const copy=v=>structuredClone(v),settle=()=>new Promise(r=>setTimeout(r,70));
const storage=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)};};
const work=()=>presetWork('essential');
const mark=(w=work(),kind='object')=>newAnnotation(w.steps[0].doc,{kind,text:'关键观测'});
function change(host,selector,value,event='input'){const node=host.querySelector(selector);assert.ok(node,selector);node.value=value;node.dispatchEvent(new win.Event(event,{bubbles:true}));}
async function fixture(t,initial=work()) {const repo=await openWorkStore({indexedDB:new IDBFactory(),name:crypto.randomUUID(),storage:storage(),broadcast:false}),host=document.createElement('main');document.body.append(host);const app=editorModule.mountWorkEditor(host,{initial,repository:repo,storage:storage()});await app.flush();t.after(()=>{app.destroy();repo.close();host.remove();});return {host,app,repo};}
test('legacy works stay annotation-free and annotation definition round trips exactly',()=>{const w=work(),before=copy(w);assert.deepEqual(cleanWork(w),before);w.steps[0].options.annotations=[mark(w)];assert.deepEqual(cleanWork(w).steps[0].options.annotations,w.steps[0].options.annotations);});
test('reject invalid times, duplicate IDs, missing bindings and overflow without truncation',()=>{const a=mark();for(const alter of [a=>a.when.end=2,a=>a.when.start=1,a=>a.targets[0].recordId='',a=>a.text='',a=>delete a.binding]){const b=copy(a);alter(b);assert.throws(()=>cleanAnnotations([b]));}assert.throws(()=>cleanAnnotations([a,a]));assert.throws(()=>cleanAnnotations(Array.from({length:13},(_,i)=>({...a,id:'mark'+i}))));});
test('rename and reorder keep stable record identity and scientific decimal in caption',()=>{const w=work(),a=mark(w),doc=w.steps[0].doc,id=a.targets[0].recordId;doc.data.reverse();const row=doc.data.find(r=>r._id===id);row.label='复测对象';row.value=2.33e-9;assert.equal(annotationStatus(doc,a).valid,true);assert.match(annotationCaption(doc,a),/复测对象.*2.33e-9/);});
test('deletion, null and observation changes become unresolved, never point to the next row',()=>{const w=work(),a=mark(w),doc=w.steps[0].doc;doc.data[0].value=null;assert.match(annotationStatus(doc,a).reason,/缺失/);doc.data.shift();assert.match(annotationStatus(doc,a).reason,/移除/);doc.unit='比例';assert.match(annotationStatus(doc,a).reason,/单位/);});
test('editor materializing a default numeric axis does not change observation meaning',()=>{const w=work(),a=mark(w);w.steps[0].doc.axes={x:`数值 / ${w.steps[0].doc.unit}`,y:'类别'};assert.equal(annotationStatus(w.steps[0].doc,a).valid,true);w.steps[0].doc.axes.x='人均收入';assert.match(annotationStatus(w.steps[0].doc,a).reason,/含义/);});
test('paired order and method definitions belong to binding, not display names',()=>{for(const template of ['slope','blandaltman']){const step=makeStep({doc:getExample(template)}),a=newAnnotation(step.doc);assert.equal(annotationStatus(step.doc,a).valid,true);const key=template==='slope'?'periodLabels':'methodLabels';step.doc[key]=['测量 B','测量 A'];assert.match(annotationStatus(step.doc,a).reason,/含义/);}});
test('explicit multi-step annotation apply preserves docs, styles, rhythms; undo preserves later data edits',()=>{const w=work(),a=mark(w),ids=w.steps.map(s=>s.id),r=applyAnnotation(w,ids[0],a,ids);assert.deepEqual(r.work.steps.map(s=>s.doc),w.steps.map(s=>s.doc));for(let i=0;i<w.steps.length;i++)assert.deepEqual({...r.work.steps[i].options,annotations:undefined},{...w.steps[i].options,annotations:undefined});r.work.steps[1].doc.data[0].value=1.2e-8;r.work.steps[1].options.palette='blue';r.work.steps[1].hold=6000;r.work.steps.reverse();const undone=undoAnnotation(r.work,r.transaction);assert.ok(undone.steps.every(s=>!s.options.annotations));assert.equal(undone.steps.find(s=>s.id===ids[1]).doc.data[0].value,1.2e-8);assert.equal(undone.steps.find(s=>s.id===ids[1]).hold,6000);assert.ok(undoAnnotation(undone,r.transaction,{redo:true}).steps.every(s=>s.options.annotations.length===1));});
test('independent and incompatible targets fail atomically; later annotation edits block stale undo',()=>{const w=work(),a=mark(w),ids=w.steps.map(s=>s.id);w.steps[1].relation='separate';assert.throws(()=>applyAnnotation(w,ids[0],a,[ids[0],ids[1]]),/关联/);const r=applyAnnotation(w,ids[0],a);r.work.steps[0].options.annotations[0].text='后续编辑';assert.throws(()=>undoAnnotation(r.work,r.transaction),/后续/);assert.ok(!w.steps[0].options.annotations);});
test('data sync previews affected annotations and whole sync undo restores their bindings',()=>{const w=work(),a=mark(w);w.steps[1].options.annotations=[a];w.steps[0].doc.unit='千篇';const preview=previewDataSync(w,w.steps[0].id),target=preview.targets.find(t=>t.id===w.steps[1].id);assert.equal(target.annotationWarnings.length,1);const applied=applyDataSync(w,preview,[w.steps[1].id]);assert.equal(annotationStatus(applied.work.steps[1].doc,a).valid,false);const back=undoDataSync(applied.work,applied.transaction);assert.equal(annotationStatus(back.steps[1].doc,a).valid,true);});
test('relative timing works in holds, static images show all, and reduced motion keeps timing',()=>{const a=mark();a.when={start:.6,end:.8};assert.equal(annotationOpacity(a,.5),0);assert.equal(annotationOpacity(a,.7),1);assert.equal(annotationOpacity(a,.9),0);assert.equal(annotationOpacity(a,1,{staticFrame:true}),1);assert.equal(annotationOpacity(a,.61,{reducedMotion:true}),1);});
test('anchors use actual keyed contours at all five frames, forwards, backwards and repeated seek',()=>{const w=work(),a=mark(w),applied=applyAnnotation(w,w.steps[0].id,a,w.steps.map(s=>s.id)).work,host=document.createElement('div'),r=new frameModule.WorkFrameRenderer(host,applied.steps,{width:800,height:420});try{for(const [from,step]of [[applied.steps[0],applied.steps[1]],[applied.steps[1],applied.steps[2]],[applied.steps[2],applied.steps[0]]]){const plan=transitionPlan(from,step);let saved;for(const p of [0,.25,.5,.75,1,.5,.25,1]){r.render({index:applied.steps.indexOf(step),from,step,plan,progress:p});const anchor=annotationAnchor(r.scene,a.targets[0],'single');assert.ok(anchor?.path);const circle=host.querySelector('[data-annotation-id] circle');assert.ok(circle);assert.equal(Number(circle.getAttribute('cx')),anchor.point[0]);assert.equal(Number(circle.getAttribute('cy')),anchor.point[1]);if(p===.5){if(saved)assert.deepEqual(anchor,saved);else saved=anchor;}}}}finally{r.destroy();}});
test('native column anchors work without enabling cell editing',()=>{const step=makeStep({doc:getExample('column')}),a=newAnnotation(step.doc);step.options.annotations=[a];const host=document.createElement('div'),s=sceneModule.createStepScene(host,step,{nativeChart:true,width:800,height:420,editable:false});try{s.render(1);assert.ok(annotationAnchor(s,a.targets[0],'single'));assert.equal(host.querySelector('[data-annotation-state]').dataset.annotationState,'valid');}finally{s.destroy();}});
test('unresolved annotations stay visible and overfull layout blocks export without stale failure after time window',()=>{const w=work(),a=mark(w),host=document.createElement('div'),s=sceneModule.createStepScene(host,w.steps[0],{width:400,height:210,annotationAuto:false});try{w.steps[0].options.annotations=[a];w.steps[0].doc.data.shift();renderAnnotations(s,w.steps[0]);assert.equal(host.querySelector('[data-annotation-state]').dataset.annotationState,'unresolved');w.steps[0].options.annotations=Array.from({length:12},(_,i)=>({...newAnnotation(w.steps[0].doc,{kind:'note',text:'说明文字'.repeat(25)}),id:'overflow'+i,when:{start:0,end:.5}}));renderAnnotations(s,w.steps[0],{fraction:.25});assert.throws(()=>assertAnnotationLayout(s),/放不下/);renderAnnotations(s,w.steps[0],{fraction:.8});assert.doesNotThrow(()=>assertAnnotationLayout(s));}finally{s.destroy();}});
test('work video renderer updates timed annotation inside settled hold; image export includes it',()=>{const w=work(),a=mark(w);a.when={start:.65,end:.85};w.steps[0].options.annotations=[a];const r=videoModule.createWorkExportRenderer(w);try{assert.doesNotMatch(r.frame(1800),/关键观测/);assert.match(r.frame(2700),/关键观测/);assert.doesNotMatch(r.frame(3500),/关键观测/);assert.match(exportModule.stepSVG(w.steps[0],w.steps),/关键观测/);}finally{r.destroy();}});
test('Agent and chart-copy contracts preserve annotation identity and timing',()=>{const w=work(),a=mark(w);w.steps[0].options.annotations=[a];const text=exportModule.workAgentBrief(w),opts=actionsModule.normalizeChartOptions(w.steps[0].options,w.steps[0].doc);assert.match(text,/targets.recordId/);assert.match(text,/when.start/);assert.deepEqual(opts.annotations,[a]);});
test('annotation boxes interpolate rather than choosing a different location on each intermediate frame',()=>{const w=work(),a=mark(w),ready=applyAnnotation(w,w.steps[0].id,a,w.steps.map(s=>s.id)).work,host=document.createElement('div'),r=new frameModule.WorkFrameRenderer(host,ready.steps,{width:800,height:420}),from=ready.steps[0],step=ready.steps[2],plan=transitionPlan(from,step);try{const at=p=>{r.render({index:2,from,step,plan,progress:p});return {...r.scene.annotationPositions.get(a.id)};},start=at(0),end=at(1),mid=at(.5),q=1-(1-.5)**3;assert.ok(Math.abs(mid.x-(start.x+(end.x-start.x)*q))<1e-7);assert.ok(Math.abs(mid.y-(start.y+(end.y-start.y)*q))<1e-7);const shown=at(.4);r.render({index:1,from:step,step:ready.steps[1],plan:transitionPlan(step,ready.steps[1]),progress:0,retarget:true});for(const key of ['x','y','w','h'])assert.equal(r.scene.annotationPositions.get(a.id)[key],shown[key]);}finally{r.destroy();}});
test('annotation editor creates, applies to selected steps, persists and undoes only annotations',async t=>{const f=await fixture(t),w=f.app.getWork();f.host.querySelector('[data-we-tool=annotations]').click();f.host.querySelector('[data-an-add]').click();change(f.host,'[data-an-text]','研究重点');const targets=f.host.querySelectorAll('[data-an-scope]:not(:disabled)');assert.equal(targets.length,3);targets[0].click();f.host.querySelector('[data-an-form]').dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));await settle();await f.app.flush();let next=f.app.getWork();assert.equal(next.steps[0].options.annotations[0].text,'研究重点');assert.equal(next.steps[1].options.annotations[0].text,'研究重点');assert.equal(next.steps[2].options.annotations,undefined);assert.equal(f.repo.peek(next.id).work.steps[0].options.annotations[0].text,'研究重点');f.host.querySelector('[data-we-tool=data]').click();change(f.host,'[data-dw-cell="0:1"]','2.33e-9');f.host.querySelector('[data-we-tool=annotations]').click();f.host.querySelector('[data-an-history=undo]').click();await settle();next=f.app.getWork();assert.ok(!next.steps[0].options.annotations);assert.ok(!next.steps[1].options.annotations);assert.equal(next.steps[0].doc.data[0].value,2.33e-9);assert.equal(next.steps[0].id,w.steps[0].id);});
test('unfinished annotation draft survives switching step; delete, undo and redo are usable',async t=>{const f=await fixture(t),steps=f.app.getWork().steps;f.host.querySelector('[data-we-tool=annotations]').click();f.host.querySelector('[data-an-add]').click();change(f.host,'[data-an-text]','暂未应用的说明');f.host.querySelector('[data-we=next-step]').click();f.host.querySelector('[data-we=previous-step]').click();assert.equal(f.host.querySelector('[data-an-text]').value,'暂未应用的说明');assert.equal(f.app.getWork().steps[0].options.annotations,undefined);f.host.querySelector('[data-an-form]').dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));await settle();f.host.querySelector('[data-an-remove]').click();await settle();assert.ok(!f.app.getWork().steps[0].options.annotations);assert.equal(f.host.querySelector('[data-an-select]'),null);f.host.querySelector('[data-an-history=undo]').click();await settle();assert.equal(f.app.getWork().steps[0].options.annotations.length,1);f.host.querySelector('[data-an-history=redo]').click();await settle();assert.ok(!f.app.getWork().steps[0].options.annotations);});
test('invalid form stays unapplied; semantic rebind requires explicit confirmation',async t=>{const w=work(),a=mark(w);w.steps[0].options.annotations=[a];w.steps[0].doc.unit='千篇';const f=await fixture(t,w);f.host.querySelector('[data-we-tool=annotations]').click();f.host.querySelector('[data-an-select]').click();change(f.host,'[data-an-time=start]','3');change(f.host,'[data-an-time=end]','1');f.host.querySelector('[data-an-form]').dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));await settle();assert.match(f.host.querySelector('[data-an-status]').textContent,/时间/);change(f.host,'[data-an-time=start]','0');change(f.host,'[data-an-time=end]','3.7');f.host.querySelector('[data-an-form]').dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));await settle();assert.match(f.host.querySelector('[data-an-status]').textContent,/单位/);f.host.querySelector('[data-an-confirm]').click();f.host.querySelector('[data-an-form]').dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));await settle();assert.equal(f.app.getWork().steps[0].options.annotations[0].binding.unit,'千篇');});
