import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {IDBFactory} from 'fake-indexeddb';
import {Window} from 'happy-dom';
import {createServer} from 'vite';
import {openWorkStore} from '../../src/forma/work-store.js';
import {presetWork} from '../../src/forma/work-model.js';
let win,server,mountWorkEditor,mountBrandPanel,mountStandalone;const old=new Map();
before(async()=>{win=new Window({url:'http://localhost:4205/'});for(const [k,v] of Object.entries({window:win,document:win.document,XMLSerializer:win.XMLSerializer,ResizeObserver:win.ResizeObserver,requestAnimationFrame:win.requestAnimationFrame.bind(win),cancelAnimationFrame:win.cancelAnimationFrame.bind(win)})){old.set(k,Object.getOwnPropertyDescriptor(globalThis,k));Object.defineProperty(globalThis,k,{value:v,configurable:true,writable:true});}server=await createServer({server:{middlewareMode:true,hmr:false},appType:'custom'});({mountWorkEditor}=await server.ssrLoadModule('/src/forma/work-editor.js'));({mountBrandPanel}=await server.ssrLoadModule('/src/forma/brand-panel.js'));({mount:mountStandalone}=await server.ssrLoadModule('/src/forma/work-player-entry.js'));});
after(async()=>{await server?.close();await win?.happyDOM.close();for(const [k,v] of old){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];}});
const settle=()=>new Promise(r=>setTimeout(r,80)),storage=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)};};
function change(host,selector,value,event='change'){const node=host.querySelector(selector);assert.ok(node,selector);node.value=value;node.dispatchEvent(new win.Event(event,{bubbles:true}));}
async function fixture(t){const repo=await openWorkStore({indexedDB:new IDBFactory(),name:crypto.randomUUID(),storage:storage(),broadcast:false}),host=document.createElement('main');document.body.append(host);const app=mountWorkEditor(host,{repository:repo,storage:storage(),initial:presetWork('essential')});await app.flush();t.after(()=>{app.destroy();repo.close();host.remove();});return{repo,host,app};}
async function openBrand(f){f.host.querySelector('[data-we-tool=style]').click();f.host.querySelector('[data-we=brand]').click();await settle();assert.ok(f.host.querySelector('[data-brand-name]'));}

test('brand UI previews locally, saves reusable profile, applies all, and undo keeps later data edit',async t=>{const f=await fixture(t),before=f.app.getWork();await openBrand(f);assert.equal(f.host.querySelector('[data-we-panel]').getAttribute('aria-modal'),'false');change(f.host,'[data-brand-name]','年度研究','input');f.host.querySelector('[data-brand-type=editorial]').click();change(f.host,'[data-brand-ratio]','portrait');assert.deepEqual(f.app.getWork().steps,before.steps);f.host.querySelector('[data-brand-save]').click();await settle();assert.equal((await f.repo.brands())[0].profile.name,'年度研究');f.host.querySelector('[data-brand-apply]').click();await settle();await f.app.flush();const work=f.app.getWork();assert.ok(work.steps.every(s=>s.options.brand.name==='年度研究'&&s.options.ratio==='portrait'));assert.deepEqual(work.steps.map(s=>s.doc),before.steps.map(s=>s.doc));assert.ok(f.host.querySelector('[data-we=undo-brand]'));f.host.querySelector('[data-we-tool=data]').click();change(f.host,'[data-dw-cell="0:1"]','2.33e-9','input');await f.app.flush();f.host.querySelector('[data-we-tool=style]').click();f.host.querySelector('[data-we=undo-brand]').click();await settle();await f.app.flush();assert.deepEqual(f.app.getWork().steps.map(s=>s.options),before.steps.map(s=>s.options));assert.equal(f.app.getWork().steps[0].doc.data[0].value,2.33e-9);});
test('scope current changes only active step; reopen and video panel default retain branded ratio',async t=>{const f=await fixture(t),before=f.app.getWork();await openBrand(f);change(f.host,'[data-brand-ratio]','story');f.host.querySelector('[data-brand-scope][value=current]').click();f.host.querySelector('[data-brand-apply]').click();await settle();await f.app.flush();const work=f.app.getWork();assert.deepEqual(work.steps.slice(1),before.steps.slice(1));const host=document.createElement('main');document.body.append(host);const app=mountWorkEditor(host,{repository:f.repo,storage:storage()});t.after(()=>{app.destroy();host.remove();});assert.equal(app.getWork().steps[0].options.brand.typography,'sans');assert.equal(app.getWork().steps[0].options.ratio,'story');host.querySelector('[data-we=export]').click();host.querySelector('[data-we=video]').click();assert.equal(host.querySelector('[data-we-video=ratio]').value,'story');});
test('slow profile commit locks fields; failed commit reports error and re-enables editing',async t=>{const step=presetWork('essential').steps[0],host=document.createElement('div');document.body.append(host);let release;const repo={available:true,brands:async()=>[],saveBrand:()=>new Promise((_,reject)=>release=()=>reject(new Error('空间不足')))};const app=mountBrandPanel(host,{repository:repo,step,steps:[step],onApply(){}});t.after(()=>{app.destroy();host.remove();});await settle();host.querySelector('[data-brand-save]').click();assert.equal(host.querySelector('[data-brand-name]').disabled,true);release();await settle();assert.equal(host.querySelector('[data-brand-name]').disabled,false);assert.match(host.querySelector('[data-brand-status]').textContent,/空间不足/);change(host,'[data-brand-name]',' ','input');assert.equal(host.querySelector('[data-brand-apply]').disabled,true);});
test('pending logo decode cannot replace newly selected profile',async t=>{const step=presetWork('essential').steps[0],host=document.createElement('div');document.body.append(host);let release;const Image=win.Image;win.Image=class{naturalWidth=1;naturalHeight=1;decode(){return new Promise(resolve=>release=resolve);}};const app=mountBrandPanel(host,{repository:{brands:async()=>[]},step,steps:[step],onApply(){}});t.after(()=>{app.destroy();host.remove();win.Image=Image;});const file=host.querySelector('[data-brand-file]');Object.defineProperty(file,'files',{value:[new win.File(['png'],'test.png',{type:'image/png'})],configurable:true});file.dispatchEvent(new win.Event('change',{bubbles:true}));await settle();assert.equal(host.querySelector('[data-brand-apply]').disabled,true);change(host,'[data-brand-saved]','');release();await settle();assert.equal(host.querySelector('[data-brand-preview-logo]').hidden,true);assert.equal(host.querySelector('[data-brand-apply]').disabled,false);});
test('standalone branded work switches export ratio with selected step and keeps the original player controls',async t=>{const work=presetWork('essential');work.steps[0].options.brand={name:'研究',typography:'editorial'};work.steps[0].options.ratio='story';work.steps[1].options.brand={name:'研究',typography:'mono'};work.steps[1].options.ratio='square';const host=document.createElement('main');document.body.append(host);const app=mountStandalone(host,work);t.after(()=>{app.destroy();host.remove();});assert.equal(parseFloat(host.querySelector('[data-wp-stage]').style.aspectRatio),9/16);host.querySelectorAll('[data-wp-step]')[1].click();await settle();assert.equal(parseFloat(host.querySelector('[data-wp-stage]').style.aspectRatio),1);});
