import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {color as parseColor,interpolateRgb} from 'd3';
import {getExample,findTemplate} from '../../src/forma/catalog.js';
import {withRecordIds,recordId} from '../../src/forma/data-identity.js';
import {setLocale} from '../../src/forma/locale.js';
import {themeFor} from '../../src/forma/palettes.js';
import {hexbinLayout,regularGrid} from '../../src/forma/volume6-data.js';
import {bins12,densityGrid12,bivariateDensity12} from '../../src/forma/volume12-data.js';
import {completionSpatialViews as views,completionSpatialViewMap as nativeMap,completionSpatialDocument as adapt,completionSpatialEligibility as eligible,completionSpatialCompatibility as compatible,completionSpatialBounds as bounds,completionSpatialColorSubjects as subjects,completionSpatialColorKeys as colorKeys,completionSpatialGuide as guide,completionSpatialAgentGuide as agentGuide,completionSpatialNames} from '../../src/forma/completion-spatial-rules.js';
import {layoutCompletionSpatial as layout,completionSpatialProjector} from '../../src/forma/completion-spatial-morph.js';
import {completionSpatialPresets as presets,completionSpatialRecords as records} from '../../src/forma/completion-spatial-presets.js';
import {ScientificMorphChart} from '../../src/forma/scientific-morph.js';
import {ChartScene} from '../../src/forma/charts.js';
import {newWork,cleanWork,stepReport,morphReady,transitionPlan} from '../../src/forma/work-model.js';
import {workColorMap,createStepScene} from '../../src/forma/work-scene.js';
import {stepSVG} from '../../src/forma/work-export.js';
import {createEditorModel} from '../../src/forma/editor-model.js';
const raw=t=>withRecordIds(getExample(t),{legacyNamespace:'completion-spatial-qa:'+t}),doc=t=>adapt(raw(t)),originals=l=>l.marks.filter(m=>m.original),near=(a,b)=>assert.ok(Math.abs(a-b)<=1e-9*Math.max(1,Math.abs(a),Math.abs(b)),`${a} ≠ ${b}`),finite=l=>{assert.equal(new Set(l.marks.map(m=>m.key)).size,l.marks.length);for(const m of l.marks){assert.equal(m.points.length,128,m.key);assert.equal(m.entrance.length,128,m.key);assert.ok(m.points.flat().every(Number.isFinite),m.key);assert.ok(m.entrance.flat().every(Number.isFinite),m.key);}};

test('nine native contracts retain every original field, source, unit and independent edit targets',()=>{
 assert.equal(Object.keys(nativeMap).length,9);assert.equal(views.length,18);
 for(const[template,view]of Object.entries(nativeMap)){const source=raw(template),before=structuredClone(source),d=adapt(source);assert.equal(eligible(d,view).valid,true,template);assert.deepEqual(source,before);assert.equal(d.data.length,source.data.length);assert.equal(d.unit,source.unit);assert.deepEqual(d.axes,source.axes);assert.deepEqual(d.source,source.source);for(const[r,i]of d.data.map((r,i)=>[r,i])){assert.equal(r.inputIndex,i);for(const[k,v]of Object.entries(source.data[i]))assert.deepEqual(r[k],v,k);}
  for(const v of views.filter(v=>v.family===d.family))for(const[w,h]of[[300,240],[800,440],[1280,720]]){const l=layout(d,v.id,w,h);finite(l);const ids=new Set(originals(l).map(m=>m.identity));assert.deepEqual([...ids].sort(),source.data.map(recordId).sort());for(const m of originals(l)){assert.equal(m.identity,recordId(source.data[m.row]));assert.equal(m.value,source.data[m.row][m.editable]);assert.ok(findTemplate(template).fields.some(([f])=>f===m.editable));assert.ok(m.opacity>0);assert.equal(m.recordIds,undefined);}for(const m of l.marks.filter(m=>m.derived)){assert.ok(Array.isArray(m.recordIds));assert.equal(m.editable,undefined);assert.ok(m.recordIds.every(id=>ids.has(id)));}}
 }
 const bars=doc('bars3d');assert.equal(typeof bars.data[0].row,'string');
});

test('sample-grid cells use the actual regular grid and original values, including negative constants',()=>{
 const d=doc('contour'),grid=regularGrid(d.data),a=layout(d,nativeMap.contour),b=layout(d,'complete-spatial-sampled-grid');assert.deepEqual(b.statistics.grid.xs,grid.xs);assert.deepEqual(b.statistics.grid.ys,grid.ys);for(const m of originals(b)){const r=d.data[m.row];near(b.scales.x.invert(m.point[0]),r.x);near(b.scales.y.invert(m.point[1]),r.y);assert.equal(m.value,r.value);assert.ok(m.cell[2]>0&&m.cell[3]>0);assert.ok(m.cell[0]>=b.plot.x-1e-8&&m.cell[1]>=b.plot.y-1e-8);}assert.equal(a.marks.filter(m=>m.role==='isoline').length,b.marks.filter(m=>m.role==='isoline').length);assert.ok(a.marks.some(m=>m.role==='isoline'&&m.opacity>0));assert.ok(b.marks.filter(m=>m.role==='isoline').every(m=>m.opacity===0));const constant=structuredClone(d);constant.data.forEach(r=>r.value=-7);for(const v of views.filter(v=>v.family===d.family)){assert.equal(eligible(constant,v.id).valid,true);finite(layout(constant,v.id,300,240));}
});

test('hexagonal bins reuse native normalized-grid membership and release all original coordinates',()=>{
 const d=doc('hexbin'),before=structuredClone(d),model=hexbinLayout(d),a=layout(d,nativeMap.hexbin),b=layout(d,'complete-spatial-hex-samples'),bins=a.marks.filter(m=>m.role==='hex-bin');assert.equal(bins.length,model.bins.length);assert.equal(bins.reduce((sum,m)=>sum+m.count,0),d.data.length);for(const bin of model.bins)assert.ok(bins.some(m=>JSON.stringify([...m.recordIds].sort())===JSON.stringify(bin.map(recordId).sort())&&m.count===bin.length));for(const m of originals(b)){const r=d.data[m.row];near(b.scales.x.invert(m.point[0]),r.x);near(b.scales.y.invert(m.point[1]),r.y);assert.equal(m.binDisplay,false);}assert.ok(originals(a).some(m=>m.point[0]!==m.originalPoint[0]||m.point[1]!==m.originalPoint[1]));assert.deepEqual(d,before);const repeated=structuredClone(d);repeated.data.forEach(r=>{r.x=7;r.y=-3;});assert.equal(eligible(repeated,nativeMap.hexbin).valid,true);finite(layout(repeated,'complete-spatial-hex-samples',300,240));assert.equal(layout(repeated,nativeMap.hexbin).marks.filter(m=>m.role==='hex-bin')[0].count,repeated.data.length);
});

test('native grid columns use the original orthographic world ranges and unfold with common zero baseline',()=>{
 const d=doc('bars3d');d.data[0].value=0;const a=layout(d,nativeMap.bars3d),b=layout(d,'complete-spatial-bars-unfold'),project=completionSpatialProjector(a.plot);for(const m of originals(a)){const r=d.data[m.row],ri=a.statistics.rowNames.indexOf(r.row),ci=a.statistics.columns.indexOf(r.column),world=[a.scales.worldX(ci),a.scales.worldZ(r.value),a.scales.worldY(ri)];assert.deepEqual(m.world,world);assert.deepEqual(m.point,project(world));const n=originals(b).find(n=>n.key===m.key);near(b.scales.ys[ri].invert(n.point[1]),r.value);assert.equal(b.scales.ys[ri].domain()[0],0);assert.equal(n.zero,r.value===0);}assert.ok(a.marks.filter(m=>m.role==='box-side').every(m=>m.opacity>0));assert.deepEqual(b.scales.ys.map(s=>s.domain()),b.statistics.rowNames.map(()=>b.statistics.valueDomain));
});

test('dated three-dimensional paths unfold all components on their own raw scales and true date spacing',()=>{
 const d=doc('trajectory3d');d.data[1].period='2025-01-03';const before=structuredClone(d),a=layout(d,nativeMap.trajectory3d),b=layout(d,'complete-spatial-trajectory-profiles');assert.equal(eligible(d,nativeMap.trajectory3d).valid,true);assert.equal(originals(a).length,d.data.length*3);for(const m of originals(b)){const r=d.data[m.row],j=['x','y','z'].indexOf(m.component);near(+b.scales.x.invert(m.point[0]),Date.parse(r.period));near(b.scales.ys[j].invert(m.point[1]),r[m.component]);assert.equal(m.value,r[m.component]);assert.equal(m.latest,r.period===b.statistics.ordered.at(-1).period);}assert.equal(b.marks.filter(m=>m.role.startsWith('observed-connection-')).length,(d.data.length-1)*3);const shuffled=structuredClone(d);shuffled.data.reverse();const other=layout(shuffled,'complete-spatial-trajectory-profiles');assert.deepEqual(other.statistics.ordered.map(recordId),b.statistics.ordered.map(recordId));assert.deepEqual(d,before);
});

test('field vectors preserve equal physical scales, shared lengths, sign colors and zero observations',()=>{
 const d=doc('vectorfield');d.data[0].u=0;d.data[0].v=0;const before=structuredClone(d),a=layout(d,nativeMap.vectorfield),b=layout(d,'complete-spatial-vector-components');for(const l of[a,b]){near((l.scales.x(1)-l.scales.x(0)),Math.abs(l.scales.y(1)-l.scales.y(0)));const vectors=l.marks.filter(m=>m.role==='vector');assert.equal(vectors.length,d.data.length);assert.equal(new Set(vectors.map(m=>m.vectorScale)).size,1);for(const m of vectors){const r=d.data.find(r=>m.recordIds[0]===recordId(r));near((m.vectorEnd[0]-m.vectorStart[0])/ (m.vectorScale||1),r.u);near(-(m.vectorEnd[1]-m.vectorStart[1])/(m.vectorScale||1),r.v);if(l===b){near(l.scales.x.invert(m.vectorStart[0]),0);near(l.scales.y.invert(m.vectorStart[1]),0);}if(r.u===0&&r.v===0)assert.equal(m.opacity,0);else assert.equal(m.nativeColorRole,r.v>=0?'accent':'fg');}assert.ok(originals(l).some(m=>m.zero&&m.opacity>0));}assert.deepEqual(d,before);const zeros=structuredClone(d);zeros.data.forEach(r=>{r.u=0;r.v=0;});for(const v of views.filter(v=>v.family===d.family)){assert.equal(eligible(zeros,v.id).valid,true);finite(layout(zeros,v.id,300,240));}
});

test('Voronoi nearest regions keep all sites and provenance while contracting without encoding region area',()=>{
 const d=doc('voronoi'),a=layout(d,nativeMap.voronoi),b=layout(d,'complete-spatial-sites');for(const l of[a,b]){near(l.scales.x(1)-l.scales.x(0),Math.abs(l.scales.y(1)-l.scales.y(0)));const cells=l.marks.filter(m=>m.role==='nearest-cell');assert.equal(cells.length,d.data.length);assert.ok(cells.every(m=>m.derived&&m.recordIds.length===1));for(const m of originals(l)){const r=d.data[m.row];near(l.scales.x.invert(m.point[0]),r.x);near(l.scales.y.invert(m.point[1]),r.y);}}for(const m of b.marks.filter(m=>m.role==='nearest-cell'))near(Math.hypot(m.points[0][0]-m.point[0],m.points[0][1]-m.point[1]),6);assert.deepEqual(a.marks.map(m=>m.key).sort(),b.marks.map(m=>m.key).sort());
});

test('spatial lines preserve explicit period and series order plus one common raw-value scale',()=>{
 const d=doc('lines3d'),b=layout(d,'complete-spatial-line-panels');for(const m of originals(b)){const r=d.data[m.row],si=d.seriesOrder.indexOf(r.series),pi=d.periodOrder.indexOf(r.period);near(b.scales.x.invert(m.point[0]),pi);near(b.scales.ys[si].invert(m.point[1]),r.value);}assert.deepEqual(b.scales.ys.map(s=>s.domain()),d.seriesOrder.map(()=>b.statistics.valueDomain));const shuffled=structuredClone(d);shuffled.data.reverse();assert.equal(compatible(d,shuffled),'');const other=layout(shuffled,'complete-spatial-line-panels');assert.deepEqual(other.statistics.periods,d.periodOrder);assert.deepEqual(other.statistics.series,d.seriesOrder);shuffled.periodOrder.reverse();assert.notEqual(compatible(d,shuffled),'');
});

test('rectangular count bins preserve exact native boundaries, maxima, zero cells and complete sample totals',()=>{
 const d=doc('histogram2d'),model=bins12(d.data,d.binsX,d.binsY);for(const v of views.filter(v=>v.family===d.family)){const l=layout(d,v.id),cells=l.marks.filter(m=>m.role==='count-bin');assert.equal(cells.length,d.binsX*d.binsY);assert.equal(cells.reduce((sum,c)=>sum+c.count,0),d.data.length);assert.ok(cells.some(c=>c.count===0&&c.opacity>0));for(const c of model.cells){const m=cells.find(m=>m.ix===c.ix&&m.iy===c.iy);assert.equal(m.count,c.count);assert.deepEqual(m.recordIds,c.rows.map(recordId));assert.equal(m.derived,true);if(v.id==='complete-spatial-bin-counts')near(l.scales.y.invert(m.point[1]),c.count);}assert.equal(originals(l).length,d.data.length*2);}const a=layout(d,nativeMap.histogram2d),b=layout(d,'complete-spatial-bin-counts');assert.ok(a.marks.filter(m=>m.role==='count-bin').some(m=>JSON.stringify(m.points)!==JSON.stringify(b.marks.find(n=>n.key===m.key).points)));
});

test('joint KDE evaluations reuse original bandwidths, complete raw samples and native peak-relative levels',()=>{
 const d=doc('density2d'),before=structuredClone(d),native=densityGrid12(d.data,d.bandwidthX,d.bandwidthY),a=layout(d,nativeMap.density2d),b=layout(d,'complete-spatial-density-samples');assert.deepEqual(a.statistics.values,native.values);assert.deepEqual(a.statistics.levels,[.15,.3,.5,.7,.9].map(q=>q*native.max));for(const m of originals(b)){const r=d.data[m.row],expected=bivariateDensity12(d.data,r.x,r.y,d.bandwidthX,d.bandwidthY);near(b.scales.x.invert(m.point[0]),r.x);near(b.scales.y.invert(m.point[1]),expected);near(m.density,expected);assert.equal(m.value,r[m.editable]);assert.ok(m.tooltip.includes(String(r.y)));}assert.deepEqual(d,before);
});

test('invalid original tables and incompatible metadata are rejected without repairing or deleting records',()=>{
 for(const[template,view]of Object.entries(nativeMap)){const d=doc(template),invalid=structuredClone(d),field=originals(layout(d,view))[0].editable;invalid.data[0][field]=null;assert.equal(eligible(invalid,view).valid,false,template);for(const change of[x=>x.unit='other',x=>x.source.name='other',x=>x.axes={x:'changed'},x=>x.data[0]._id='different']){const other=structuredClone(d);change(other);assert.notEqual(compatible(d,other),'');}invalid.data[0]._id=invalid.data[1]._id;assert.equal(eligible(invalid,view).valid,false);}
 for(const[template,fields]of[['hexbin',['binRadius']],['histogram2d',['binsX','binsY']],['density2d',['bandwidthX','bandwidthY']]])for(const field of fields){const a=doc(template),b=structuredClone(a);b[field]+=1;assert.notEqual(compatible(a,b),'');}
 for(const template of['bars3d','lines3d','voronoi']){const d=doc(template);for(const property of Object.keys(d).filter(k=>k.endsWith('Order'))){const invalid=structuredClone(d);invalid[property]=['missing'];assert.equal(eligible(invalid,nativeMap[template]).valid,false);assert.doesNotThrow(()=>subjects(invalid));}}
});

test('group palettes remain identified by original populations through complete category renames and row reorder',()=>{
 for(const template of['bars3d','lines3d','voronoi']){const d=doc(template),changed=structuredClone(d),field=template==='bars3d'?'row':template==='lines3d'?'series':'group',property=field==='row'?'rowOrder':field==='series'?'seriesOrder':'groupOrder';changed.data.reverse();changed.data.forEach(r=>r[field]='Rename '+r[field]);changed[property]=changed[property].map(v=>'Rename '+v);assert.equal(compatible(d,changed),'');assert.deepEqual(colorKeys(d).sort(),colorKeys(changed).sort());assert.deepEqual(subjects(d).map(s=>s.id).sort(),subjects(changed).map(s=>s.id).sort());for(const v of views.filter(v=>v.family===d.family))finite(layout(changed,v.id));}
});

test('eighteen morph directions keep real DOM shapes, exact endpoints, reverse seeks and interrupted contours',async()=>{
 let count=0;for(const preset of presets){const d=adapt(records(preset.id)[0].doc);for(const from of preset.views)for(const to of preset.views){if(from===to)continue;count++;const win=new Window();try{const chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:from,width:800,height:440,editable:true}),nodes=new Map([...chart.nodes].map(([k,n])=>[k,n.shape])),a=chart.layout,seek=chart.setDocument(d,to,{manual:true,effect:'guided'}),b=chart.layout;assert.deepEqual(a.marks.map(m=>m.key).sort(),b.marks.map(m=>m.key).sort());seek(.5);const middle=structuredClone([...chart.current]);assert.ok([...chart.current.values()].flat(2).every(Number.isFinite));assert.ok(b.marks.some(m=>m.opacity>0&&JSON.stringify(chart.current.get(m.key))!==JSON.stringify(a.marks.find(n=>n.key===m.key).points)&&JSON.stringify(chart.current.get(m.key))!==JSON.stringify(m.points)),from);seek(1);seek(.5);assert.deepEqual([...chart.current],middle);seek(0);for(const m of a.marks)assert.deepEqual(chart.current.get(m.key),m.points,m.key);seek(1);for(const m of b.marks)assert.deepEqual(chart.current.get(m.key),m.points,m.key);for(const[k,node]of nodes)assert.equal(chart.nodes.get(k).shape,node);seek(.37);const interrupted=structuredClone([...chart.current]),resume=chart.setDocument(d,from,{manual:true,resume:true,effect:'guided'});resume(0);assert.deepEqual([...chart.current],interrupted);resume(.71);resume(1);for(const m of chart.layout.marks)assert.deepEqual(chart.current.get(m.key),m.points,m.key);for(const m of originals(chart.layout)){const node=chart.nodes.get(m.key);assert.equal(node.group.dataset.editField,m.editable);assert.equal(Number(node.group.dataset.editRow),m.row);}assert.doesNotMatch(chart.svg.outerHTML,/NaN|Infinity|undefined/);chart.destroy();}finally{await win.happyDOM.close();}}}assert.equal(count,18);
});

test('all spatial scenarios round-trip original tables, preserve plans and export finite SVG',async t=>{
 const win=new Window(),prior=new Map();for(const[k,value]of Object.entries({document:win.document,XMLSerializer:win.XMLSerializer})){prior.set(k,Object.getOwnPropertyDescriptor(globalThis,k));Object.defineProperty(globalThis,k,{value,configurable:true,writable:true});}t.after(async()=>{for(const[k,p]of prior){if(p)Object.defineProperty(globalThis,k,p);else delete globalThis[k];}await win.happyDOM.close();});assert.equal(presets.length,9);assert.equal(records('missing'),null);
 for(const p of presets){const work=newWork(records(p.id,'vermilion'));assert.deepEqual(cleanWork(JSON.parse(JSON.stringify(work))),work);for(const step of work.steps){assert.equal(stepReport(step).valid,true,step.view);assert.equal(morphReady(step),true);assert.deepEqual(step.doc.data,work.steps[0].doc.data);assert.doesNotMatch(stepSVG(step,work.steps).replace(/url\([^)]*base64[^)]*\)/g,''),/NaN|Infinity|undefined/);assert.doesNotThrow(()=>workColorMap(step,work.steps));const scene=createStepScene(win.document.createElement('div'),step,{width:390,height:320});try{scene.render(.5);assert.doesNotMatch(scene.svg.outerHTML,/NaN|Infinity|undefined/);}finally{scene.destroy();}}for(const a of work.steps)for(const b of work.steps)if(a.id!==b.id)assert.equal(transitionPlan(a,b,{steps:work.steps}).mode,'morph',a.view+' → '+b.view);}
});

test('native editors modify only original fields and retain every stable record and physical parameter',()=>{
 for(const template of Object.keys(nativeMap)){const source=raw(template),editor=createEditorModel(source),field=template==='contour'||template==='bars3d'||template==='lines3d'?'value':template==='vectorfield'?'u':'x',column=findTemplate(template).fields.findIndex(([f])=>f===field),value=source.data[0][field]+.0125,ids=editor.recordIds();editor.setCell(0,column,String(value));assert.equal(editor.report.valid,true,template);assert.deepEqual(editor.recordIds(),ids);assert.equal(editor.doc.data[0][field],value);for(const key of['unit','axes','binRadius','binsX','binsY','bandwidthX','bandwidthY'])assert.deepEqual(editor.doc[key],source[key]);assert.equal(editor.doc.data[0].projection,undefined);assert.ok(originals(layout(adapt(editor.doc),nativeMap[template])).some(m=>m.row===0&&m.value===value));}
});

test('native grouped renderer overrides and morph colors share exact population keys',async()=>{
 const win=new Window(),prior={document:globalThis.document,window:globalThis.window};globalThis.document=win.document;globalThis.window=win;try{for(const template of['bars3d','lines3d','voronoi']){const original=raw(template),bindings=subjects(original).map(s=>({id:s.id,color:'#347855'})),scene=new ChartScene(win.document.createElement('div'),original,{width:800,height:440,interactive:false,colorBindings:bindings});try{scene.render(1);assert.ok([...scene.svg.querySelectorAll('path,circle,line,rect')].filter(el=>!el.closest('defs')).some(el=>[el.getAttribute('fill'),el.getAttribute('stroke'),el.getAttribute('style')].some(v=>v==='#347855'||v==='rgb(52,120,85)'||v?.includes('fill:rgb(52,120,85)'))),template);}finally{scene.destroy();}const d=adapt(original);for(const v of views.filter(v=>v.family===d.family)){const chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:v.id,width:800,height:440,colorBindings:bindings});try{for(const m of originals(chart.layout))assert.equal(parseColor(chart.markColor(m)).formatHex(),'#347855',v.id);}finally{chart.destroy();}}}}finally{globalThis.document=prior.document;globalThis.window=prior.window;await win.happyDOM.close();}
});

test('native 3D bindings colour real materials and visible data faces independently of Lambert shading',async()=>{
 const win=new Window(),prior={document:globalThis.document,window:globalThis.window};globalThis.document=win.document;globalThis.window=win;
 try{for(const template of ['bars3d','lines3d']){const d=raw(template),colors=['#255879','#b75d48','#7b7c45','#805e95'],bindings=subjects(d).map((s,i)=>({id:s.id,color:colors[i%colors.length]})),scene=new ChartScene(win.document.createElement('div'),d,{width:900,height:550,interactive:false,palette:'ink',colorMode:'categorical',colorBindings:bindings});
  try{scene.render(1);const keys=colorKeys(d);for(const entry of scene.spatial.entries){const sourceIndex=d.data.findIndex(row=>recordId(row)===recordId(entry.row)),expected=bindings.find(b=>b.id===keys[sourceIndex]).color;assert.equal('#'+entry.mesh.material.color.getHexString(),expected,'body material uses the persistent binding');}
   const faces=[...scene.svg.querySelectorAll('[data-spatial-renderer] path')];for(const binding of bindings)assert.ok(faces.some(path=>[path.getAttribute('fill'),path.getAttribute('stroke')].includes(binding.color)),template+' original colour is visible on the real body/line');for(const face of faces)assert.equal((face.getAttribute('d').match(/M/g)||[]).length,1,'primitive geometry does not depend on paint batching');
  }finally{scene.destroy();}
 }}finally{globalThis.document=prior.document;globalThis.window=prior.window;await win.happyDOM.close();}
});

test('native color formulas for contour, hex counts, count bins and density levels remain exact',async()=>{
 const win=new Window();try{for(const template of['contour','hexbin','histogram2d','density2d'])for(const palette of['vermilion','cobalt']){const d=doc(template),theme=themeFor(palette),chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:nativeMap[template],width:800,height:440,palette});try{for(const m of chart.layout.marks){let expected;if(template==='contour'&&m.original)expected=theme.fg;else if(template==='contour'&&m.role==='isoline')expected=theme.accent;else if(template==='hexbin'&&m.role==='hex-bin')expected=interpolateRgb(theme.soft,theme.accent)(m.tone);else if(['histogram2d','density2d'].includes(template)&&m.derived)expected=interpolateRgb(theme.bg,theme.accent)(m.tone);if(expected)assert.equal(parseColor(chart.markColor(m)).formatHex(),parseColor(expected).formatHex(),template);}}finally{chart.destroy();}}}finally{await win.happyDOM.close();}
});

test('finite extremes, native capacities and compact canvases preserve all originals',()=>{
 const capacities={hexbin:600,bars3d:36,trajectory3d:60,vectorfield:100,voronoi:50,lines3d:64,histogram2d:500,density2d:400,contour:400};
 for(const[template,n]of Object.entries(capacities)){const d=doc(template),source=d.data;d.data=Array.from({length:n},(_,i)=>{const r={...source[i%source.length],_id:'spatial-capacity:'+template+':'+i,inputIndex:i,label:'Record '+i};if(template==='contour'){r.x=i%20;r.y=Math.floor(i/20);}if(template==='bars3d'){r.row='R'+Math.floor(i/6);r.column='C'+(i%6);}if(template==='lines3d'){r.period='P'+(i%16);r.series='S'+Math.floor(i/16);}if(template==='trajectory3d')r.period=new Date(Date.UTC(2025,0,i+1)).toISOString().slice(0,10);if(['vectorfield','voronoi'].includes(template)){r.x=i%10;r.y=Math.floor(i/10);}return r;});if(template==='bars3d'){d.rowOrder=[...new Set(d.data.map(r=>r.row))];d.columnOrder=[...new Set(d.data.map(r=>r.column))];}if(template==='lines3d'){d.periodOrder=[...new Set(d.data.map(r=>r.period))];d.seriesOrder=[...new Set(d.data.map(r=>r.series))];}for(const v of views.filter(v=>v.family===d.family)){assert.equal(eligible(d,v.id).valid,true,v.id);const l=layout(d,v.id,300,240);finite(l);assert.equal(new Set(originals(l).map(m=>m.identity)).size,n);}}
 for(const template of['bars3d','lines3d','trajectory3d','vectorfield','voronoi','contour']){const d=doc(template);if(['bars3d','lines3d','contour'].includes(template))d.data.forEach((r,i)=>r.value=i%2?1e15:0);else d.data.forEach((r,i)=>{for(const field of(template==='vectorfield'?['u','v']:['x','y','z'].filter(k=>Object.hasOwn(r,k))))r[field]=(r[field]||1)*1e8;});for(const v of views.filter(v=>v.family===d.family)){assert.equal(eligible(d,v.id).valid,true,v.id);finite(layout(d,v.id,300,240));}}
});

test('both languages preserve view names and mathematical cautions without untranslated generated UI',()=>{
 try{setLocale('en');for(const v of views){assert.equal(v.name,v.en);assert.doesNotMatch(v.note,/\p{Script=Han}/u);}for(const p of presets){assert.doesNotMatch(p.name+p.description+p.relation+p.dataNote,/\p{Script=Han}/u);const d=adapt(records(p.id)[0].doc);for(const v of p.views){assert.doesNotMatch(guide(d,v).join(' '),/\p{Script=Han}/u);const l=layout(d,v);assert.doesNotMatch(l.heading+l.details,/\p{Script=Han}/u);}}assert.doesNotMatch(agentGuide(true),/\p{Script=Han}/u);}finally{setLocale('zh-CN');}for(const en of[false,true])for(const token of['_id','inputIndex','hexbinLayout','bins12','densityGrid12','bivariateDensity12','recordId','populationId','HTML/SVG'])assert.ok(agentGuide(en).includes(token),token);
});
