import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {getExample,findTemplate} from '../../src/forma/catalog.js';
import {recordId,withRecordIds} from '../../src/forma/data-identity.js';
import {completionBusinessViews as views,completionBusinessViewMap as map,completionBusinessDocument as adapt,completionBusinessEligibility as eligible,completionBusinessCompatibility as compatible,completionBusinessBounds as bounds,completionBusinessGuide as guide,completionBusinessAgentGuide as agentGuide,completionBusinessColorSubjects as subjects,businessWaterfall} from '../../src/forma/completion-business-rules.js';
import {layoutCompletionBusiness as layout} from '../../src/forma/completion-business-morph.js';
import {completionBusinessPresets as presets,completionBusinessRecords as records} from '../../src/forma/completion-business-presets.js';
import {ScientificMorphChart} from '../../src/forma/scientific-morph.js';
import {ChartScene} from '../../src/forma/charts.js';
import {newWork,cleanWork,morphReady,stepReport,transitionPlan,stepDomain} from '../../src/forma/work-model.js';
import {stepSVG} from '../../src/forma/work-export.js';
import {createEditorModel} from '../../src/forma/editor-model.js';
import {setLocale} from '../../src/forma/locale.js';
const raw=template=>withRecordIds(getExample(template),{legacyNamespace:'completion-business-qa:'+template}),doc=template=>adapt(raw(template)),own=l=>l.marks.filter(m=>m.original),near=(a,b)=>assert.ok(Math.abs(a-b)<=1e-8*Math.max(1,Math.abs(a),Math.abs(b)),`${a} != ${b}`);
const finite=l=>{assert.equal(new Set(l.marks.map(m=>m.key)).size,l.marks.length);for(const m of l.marks){assert.equal(m.points.length,128,m.key);assert.equal(m.entrance.length,128,m.key);assert.ok(m.points.flat().every(Number.isFinite),m.key);assert.ok(m.entrance.flat().every(Number.isFinite),m.key);}for(const label of l.labels)assert.ok(Number.isFinite(label.x)&&Number.isFinite(label.y));};

test('twelve native adapters retain every field, stable identity and all records across 24 layouts',()=>{
 assert.equal(Object.keys(map).length,12);assert.equal(views.length,24);assert.equal(presets.length,12);assert.equal(records('missing'),null);
 for(const [native,id]of Object.entries(map)){const r=raw(native),before=structuredClone(r),d=adapt(r);assert.equal(eligible(d,id).valid,true,native);assert.deepEqual(r,before);for(const[k,value]of Object.entries(r).filter(([k])=>k!=='data'))assert.deepEqual(d[k],value);assert.deepEqual(subjects(d),[]);
  for(const v of views.filter(v=>v.family===d.family))for(const[w,h]of[[300,200],[800,440],[1280,720]]){const l=layout(d,v.id,w,h);finite(l);assert.deepEqual([...new Set(own(l).map(m=>m.identity))].sort(),r.data.map(recordId).sort());for(const m of own(l)){const row=r.data[m.row];assert.equal(m.identity,recordId(row));assert.equal(m.value,row[m.editable],m.key);assert.ok(m.opacity>0);assert.equal(m.derived,undefined);}for(const m of l.marks.filter(m=>m.derived)){assert.ok(m.recordIds.length,m.key);assert.equal(m.editable,undefined,m.key);}}
 }
});

test('waterfall bridges preserve total/change meanings and decomposed opposing changes reconcile',()=>{
 const d=doc('waterfall'),model=businessWaterfall(d.data),a=layout(d,map.waterfall),b=layout(d,map.waterfall+'-deltas');let balance=d.data[0].value;for(const m of own(a)){const r=d.data[m.row];assert.equal(m.kind,r.kind);near(m.projection.start,model[m.row].start);near(m.projection.end,model[m.row].end);const n=own(b).find(n=>n.key===m.key);near(n.projection.start,0);near(n.projection.end,r.value);if(r.kind==='change')balance+=r.value;}near(balance,d.data.at(-1).value);
 const c=doc('stackedwaterfall'),native=layout(c,map.stackedwaterfall),alt=layout(c,map.stackedwaterfall+'-deltas');near(native.statistics.total,c.finalTotal);for(const m of own(native)){const r=c.data[m.row],n=own(alt).find(n=>n.key===m.key);near(m.projection.end-m.projection.start,r.value);near(n.projection.start,0);near(n.projection.end,r.value);}assert.ok(own(native).some(m=>m.value<0));assert.equal(native.marks.filter(m=>m.role==='business-component-total').length,2);assert.deepEqual(c.data,doc('stackedwaterfall').data);
});

test('marimekko global areas and count stack lengths encode the same complete original grid',()=>{
 const d=doc('marimekko'),a=layout(d,map.marimekko),b=layout(d,map.marimekko+'-counts'),total=d.data.reduce((s,r)=>s+r.value,0);for(const m of own(a)){const r=d.data[m.row],area=m.projection.groupWidth*m.projection.withinShare;near(area,r.value/total);near(m.projection.share,r.value/total);const n=own(b).find(n=>n.key===m.key);near(b.scales.x.invert(Math.max(...n.points.map(p=>p[0])))-b.scales.x.invert(Math.min(...n.points.map(p=>p[0]))),r.value);}assert.equal(a.marks.filter(m=>m.role==='business-cell-hatch').length,d.data.length*8);const zero=structuredClone(d);zero.data[0].value=0;for(const v of views.filter(v=>v.family===zero.family)){assert.equal(eligible(zero,v.id).valid,true);const m=own(layout(zero,v.id)).find(m=>m.row===0);near(Math.max(...m.points.map(p=>p[0]))-Math.min(...m.points.map(p=>p[0])),v.id.endsWith('-counts')?0:layout(zero,v.id).plot.w*m.projection.groupWidth);assert.equal(m.value,0);}
});

test('OHLC preserves irregular ISO time spacing, all endpoints and per-row opening references',()=>{
 const d=doc('range');d.data.forEach((r,i)=>r.period=new Date(Date.UTC(2026,0,1+i*i)).toISOString().slice(0,10));const a=layout(d,map.range),b=layout(d,map.range+'-departures');for(const m of own(b)){const r=d.data[m.row];near(m.projection.x,Date.parse(r.period));near(m.projection.y,r[m.editable]-r.open);near(b.scales.y.invert(m.point[1]),m.projection.y);assert.equal(own(a).find(n=>n.key===m.key).value,m.value);}assert.equal(own(b).length,d.data.length*4);const points=own(b).filter(m=>m.editable==='low');near((points[2].point[0]-points[1].point[0])/(points[1].point[0]-points[0].point[0]),3);
});

test('mirrored bars retain positive raw quantities and tree geometry retains original memberships',()=>{
 const d=doc('pyramid'),a=layout(d,map.pyramid),b=layout(d,map.pyramid+'-paired');for(const m of own(b)){assert.ok(m.value>=0);near(b.scales.x.invert(Math.max(...m.points.map(p=>p[0]))),m.value);assert.equal(own(a).find(n=>n.key===m.key).projection.quantity,m.value);}assert.deepEqual(a.groupColorMarks,[{nativeColorRole:'fg'},{nativeColorRole:'accent'}]);
 const tree=doc('dendrogram'),cartesian=layout(tree,map.dendrogram),radial=layout(tree,map.dendrogram+'-radial');assert.equal(cartesian.statistics.total,tree.data.reduce((s,r)=>s+r.value,0));for(const m of own(radial)){const r=tree.data[m.row],n=own(cartesian).find(n=>n.key===m.key);near(m.radius,n.radius);near(m.radius**2/n.value,n.radius**2/n.value);assert.equal(m.projection.parent,r.parent);}assert.deepEqual(cartesian.marks.map(m=>m.key).sort(),radial.marks.map(m=>m.key).sort());
});

test('Likert retains explicit response order, complete neutral segment and 100% totals',()=>{
 const d=doc('likert'),a=layout(d,map.likert),b=layout(d,map.likert+'-stacked');for(const q of new Set(d.data.map(r=>r.question))){const marks=own(b).filter(m=>d.data[m.row].question===q).sort((a,b)=>a.projection.responseIndex-b.projection.responseIndex);near(marks[0].projection.start,0);near(marks.at(-1).projection.end,100);for(let j=1;j<marks.length;j++)near(marks[j-1].projection.end,marks[j].projection.start);const neutral=own(a).find(m=>d.data[m.row].question===q&&m.projection.responseIndex===2);near(neutral.projection.start,-neutral.value/2);near(neutral.projection.end,neutral.value/2);assert.equal(marks[2].value,neutral.value);}const zero=structuredClone(d);const q=zero.data[0].question,rows=zero.data.filter(r=>r.question===q);rows[1].value+=rows[0].value;rows[0].value=0;assert.equal(eligible(zero,map.likert).valid,true);finite(layout(zero,map.likert));assert.equal(own(layout(zero,map.likert)).find(m=>m.row===0).value,0);
});

test('forecast fans retain all supplied intervals, their widths and the history/forecast partition',()=>{
 const d=doc('forecastfan'),a=layout(d,map.forecastfan),b=layout(d,map.forecastfan+'-departures'),reference=d.data.filter(r=>r.observed!==null).at(-1).observed;near(b.statistics.reference,reference);for(const m of own(b)){const r=d.data[m.row],n=own(a).find(n=>n.key===m.key);near(m.projection.y,r[m.editable]-reference);near(n.projection.y,r[m.editable]);assert.equal(m.value,r[m.editable]);}for(const r of d.data.filter(r=>r.observed===null))for(const level of[50,80,95]){const low=own(b).find(m=>m.row===r.row&&m.editable==='lower'+level),high=own(b).find(m=>m.row===r.row&&m.editable==='upper'+level);near(high.projection.y-low.projection.y,r['upper'+level]-r['lower'+level]);}for(const level of[50,80,95]){const band=b.marks.find(m=>m.intervalLevel===level);assert.equal(band.recordIds.length,d.data.length-b.statistics.split);assert.ok(band.points.every(p=>p[0]>=b.scales.x(b.statistics.split)-1e-8));}assert.equal(b.marks.filter(m=>m.role==='business-forecast-trace').length,d.data.length-2);
});

test('sensitivity low/high stay original scenario outputs even when reversed or on one side',()=>{
 const d=doc('tornado');d.data[0].low=120;d.data[0].high=110;d.data[1].low=90;d.data[1].high=95;assert.equal(eligible(d,map.tornado).valid,true);const a=layout(d,map.tornado),b=layout(d,map.tornado+'-plane');assert.equal(a.statistics[0].impact,Math.max(...d.data.map(r=>Math.max(Math.abs(r.low-d.baseline),Math.abs(r.high-d.baseline)))));for(const m of own(b).filter(m=>m.role.startsWith('business-tornado-end'))){const r=d.data[m.row];near(b.scales.x.invert(m.point[0]),r.low);near(b.scales.y.invert(m.point[1]),r.high);assert.equal(m.value,r[m.editable]);assert.equal(m.projection.scenario,m.editable);}assert.ok(own(b).some(m=>m.editable==='low'&&m.value> d.data[m.row].high));
});

test('variwide width/rate rectangles and amount bars preserve products and zero rate',()=>{
 const d=doc('variwide');d.data[0].rate=0;assert.equal(eligible(d,map.variwide).valid,true);const a=layout(d,map.variwide),b=layout(d,map.variwide+'-amount');for(const m of own(a)){const r=d.data[m.row],n=own(b).find(n=>n.key===m.key);near(m.projection.end-m.projection.start,r.width);near(m.projection.amount,r.width*r.rate);near(b.scales.x.invert(Math.max(...n.points.map(p=>p[0]))),r.width*r.rate);assert.equal(n.editable,'rate');assert.equal(n.value,r.rate);}const zero=own(a).find(m=>m.row===0);assert.equal(Math.max(...zero.points.map(p=>p[1]))-Math.min(...zero.points.map(p=>p[1])),0);near(a.statistics.totalAmount,d.data.reduce((s,r)=>s+r.width*r.rate,0));
});

test('nomogram fixed coefficient contributions and cumulative totals never overwrite raw predictors',()=>{
 const d=doc('nomogram'),a=layout(d,map.nomogram),b=layout(d,map.nomogram+'-cumulative');let running=d.intercept;for(const m of own(b)){const r=d.data[m.row],contribution=r.coefficient*(r.value-r.reference),n=own(a).find(n=>n.key===m.key);running+=contribution;near(m.projection.score,running);near(m.projection.contribution,contribution);near(n.projection.score,contribution);assert.equal(m.value,r.value);assert.equal(m.editable,'value');}near(b.statistics.total,running);const total=b.marks.find(m=>m.role==='business-total-score');near(total.value,running);assert.equal(total.editable,undefined);assert.deepEqual(total.recordIds,d.data.map(recordId));
});

test('L’Abbé keeps complete original counts, real denominators and sample-size bubble area',()=>{
 const d=doc('labbe'),a=layout(d,map.labbe),b=layout(d,map.labbe+'-difference');for(const m of own(b)){const r=d.data[m.row],n=own(a).find(n=>n.key===m.key);near(m.projection.control,r.controlEvents/r.controlTotal);near(m.projection.treatment,r.treatmentEvents/r.treatmentTotal);near(m.projection.difference,r.treatmentEvents/r.treatmentTotal-r.controlEvents/r.controlTotal);near(m.projection.size,r.controlTotal+r.treatmentTotal);near(m.radius,n.radius);near(b.scales.y.invert(m.point[1]),m.projection.difference);assert.equal(m.value,r.treatmentEvents);}const first=own(b)[0],second=own(b)[1];near(first.radius**2/second.radius**2,first.projection.size/second.projection.size);assert.ok(!Object.hasOwn(d.data[0],'riskDifference'));
});

test('business eligibility and compatibility reject malformed identity, metadata and contracts',()=>{
 for(const [native,id]of Object.entries(map)){const d=doc(native);const malformed=structuredClone(d);malformed.data[0]._id=malformed.data[1]._id;assert.equal(eligible(malformed,id).valid,false);const mismatch=structuredClone(d);mismatch.template='not-native';assert.equal(eligible(mismatch,id).valid,false);for(const mutate of[b=>b.data.reverse(),b=>b.unit='new unit',b=>b.source.name='new source',b=>b.axes={x:'different quantity'}]){const b=structuredClone(d);mutate(b);assert.notEqual(compatible(d,b),'');}}
 for(const[native,key,value]of[['pyramid','sideLabels',['same','same']],['likert','responses',['missing']],['marimekko','groupOrder',['missing']],['marimekko','seriesOrder',{}],['likert','questionOrder',[]],['nomogram','intercept',Infinity],['stackedwaterfall','components',['missing']],['tornado','baseline',Infinity]]){const d=doc(native);d[key]=value;assert.equal(eligible(d,map[native]).valid,false,native+' '+key);}
 const interval=doc('forecastfan');interval.data.find(r=>r.observed===null).lower95=1e6;assert.equal(eligible(interval,map.forecastfan).valid,false);const count=doc('labbe');count.data[0].treatmentTotal=0;assert.equal(eligible(count,map.labbe).valid,false);const coefficients=doc('nomogram'),changed=structuredClone(coefficients);changed.data[0].coefficient*=2;assert.notEqual(compatible(coefficients,changed),'');
});

test('all original chart fields remain editable while preserving identity, units and model metadata',()=>{
 const edits={waterfall:[1,'value'],marimekko:[0,'value'],range:[0,'close'],pyramid:[0,'left'],dendrogram:[0,'value'],likert:[0,'value'],forecastfan:[16,'median'],tornado:[0,'low'],variwide:[0,'rate'],stackedwaterfall:[0,'value'],nomogram:[0,'value'],labbe:[0,'treatmentEvents']};
 for(const[native,[row,field]]of Object.entries(edits)){const source=raw(native),model=createEditorModel(source),columns=findTemplate(native).fields,next=source.data[row][field]+(native==='forecastfan'?.1:1),col=columns.findIndex(f=>f[0]===field),ids=model.recordIds();model.setCell(row,col,String(next));if(native==='waterfall')model.setCell(source.data.length-1,col,String(source.data.at(-1).value+1));if(native==='likert')model.setCell(1,col,String(source.data[1].value-1));if(native==='stackedwaterfall')model.setMeta('finalTotal',source.finalTotal+1);assert.equal(model.report.valid,true,native);assert.deepEqual(model.recordIds(),ids);assert.equal(model.doc.data[row][field],next);for(const[k,value]of Object.entries(source).filter(([k])=>!['data','finalTotal','source'].includes(k)))assert.deepEqual(model.doc[k],value);assert.equal(model.doc.source.type,'user');assert.ok(columns.every(([key])=>Object.hasOwn(model.doc.data[row],key)));const d=adapt(model.doc);assert.equal(eligible(d,map[native]).valid,true,native);assert.ok(own(layout(d,map[native])).some(m=>m.row===row&&m.editable===field&&m.value===next));assert.equal(model.doc.data[row].projection,undefined);}
});

test('maximum declared native populations retain every original row and finite geometry',()=>{
 for(const[native,id]of Object.entries(map)){const d=doc(native),first=d.data[0];
  if(native==='waterfall'){d.data=[{...first,label:'Initial',value:100,kind:'total'},...Array.from({length:10},(_,i)=>({...first,label:'Change '+i,value:i%2?-3:5,kind:'change'})),{...first,label:'Final',value:110,kind:'total'}];}
  if(native==='marimekko')d.data=Array.from({length:6},(_,i)=>Array.from({length:5},(_,j)=>({...first,group:'G'+i,series:'S'+j,value:i+j+1}))).flat();
  if(native==='range')d.data=Array.from({length:40},(_,i)=>({...first,period:new Date(Date.UTC(2026,0,i+1)).toISOString().slice(0,10),open:i,close:i+.5,low:i-1,high:i+1}));
  if(native==='pyramid')d.data=Array.from({length:10},(_,i)=>({...first,label:'G'+i,left:i,right:10-i}));
  if(native==='dendrogram')d.data=Array.from({length:5},(_,i)=>Array.from({length:i<3?4:3},(_,j)=>({...first,parent:'P'+i,label:'L'+j,value:i+j+1}))).flat();
  if(native==='likert')d.data=Array.from({length:7},(_,i)=>d.responses.map((response,j)=>({...first,question:'Q'+i,response,value:[0,25,0,25,50][j]}))).flat();
  if(native==='forecastfan')d.data=[...Array.from({length:60},(_,i)=>({...first,period:'P'+i,observed:100+i})),...Array.from({length:40},(_,i)=>({...d.data.find(r=>r.observed===null),period:'P'+(60+i),observed:null,median:160+i,lower50:158+i,upper50:162+i,lower80:156+i,upper80:164+i,lower95:154+i,upper95:166+i}))];
  if(native==='tornado')d.data=Array.from({length:16},(_,i)=>({...first,parameter:'P'+i,low:d.baseline-i,high:d.baseline+i}));
  if(native==='variwide')d.data=Array.from({length:16},(_,i)=>({...first,label:'L'+i,width:i+1,rate:i}));
  if(native==='stackedwaterfall'){d.stepOrder=Array.from({length:8},(_,i)=>'Step'+i);d.components=Array.from({length:6},(_,i)=>'C'+i);d.data=d.stepOrder.flatMap((step,i)=>d.components.map((component,j)=>({...first,step,component,value:(j%2?-1:1)*(i+j+1)})));d.finalTotal=d.baseline+d.data.reduce((s,r)=>s+r.value,0);}
  if(native==='nomogram')d.data=Array.from({length:7},(_,i)=>({...first,variable:'V'+i,minimum:0,maximum:10,reference:5,value:i,coefficient:i%2?-1:1}));
  if(native==='labbe')d.data=Array.from({length:60},(_,i)=>({...first,label:'S'+i,controlTotal:100+i,controlEvents:i,treatmentTotal:200+i,treatmentEvents:i*2}));
  d.data=d.data.map((r,i)=>({...r,_id:'capacity:'+native+':'+i,row:i}));for(const view of views.filter(v=>v.family===d.family)){assert.equal(eligible(d,view.id).valid,true,view.id);const l=layout(d,view.id,300,200);finite(l);assert.deepEqual([...new Set(own(l).map(m=>m.identity))].sort(),d.data.map(recordId).sort());for(const m of l.marks)assert.ok(m.points.every(([x,y])=>Math.abs(x)<5000&&Math.abs(y)<5000));}
 }
});

test('small and large common units keep complete native values and finite coordinates',()=>{
 for(const native of['waterfall','marimekko','range','pyramid','dendrogram','forecastfan','tornado','stackedwaterfall'])for(const scale of[1e-12,1e11]){const d=doc(native),numeric=findTemplate(native).fields.filter(([,type])=>type==='number'||type==='number | null').map(([key])=>key);d.data.forEach(r=>{for(const k of numeric)if(r[k]!==null)r[k]*=scale;});if(native==='tornado')d.baseline*=scale;if(native==='stackedwaterfall'){d.baseline*=scale;d.finalTotal*=scale;}for(const v of views.filter(v=>v.family===d.family)){assert.equal(eligible(d,v.id).valid,true,native+' '+scale);finite(layout(d,v.id));}}
});

test('24 directions keep DOM objects, exact endpoints, reversible seeking and interruption continuity',async()=>{
 for(const preset of presets){const d=adapt(records(preset.id)[0].doc);for(const[from,to]of[preset.views,preset.views.toReversed()]){const win=new Window();try{const chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:from,width:800,height:440,editable:true}),a=chart.layout,nodes=new Map([...chart.nodes].map(([key,n])=>[key,n.shape])),seek=chart.setDocument(d,to,{manual:true,effect:'guided'}),b=chart.layout;assert.deepEqual(a.marks.map(m=>m.key).sort(),b.marks.map(m=>m.key).sort());seek(.5);const midpoint=structuredClone([...chart.current]);assert.ok([...chart.current.values()].flat(2).every(Number.isFinite));assert.ok(b.marks.some(m=>JSON.stringify(chart.current.get(m.key))!==JSON.stringify(a.marks.find(n=>n.key===m.key).points)&&JSON.stringify(chart.current.get(m.key))!==JSON.stringify(m.points)),preset.id);seek(1);seek(.5);assert.deepEqual([...chart.current],midpoint);seek(0);for(const m of a.marks)assert.deepEqual(chart.current.get(m.key),m.points);seek(1);for(const m of b.marks)assert.deepEqual(chart.current.get(m.key),m.points);for(const[key,node]of nodes)assert.equal(chart.nodes.get(key).shape,node);seek(.37);const stopped=structuredClone([...chart.current]),resume=chart.setDocument(d,from,{manual:true,resume:true,effect:'guided'});resume(0);assert.deepEqual([...chart.current],stopped);resume(.6);resume(1);for(const m of own(chart.layout)){const n=chart.nodes.get(m.key);assert.equal(n.group.dataset.editField,m.editable);assert.equal(Number(n.group.dataset.editRow),m.row);}assert.doesNotMatch(chart.svg.outerHTML,/NaN|Infinity|undefined/);chart.destroy();}finally{await win.happyDOM.close();}}}
});

test('twelve complete-native scenarios export original provenance and real morph plans both ways',async()=>{
 const win=new Window(),previous=new Map(['document','XMLSerializer'].map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));for(const k of previous.keys())Object.defineProperty(globalThis,k,{value:win[k],configurable:true});try{for(const p of presets){const work=newWork(records(p.id));assert.deepEqual(cleanWork(JSON.parse(JSON.stringify(work))),work);for(const step of work.steps){assert.equal(stepReport(step).valid,true,step.view);assert.equal(morphReady(step),true,step.view);assert.deepEqual(step.doc.data,work.steps[0].doc.data);assert.match(stepSVG(step,work.steps),/data-science-role="business-/);}assert.equal(transitionPlan(work.steps[0],work.steps[1],{steps:work.steps}).mode,'morph');assert.equal(transitionPlan(work.steps[1],work.steps[0],{steps:work.steps}).mode,'morph');assert.deepEqual(stepDomain(work.steps[0],work.steps),stepDomain(work.steps[1],work.steps));}}finally{for(const[k,v]of previous){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];}await win.happyDOM.close();}
});

test('complete-native names, scenarios and contracts are bilingual without dropping method meaning',()=>{
 try{setLocale('en');for(const v of views){assert.equal(v.name,v.en);assert.doesNotMatch(v.note,/\p{Script=Han}/u);}for(const p of presets){assert.doesNotMatch(p.name+p.description+p.dataNote+p.relation,/\p{Script=Han}/u);const d=adapt(records(p.id)[0].doc);for(const id of p.views){const l=layout(d,id);assert.doesNotMatch(guide(d,id).join(' ')+l.heading+l.details,/\p{Script=Han}/u);}}assert.doesNotMatch(agentGuide(true),/\p{Script=Han}/u);}finally{setLocale('zh-CN');}for(const english of[true,false])for(const token of['_id','source','unit','axes','sideLabels','responses','baseline','intercept','stepOrder','components','recordId','populationId','HTML/SVG'])assert.ok(agentGuide(english).includes(token));
});

test('complete-native morph marks preserve native palette roles for every supplied palette configuration',async()=>{
 const win=new Window(),previous=Object.getOwnPropertyDescriptor(globalThis,'document');Object.defineProperty(globalThis,'document',{value:win.document,configurable:true});try{for(const native of['range','likert','forecastfan','variwide','stackedwaterfall','nomogram','labbe'])for(const options of[{palette:'ink'},{palette:'ochre'},{palette:'ochre',colorMode:'emphasis'},{palette:'ink',colorMode:'categorical'},{palette:'ink',colors:['#356b8a','#b66834','#657e46']}]){const source=raw(native),d=adapt(source),nativeChart=new ChartScene(win.document.createElement('div'),source,{...options,width:800,height:440,interactive:false}),morph=new ScientificMorphChart(win.document.createElement('div'),d,{...options,view:map[native],width:800,height:440});try{
   if(native==='range'){const groups=[...nativeChart.svg.querySelectorAll('[data-mark="range-observation"]')];for(const m of own(morph.layout))assert.equal(morph.markColor(m),groups[m.row].querySelector('line').getAttribute('stroke'));}
   if(native==='likert'){const marks=[...nativeChart.svg.querySelectorAll('[data-mark="likert-segment"]')];for(const m of own(morph.layout))assert.equal(morph.markColor(m),marks[m.row].getAttribute('fill'));}
   if(native==='forecastfan'){const marks=[...nativeChart.svg.querySelectorAll('[data-mark="forecast-estimate"]')];for(const m of own(morph.layout).filter(m=>m.editable==='median'))assert.equal(morph.markColor(m),marks[m.row-morph.layout.statistics.split].getAttribute('fill'));}
   if(native==='variwide'){const marks=[...nativeChart.svg.querySelectorAll('[data-mark="variwide-bar"]')];for(const m of own(morph.layout))assert.equal(morph.markColor(m),marks[m.row].getAttribute('fill'));}
   if(native==='stackedwaterfall'){const marks=[...nativeChart.svg.querySelectorAll('[data-mark="waterfall-part"]')];for(const m of own(morph.layout))assert.equal(morph.markColor(m),marks[m.row].getAttribute('fill'));}
   if(native==='nomogram'){const marks=[...nativeChart.svg.querySelectorAll('[data-mark="nomogram-input"]')];for(const m of own(morph.layout))assert.equal(morph.markColor(m),marks[m.row].getAttribute('fill'));}
   if(native==='labbe'){const marks=[...nativeChart.svg.querySelectorAll('[data-mark="labbe-study"]')];for(const m of own(morph.layout))assert.equal(morph.markColor(m),marks[0].getAttribute('stroke'));}
  }finally{nativeChart.destroy();morph.destroy();}}}finally{if(previous)Object.defineProperty(globalThis,'document',previous);else delete globalThis.document;await win.happyDOM.close();}
});
