import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {interpolateRgb,color as parseColor} from 'd3';
import {themeFor} from '../../src/forma/palettes.js';
import {getExample,findTemplate} from '../../src/forma/catalog.js';
import {recordId,withRecordIds} from '../../src/forma/data-identity.js';
import {setLocale} from '../../src/forma/locale.js';
import {engineeringViews as views,engineeringViewMap as nativeMap,engineeringDocument as adapt,engineeringEligibility as eligible,engineeringCompatibility as compatible,engineeringBounds as bounds,engineeringColorKeys as colorKeys,engineeringColorSubjects as subjects,engineeringPhasorRows,engineeringGuide as guide,engineeringAgentGuide as agentGuide} from '../../src/forma/engineering-series-rules.js';
import {layoutEngineering as layout} from '../../src/forma/engineering-series-morph.js';
import {engineeringPresets as presets,engineeringRecords as records} from '../../src/forma/engineering-series-presets.js';
import {smith19,windrose19} from '../../src/forma/volume19-data.js';
import {ScientificMorphChart} from '../../src/forma/scientific-morph.js';
import {ChartScene} from '../../src/forma/charts.js';
import {newWork,cleanWork,stepReport,stepDomain,morphReady,transitionPlan} from '../../src/forma/work-model.js';
import {workColorMap,createStepScene} from '../../src/forma/work-scene.js';
import {stepSVG} from '../../src/forma/work-export.js';
import {createEditorModel} from '../../src/forma/editor-model.js';
const raw=template=>withRecordIds(getExample(template),{legacyNamespace:'engineering-qa:'+template}),doc=template=>adapt(raw(template)),own=l=>l.marks.filter(m=>m.original),near=(a,b)=>assert.ok(Math.abs(a-b)<=1e-8*Math.max(1,Math.abs(a),Math.abs(b)),`${a} ≠ ${b}`),fieldFor=t=>({smith:'real',polarscatter:'radius',phasor:'real',constellation:'real',polezero:'real',hodograph:'u',windrose:'speed',campbell:'amplitude'})[t];
const finite=l=>{assert.equal(new Set(l.marks.map(m=>m.key)).size,l.marks.length);for(const m of l.marks){assert.equal(m.points.length,128,m.key);assert.equal(m.entrance.length,128,m.key);assert.ok(m.points.flat().every(Number.isFinite),m.key);assert.ok(m.entrance.flat().every(Number.isFinite),m.key);}};

test('eight native engineering contracts preserve every original field and editable observation',()=>{
 assert.equal(Object.keys(nativeMap).length,8);assert.equal(views.length,16);
 for(const [template,view]of Object.entries(nativeMap)){const original=raw(template),before=structuredClone(original),d=adapt(original);assert.deepEqual(original,before);assert.equal(eligible(d,view).valid,true,template);assert.equal(d.data.length,original.data.length);assert.equal(d.unit,original.unit);assert.deepEqual(d.source,original.source);
  for(const v of views.filter(v=>v.family===d.family))for(const [w,h]of[[300,240],[800,440],[1280,720]]){const l=layout(d,v.id,w,h);finite(l);assert.equal(own(l).length,original.data.length);for(const m of own(l)){assert.equal(m.identity,recordId(original.data[m.row]));assert.equal(m.value,original.data[m.row][m.editable]);assert.equal(m.editable,fieldFor(template));assert.ok(m.opacity>0);assert.equal(m.recordIds,undefined);}for(const m of l.marks.filter(m=>m.derived)){assert.ok(Array.isArray(m.recordIds));assert.equal(m.editable,undefined);}}
 }
});

test('Smith views retain original ohms and reuse the native stable reflection-coefficient mapping',()=>{
 const d=doc('smith'),before=structuredClone(d),a=layout(d,'engineering-smith'),b=layout(d,'engineering-impedance');for(const m of own(a)){const r=d.data[m.row],p=smith19(r.real,r.imag,d.referenceImpedance);near(a.scales.x.invert(m.point[0]),p.real);near(a.scales.y.invert(m.point[1]),p.imag);const n=own(b).find(n=>n.key===m.key);near(b.scales.x.invert(n.point[0]),r.real);near(b.scales.y.invert(n.point[1]),r.imag);assert.equal(m.value,r.real);}assert.deepEqual(d,before);const bad=structuredClone(d);bad.referenceImpedance=0;assert.equal(eligible(bad,'engineering-smith').valid,false);bad.referenceImpedance=50;bad.unit='V';assert.equal(eligible(bad,'engineering-smith').valid,false);
});

test('compass bearings remain north-clockwise and zero radii retain their supplied direction',()=>{
 const d=doc('polarscatter');d.data.slice(0,4).forEach((r,i)=>{r.angle=i*90;r.radius=10;});d.data[4].radius=0;d.data[4].angle=127;const a=layout(d,'engineering-polar'),b=layout(d,'engineering-bearing-radius');for(const m of own(a)){const r=d.data[m.row],radians=r.angle*Math.PI/180;near(a.scales.x.invert(m.point[0]),r.radius*Math.sin(radians));near(a.scales.y.invert(m.point[1]),r.radius*Math.cos(radians));const n=own(b).find(n=>n.key===m.key);near(b.scales.x.invert(n.point[0]),r.angle);near(b.scales.y.invert(n.point[1]),r.radius);}const bad=structuredClone(d);bad.data[0].radius=-1;assert.equal(eligible(bad,'engineering-polar').valid,false);
});

test('phasor chains translate original vectors and preserve an explicit identity-based order',()=>{
 const d=doc('phasor');d.phasorOrder=[...d.data].reverse().map(recordId);const l=layout(d,'engineering-phasor-chain'),native=layout(d,'engineering-phasor'),vectors=l.marks.filter(m=>m.role==='phasor-vector');let x=0,y=0;for(const r of engineeringPhasorRows(d)){const mark=vectors.find(m=>m.identity===recordId(r));assert.deepEqual(mark.start,[x,y]);x+=r.real;y+=r.imag;near(mark.end[0],x);near(mark.end[1],y);near(mark.end[0]-mark.start[0],r.real);near(mark.end[1]-mark.start[1],r.imag);}assert.deepEqual(native.marks.filter(m=>m.role==='phasor-resultant').map(m=>m.points),l.marks.filter(m=>m.role==='phasor-resultant').map(m=>m.points));const shuffled=structuredClone(d);shuffled.data.reverse();shuffled.data.forEach((r,i)=>r.label='Renamed '+i);assert.deepEqual(engineeringPhasorRows(shuffled).map(recordId),d.phasorOrder);assert.equal(compatible(d,shuffled),'');shuffled.phasorOrder.reverse();assert.notEqual(compatible(d,shuffled),'');shuffled.phasorOrder=['missing'];assert.equal(eligible(shuffled,'engineering-phasor').valid,false);assert.doesNotThrow(()=>colorKeys(shuffled));
});

test('I/Q and roots retain undefined zero phase and distinguish mathematical from compass angles',()=>{
 for(const [template,to]of[['constellation','engineering-symbol-polar'],['polezero','engineering-root-polar']]){const d=doc(template);d.data[0].real=0;d.data[0].imag=0;d.data[1].real=0;d.data[1].imag=2;assert.equal(eligible(d,to).valid,true);const l=layout(d,to);const zero=own(l).find(m=>m.row===0);assert.equal(zero.projection.phase,null);assert.equal(zero.undefinedPhase,true);assert.ok(zero.point[1]>l.plot.y+l.plot.h);for(const m of own(l).filter(m=>!m.undefinedPhase)){const r=d.data[m.row];near(l.scales.x.invert(m.point[0]),Math.atan2(r.imag,r.real)*180/Math.PI);near(l.scales.y.invert(m.point[1]),Math.hypot(r.real,r.imag));}assert.equal(d.data[0].real,0);assert.equal(d.data[0].imag,0);if(template==='polezero'){const same=structuredClone(d);same.data[1]={...same.data[1],real:0,imag:0};assert.equal(own(layout(same,to)).length,same.data.length);same.data[0].kind='zero';assert.notEqual(compatible(d,same),'');}}
});

test('hodograph projection uses actual measured heights and retains original u/v with height colors',()=>{
 const d=doc('hodograph'),a=layout(d,'engineering-hodograph'),b=layout(d,'engineering-height-speed');for(const m of own(b)){const r=d.data[m.row];near(b.scales.x.invert(m.point[0]),Math.hypot(r.u,r.v));near(b.scales.y.invert(m.point[1]),r.height);assert.equal(m.value,r.u);assert.equal(m.colorValue,r.height);assert.deepEqual(m.valueDomain,bounds(d).height);const n=own(a).find(n=>n.key===m.key);near(a.scales.x.invert(n.point[0]),r.u);near(a.scales.y.invert(n.point[1]),r.v);}assert.equal(b.marks.filter(m=>m.role==='measured-connection').length,d.data.length-1);assert.deepEqual(subjects(d),[]);
});

test('wind summaries reuse native bins and all-row denominators while retaining calm null directions',()=>{
 const d=doc('windrose'),before=structuredClone(d),native=windrose19(d),a=layout(d,'engineering-windrose'),b=layout(d,'engineering-wind-sectors');for(const l of[a,b]){assert.equal(own(l).length,d.data.length);const bins=l.marks.filter(m=>m.role==='wind-frequency');assert.equal(bins.length,d.windSectors*d.speedBreaks.length);for(const cell of native.cells){const mark=bins.find(m=>m.sector===cell.sector&&m.bin===cell.bin);near(mark.frequency,cell.count/d.data.length);assert.deepEqual(mark.recordIds,cell.rows.map(recordId));assert.equal(mark.derived,true);}for(const m of own(l)){assert.equal(m.direction,d.data[m.row].direction);if(m.calm&&m.direction===null)assert.match(m.tooltip,/null/);}}assert.deepEqual(d,before);const calm=structuredClone(d);calm.data.forEach(r=>{r.speed=0;r.direction=null;});for(const view of['engineering-windrose','engineering-wind-sectors']){assert.equal(eligible(calm,view).valid,true);const l=layout(calm,view);finite(l);assert.equal(own(l).length,calm.data.length);assert.equal(l.statistics.calmFrequency,1);}const bad=structuredClone(d);bad.data[1].direction=null;assert.equal(eligible(bad,'engineering-windrose').valid,false);
});

test('Campbell amplitude areas, zero marks and original-frequency projections preserve branch data',()=>{
 const d=doc('campbell');d.data[0].amplitude=0;const a=layout(d,'engineering-campbell'),b=layout(d,'engineering-speed-amplitude'),max=bounds(d).amplitude[1];for(const m of own(a)){const r=d.data[m.row];near(a.scales.x.invert(m.point[0]),r.speed);near(a.scales.y.invert(m.point[1]),r.frequency);assert.equal(m.value,r.amplitude);assert.equal(m.zeroAmplitude,r.amplitude===0);if(r.amplitude>0)near(m.radius*m.radius,100*r.amplitude/max);const n=own(b).find(n=>n.key===m.key);near(b.scales.y.invert(n.point[1]),r.amplitude);assert.equal(n.projection.frequency,r.frequency);}assert.ok(a.marks.some(m=>m.role==='order-reference'&&m.opacity>0));assert.ok(b.marks.filter(m=>m.role==='order-reference').every(m=>m.opacity===0));
});

test('contracts reject missing originals, changed physical metadata and changed populations without coercion',()=>{
 for(const [template,view]of Object.entries(nativeMap)){const d=doc(template),bad=structuredClone(d);bad.data[0][fieldFor(template)]=null;assert.equal(eligible(bad,view).valid,false);for(const change of[x=>x.unit='other',x=>x.source.name='other',x=>x.axes={x:'other meaning'},x=>x.data[0]._id='other']){const b=structuredClone(d);change(b);assert.notEqual(compatible(d,b),'');}}
 for(const [template,field]of[['smith','referenceImpedance'],['smith','frequencyUnit'],['polezero','systemDomain'],['phasor','frequency'],['phasor','phaseConvention'],['hodograph','heightUnit'],['windrose','calmThreshold'],['windrose','speedBreaks'],['campbell','orders']]){const a=doc(template),b=structuredClone(a);b[field]=Array.isArray(a[field])?[...a[field],99]:typeof a[field]==='number'?a[field]+1:'other';assert.notEqual(compatible(a,b),'',field);}
 for(const template of Object.keys(nativeMap)){const d=doc(template),changed=structuredClone(d);changed.data.reverse();changed.data.forEach((r,i)=>{if(r.label)r.label='Renamed '+i;if(r.group)r.group='Rename '+r.group;if(r.mode)r.mode='Rename '+r.mode;});assert.equal(compatible(d,changed),'');assert.deepEqual([...colorKeys(d)].sort(),[...colorKeys(changed)].sort());for(const v of views.filter(v=>v.family===d.family))finite(layout(changed,v.id));}
 const invalid=doc('windrose');invalid.speedBreaks=null;assert.doesNotThrow(()=>subjects(invalid));assert.equal(eligible(invalid,'engineering-windrose').valid,false);
});

test('native editors retain metadata and modify raw fields without persisting projections',()=>{
 for(const template of Object.keys(nativeMap)){const original=raw(template),editor=createEditorModel(original),field=fieldFor(template),column=findTemplate(template).fields.findIndex(f=>f[0]===field),next=original.data[0][field]+.0125,ids=editor.recordIds();editor.setCell(0,column,String(next));assert.equal(editor.report.valid,true,template);assert.equal(editor.doc.data[0][field],next);assert.deepEqual(editor.recordIds(),ids);for(const [name]of findTemplate(template).fields)assert.ok(Object.hasOwn(editor.doc.data[0],name));assert.equal(editor.doc.data[0].projection,undefined);for(const key of['unit','referenceImpedance','phaseConvention','frequencyUnit','heightUnit','calmThreshold','orders'])assert.deepEqual(editor.doc[key],original[key]);const d=adapt(editor.doc);assert.ok(own(layout(d,nativeMap[template])).some(m=>m.row===0&&m.value===next));}
});

test('all sixteen directions retain DOM identity, exact reverse seeks and interrupted geometry',async()=>{
 let count=0;for(const preset of presets){const d=adapt(records(preset.id)[0].doc);for(const from of preset.views)for(const to of preset.views){if(from===to)continue;count++;const win=new Window();try{const bindings=subjects(d).map(s=>({id:s.id,color:'#347855'})),chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:from,width:800,height:440,editable:true,colorBindings:bindings}),nodes=new Map([...chart.nodes].map(([k,v])=>[k,v.shape])),a=chart.layout,seek=chart.setDocument(d,to,{manual:true,effect:'guided',colorBindings:bindings}),b=chart.layout;assert.deepEqual(a.marks.map(m=>m.key).sort(),b.marks.map(m=>m.key).sort(),from);seek(.5);const middle=structuredClone([...chart.current]);assert.ok([...chart.current.values()].flat(2).every(Number.isFinite));assert.ok(own(b).some(m=>JSON.stringify(chart.current.get(m.key))!==JSON.stringify(a.marks.find(p=>p.key===m.key).points)&&JSON.stringify(chart.current.get(m.key))!==JSON.stringify(m.points)),from);seek(1);seek(.5);assert.deepEqual([...chart.current],middle);seek(0);for(const m of a.marks)assert.deepEqual(chart.current.get(m.key),m.points);seek(1);for(const m of b.marks)assert.deepEqual(chart.current.get(m.key),m.points);for(const[k,node]of nodes)assert.equal(chart.nodes.get(k).shape,node);seek(.37);const interrupted=structuredClone([...chart.current]),resume=chart.setDocument(d,from,{manual:true,resume:true,effect:'guided',colorBindings:bindings});resume(0);assert.deepEqual([...chart.current],interrupted);resume(.72);resume(1);for(const m of own(chart.layout)){const node=chart.nodes.get(m.key);assert.equal(node.group.dataset.editField,m.editable);assert.equal(Number(node.group.dataset.editRow),m.row);if(d.template!=='hodograph')assert.equal(chart.markColor(m),'#347855');}assert.doesNotMatch(chart.svg.outerHTML,/NaN|Infinity|undefined/);chart.destroy();}finally{await win.happyDOM.close();}}}assert.equal(count,16);
});

test('eight scenarios round-trip exact raw tables and use real morph plans plus SVG export',t=>{
 const win=new Window(),prior=new Map();for(const[k,value]of Object.entries({document:win.document,XMLSerializer:win.XMLSerializer})){prior.set(k,Object.getOwnPropertyDescriptor(globalThis,k));Object.defineProperty(globalThis,k,{value,configurable:true,writable:true});}t.after(()=>{for(const[k,p]of prior){if(p)Object.defineProperty(globalThis,k,p);else delete globalThis[k];}win.happyDOM.close();});assert.equal(presets.length,8);assert.equal(records('missing'),null);
 for(const preset of presets){const work=newWork(records(preset.id,'vermilion'));assert.deepEqual(cleanWork(JSON.parse(JSON.stringify(work))),work);for(const step of work.steps){assert.equal(stepReport(step).valid,true,step.view);assert.equal(morphReady(step),true);assert.deepEqual(step.doc.data,work.steps[0].doc.data);assert.match(stepSVG(step,work.steps),/data-science-role="sample"/);assert.doesNotThrow(()=>workColorMap(step,work.steps));const domain=stepDomain(step,work.steps);for(const values of Object.values(domain))assert.ok(values.every(Number.isFinite));const scene=createStepScene(win.document.createElement('div'),step,{width:390,height:320,domain});try{scene.render(.5);assert.doesNotMatch(scene.svg.outerHTML,/NaN|Infinity|undefined/);}finally{scene.destroy();}}for(const a of work.steps)for(const b of work.steps)if(a.id!==b.id)assert.equal(transitionPlan(a,b,{steps:work.steps}).mode,'morph',a.view+' → '+b.view);}
});

test('all native bound colors reach actual marks after reorder and group renaming',async()=>{
 const win=new Window(),prior={document:globalThis.document,window:globalThis.window};globalThis.document=win.document;globalThis.window=win;
 try{for(const template of Object.keys(nativeMap).filter(t=>t!=='hodograph')){const native=raw(template),bindings=subjects(native).map(s=>({id:s.id,color:'#347855'}));native.data.reverse();native.data.forEach((r,i)=>{if(r.label)r.label='Renamed '+i;if(r.group)r.group='Rename '+r.group;if(r.mode)r.mode='Rename '+r.mode;});const scene=new ChartScene(win.document.createElement('div'),native,{width:800,height:440,interactive:false,colorBindings:bindings});try{scene.render(1);assert.ok([...scene.svg.querySelectorAll('path,circle,line,rect')].filter(el=>!el.closest('defs')).some(el=>[el.getAttribute('fill'),el.getAttribute('stroke')].includes('#347855')),template);}finally{scene.destroy();}}}finally{globalThis.document=prior.document;globalThis.window=prior.window;await win.happyDOM.close();}
});

test('large finite coordinates, zero components and compact layouts remain finite without clipping records',()=>{
 for(const template of Object.keys(nativeMap)){const d=doc(template);if(['smith','phasor','constellation','polezero'].includes(template))d.data.forEach((r,i)=>{r.real=i%3?1e15:0;r.imag=i%2?-1e15:0;});else if(template==='polarscatter')d.data.forEach((r,i)=>r.radius=i%2?1e15:0);else if(template==='hodograph')d.data.forEach((r,i)=>{r.u=i%3?1e15:0;r.v=i%2?-1e15:0;});else if(template==='campbell')d.data.forEach((r,i)=>{r.frequency=i%3?1e15:0;r.amplitude=i%2?1e15:0;});else d.data.forEach((r,i)=>{r.speed=i%3?1e15:0;if(r.speed===0)r.direction=null;else if(r.direction===null)r.direction=0;});
  for(const v of views.filter(v=>v.family===d.family)){assert.equal(eligible(d,v.id).valid,true,v.id);const l=layout(d,v.id,300,240);finite(l);assert.equal(own(l).length,d.data.length);for(const m of l.marks)for(const[x,y]of m.points){assert.ok(Math.abs(x)<300*20,m.key);assert.ok(Math.abs(y)<240*20,m.key);}}for(const values of Object.values(bounds(d))){assert.ok(values.every(Number.isFinite));assert.ok(Number.isFinite(values[1]-values[0]));}
 }
});

test('engineering metadata and mathematical cautions support both languages',()=>{
 try{setLocale('en');for(const v of views){assert.equal(v.name,v.en);assert.doesNotMatch(v.note,/\p{Script=Han}/u);}for(const p of presets){assert.doesNotMatch(p.name+p.description+p.dataNote+p.relation,/\p{Script=Han}/u);const d=adapt(records(p.id)[0].doc);for(const view of p.views){assert.doesNotMatch(guide(d,view).join(' '),/\p{Script=Han}/u);const l=layout(d,view);assert.doesNotMatch(l.heading+l.details,/\p{Script=Han}/u);}}assert.doesNotMatch(agentGuide(true),/\p{Script=Han}/u);}finally{setLocale('zh-CN');}for(const en of[false,true])for(const token of['_id','recordId','populationId','referenceImpedance','phasorOrder','direction=null','HTML/SVG'])assert.ok(agentGuide(en).includes(token),token);
});

test('maximum supported populations keep every observation and finite stable contours',()=>{
 const capacities={smith:480,polarscatter:400,phasor:12,constellation:1000,polezero:80,hodograph:100,windrose:1000,campbell:600};
 for(const [template,n]of Object.entries(capacities)){const d=doc(template),source=d.data;d.data=Array.from({length:n},(_,i)=>{const r={...source[i%source.length],_id:'capacity:'+template+':'+i,label:'Record '+i,row:i};if(template==='smith'){r.group='G'+Math.floor(i/160);r.frequency=1+(i%160)*.1;}if(template==='hodograph')r.height=i*10;if(template==='campbell'){r.mode='Mode '+Math.floor(i/100);r.speed=i%100;}return r;});for(const v of views.filter(v=>v.family===d.family)){assert.equal(eligible(d,v.id).valid,true,v.id);const l=layout(d,v.id,390,320);finite(l);assert.equal(own(l).length,n);}}
});


test('height marks and exported color swatches preserve each native accent gradient',async()=>{
 const win=new Window();try{const d=doc('hodograph');for(const palette of['vermilion','cobalt']){const theme=themeFor(palette),chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:'engineering-height-speed',width:800,height:440,palette});try{chart.render(1);for(const m of own(chart.layout)){const expected=interpolateRgb(theme.bg,theme.accent)(.24+.7*(m.colorValue-chart.layout.valueDomain[0])/(chart.layout.valueDomain[1]-chart.layout.valueDomain[0]));assert.equal(parseColor(chart.markColor(m)).formatHex(),parseColor(expected).formatHex());}const swatches=[...chart.svg.querySelectorAll('[data-value-color-swatch]')];assert.equal(swatches.length,48);for(const[i,el]of swatches.entries())assert.equal(parseColor(el.getAttribute('fill')).formatHex(),parseColor(interpolateRgb(theme.bg,theme.accent)(.24+.7*i/47)).formatHex());}finally{chart.destroy();}}}finally{await win.happyDOM.close();}
});
