import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {color} from 'd3';
import {getExample} from '../../src/forma/catalog.js';
import {withRecordIds} from '../../src/forma/data-identity.js';
import {presetWork} from '../../src/forma/work-model.js';
import {ScientificMorphChart} from '../../src/forma/scientific-morph.js';
import {SeriesMorphChart,layoutSeries} from '../../src/forma/series-morph.js';
import {MorphChart,morphExample} from '../../src/forma/morph.js';
import {seriesDocument} from '../../src/forma/series-rules.js';
import {businessSeriesDocument} from '../../src/forma/business-series-rules.js';
import {layoutBusinessSeries,interpolateBusinessSeriesMark} from '../../src/forma/business-series-morph.js';
import {temporalDocument} from '../../src/forma/temporal-series-rules.js';
import {layoutTemporal,interpolateTemporalMark} from '../../src/forma/temporal-series-morph.js';
import {completionBusinessDocument} from '../../src/forma/completion-business-rules.js';
import {layoutCompletionBusiness} from '../../src/forma/completion-business-morph.js';
import {timePlanningDocument,timePlanningGroups} from '../../src/forma/time-planning-rules.js';
import {layoutTimePlanning} from '../../src/forma/time-planning-morph.js';

const area=points=>Math.abs(points.reduce((sum,p,i)=>{const n=points[(i+1)%points.length];return sum+p[0]*n[1]-n[0]*p[1];},0))/2;
const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
function simple(points){for(let i=0;i<points.length;i++)for(let j=i+2;j<points.length;j++){if(i===0&&j===points.length-1)continue;const a=points[i],b=points[(i+1)%points.length],c=points[j],d=points[(j+1)%points.length];assert.ok(!(cross(a,b,c)*cross(a,b,d)<-1e-6&&cross(c,d,a)*cross(c,d,b)<-1e-6),`crossed edges ${i}/${j}`);}}
function timeFlanks(points){assert.equal(points.length,128);for(let i=1;i<64;i++)assert.ok(points[i][0]>=points[i-1][0]-1e-8);for(let i=0;i<64;i++)assert.ok(points[i][1]<=points[127-i][1]+1e-8);}

test('gauge arc unwraps into completion strip without intermediate folded wedges',async()=>{
 const d=businessSeriesDocument(presetWork('target-single-gauge').steps[0].doc),a=layoutBusinessSeries(d,'target-gauge'),b=layoutBusinessSeries(d,'target-progress');
 for(const role of['actual-contour','target-track']){const first=a.marks.find(m=>m.role===role),last=b.marks.find(m=>m.key===first.key);for(const reverse of[false,true]){const source=reverse?last:first,dest=reverse?first:last;for(const q of[0,.05,.15,.25,.35,.5,.65,.75,.85,.95,1]){const points=interpolateBusinessSeriesMark(source.points,source,dest,q);assert.ok(points.flat().every(Number.isFinite));assert.ok(area(points)>1);simple(points);}assert.deepEqual(interpolateBusinessSeriesMark(source.points,source,dest,0),source.points);assert.deepEqual(interpolateBusinessSeriesMark(source.points,source,dest,1),dest.points);}}
 for(const min of[0,50]){const input=structuredClone(d);input.data[0].min=min;input.data[0].value=min;const first=layoutBusinessSeries(input,'target-gauge').marks.find(m=>m.role==='actual-contour'),last=layoutBusinessSeries(input,'target-progress').marks.find(m=>m.role==='actual-contour');for(const q of[.1,.5,.9]){const points=interpolateBusinessSeriesMark(first.points,first,last,q);assert.ok(points.flat().every(v=>Number.isFinite(v)&&Math.abs(v)<1600));simple(points);}}
 const win=new Window(),chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:'target-gauge',width:800,height:440});try{const from=chart.layout,seek=chart.setDocument(d,'target-progress',{manual:true,effect:'guided'});seek(.5);for(const mark of chart.layout.marks.filter(m=>['actual-contour','target-track'].includes(m.role))){const old=from.marks.find(m=>m.key===mark.key);assert.deepEqual(chart.current.get(mark.key),interpolateBusinessSeriesMark(old.points,old,mark,.5));}}finally{chart.destroy();await win.happyDOM.close();}
});

test('horizon helpers unfurl along their own time contour and disappear into their target centreline',()=>{
 const d=temporalDocument(presetWork('temporal-source-story').steps[0].doc),layouts=['temporal-stream','temporal-horizon','temporal-lines'].map(view=>layoutTemporal(d,view));
 for(const from of layouts)for(const to of layouts)if(from!==to){const old=new Map(from.marks.map(m=>[m.key,m]));for(const next of to.marks.filter(m=>m.role.startsWith('temporal-band-'))){const prior=old.get(next.key);for(const q of[.001,.2,.5,.8,.999]){const points=interpolateTemporalMark(prior.points,prior,next,q);timeFlanks(points);for(let i=0;i<64;i++)assert.equal(points[i][0],next.points[i][0]);}assert.deepEqual(interpolateTemporalMark(prior.points,prior,next,0),prior.points);assert.deepEqual(interpolateTemporalMark(prior.points,prior,next,1),next.points);}}
});

test('progress strips rotate into thin fan rays while staying attached to actual and target endpoints',async()=>{
 const win=new Window(),d=businessSeriesDocument(presetWork('target-scorecard').steps[0].doc),chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:'target-progress',width:800,height:440});
 try{const seek=chart.setDocument(d,'target-fan',{manual:true,effect:'guided'});for(const p of[.2,.5,.65,.85]){seek(p);for(const strip of chart.layout.marks.filter(m=>['actual-contour','target-track'].includes(m.role))){const points=chart.current.get(strip.key);if(p===.65)for(let i=0;i<64;i++)assert.ok(Math.hypot(points[i][0]-points[127-i][0],points[i][1]-points[127-i][1])<4.5);const endpointRole=strip.role==='actual-contour'?'actual-point':'target-endpoint',marker=chart.layout.marks.find(m=>m.identity===strip.identity&&m.role===endpointRole),markerPoints=chart.current.get(marker.key),centre=markerPoints.reduce((sum,p)=>[sum[0]+p[0]/128,sum[1]+p[1]/128],[0,0]),end=[(points[63][0]+points[64][0])/2,(points[63][1]+points[64][1])/2];assert.ok(Math.hypot(end[0]-centre[0],end[1]-centre[1])<1e-8);simple(points);}}}finally{chart.destroy();await win.happyDOM.close();}
});

test('over-target progress and reversed pair distances stay inside the canvas and attached during manual and live seeking',async()=>{
 const win=new Window(),queue=new Map();let frameId=0;win.requestAnimationFrame=callback=>{queue.set(++frameId,callback);return frameId;};win.cancelAnimationFrame=id=>queue.delete(id);const advance=time=>{const callbacks=[...queue.values()];queue.clear();callbacks.forEach(callback=>callback(time));};
 const d=businessSeriesDocument(withRecordIds(getExample('progress'),{legacyNamespace:'polish-over-target'})),original=structuredClone(d),center=points=>points.reduce((sum,p)=>[sum[0]+p[0]/points.length,sum[1]+p[1]/points.length],[0,0]);assert.equal(d.data[0].value,120);assert.equal(d.data[0].target,100);
 const validate=(chart,w,h)=>{for(const mark of chart.layout.marks.filter(m=>['actual-contour','target-track'].includes(m.role))){const points=chart.current.get(mark.key);assert.ok(points.flat().every(Number.isFinite));for(const[x,y]of points){assert.ok(x>=-1e-8&&x<=w+1e-8,`${mark.role} x ${x}`);assert.ok(y>=-1e-8&&y<=h+1e-8,`${mark.role} y ${y}`);}const sibling=chart.layout.marks.find(m=>m.identity===mark.identity&&m.role===(mark.role==='actual-contour'?'actual-point':'target-endpoint')),point=center(chart.current.get(sibling.key)),end=[(points[63][0]+points[64][0])/2,(points[63][1]+points[64][1])/2];assert.ok(Math.hypot(end[0]-point[0],end[1]-point[1])<1e-8);simple(points);}};
 try{for(const [w,h]of[[300,180],[640,340],[800,440]])for(const effect of['guided','smooth','cascade'])for(const[from,to]of[['target-progress','target-pairs'],['target-pairs','target-progress']]){const options={view:from,width:w,height:h,palette:'vermilion'},manual=new ScientificMorphChart(win.document.createElement('div'),d,options),live=new ScientificMorphChart(win.document.createElement('div'),d,{...options}),source=manual.layout,nodes=new Map([...manual.nodes].map(([id,n])=>[id,n.shape])),seek=manual.setDocument(d,to,{manual:true,effect});try{live.setView(to,{effect,duration:1000});for(const p of[0,.001,.1,.25,.49,.5,.51,.65,.75,.9,.999,1]){seek(p);advance(p*1000);validate(manual,w,h);validate(live,w,h);assert.deepEqual([...live.current],[...manual.current]);}seek(0);for(const m of source.marks)assert.deepEqual(manual.current.get(m.key),m.points);seek(1);for(const m of manual.layout.marks)assert.deepEqual(manual.current.get(m.key),m.points);seek(.43);const shown=structuredClone([...manual.current]),resume=manual.setDocument(d,from,{manual:true,resume:true});resume(0);assert.deepEqual([...manual.current],shown);for(const p of[.000001,.2,.5,.8,1]){resume(p);validate(manual,w,h);}for(const m of source.marks)assert.deepEqual(manual.current.get(m.key),m.points);for(const[id,node]of nodes)assert.equal(manual.nodes.get(id).shape,node);}finally{manual.destroy();live.destroy();}}assert.deepEqual(d,original);}finally{await win.happyDOM.close();}
});

test('a straight target distance that changes direction closes at its real endpoints instead of rotating its old length',()=>{
 const d=businessSeriesDocument(withRecordIds(getExample('progress'),{legacyNamespace:'polish-zero-cap'})),a=layoutBusinessSeries(d,'target-progress',640,340),b=layoutBusinessSeries(d,'target-pairs',640,340),old=a.marks.find(m=>m.role==='actual-contour'&&d.data[m.row].value<d.data[m.row].target),next=b.marks.find(m=>m.key===old.key),span=mark=>((mark.points[63][0]+mark.points[64][0])-(mark.points[0][0]+mark.points[127][0]))/2,from=span(old),to=span(next),q=from/(from-to),cap=interpolateBusinessSeriesMark(old.points,old,next,q);assert.ok(cap.flat().every(Number.isFinite));assert.ok(Math.max(...cap.map(p=>p[0]))-Math.min(...cap.map(p=>p[0]))<1e-8);assert.ok(area(cap)<1e-7);assert.ok(Math.max(...cap.map(p=>p[1]))-Math.min(...cap.map(p=>p[1]))<14);for(const p of[q-.001,q,q+.001])for(const[x,y]of interpolateBusinessSeriesMark(old.points,old,next,p)){assert.ok(x>=0&&x<=640);assert.ok(y>=0&&y<=340);}assert.deepEqual(interpolateBusinessSeriesMark(old.points,old,next,0),old.points);assert.deepEqual(interpolateBusinessSeriesMark(old.points,old,next,1),next.points);
});

test('filled native series converge through measured endpoints before opening thin rank trajectories',async()=>{
 const win=new Window();
 try{for(const template of['groupedbar','groupedbarh','stackedbar','stackedcolumn','percentcolumn','percentarea','stream']){const d=seriesDocument({doc:withRecordIds(getExample(template),{legacyNamespace:'polish-rank:'+template})}),before=structuredClone(d),from={groupedbar:'grouped-columns',groupedbarh:'grouped-bars',stackedbar:'stacked-bars',stackedcolumn:'stacked-columns',percentcolumn:'percent-columns',percentarea:'percent-area',stream:'stacked-area'}[template],chart=new SeriesMorphChart(win.document.createElement('div'),d,{view:from,width:800,height:440});try{const seek=chart.setDocument(d,'series-rank',{manual:true,effect:'guided'});seek(.5);for(const m of chart.layout.marks){const points=chart.current.get(m.key);assert.ok(Math.max(...points.map(p=>p[0]))-Math.min(...points.map(p=>p[0]))<=5.01);assert.ok(Math.max(...points.map(p=>p[1]))-Math.min(...points.map(p=>p[1]))<=5.01);assert.equal(m.value,d.data.find(r=>r._id===m.key).value);}seek(.65);for(const m of chart.layout.marks){const points=chart.current.get(m.key);for(let i=0;i<64;i++)assert.ok(Math.hypot(points[i][0]-points[127-i][0],points[i][1]-points[127-i][1])<=5.01);simple(points);}seek(1);for(const m of chart.layout.marks)assert.deepEqual(chart.current.get(m.key),m.points);assert.deepEqual(d,before);}finally{chart.destroy();}}}finally{await win.happyDOM.close();}
});

test('explicit arc and turn controls keep their own geometry after the guided series refinement',async()=>{
 const win=new Window(),d=seriesDocument(presetWork('series-revenue').steps[0]),frames=[];
 try{for(const effect of['smooth','arc','turn']){const chart=new SeriesMorphChart(win.document.createElement('div'),d,{view:'grouped-columns',width:800,height:440});try{const seek=chart.setDocument(d,'stacked-columns',{manual:true,effect});seek(.5);frames.push([...chart.current]);seek(1);for(const m of chart.layout.marks)assert.deepEqual(chart.current.get(m.key),m.points);}finally{chart.destroy();}}assert.notDeepEqual(frames[0],frames[1]);assert.notDeepEqual(frames[0],frames[2]);}finally{await win.happyDOM.close();}
});

test('signed series bars and line flanks stay ordered through actual chart seeking and interruption',async()=>{
 const win=new Window(),d=seriesDocument(presetWork('series-change').steps[0]);
 for(const view of['multi-line','small-multiples'])for(const mark of layoutSeries(d,view,800,440).marks.filter(m=>m.value!==null)){const thickness=view==='multi-line'?1.15:.9;assert.deepEqual(mark.points[32],[mark.geometry.cx,mark.geometry.cy-thickness]);assert.deepEqual(mark.points[95],[mark.geometry.cx,mark.geometry.cy+thickness]);}
 try{for(const from of['grouped-columns','multi-line']){const to=from==='multi-line'?'grouped-columns':'multi-line',chart=new SeriesMorphChart(win.document.createElement('div'),d,{view:from,width:800,height:440}),start=chart.layout,nodes=new Map([...chart.nodes].map(([id,n])=>[id,n.shape])),seek=chart.setDocument(d,to,{manual:true,effect:'guided',recipe:'series-endpoints'});try{for(const q of[.1,.35,.5,.65,.9]){seek(q);for(const m of chart.layout.marks.filter(m=>m.value!==null)){const points=chart.current.get(m.key);assert.ok(points.flat().every(Number.isFinite));if(m.value!==0)assert.ok(area(points)>1e-8);simple(points);if(q===.5)assert.ok(Math.max(...points.map(p=>p[0]))-Math.min(...points.map(p=>p[0]))<=5.01);}}seek(.43);const current=structuredClone([...chart.current]),resume=chart.setDocument(d,from,{manual:true,resume:true});resume(0);assert.deepEqual([...chart.current],current);resume(.5);for(const m of chart.layout.marks.filter(m=>m.value!==null))simple(chart.current.get(m.key));resume(1);for(const m of start.marks)assert.deepEqual(chart.current.get(m.key),m.points);for(const [id,node]of nodes)assert.equal(chart.nodes.get(id).shape,node);}finally{chart.destroy();}}}finally{await win.happyDOM.close();}
});

test('thin series trajectories retain shared measured midpoints while changing panels or ranks',async()=>{
 const win=new Window();
 try{for(const effect of['guided','smooth','cascade'])for(const[from,to]of[['multi-line','small-multiples'],['small-multiples','multi-line'],['multi-line','series-rank'],['series-rank','multi-line']]){const d=seriesDocument(presetWork(from==='series-rank'||to==='series-rank'?'series-revenue':'series-focus').steps[0]),chart=new SeriesMorphChart(win.document.createElement('div'),d,{view:from,width:800,height:440});try{const seek=chart.setDocument(d,to,{manual:true,effect});for(const p of[.1,.35,.5,.65,.9]){seek(p);for(const mark of chart.layout.marks){const next=chart.layout.marks.find(m=>m.seriesId===mark.seriesId&&m.periodIndex===mark.periodIndex+1);if(!next||mark.value===null||next.value===null)continue;const a=chart.current.get(mark.key),b=chart.current.get(next.key);assert.deepEqual(a[63],b[0]);assert.deepEqual(a[64],b[127]);}}seek(1);for(const m of chart.layout.marks)assert.deepEqual(chart.current.get(m.key),m.points);}finally{chart.destroy();}}}finally{await win.happyDOM.close();}
});

test('business plot reserves wrapped legend rows and percentage zero ticks avoid roundtrip noise',()=>{
 for(const id of['marimekko','likert','stackedwaterfall','pyramid'])for(const [w,h]of[[300,160],[300,200],[800,440]]){const work=presetWork('complete-business-'+id+'-story'),d=completionBusinessDocument(work.steps[0].doc);for(const step of work.steps){const layout=layoutCompletionBusiness(d,step.view,w,h),columns=layout.groupLegendColumns||layout.groups.length,lastLegend=35+Math.floor((layout.groups.length-1)/columns)*18;assert.ok(layout.plot.y-12>lastLegend+10,`${id} ${w}`);assert.ok(layout.plot.h>0);assert.ok(layout.plot.y+layout.plot.h+20<=h);}}
 const work=presetWork('complete-business-labbe-story'),l=layoutCompletionBusiness(completionBusinessDocument(work.steps[0].doc),work.steps[1].view);assert.ok(l.labels.some(label=>label.text==='0%'));assert.ok(l.labels.filter(label=>label.small).every(label=>!label.text.includes('e-')));
});

test('ledger line names separate without changing measured endpoints or original counts',()=>{
 const d=timePlanningDocument(presetWork('planning-ledger-story').steps[0].doc),layout=layoutTimePlanning(d,'planning-monthly-lines',540,300),groups=timePlanningGroups(d),names=new Set(groups.map(g=>g.name)),labels=layout.labels.filter(label=>names.has(label.fullText)).sort((a,b)=>a.y-b.y);assert.equal(labels.length,groups.length);for(let i=1;i<labels.length;i++)assert.ok(labels[i].y-labels[i-1].y>=10.9);assert.equal(layout.marks.filter(m=>m.original).length,d.data.length);for(const mark of layout.marks.filter(m=>m.original)){const row=d.data[mark.row];assert.equal(mark.originalValue,row.value);assert.ok(Math.abs(layout.scales.y.invert(mark.point[1])-row.value)<1e-8);}
});

test('scientific palette changes survive direct view changes and resumes start with actual displayed colors',async()=>{
 const win=new Window(),d=businessSeriesDocument(presetWork('target-single-gauge').steps[0].doc),chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:'target-gauge',width:800,height:440,palette:'ink'}),attrs=['fill','stroke','fill-opacity','stroke-opacity','stroke-width'];
 const key=chart.layout.marks.find(m=>m.role==='actual-contour').key,styles=()=>attrs.map(attr=>chart.nodes.get(key).shape.getAttribute(attr));
 try{chart.setPalette('vermilion',true);const theme=[chart.theme.bg,chart.theme.accent],before=styles();chart.setView('target-progress',{animate:false});assert.deepEqual([chart.theme.bg,chart.theme.accent],theme);assert.equal(chart.options.palette,'vermilion');assert.equal(chart.options.dark,true);
  chart.setView('target-gauge',{animate:false});assert.deepEqual(styles(),before);const seek=chart.setDocument(d,'target-progress',{manual:true,effect:'guided',palette:'cobalt',dark:false});seek(0);assert.deepEqual(styles(),before);seek(.43);const displayed=styles(),resume=chart.setDocument(d,'target-gauge',{manual:true,resume:true,palette:'vermilion',dark:true});resume(0);assert.deepEqual(styles(),displayed);resume(.0000001);for(let i=0;i<2;i++){const a=color(displayed[i]),b=color(styles()[i]);for(const channel of['r','g','b'])assert.ok(Math.abs(a[channel]-b[channel])<=1);}resume(1);assert.equal(chart.options.palette,'vermilion');assert.equal(chart.options.dark,true);
  chart.seekTransition('target-gauge','target-progress',.5);chart.setPalette('cobalt',false);const changed=styles();chart.seekTransition('target-gauge','target-progress',.5);assert.deepEqual(styles(),changed);
 }finally{chart.destroy();await win.happyDOM.close();}
});

test('cascade connectors follow both real observations with the same series timing',async()=>{
 const win=new Window(),d=temporalDocument(presetWork('temporal-rank-story').steps[0].doc),center=points=>points.reduce((sum,p)=>[sum[0]+p[0]/128,sum[1]+p[1]/128],[0,0]);
 try{for(const effect of['guided','smooth','cascade']){const chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:'temporal-rankclock',width:800,height:440});try{const seek=chart.setDocument(d,'temporal-ranklines',{manual:true,effect});for(const p of[.2,.35,.5,.65,.8]){seek(p);for(const link of chart.layout.marks.filter(m=>m.role==='rank-link')){const line=chart.current.get(link.key),ends=[[0,96],[32,64]].map(([a,b])=>[(line[a][0]+line[b][0])/2,(line[a][1]+line[b][1])/2]);for(const[i,id]of link.recordIds.entries()){const mark=chart.layout.marks.find(m=>m.identity===id&&m.role==='temporal-observation'),point=center(chart.current.get(mark.key));assert.ok(Math.hypot(point[0]-ends[i][0],point[1]-ends[i][1])<1e-8,`${effect} ${p}`);}}}}finally{chart.destroy();}}}finally{await win.happyDOM.close();}
});

test('direct waffle seeking hides compound bridge outlines and restores native appearance at both endpoints',async()=>{
 const win=new Window(),chart=new MorphChart(win.document.createElement('div'),morphExample,{view:'waffle',width:800,height:440,palette:'vermilion'}),styles=()=>chart.layout.marks.map(m=>[chart.nodes.get(m.key).shape.getAttribute('stroke-width'),chart.nodes.get(m.key).texture.getAttribute('opacity')]);
 try{const source=styles();chart.seekTransition('waffle','bars',.5);for(const[stroke,texture]of styles()){assert.equal(stroke,'0');assert.equal(texture,'0');}chart.seekTransition('waffle','bars',0);assert.deepEqual(styles(),source);chart.seekTransition('waffle','bars',1);for(const[stroke]of styles())assert.equal(stroke,'0.9');chart.seekTransition('waffle','bars',.5);for(const[stroke,texture]of styles()){assert.equal(stroke,'0');assert.equal(texture,'0');}chart.seekTransition('waffle','bars',1);for(const[stroke]of styles())assert.equal(stroke,'0.9');
 }finally{chart.destroy();await win.happyDOM.close();}
});
