import {test,before,after,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {createServer} from 'vite';
import english from '../../src/forma/locales/en.json' with {type:'json'};
let win,server,mountMotionGallery,scenarioPresets,scenarioCategory,setLocale;const previous=new Map();
before(async()=>{win=new Window({url:'http://localhost:4217/#motion'});for(const[k,v]of Object.entries({__FORMA_MESSAGES__:english,window:win,document:win.document,XMLSerializer:win.XMLSerializer,ResizeObserver:win.ResizeObserver,requestAnimationFrame:win.requestAnimationFrame.bind(win),cancelAnimationFrame:win.cancelAnimationFrame.bind(win)})){previous.set(k,Object.getOwnPropertyDescriptor(globalThis,k));Object.defineProperty(globalThis,k,{value:v,configurable:true,writable:true});}server=await createServer({server:{middlewareMode:true,hmr:false},appType:'custom'});({mountMotionGallery}=await server.ssrLoadModule('/src/forma/motion-gallery.js'));({scenarioPresets,scenarioCategory}=await server.ssrLoadModule('/src/forma/scenario-presets.js'));({setLocale}=await server.ssrLoadModule('/src/forma/locale.js'));});
afterEach(()=>setLocale('zh-CN'));
after(async()=>{await server?.close();await win?.happyDOM.close();for(const[k,v]of previous)if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];});
function fixture(t){document.body.innerHTML='<main></main>';const host=document.querySelector('main');let used;const gallery=mountMotionGallery(host,{onUse:w=>used=structuredClone(w)});t.after(()=>gallery.destroy());return {host,use(){host.querySelector('[data-mg-use]').click();return used;}};}
function input(host,selector,value,event='input'){const el=host.querySelector(selector);assert.ok(el,selector);el.value=String(value);el.dispatchEvent(new win.Event(event,{bubbles:true}));}
function geometry(host){return [...host.querySelectorAll('.mg-player-host svg :is(path,rect,circle,line)')].map(el=>[el.tagName,...['d','x','y','x1','x2','y1','y2','cx','cy','r','width','height','transform','opacity'].map(a=>el.getAttribute(a))]);}

test('preset filters and search browse without replacing or interrupting the selected work',t=>{const{host,use}=fixture(t),before=use(),svg=host.querySelector('.mg-player-host svg');assert.equal(host.querySelectorAll('[data-mg-preset]').length,scenarioPresets.filter(p=>scenarioCategory(p)!=='research').length);host.querySelector('[data-mg-group=research]').click();assert.equal(host.querySelectorAll('[data-mg-preset]').length,scenarioPresets.filter(p=>scenarioCategory(p)==='research').length);input(host,'[data-mg-search]','public-penguins');assert.equal(host.querySelectorAll('[data-mg-preset]').length,1);assert.ok(host.querySelector('[data-mg-preset=public-penguins]'));assert.equal(host.querySelector('.mg-player-host svg'),svg);assert.deepEqual(use(),before);});

test('an empty search keeps the preview usable and Escape or clear restores matching presets',t=>{const{host,use}=fixture(t),before=use();input(host,'[data-mg-search]','unmatched-query-89431');assert.equal(host.querySelector('.mg-search-empty').hidden,false);assert.equal(host.querySelector('.mg-presets').hidden,true);assert.deepEqual(use(),before);host.querySelector('[data-mg-search]').dispatchEvent(new win.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(host.querySelector('.mg-search-empty').hidden,true);assert.equal(host.querySelector('[data-mg-search]').value,'');input(host,'[data-mg-search]','monthly');host.querySelector('.mg-search [data-mg-clear]').click();assert.equal(document.activeElement,host.querySelector('[data-mg-search]'));assert.equal(host.querySelectorAll('[data-mg-preset]').length,scenarioPresets.filter(p=>scenarioCategory(p)!=='research').length);});

test('expanded browsing and keyboard navigation keep explicit selection separate from focus',t=>{const{host,use}=fixture(t),before=use();host.querySelector('[data-mg-expand]').click();assert.equal(host.querySelector('.mg-presets').dataset.expanded,'true');const buttons=[...host.querySelectorAll('[data-mg-preset]')];buttons[0].focus();buttons[0].dispatchEvent(new win.KeyboardEvent('keydown',{key:'End',bubbles:true}));assert.equal(document.activeElement,buttons.at(-1));assert.deepEqual(use(),before);buttons.at(-1).click();assert.equal(host.querySelector('.mg-presets').dataset.expanded,'false');assert.equal(host.querySelector('[data-mg-expand]').getAttribute('aria-expanded'),'false');assert.equal(document.activeElement.getAttribute('aria-pressed'),'true');assert.notEqual(use().name,before.name);});

test('pair inspection reaches repeatable nonadjacent and reversed frames without changing authored steps',t=>{const{host,use}=fixture(t);host.querySelector('[data-mg-preset=paired-evaluation]').click();const before=use();input(host,'[data-mg-pair]',2,'change');input(host,'[data-mg-progress]',50);const middle=geometry(host);assert.equal(host.querySelector('[data-mg-progress-label]').textContent,'50%');assert.equal(host.querySelector('[data-mg-from]').value,'0');assert.equal(host.querySelector('[data-mg-pair]').value,'2');input(host,'[data-mg-progress]',100);assert.equal(host.querySelector('[data-mg-progress-label]').textContent,'100%');assert.notDeepEqual(geometry(host),middle);const endpoint=geometry(host);input(host,'[data-mg-progress]',50);assert.deepEqual(geometry(host),middle);host.querySelector('[data-mg-swap]').click();assert.equal(host.querySelector('[data-mg-progress-label]').textContent,'0%');assert.deepEqual(geometry(host),endpoint);assert.equal(host.querySelector('[data-mg-from]').value,'2');assert.equal(host.querySelector('[data-mg-pair]').value,'0');input(host,'[data-mg-progress]',75);assert.equal(host.querySelector('[data-mg-progress-label]').textContent,'75%');assert.deepEqual(use().steps,before.steps);});

test('choosing the same endpoint swaps the other endpoint and keeps a real pair',t=>{const{host}=fixture(t);input(host,'[data-mg-pair]',0,'change');assert.equal(host.querySelector('[data-mg-from]').value,'1');assert.equal(host.querySelector('[data-mg-pair]').value,'0');input(host,'[data-mg-from]',0,'change');assert.equal(host.querySelector('[data-mg-from]').value,'0');assert.equal(host.querySelector('[data-mg-pair]').value,'1');});

test('English preset search, empty state and inspection controls are translated',t=>{setLocale('en');const{host}=fixture(t);assert.equal(host.querySelector('[data-mg-search]').placeholder,'Search presets or chart types');assert.equal(host.querySelector('[data-mg-progress]').getAttribute('aria-label'),'Transition progress');assert.equal(host.querySelector('[data-mg-swap]').getAttribute('aria-label'),'Swap start and end');host.querySelector('[data-mg-group=research]').click();input(host,'[data-mg-search]','penguins');assert.ok(host.querySelector('[data-mg-preset=public-penguins]'));input(host,'[data-mg-search]','no-match-723811');assert.equal(host.querySelector('.mg-search-empty p').textContent,'No matching presets');});
