import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {getExample} from '../../src/forma/catalog.js';
import {withRecordIds,recordId} from '../../src/forma/data-identity.js';
import {setLocale} from '../../src/forma/locale.js';
import {andrewsValue14} from '../../src/forma/volume14-data.js';
import {multivariateExtendedViews as views,multivariateExtendedViewMap as viewMap,multivariateExtendedDocument as document,multivariateExtendedEligibility as eligible,multivariateExtendedCompatibility as compatible,multivariateExtendedBounds as bounds,multivariateExtendedColorKeys as colorKeys,multivariateExtendedColorSubjects as colorSubjects,multivariateExtendedOrderFields as orderFields,multivariateExtendedGuide as guide,multivariateExtendedAgentGuide as agentGuide} from '../../src/forma/multivariate-extended-rules.js';
import {layoutMultivariateExtended as layout} from '../../src/forma/multivariate-extended-morph.js';
import {multivariateExtendedPresets as presets,multivariateExtendedRecords as records} from '../../src/forma/multivariate-extended-presets.js';
const raw=template=>withRecordIds(getExample(template),{legacyNamespace:'mvx-qa'}),doc=template=>document(raw(template));
const near=(a,b)=>assert.ok(Math.abs(a-b)<=1e-8*Math.max(1,Math.abs(a),Math.abs(b)),`${a} != ${b}`);
function finite(l){assert.ok(l.plot.h>0);assert.equal(new Set(l.marks.map(m=>m.key)).size,l.marks.length);for(const m of l.marks){assert.equal(m.points.length,128,m.key);assert.ok(m.points.flat().every(Number.isFinite),m.key);assert.ok(m.anchor.every(Number.isFinite),m.key);}for(const label of l.labels)assert.ok(Number.isFinite(label.x)&&Number.isFinite(label.y),JSON.stringify(label));}
const forDoc=d=>views.filter(v=>v.family===d.family);

test('eight actual native examples supply sixteen valid layouts with all original records and fields',()=>{
 assert.equal(Object.keys(viewMap).length,8);assert.equal(views.length,16);for(const[template,view]of Object.entries(viewMap)){const original=raw(template),before=structuredClone(original),d=document(original);assert.deepEqual(original,before);assert.equal(d.unit,original.unit);assert.deepEqual(d.source,original.source);for(let i=0;i<d.data.length;i++)for(const[k,v]of Object.entries(original.data[i]))assert.deepEqual(d.data[i][k],v);for(const v of forDoc(d)){assert.equal(eligible(d,v.id).valid,true,template+'/'+v.id);for(const[w,h]of[[300,240],[800,440],[1280,720]]){const l=layout(d,v.id,w,h);finite(l);assert.deepEqual([...new Set(l.marks.filter(m=>!m.derived).map(m=>m.identity))].sort(),d.data.map(recordId).sort());for(const m of l.marks.filter(m=>m.editable)){assert.equal(m.identity,recordId(d.data[m.row]));assert.equal(m.value,d.data[m.row][m.editable]);assert.equal(m.originalValue,d.data[m.row][m.editable]);}}}assert.equal(eligible(d,view).valid,true);}
});

test('parallel matrix preserves signed exact measurements and each point’s identity',()=>{
 const d=doc('parallel');d.data[0].value=-5;d.data[1].value=0;assert.equal(eligible(d,'mvx-profile-matrix').valid,true);const a=layout(d,'mvx-parallel'),b=layout(d,'mvx-profile-matrix');assert.deepEqual(a.marks.map(m=>m.key).sort(),b.marks.map(m=>m.key).sort());assert.ok(b.labels.some(l=>l.text==='-5'));assert.ok(b.labels.some(l=>l.text==='0'));for(const m of b.marks.filter(m=>m.editable)){assert.equal(m.value,d.data[m.row].value);assert.ok(m.opacity>0);}
});

test('radar retains max, fixed axis order and only an explicitly derived closing copy',()=>{
 const d=doc('radar');d.data[0].value=0;for(const v of['mvx-radar','mvx-radar-unfold']){const l=layout(d,v);finite(l);assert.equal(l.marks.filter(m=>m.editable).length,d.data.length);assert.equal(l.marks.filter(m=>m.role==='mvx-closure').length,d.seriesOrder.length);assert.ok(l.marks.filter(m=>m.role==='mvx-closure').every(m=>m.derived&&!m.editable));assert.equal(l.marks.filter(m=>m.closure).length,d.seriesOrder.length);}const changed=structuredClone(d);changed.max+=1;assert.notEqual(compatible(d,changed),'');const invalid=structuredClone(d);invalid.max=0;assert.equal(eligible(invalid,'mvx-radar').valid,false);
});

test('ternary uses true barycentric coordinates and exposes three native component edits without renormalizing',()=>{
 const d=doc('ternary');d.data[0]={...d.data[0],a:100,b:0,c:0};for(const v of['mvx-ternary','mvx-composition']){const l=layout(d,v);finite(l);for(const r of d.data){const marks=l.marks.filter(m=>!m.derived&&m.identity===recordId(r));assert.equal(marks.length,3);assert.deepEqual(marks.map(m=>m.editable),['a','b','c']);if(v==='mvx-ternary'){const expected=l.statistics.vertices.reduce((a,p,i)=>a.map((n,k)=>n+p[k]*r[['a','b','c'][i]]/100),[0,0]);for(const m of marks)m.point.forEach((n,i)=>near(n,expected[i]));}}}const invalid=structuredClone(d);invalid.data[0].c=1;assert.equal(eligible(invalid,'mvx-ternary').valid,false);assert.equal(invalid.data[0].c,1);
});

test('PCA keeps equal physical units, input signs, variance metadata and independent raw component fields',()=>{
 const d=doc('pca'),l=layout(d,'mvx-pca');near(l.scales.x(1)-l.scales.x(0),l.scales.y(0)-l.scales.y(1));assert.equal(l.marks.filter(m=>m.editable==='pc1').length,d.data.length);assert.equal(l.marks.filter(m=>m.editable==='pc2').length,d.data.length);for(const factor of[1e-12,1e12]){const scaled=structuredClone(d);scaled.data.forEach(r=>{r.pc1*=factor;r.pc2*=factor;});assert.equal(eligible(scaled,'mvx-pca').valid,true);const s=layout(scaled,'mvx-pca'),before=new Map(l.marks.map(m=>[m.key,m]));for(const m of s.marks)if(m.point)m.point.forEach((n,i)=>near(n,before.get(m.key).point[i]));}const changed=structuredClone(d);changed.pc1Variance+=.1;assert.notEqual(compatible(d,changed),'');const signs=structuredClone(d);signs.data[0].pc1*=-1;assert.equal(document(signs).data[0].pc1,signs.data[0].pc1);
});

test('correlation loadings preserve zero vectors, both original fields and the fixed unit circle',()=>{
 const d=doc('pcaloadings');d.data[0].loading1=d.data[0].loading2=0;for(const v of['mvx-loadings','mvx-loading-components']){assert.equal(eligible(d,v).valid,true);const l=layout(d,v);finite(l);const original=l.marks.filter(m=>!m.derived&&m.identity===recordId(d.data[0]));assert.equal(original.length,2);assert.ok(original.some(m=>m.opacity>0));assert.ok(l.marks.every(m=>m.nativeColorRole==='accent'));}const invalid=structuredClone(d);invalid.data[0].loading1=invalid.data[0].loading2=1;assert.equal(eligible(invalid,'mvx-loadings').valid,false);assert.deepEqual(colorSubjects(d),[]);
});

test('scree uses every original eigenvalue with exact percentages, cumulative endpoint and zero-height zeros',()=>{
 const d=doc('scree');d.data.at(-1).eigenvalue=0;for(const v of['mvx-scree','mvx-cumulative']){const l=layout(d,v);finite(l);near(l.statistics.shares.reduce((a,b)=>a+b),1);near(l.statistics.cumulative.at(-1),1);const zero=l.marks.find(m=>m.editable&&m.identity===recordId(d.data.at(-1)));assert.equal(zero.value,0);assert.ok(zero.points.every(p=>p[1]===zero.points[0][1]));for(const m of l.marks.filter(m=>m.editable))near(m.share,m.value/l.statistics.total);}const wrong=structuredClone(d);wrong.componentOrder.reverse();assert.equal(eligible(wrong,'mvx-scree').valid,false);const missing=structuredClone(d);missing.data[0].eigenvalue=null;assert.equal(eligible(missing,'mvx-scree').valid,false);
});

test('Andrews reuses fixed-order Fourier values and separates whole-vector curves from all editable coefficients',()=>{
 const d=doc('andrews'),l=layout(d,'mvx-andrews');assert.equal(l.marks.filter(m=>m.role==='mvx-fourier-curve').length,d.objectOrder.length);assert.equal(l.marks.filter(m=>m.editable).length,d.data.length);assert.ok(l.marks.length<d.data.length+d.objectOrder.length+1);for(const curve of l.statistics.curves)for(const p of curve.points)near(p.value,andrewsValue14(curve.values,p.t));for(const m of l.marks.filter(m=>m.role==='mvx-fourier-curve')){assert.equal(m.derived,true);assert.equal(m.editable,undefined);assert.equal(m.recordIds.length,d.variables.length);assert.ok(!d.data.some(r=>recordId(r)===m.identity));}const invalid=raw('andrews');delete invalid.variables;assert.equal(eligible(document(invalid),'mvx-andrews').valid,false);const reordered=structuredClone(d);reordered.variables.reverse();assert.notEqual(compatible(d,reordered),'');
});

test('RadViz keeps complete-table native normalization, separate derived samples and raw editable values',()=>{
 const d=doc('radviz'),l=layout(d,'mvx-radviz'),alternate=layout(d,'mvx-normalized-profiles');assert.equal(l.marks.filter(m=>m.role==='mvx-radviz-projection').length,d.sampleOrder.length);assert.equal(l.marks.filter(m=>m.editable).length,d.data.length);assert.deepEqual(l.marks.map(m=>m.key).sort(),alternate.marks.map(m=>m.key).sort());for(const p of l.statistics.points){const weights=p.records.map((r,i)=>(r.value-l.statistics.ranges[i][0])/(l.statistics.ranges[i][1]-l.statistics.ranges[i][0]));weights.forEach((v,i)=>near(v,p.weights[i]));near(p.x,weights.reduce((n,v,i)=>n+v*l.statistics.anchors[i].x,0)/weights.reduce((a,b)=>a+b));near(p.y,weights.reduce((n,v,i)=>n+v*l.statistics.anchors[i].y,0)/weights.reduce((a,b)=>a+b));const m=l.marks.find(m=>m.role==='mvx-radviz-projection'&&m.recordIds.includes(recordId(p.records[0])));assert.ok(m.derived&&!m.editable);assert.deepEqual(m.recordIds,p.records.map(recordId));}for(const r of d.data){const m=l.marks.find(m=>m.editable&&m.identity===recordId(r));assert.ok(m.opacity>0);assert.equal(m.value,r.value);}const zero=structuredClone(d);zero.data.filter(r=>r.sample===zero.sampleOrder[0]).forEach(r=>r.value=Math.min(...d.data.filter(q=>q.variable===r.variable).map(q=>q.value))-1);assert.equal(eligible(zero,'mvx-radviz').valid,false);const constant=structuredClone(d);constant.data.filter(r=>r.variable===constant.variableOrder[0]).forEach(r=>r.value=2);assert.equal(eligible(constant,'mvx-radviz').valid,false);
});

test('declared orders survive row sorting and invalid metadata never crashes color or bounds readers',()=>{
 for(const template of Object.keys(viewMap)){const d=doc(template),changed=structuredClone(d);changed.data.reverse();if(template==='scree')assert.equal(eligible(changed,viewMap[template]).valid,false);else{assert.equal(eligible(changed,viewMap[template]).valid,true);assert.equal(compatible(d,changed),'');const a=layout(d,viewMap[template]),b=layout(document(changed),viewMap[template]),points=new Map(a.marks.map(m=>[m.key,m.points]));for(const m of b.marks)assert.deepEqual(m.points,points.get(m.key));}assert.deepEqual(colorKeys(d).sort(),colorKeys(changed).sort());for(const property of Object.keys(orderFields(d)))for(const value of[null,[],['invalid'],'bad']){const bad={...raw(template),[property]:value},adapted=document(bad);assert.equal(eligible(adapted,viewMap[template]).valid,false,template+'/'+property);assert.doesNotThrow(()=>colorKeys(adapted));assert.doesNotThrow(()=>colorSubjects(adapted));assert.ok(Object.values(bounds(adapted)).flat().every(Number.isFinite));}for(const mutate of[c=>c.unit+=' changed',c=>c.source={...c.source,name:'changed'},c=>c.data[0]._id='changed']){const bad=structuredClone(d);mutate(bad);assert.notEqual(compatible(d,bad),'');}}
});

test('missing observations and nonfinite inputs reject without deleting or replacing original rows',()=>{
 for(const template of Object.keys(viewMap)){const d=doc(template),field=layout(d,viewMap[template]).marks.find(m=>m.editable).editable;for(const badValue of[null,NaN,Infinity]){const bad=structuredClone(d);bad.data[0][field]=badValue;assert.equal(eligible(bad,viewMap[template]).valid,false,template+'/'+field);assert.equal(bad.data.length,d.data.length);assert.ok(Object.is(bad.data[0][field],badValue));}const duplicate=structuredClone(d);duplicate.data[1]._id=duplicate.data[0]._id;assert.equal(eligible(duplicate,viewMap[template]).valid,false);}
});

test('eight independent native presets expose complete bilingual renderer and Agent contracts',()=>{
 assert.equal(presets.length,8);assert.equal(presets.filter(p=>p.category==='regular').length,2);assert.equal(presets.filter(p=>p.category==='research').length,6);assert.equal(records('missing'),null);for(const p of presets){const steps=records(p.id,'ochre');assert.deepEqual(steps.map(s=>s.view),p.views);for(const s of steps){assert.equal(s.doc.template,p.template);assert.deepEqual(s.doc.data,steps[0].doc.data);assert.equal(s.options.palette,'ochre');assert.equal(eligible(document(s.doc),s.view).valid,true);}steps[0].doc.data[0].sentinel=true;assert.equal(steps[1].doc.data[0].sentinel,undefined);}try{setLocale('en');for(const v of views){assert.equal(v.name,v.en);assert.doesNotMatch(v.note,/\p{Script=Han}/u);}for(const p of presets){assert.doesNotMatch(p.name+p.description+p.dataNote+p.relation,/\p{Script=Han}/u);assert.doesNotMatch(guide(document(records(p.id)[0].doc),p.views[0]).join(' '),/\p{Script=Han}/u);}assert.doesNotMatch(agentGuide(true),/\p{Script=Han}/u);}finally{setLocale('zh-CN');}
});

test('sixteen directed multivariate transitions preserve DOM objects with exact endpoints, reverse seek and interrupted resume',async()=>{
 const {ScientificMorphChart}=await import('../../src/forma/scientific-morph.js');let directions=0;for(const p of presets)for(const from of p.views)for(const to of p.views){if(from===to)continue;directions++;const win=new Window(),d=document(records(p.id)[0].doc);let chart;try{chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:from,width:800,height:440,editable:true});const first=chart.layout,nodes=new Map([...chart.nodes].map(([k,n])=>[k,n.shape])),seek=chart.setDocument(d,to,{manual:true,effect:'guided',recipe:'mvx-unfold'});seek(.37);const captured=structuredClone([...chart.current]),reverse=chart.setDocument(d,from,{manual:true,resume:true,effect:'guided',recipe:'mvx-unfold'});reverse(0);assert.deepEqual([...chart.current],captured);reverse(1);for(const m of first.marks)assert.deepEqual(chart.current.get(m.key),m.points);const again=chart.setDocument(d,to,{manual:true,effect:'guided',recipe:'mvx-unfold'});again(.5);const halfway=structuredClone([...chart.current]);again(1);again(.5);assert.deepEqual([...chart.current],halfway);again(1);for(const m of chart.layout.marks)assert.deepEqual(chart.current.get(m.key),m.points);for(const[k,node]of nodes)assert.equal(chart.nodes.get(k).shape,node);assert.doesNotMatch(chart.svg.outerHTML,/NaN|Infinity|undefined/);}finally{chart?.destroy();await win.happyDOM.close();}}assert.equal(directions,16);
});

test('saved-work, native edit fields, stable color bindings and standalone SVG exports retain complete original schemas',async()=>{
 const [{newWork,cleanWork,stepReport,transitionPlan},{stepSVG},{ScientificMorphChart},{colorSubjects:subjects}]=await Promise.all([import('../../src/forma/work-model.js'),import('../../src/forma/work-export.js'),import('../../src/forma/scientific-morph.js'),import('../../src/forma/color-semantics.js')]),win=new Window(),old=new Map();for(const[k,v]of Object.entries({document:win.document,XMLSerializer:win.XMLSerializer})){old.set(k,Object.getOwnPropertyDescriptor(globalThis,k));Object.defineProperty(globalThis,k,{value:v,configurable:true,writable:true});}try{for(const p of presets){const work=newWork(records(p.id));assert.deepEqual(cleanWork(JSON.parse(JSON.stringify(work))),work);for(const step of work.steps){assert.equal(stepReport(step).valid,true,p.id);assert.deepEqual(subjects(step.doc),colorSubjects(step.doc));const bindings=colorSubjects(step.doc).map(s=>({id:s.id,color:'#123456'}));step.options.colorBindings=bindings;const svg=stepSVG(step,work.steps);assert.doesNotMatch(svg.replace(/<style>[\s\S]*?<\/style>/g,''),/NaN|Infinity|undefined/);const chart=new ScientificMorphChart(win.document.createElement('div'),document(step.doc),{view:step.view,editable:true,colorBindings:bindings});for(const m of chart.layout.marks.filter(m=>m.editable)){assert.equal(chart.nodes.get(m.key).group.dataset.editField,m.editable);assert.equal(Number(chart.nodes.get(m.key).group.dataset.editRow),m.row);if(bindings.length)assert.equal(chart.markColor(m),'#123456');}chart.destroy();}assert.equal(transitionPlan(work.steps[0],work.steps[1],{steps:work.steps}).mode,'morph');}const d=doc('parallel'),oldName=d.objectOrder[0],name='<script>&"';d.data.filter(r=>r.label===oldName).forEach(r=>r.label=name);d.objectOrder[0]=name;const chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:'mvx-profile-matrix'});assert.equal(chart.svg.querySelectorAll('script').length,0);assert.match(chart.svg.outerHTML,/&lt;script&gt;/);chart.destroy();}finally{for(const[k,v]of old){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];}await win.happyDOM.close();}
});

test('actual native and morph SVGs agree on PCA palette and loading/scree semantic colors, with bindings taking precedence',async()=>{
 const [{ScientificMorphChart},{ChartScene},{themeFor}]=await Promise.all([import('../../src/forma/scientific-morph.js'),import('../../src/forma/charts.js'),import('../../src/forma/palettes.js')]),win=new Window(),old=new Map();for(const[k,v]of Object.entries({window:win,document:win.document})){old.set(k,Object.getOwnPropertyDescriptor(globalThis,k));Object.defineProperty(globalThis,k,{value:v,configurable:true,writable:true});}
 try{for(const template of['pca','pcaloadings','scree'])for(const options of[{palette:'ink'},{palette:'cobalt',dark:true},{palette:'ochre'},{palette:'ink',colors:['#315577','#ba6750','#858455']}]){const d=raw(template),a=document(d),native=new ChartScene(win.document.createElement('div'),d,{...options,interactive:false,width:800,height:440}),chart=new ScientificMorphChart(win.document.createElement('div'),a,{...options,view:viewMap[template],width:800,height:440});native.render(1);chart.render(1);try{if(template==='pca'){const marks=[...native.svg.querySelectorAll('[data-mark="pca-score"]')];for(let i=0;i<a.data.length;i++){const mark=chart.layout.marks.find(m=>m.identity===recordId(a.data[i])&&m.editable==='pc1');assert.equal(chart.markColor(mark),marks[i].getAttribute('stroke'));assert.equal(chart.nodes.get(mark.key).shape.getAttribute('stroke'),marks[i].getAttribute('stroke'));}}if(template==='pcaloadings'){const stroke=native.svg.querySelector('[data-mark="pca-loading"]').getAttribute('stroke');for(const m of chart.layout.marks)assert.equal(chart.nodes.get(m.key).shape.getAttribute('stroke'),stroke);}if(template==='scree'){const bars=[...native.svg.querySelectorAll('[data-mark="scree-bar"]')];for(let i=0;i<a.data.length;i++){const m=chart.layout.marks.find(m=>m.editable&&m.identity===recordId(a.data[i]));assert.equal(chart.nodes.get(m.key).shape.getAttribute('fill'),bars[i].getAttribute('fill'));}}}finally{native.destroy();chart.destroy();}}
 const d=raw('pca'),bindings=colorSubjects(d).map(s=>({id:s.id,color:'#123456'})),native=new ChartScene(win.document.createElement('div'),d,{palette:'ink',colorBindings:bindings,interactive:false}),chart=new ScientificMorphChart(win.document.createElement('div'),document(d),{view:'mvx-pca',palette:'ink',colorBindings:bindings});native.render(1);chart.render(1);assert.ok([...native.svg.querySelectorAll('[data-mark="pca-score"]')].every(n=>n.getAttribute('stroke')==='#123456'));for(const m of chart.layout.marks.filter(m=>m.editable))assert.equal(chart.nodes.get(m.key).shape.getAttribute('stroke'),'#123456');native.destroy();chart.destroy();
 }finally{for(const[k,v]of old){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];}await win.happyDOM.close();}
});

test('maximum native populations, signed extremes and tiny nonzero spans remain finite inside compact and desktop canvases',()=>{
 const cases=[];const p=raw('parallel');p.data=Array.from({length:6},(_,i)=>Array.from({length:6},(_,j)=>({_id:`p-${i}-${j}`,label:`P${i}`,dimension:`D${j}`,value:(i-j)*1e12}))).flat();cases.push(p);
 const r=raw('radar');r.max=1e-12;r.data=Array.from({length:4},(_,i)=>Array.from({length:8},(_,j)=>({_id:`r-${i}-${j}`,series:`S${i}`,axis:`A${j}`,value:(i+j)%9/8*1e-12}))).flat();cases.push(r);
 const t=raw('ternary');t.data=Array.from({length:80},(_,i)=>({_id:`t-${i}`,label:`S${i}`,group:`G${i%4}`,a:i%3===0?100:0,b:i%3===1?100:0,c:i%3===2?100:0}));cases.push(t);
 const c=raw('pca');c.data=Array.from({length:300},(_,i)=>({_id:`pc-${i}`,label:`S${i}`,group:`G${i%5}`,pc1:Math.sin(i)*1e12,pc2:Math.cos(i*.7)*1e-12}));cases.push(c);
 const l=raw('pcaloadings');l.data=Array.from({length:24},(_,i)=>({_id:`l-${i}`,variable:`V${i}`,loading1:i===0?0:Math.sin(i)*.7,loading2:i===0?0:Math.cos(i)*.7}));cases.push(l);
 const s=raw('scree');s.data=Array.from({length:16},(_,i)=>({_id:`s-${i}`,component:`PC${i+1}`,eigenvalue:(16-i)*1e-300}));cases.push(s);
 const a=raw('andrews');a.variables=Array.from({length:8},(_,i)=>`V${i}`);a.data=Array.from({length:60},(_,i)=>a.variables.map((variable,j)=>({_id:`a-${i}-${j}`,label:`S${i}`,group:`G${i%6}`,variable,value:Math.sin(i+j)*1e12}))).flat();cases.push(a);
 const v=raw('radviz');v.data=Array.from({length:100},(_,i)=>Array.from({length:8},(_,j)=>({_id:`v-${i}-${j}`,sample:`S${i}`,group:`G${i%6}`,variable:`V${j}`,value:(20+Math.sin(i*.7+j)*10+i*.01)*1e-12}))).flat();cases.push(v);
 for(const original of cases){const d=document(original);for(const view of forDoc(d)){assert.equal(eligible(d,view.id).valid,true,original.template);for(const[w,h]of[[300,240],[800,440]]){const l=layout(d,view.id,w,h);finite(l);for(const m of l.marks)for(const[x,y]of m.points)assert.ok(x>=-3&&x<=w+3&&y>=-3&&y<=h+3,`${view.id} ${m.role}: ${x},${y}`);}}}
});

test('PCA legend swatches match the actual native-color observation marks in all palette modes',async()=>{
 const {ScientificMorphChart}=await import('../../src/forma/scientific-morph.js'),win=new Window();try{for(const options of[{palette:'ink'},{palette:'cobalt',dark:true},{palette:'ochre'},{palette:'ink',colors:['#315577','#ba6750','#858455']}]){const d=doc('pca'),chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:'mvx-pca',width:800,height:440,...options});try{const dots=[...chart.guideLayer.querySelectorAll('circle[cy="32"]')];assert.equal(dots.length,chart.layout.groups.length);for(let i=0;i<dots.length;i++){const m=chart.layout.marks.find(m=>m.editable&&m.group===chart.layout.groups[i]);assert.equal(dots[i].getAttribute('fill'),chart.markColor(m));}}finally{chart.destroy();}}}finally{await win.happyDOM.close();}
});

test('co-located component fields actually unfold from the displayed native sample at intermediate frames',async()=>{
 const {ScientificMorphChart}=await import('../../src/forma/scientific-morph.js'),win=new Window();try{for(const template of['ternary','pca','pcaloadings']){const p=presets.find(p=>p.template===template),d=document(records(p.id)[0].doc),chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:p.views[0],width:800,height:440});try{const old=new Map(chart.layout.marks.map(m=>[m.key,m])),seek=chart.setDocument(d,p.views[1],{manual:true,effect:'guided',recipe:'mvx-unfold'});seek(.5);for(const m of chart.layout.marks.filter(m=>m.role.startsWith('mvx-component-'))){const before=old.get(m.key),points=chart.current.get(m.key);for(let i=0;i<points.length;i++)points[i].forEach((v,j)=>near(v,(before.points[i][j]+m.points[i][j])/2));}const captured=structuredClone([...chart.current]),back=chart.setDocument(d,p.views[0],{manual:true,resume:true,effect:'guided'});back(0);assert.deepEqual([...chart.current],captured);back(.5);const start=new Map(captured);for(const m of chart.layout.marks.filter(m=>m.role.startsWith('mvx-component-'))){const points=chart.current.get(m.key);for(let i=0;i<points.length;i++)points[i].forEach((v,j)=>near(v,(start.get(m.key)[i][j]+m.points[i][j])/2));}}finally{chart.destroy();}}}finally{await win.happyDOM.close();}
});

test('real table edits retain native numeric fields and IDs through undo, redo and saved-work reload',async()=>{
 const[{findTemplate},{createEditorModel},{newWork,cleanWork,stepEligibility,stepMorphDocument}]=await Promise.all([import('../../src/forma/catalog.js'),import('../../src/forma/editor-model.js'),import('../../src/forma/work-model.js')]);
 for(const p of presets){const work=newWork(records(p.id)),step=work.steps[0],before=step.doc.data[0],fields=findTemplate(p.template).fields.map(f=>f[0]),model=createEditorModel(step.doc,undefined,{viewValidation:doc=>stepEligibility({...step,doc})}),field=layout(document(step.doc),step.view).marks.find(m=>m.editable&&m.row===0).editable;let expected;
  if(p.template==='ternary'){const values=fields.map(k=>before[k]);values[fields.indexOf('a')]+=1;values[fields.indexOf('c')]-=1;expected=values[fields.indexOf(field)];model.setRow(0,values);}else{expected=before[field]*(p.template==='scree'?1.01:.99)+(['parallel','andrews','radviz'].includes(p.template)?.001:0);model.setCell(0,fields.indexOf(field),expected);}
  assert.equal(model.report.valid,true,p.template);assert.equal(model.doc.data[0][field],expected);assert.equal(model.doc.data[0]._id,before._id);model.undo();assert.equal(model.doc.data[0][field],before[field]);model.redo();assert.equal(model.doc.data[0][field],expected);const reopened=cleanWork(JSON.parse(JSON.stringify(newWork([{doc:model.doc,view:step.view}])))),adapted=stepMorphDocument(reopened.steps[0]);assert.equal(adapted.data[0][field],expected);assert.equal(adapted.data[0]._id,before._id);assert.equal(eligible(adapted,step.view).valid,true);const mark=layout(adapted,step.view).marks.find(m=>m.editable===field&&m.identity===before._id);assert.equal(mark.value,expected);
 }
});
