import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {mountMultivariateControls} from '../../src/forma/multivariate-controls.js';
import {getExample} from '../../src/forma/catalog.js';
import {createEditorModel} from '../../src/forma/editor-model.js';
import {multivariateVariables} from '../../src/forma/multivariate-rules.js';
test('variable selectors store IDs, display units, disable duplicate axes, and swap in one undo',()=>{const win=new Window(),host=win.document.createElement('div'),model=createEditorModel(getExample('splom'));win.document.body.append(host);let view;const tools=mountMultivariateControls(host,{getDoc:()=>model.doc,onPair:pair=>model.setMeta('selectedPair',pair),onView:next=>view=next,view:'multivariate-matrix'});try{const pair=structuredClone(model.doc.selectedPair),rows=structuredClone(model.doc.data),vars=multivariateVariables(model.doc);assert.equal(host.querySelectorAll('[data-variable-axis]').length,2);assert.equal(host.querySelector('[data-variable-axis="0"]').value,pair[0]);assert.equal(host.querySelector(`[data-variable-axis="0"] option[value="${pair[1]}"]`).disabled,true);host.querySelector('[data-variable-swap]').click();assert.deepEqual(model.doc.selectedPair,[pair[1],pair[0]]);assert.deepEqual(model.doc.data,rows);model.undo();tools.refresh();assert.deepEqual(model.doc.selectedPair,pair);host.querySelector('[data-variable-view]').click();assert.equal(view,'multivariate-focus');const input=host.querySelector('[data-variable-axis="0"]');input.value=vars[2].id;input.dispatchEvent(new win.Event('change',{bubbles:true}));assert.equal(model.doc.selectedPair[0],vars[2].id);assert.equal(host.querySelector('[data-variable-axis="1"]').value,pair[1]);}finally{tools.destroy();win.happyDOM.close();}});
test('ordinary charts do not expose unrelated scientific controls',()=>{const win=new Window(),host=win.document.createElement('div'),tools=mountMultivariateControls(host,{getDoc:()=>getExample('column')});assert.equal(host.hidden,true);assert.equal(host.querySelector('select'),null);tools.destroy();win.happyDOM.close();});
