import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {mountPlayerViewport} from '../../src/forma/player-viewport.js';
function setup(){const win=new Window(),host=win.document.createElement('div');host.className='wp-player';host.innerHTML='<div data-wp-stage><article class="wp-artboard"><svg viewBox="0 0 320 230"><path d="M 2 3 L 40 50"/></svg></article></div>';win.document.body.append(host);const stage=host.firstElementChild;Object.defineProperties(stage,{clientWidth:{value:340},clientHeight:{value:310}});const view=mountPlayerViewport(host);return{win,host,stage,view,close(){view.destroy();win.happyDOM.close();}};}
test('live viewport scales the original nodes and restores exact canvas origin',()=>{const s=setup();try{const svg=s.host.querySelector('svg'),path=svg.innerHTML;s.view.setZoom(2);assert.equal(s.host.dataset.canvasZoom,'2');assert.equal(s.host.querySelector('svg'),svg);assert.equal(svg.innerHTML,path);assert.equal(s.host.querySelector('.wp-artboard').style.transform,'scale(2)');assert.equal(s.host.querySelector('.wp-viewport-space').style.width,'680px');assert.equal(s.stage.tabIndex,0);s.view.fit();assert.deepEqual(s.view.capture(),{zoom:1,left:0,top:0});assert.equal(s.host.querySelector('.wp-artboard').style.transform,'scale(1)');assert.equal(s.stage.tabIndex,-1);}finally{s.close();}});
test('reading controls support Escape, bounded zoom, and viewport restoration without application events',()=>{const s=setup();try{let input=0;s.host.addEventListener('input',()=>input++);s.host.querySelector('[data-wp-zoom=detail]').click();assert.equal(s.view.capture().zoom,2);s.view.restore({zoom:2.5,left:80,top:45});assert.deepEqual(s.view.capture(),{zoom:2.5,left:80,top:45});s.view.setZoom(99);assert.equal(s.view.capture().zoom,3);assert.equal(s.host.querySelector('[data-wp-zoom=in]').disabled,true);s.host.dispatchEvent(new s.win.KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));assert.equal(s.view.capture().zoom,1);assert.equal(s.win.document.activeElement,s.host.querySelector('[data-wp-zoom=detail]'));assert.equal(input,0);}finally{s.close();}});
test('destroy removes viewport wrappers and preserves artboard contents',()=>{const s=setup(),art=s.host.querySelector('.wp-artboard');s.view.setZoom(2);s.view.destroy();assert.equal(s.stage.firstElementChild,art);assert.equal(art.style.transform,'');assert.equal(s.host.querySelector('.wp-view-tools'),null);assert.ok(art.querySelector('svg'));s.win.happyDOM.close();});
test('playback and pair inspection retain zoom without changing authored state or resetting time',async()=>{const {mountWorkPlayer}=await import('../../src/forma/work-player.js'),{presetWork}=await import('../../src/forma/work-model.js');const win=new Window(),host=win.document.createElement('div'),work=presetWork('matrix-to-focus'),original=structuredClone(work),queue=new Map();let id=0;win.requestAnimationFrame=fn=>{queue.set(++id,fn);return id;};win.cancelAnimationFrame=id=>queue.delete(id);const player=mountWorkPlayer(host,work);try{player.inspectBetween(work.steps[0].id,work.steps[1].id,.5);const at=player.getTime(),svg=host.querySelector('.wp-graphic svg'),shape=svg.innerHTML;Object.defineProperties(host.querySelector('[data-wp-stage]'),{clientWidth:{value:340},clientHeight:{value:310}});player.setZoom(2);assert.equal(player.getTime(),at);assert.equal(host.querySelector('.wp-graphic svg'),svg);assert.equal(svg.innerHTML,shape);player.inspectBetween(work.steps[0].id,work.steps[1].id,.75);assert.equal(host.querySelector('.wp-artboard').style.transform,'scale(2)');player.play();for(const now of[0,100]){const pending=[...queue.values()];queue.clear();pending.forEach(fn=>fn(now));}assert.ok(player.getTime()>at);assert.equal(host.querySelector('.wp-artboard').style.transform,'scale(2)');player.fit();assert.deepEqual(work,original);assert.equal(player.getViewport().zoom,1);}finally{player.destroy();win.happyDOM.close();}});
