import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {createServer} from 'vite';
let w,server,openDataImporter,getExample,createEditorModel,mountDataWorkspace;const globals=new Map();
before(async()=>{w=new Window({url:'http://localhost:4191'});for(const [k,v] of Object.entries({window:w,document:w.document,navigator:w.navigator,XMLSerializer:w.XMLSerializer,ResizeObserver:w.ResizeObserver,requestAnimationFrame:w.requestAnimationFrame.bind(w),cancelAnimationFrame:w.cancelAnimationFrame.bind(w)})){globals.set(k,Object.getOwnPropertyDescriptor(globalThis,k));Object.defineProperty(globalThis,k,{value:v,configurable:true,writable:true});}server=await createServer({server:{middlewareMode:true,hmr:false},appType:'custom'});({openDataImporter}=await server.ssrLoadModule('/src/forma/data-importer.js'));({getExample}=await server.ssrLoadModule('/src/forma/catalog.js'));({createEditorModel}=await server.ssrLoadModule('/src/forma/editor-model.js'));({mountDataWorkspace}=await server.ssrLoadModule('/src/forma/data-workspace.js'));});
after(async()=>{await server?.close();await w?.happyDOM.close();for(const [k,d]of globals){if(d)Object.defineProperty(globalThis,k,d);else delete globalThis[k];}});
beforeEach(()=>{document.body.innerHTML='<main></main>';});
const $=s=>document.querySelector(s),click=s=>{assert.ok($(s),s);$(s).click();},input=(s,v,event='input')=>{assert.ok($(s),s);$(s).value=v;$(s).dispatchEvent(new w.Event(event,{bubbles:true}));};
function paste(){input('#di-paste','月份\t销售额\t备注\n一月\t0.0000000123\t未舍入\n二月\t0\t真实零\n三月\t8\t已核对');click('[data-di="read-paste"]');click('footer [data-di="mapping"]');input('[data-di-meta="source"]','合成输入验收');}

test('import preview retains extra columns, is atomic and undoable; current source editor updates both mapped and extra values',t=>{const m=createEditorModel(getExample('column')),before=m.snapshot;let imp=openDataImporter(m.doc,{snapshot:m.snapshot,onApply:d=>m.replace(d)});t.after(()=>imp.close());assert.equal(imp.dialog.getAttribute('aria-modal'),'false');paste();click('[data-di="prepare"]');assert.ok($('[data-di="apply"]'));assert.deepEqual(m.snapshot,before);click('[data-di="apply"]');assert.equal(m.doc.data[0].value,1.23e-8);assert.equal(m.doc.data[0]._extra[2],'未舍入');const ids=m.recordIds();m.undo();assert.deepEqual(m.snapshot,before);m.redo();imp=openDataImporter(m.doc,{current:true,snapshot:m.snapshot,onApply:d=>m.replace(d)});input('[data-source-cell="1:2"]','修改备注');input('[data-source-cell="1:1"]','9e-9');click('footer [data-di="mapping"]');click('[data-di="prepare"]');click('[data-di="apply"]');assert.equal(m.doc.data[0]._extra[2],'修改备注');assert.equal(m.doc.data[0].value,9e-9);assert.deepEqual(m.recordIds(),ids);});
test('invalid numeric cells link to original coordinates and background edits invalidate application',t=>{const m=createEditorModel(getExample('column'));let applied=false;const before=JSON.stringify(m.snapshot),imp=openDataImporter(m.doc,{snapshot:m.snapshot,isCurrent:()=>JSON.stringify(m.snapshot)===before,onApply:()=>applied=true});t.after(()=>imp.close());paste();click('[data-di="source"]');input('[data-source-cell="1:1"]','bad');click('footer [data-di="mapping"]');click('[data-di="prepare"]');assert.equal($('[data-di="apply"]'),null);assert.match($('.di-errors').textContent,/B2/);click('[data-di="locate"]');assert.equal(document.activeElement.dataset.sourceCell,'1:1');input('[data-source-cell="1:1"]','5e-8');click('footer [data-di="mapping"]');click('[data-di="prepare"]');m.setCell(0,1,'90');click('[data-di="apply"]');assert.equal(applied,false);assert.match($('#di-status').textContent,/背后的数据已变化/);});
test('xlsx sheet selection and formula acknowledgment use the injected workbook session; closing terminates it',async t=>{let closed=false,applied;const imp=openDataImporter(getExample('column'),{onApply:d=>applied=d,readWorkbook:async()=>({sheets:[{name:'Sheet1',range:'B3:D5'}],close(){closed=true;},select:async()=>({matrix:[['类别','数值','备注'],['A','1e-8','公式'],['B','0','零']],locations:[['S!B3','S!C3','S!D3'],['S!B4','S!C4','S!D4'],['S!B5','S!C5','S!D5']],issues:[],notes:['1 个公式按文件中已保存的结果读取'],origin:{sheet:'Sheet1',range:'B3:D5',formulaCount:1,formulaPolicy:'cached-results-only'}})})});t.after(()=>imp.close());await imp.loadFile({name:'验收.xlsx'});assert.equal($('#di-range').value,'B3:D5');click('footer [data-di="mapping"]');click('[data-di="prepare"]');assert.match($('#di-status').textContent,/核对/);$('#di-formula-ack').checked=true;$('#di-formula-ack').dispatchEvent(new w.Event('change',{bubbles:true}));click('[data-di="prepare"]');click('[data-di="apply"]');assert.equal(applied.data[0].value,1e-8);assert.equal(applied.tableInput.origin.file,'验收.xlsx');assert.equal(closed,true);});
test('production workspace exposes original fields and replaces data through the same undo history',t=>{const records=[{key:'template:column',doc:getExample('column'),options:{palette:'ink',duration:8,ratio:'wide'}}];const controller=mountDataWorkspace($('main'),{records,activeKey:records[0].key,onChange(){},onActive(){},onRemove(){},onSave(){},toast(){}});t.after(()=>controller.destroy());click('[data-workspace="import"]');paste();click('[data-di="prepare"]');click('[data-di="apply"]');assert.equal(records[0].doc.data[0].value,1.23e-8);click('[data-workspace="source-table"]');assert.match($('.di-grid').textContent,/备注/);click('[data-dialog-close]');click('[data-workspace="undo"]');assert.equal(records[0].doc.data[0].value,42);});
test('view-specific layout limits appear before applying; they do not turn legal data into errors',t=>{let applied;const imp=openDataImporter(getExample('column'),{viewValidation:()=>({valid:false,reason:'此视图需要八个样本'}),onApply:d=>applied=d});t.after(()=>imp.close());paste();click('[data-di="prepare"]');assert.match($('.di-body').textContent,/此视图需要八个样本/);click('[data-di="apply"]');assert.equal(applied.data.length,3);});
test('delayed workbook load cannot replace a newer pasted table',async t=>{let resolveRead,terminated=false;const imp=openDataImporter(getExample('column'),{readWorkbook:()=>new Promise(r=>resolveRead=r)});t.after(()=>imp.close());const pending=imp.loadFile({name:'slow.xlsx'});click('[data-di="paste"]');paste();resolveRead({sheets:[],close(){terminated=true;}});await pending;assert.equal(terminated,true);assert.ok($('[data-di-mapping]'));assert.equal($('#di-sheet'),null);});
test('switching from Excel to paste removes the discarded file from a restored import session',async t=>{
 let reads=0;const readWorkbook=async()=>{reads++;return {sheets:[{name:'Sheet1',range:'A1:B2'}],close(){},select:async()=>({matrix:[['类别','数值'],['Excel','1']],locations:[['A1','B1'],['A2','B2']],issues:[],origin:{sheet:'Sheet1',range:'A1:B2'}})};};
 let imp=openDataImporter(getExample('column'),{readWorkbook});t.after(()=>imp.close());await imp.loadFile({name:'discarded.xlsx'});click('[data-di="paste"]');paste();const saved=imp.captureSession();imp.close();
 imp=openDataImporter(getExample('column'),{readWorkbook,resume:saved});await imp.ready;assert.equal(reads,1);assert.equal(imp.captureSession().file,null);click('[data-di="source"]');assert.equal($('#di-sheet'),null);assert.equal($('[data-source-cell="1:0"]').value,'一月');
});
test('a restored workbook is closed if its dialog was closed or changed to a pasted source while reopening',async t=>{
 const seed=openDataImporter(getExample('column'),{readWorkbook:async()=>({sheets:[{name:'Sheet1',range:'A1:B2'}],close(){},select:async()=>({matrix:[['类别','数值'],['Excel','1']],locations:[['A1','B1'],['A2','B2']],issues:[],origin:{sheet:'Sheet1',range:'A1:B2'}})})});await seed.loadFile({name:'slow.xlsx'});const saved=seed.captureSession();seed.close();
 for(const cancel of ['paste','close']){let resolveRead,terminated=false;const imp=openDataImporter(getExample('column'),{resume:saved,readWorkbook:()=>new Promise(resolve=>resolveRead=resolve)});t.after(()=>imp.close());if(cancel==='paste'){click('[data-di="paste"]');paste();}else imp.close();resolveRead({sheets:[{name:'Sheet1',range:'A1:B2'}],close(){terminated=true;}});await imp.ready;assert.equal(terminated,true,cancel);if(cancel==='paste'){assert.ok($('[data-di-mapping]'));click('[data-di="source"]');assert.equal($('#di-sheet'),null);assert.equal($('[data-source-cell="1:0"]').value,'一月');}imp.close();}
});
test('replacement clears stale template observation subtitle and original headers retain workbook addresses',async t=>{let applied;const imp=openDataImporter(getExample('column'),{onApply:d=>applied=d});t.after(()=>imp.close());paste();assert.equal($('[data-di-meta="subtitle"]').value,'');click('[data-di="prepare"]');click('[data-di="apply"]');assert.equal(applied.subtitle,'');assert.deepEqual(applied.tableInput.headerRefs,['A1','B1','C1']);});
