import {test} from 'node:test';
import assert from 'node:assert/strict';
import {utils,write} from 'xlsx';
import {readWorkbook,workbookSheets,workbookRange} from '../../src/forma/xlsx-reader.js';
import {textSource,transformSource,pasteSource,sourceFromDocument,replaceSourceCells,overwriteSource} from '../../src/forma/source-table.js';
import {importedTableDocument,splitTable} from '../../src/forma/table-data.js';
import {getExample} from '../../src/forma/catalog.js';
import {createEditorModel} from '../../src/forma/editor-model.js';
import {makeProject,readProject} from '../../src/forma/project-file.js';

function workbook(){const b=utils.book_new();utils.book_append_sheet(b,utils.aoa_to_sheet([['说明']]),'说明');const s=utils.aoa_to_sheet([['编号','数值','备注'],['0001',0.0000000123,'中文\n第二行'],['0002',0,''],['0003',null,'缺失'],['0004',.15,'百分比']]);s.B5.z='0%';utils.book_append_sheet(b,s,'实验');return b;}
function imported(){const source=textSource([['原名称','观测值','备注'],['甲','0.0000000123','保留我'],['乙','0','第二行'],['丙','2.5','第三行']]);const table={...splitTable(source.matrix),locations:source.locations.slice(1),origin:{kind:'paste'}};const doc=importedTableDocument(getExample('column'),table,[0,1]).doc;doc.source.name='合成验收数据';return doc;}
test('xlsx keeps sheets, selected coordinates, scientific precision, zero, blanks and multiline text',()=>{const b=readWorkbook(write(workbook(),{type:'array',bookType:'xlsx'}));assert.equal(workbookSheets(b).length,2);const s=workbookRange(b,'实验','A1:C5');assert.deepEqual(s.matrix[1],['0001','1.23e-8','中文\n第二行']);assert.equal(s.matrix[2][1],'0');assert.equal(s.matrix[3][1],'');assert.equal(s.matrix[4][1],'0.15');assert.equal(s.locations[4][1],'实验!B5');assert.deepEqual(workbookRange(b,'实验','B2:C3').matrix,[['1.23e-8','中文\n第二行'],['0','']]);});
test('xlsx formula errors are located, cached values acknowledged, merge and range overflow rejected',()=>{const b=workbook(),s=b.Sheets.实验;s.B2={t:'n',f:'1/100000000',v:1e-8};s.B3={t:'n',f:'1+1'};s.B4={t:'e',v:7};s['!rows']=[{},{hidden:true}];const r=workbookRange(b,'实验','A1:C5');assert.equal(r.matrix[1][1],'1e-8');assert.deepEqual(r.issues.map(i=>i.address),['B3','B4']);assert.match(r.notes.join(' '),/公式/);assert.match(r.notes.join(' '),/隐藏行/);s['!merges']=[utils.decode_range('A1:C1')];assert.throws(()=>workbookRange(b,'实验','A1:C5'),/合并/);assert.doesNotThrow(()=>workbookRange(b,'实验','A2:C5'));assert.throws(()=>workbookRange(b,'实验','A1:AG2'),/32 列/);assert.throws(()=>workbookRange(b,'实验','A1:A1502'),/1,501/);assert.throws(()=>readWorkbook(new Uint8Array([1,2])),/有效/);});
test('xlsx dates and zero-padded identifiers preserve meaning',()=>{const b=workbook(),s=b.Sheets.实验;s.A2={t:'n',v:7,z:'00000'};s.B2={t:'n',v:61,z:'yyyy-mm-dd'};assert.deepEqual(workbookRange(b,'实验','A2:B2').matrix,[['00007','1900-03-01']]);s.B2.v=60;assert.equal(workbookRange(b,'实验','B2').issues.length,1);b.Workbook={WBProps:{date1904:true}};s.B2.v=1;assert.equal(workbookRange(b,'实验','B2').matrix[0][0],'1904-01-02');});
test('wide-long and matrix expansion retain missing observations, zeros and extra columns with lineage',()=>{const source=textSource([['月份','甲','乙','备注'],['一月','0','','未填'],['二月','1e-8','2','核对']]);const long=transformSource(source,'long',[1,2]);assert.deepEqual(long.matrix[1],['一月','未填','甲','0']);assert.deepEqual(long.matrix[2],['一月','未填','乙','']);assert.equal(long.locations[2][3],'C2');assert.equal(long.matrix.length,5);const matrix=transformSource(textSource([['真实/预测','A','B'],['A','5','0'],['B','','8']]),'matrix');assert.deepEqual(matrix.matrix[3],['B','A','']);assert.equal(matrix.matrix[2][2],'0');assert.deepEqual(transformSource(transformSource(source,'transpose'),'transpose').matrix,source.matrix);assert.throws(()=>transformSource(textSource([['t','a','b'],...Array.from({length:800},()=>['x','1','2'])]),'long',[1,2]),/超过/);});
test('original columns stay editable with stable IDs; one undo restores the entire import and save reopen retains them',()=>{const model=createEditorModel(getExample('column')),before=model.snapshot,doc=imported();model.replace(doc);assert.equal(model.doc.data[0].value,1.23e-8);assert.equal(model.doc.data[0]._extra[2],'保留我');assert.equal(model.doc.tableInput.rowRefs[doc.data[0]._id][2],'C2');model.undo();assert.deepEqual(model.snapshot,before);model.redo();const source=sourceFromDocument(model.doc,model.snapshot);source.matrix[1][2]='已更改';source.matrix[1][1]='9e-9';const result=replaceSourceCells(model.doc,source,[0,1],model.snapshot);assert.deepEqual(result.errors,[]);model.replace(result.doc);assert.equal(model.doc.data[0]._id,doc.data[0]._id);assert.equal(model.doc.data[0]._extra[2],'已更改');assert.equal(model.doc.data[0].value,9e-9);const reopened=readProject(JSON.stringify(makeProject(model.doc,{}))).doc;assert.deepEqual(sourceFromDocument(reopened).matrix,sourceFromDocument(model.doc).matrix);});
test('rectangular overwrites preserve other records, reject extra columns atomically and never convert blanks to zero',()=>{const d=imported(),m=createEditorModel(d),before=m.snapshot;let result=overwriteSource(m.doc,textSource([['数值'],['77'],['88']]),true,{row:1,col:1},m.snapshot);assert.equal(result.doc.data[0].value,1.23e-8);assert.equal(result.doc.data[1].value,77);assert.equal(result.doc.data[2]._id,d.data[2]._id);assert.equal(result.doc.data[2]._extra[2],'第三行');assert.throws(()=>overwriteSource(m.doc,textSource([['1','2'],['3','4']]),false,{row:0,col:1},m.snapshot),/超出列数/);assert.deepEqual(m.snapshot,before);result=overwriteSource(m.doc,textSource([['']]),false,{row:1,col:1},m.snapshot);assert.ok(result.errors.length);assert.ok(Number.isNaN(result.doc.data[1].value));});
test('raw 3x3 paste is rectangular, retains original coordinates and leaves source untouched on overflow',()=>{const s=textSource([['a','b','c'],['1','2','3'],['4','5','6'],['7','8','9']]);const next=pasteSource(s,[['甲','0',''],['乙','1e-8','注'],['丙','2','末']],1,0,{fixedRows:true});assert.equal(next.matrix[1][2],'');assert.equal(next.locations[2][1],'B3');assert.equal(s.matrix[1][0],'1');assert.throws(()=>pasteSource(s,[['x','y']],1,2),/边界/);assert.throws(()=>pasteSource(s,[['x']],4,0,{fixedRows:true}),/边界/);});
