import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {networkDocument} from '../../src/forma/network-series-rules.js';
import {networkRecords,networkPresets} from '../../src/forma/network-series-presets.js';
import {layoutNetwork,interpolateNetworkMark,networkAttachmentPoint} from '../../src/forma/network-series-morph.js';
import {structuralDocument} from '../../src/forma/structural-series-rules.js';
import {layoutStructural,interpolateStructuralMark} from '../../src/forma/structural-series-morph.js';
import {scientificDocument} from '../../src/forma/scientific-rules.js';
import {layoutOrderedEstimates} from '../../src/forma/exploratory-morph.js';
import {ScientificMorphChart} from '../../src/forma/scientific-morph.js';
import {getExample} from '../../src/forma/catalog.js';
import {withRecordIds} from '../../src/forma/data-identity.js';
import {presetWork} from '../../src/forma/work-model.js';
import {HierarchyMorphChart} from '../../src/forma/hierarchy-morph.js';
import {relationalDocument} from '../../src/forma/relational-rules.js';
import {color} from 'd3';
import {scientificMotionState} from '../../src/forma/scientific-motion-state.js';
import {advancedRelationsDocument} from '../../src/forma/advanced-relations-rules.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} ≠ ${b}`);
const area=points=>Math.abs(points.reduce((n,p,i)=>{const q=points[(i+1)%points.length];return n+p[0]*q[1]-q[0]*p[1];},0))/2;
const finite=points=>assert.ok(points.flat().every(Number.isFinite));
const crossed=points=>{const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);for(let i=0;i<points.length;i++)for(let j=i+2;j<points.length;j++){if(i===0&&j===points.length-1)continue;const a=points[i],b=points[(i+1)%points.length],c=points[j],d=points[(j+1)%points.length];if(cross(a,b,c)*cross(a,b,d)<-1e-6&&cross(c,d,a)*cross(c,d,b)<-1e-6)return true;}return false;};

test('large network ribbons gain travel clearance without losing their exact source/target attachments',()=>{
 let checked=0;for(const p of networkPresets){const d=networkDocument(networkRecords(p.id)[0].doc),a=layoutNetwork(d,p.views[0]),b=layoutNetwork(d,p.views[1]);for(const old of a.marks.filter(m=>m.role==='network-edge')){const next=b.marks.find(m=>m.key===old.key),points=interpolateNetworkMark(old.points,old,next,.5),span=(mark,i)=>Math.hypot(mark.points[32+i][0]-mark.points[(128-i)%128][0],mark.points[32+i][1]-mark.points[(128-i)%128][1]),maxSpan=Math.max(...[0,32].map(i=>(span(old,i)+span(next,i))/2));finite(points);if(maxSpan<18)continue;checked++;for(const [i,cap]of[[0,16],[32,80]]){const width=Math.hypot(points[32+i][0]-points[(128-i)%128][0],points[32+i][1]-points[(128-i)%128][1]);assert.ok(width<=maxSpan*.341+1e-7);const expected=networkAttachmentPoint(scientificMotionState(points).networkAttachments[i===0?0:1]);for(const k of[0,1])near(points[cap][k],expected[k]);}assert.equal(interpolateNetworkMark(old.points,old,next,0),old.points);assert.equal(interpolateNetworkMark(old.points,old,next,1),next.points);}}assert.ok(checked>=10);
});

test('matrix area bubbles roll into radial cells through simple positive-area contours in both directions',()=>{
 const raw=withRecordIds(getExample('radialheatmap'),{legacyNamespace:'polish:radial'}),d=structuralDocument(raw),before=structuredClone(d),a=layoutStructural(d,'structural-bubbles'),b=layoutStructural(d,'structural-radial');
 for(const first of a.marks.filter(m=>m.role==='matrix-cell')){const second=b.marks.find(m=>m.key===first.key);for(const[old,next]of[[first,second],[second,first]])for(const q of[0,.1,.25,.5,.75,.9,1]){const points=interpolateStructuralMark(old.points,old,next,q);finite(points);assert.equal(crossed(points),false,`cell ${old.row}, q=${q}`);assert.ok(area(points)>0);if(q===0)assert.equal(points,old.points);if(q===1)assert.equal(points,next.points);}const middle=interpolateStructuralMark(first.points,first,second,.37);assert.equal(interpolateStructuralMark(middle,second,first,0),middle);finite(interpolateStructuralMark(middle,second,first,.6));}
 assert.deepEqual(d,before);
});

test('flow node long bodies curl into thin arc envelopes rather than forming broad rotating slabs',()=>{
 let count=0;for(const p of networkPresets){const d=networkDocument(networkRecords(p.id)[0].doc),layouts=p.views.map(v=>layoutNetwork(d,v));for(const a of layouts)for(const b of layouts){if(a===b)continue;for(const old of a.marks.filter(m=>m.role==='network-node')){const next=b.marks.find(m=>m.key===old.key);for(const q of[.1,.25,.5,.75,.9]){const points=interpolateNetworkMark(old.points,old,next,q);finite(points);assert.equal(crossed(points),false,`${a.view} → ${b.view}`);assert.ok(area(points)>0);assert.ok(area(points)<=Math.max(area(old.points),area(next.points))*1.85);count++;}assert.equal(interpolateNetworkMark(old.points,old,next,0),old.points);assert.equal(interpolateNetworkMark(old.points,old,next,1),next.points);}}}assert.ok(count>300);
});

test('hierarchy parent outlines retain continuous paint across the former midpoint hard switch',async()=>{
 const win=new Window();try{const d=relationalDocument(presetWork('research-budget').steps[0]),chart=new HierarchyMorphChart(win.document.createElement('div'),d,{view:'hierarchy-sunburst'}),seek=chart.setDocument(d,'hierarchy-treemap',{manual:true}),key=chart.layout.marks.find(m=>m.branch).key,node=chart.nodes.get(key).shape;seek(.499);const old=color(node.getAttribute('stroke')).rgb(),width=Number(node.getAttribute('stroke-width'));seek(.501);const next=color(node.getAttribute('stroke')).rgb();assert.ok(Math.abs(Number(node.getAttribute('stroke-width'))-width)<.001);for(const channel of['r','g','b'])assert.ok(Math.abs(next[channel]-old[channel])<2);seek(1);assert.equal(node.getAttribute('stroke-width'),'1.4');chart.destroy();}finally{await win.happyDOM.close();}
});

test('ordered estimate bands contract through paired upper/lower stations without diagonal spikes or gap bridging',()=>{
 const work=presetWork('uncertainty-over-time'),d=scientificDocument(work.steps[0]),before=structuredClone(d),a=layoutOrderedEstimates(d,'ordered-estimate-band',800,440),b=layoutOrderedEstimates(d,'ordered-estimate-intervals',800,440);
 for(const old of a.marks.filter(m=>m.role==='interval')){const next=b.marks.find(m=>m.key===old.key),row=d.data[old.row];if(row.estimate===null){assert.equal(old.opacity,0);assert.equal(next.opacity,0);continue;}for(const q of[0,.1,.25,.5,.75,.9,1]){const points=old.points.map((p,i)=>p.map((v,k)=>v+(next.points[i][k]-v)*q));finite(points);assert.equal(crossed(points),false);for(let i=0;i<64;i++){const lower=points[127-i];near(points[i][0],lower[0]);assert.ok(points[i][1]<=lower[1]+1e-7);}assert.ok(area(points)>0);}const missing=d.data.find(r=>r.estimate===null);if(missing){const gap=a.scales.x(Date.parse(missing.period));assert.ok(Math.max(...old.points.map(p=>p[0]))<gap||Math.min(...old.points.map(p=>p[0]))>gap);}}
 assert.deepEqual(d,before);
});

test('polished matrix and estimate work paths retain exact endpoints, DOM identities, backwards seek and interruption',async()=>{
 const win=new Window();try{const work=presetWork('uncertainty-over-time'),cases=[{doc:structuralDocument(withRecordIds(getExample('radialheatmap'),{legacyNamespace:'polish:matrix'})),a:'structural-bubbles',b:'structural-radial'},{doc:scientificDocument(work.steps[0]),a:'ordered-estimate-band',b:'ordered-estimate-intervals'}];for(const c of cases){const chart=new ScientificMorphChart(win.document.createElement('div'),c.doc,{view:c.a,width:800,height:440,editable:true}),nodes=new Map([...chart.nodes].map(([k,n])=>[k,n.shape])),start=chart.layout,seek=chart.setDocument(c.doc,c.b,{manual:true,effect:'guided'}),end=chart.layout;seek(.5);for(const m of end.marks.filter(m=>m.role==='matrix-cell'||m.role==='interval'&&m.opacity>0)){const points=chart.current.get(m.key);assert.equal(crossed(points),false,m.role);assert.ok(area(points)>0,m.role);}const middle=structuredClone([...chart.current]);seek(1);seek(.5);assert.deepEqual([...chart.current],middle);seek(0);for(const m of start.marks)assert.deepEqual(chart.current.get(m.key),m.points);seek(1);for(const m of end.marks)assert.deepEqual(chart.current.get(m.key),m.points);seek(.37);const interrupted=structuredClone([...chart.current]),resume=chart.setDocument(c.doc,c.a,{manual:true,resume:true,effect:'guided'});resume(0);assert.deepEqual([...chart.current],interrupted);resume(.7);resume(1);for(const[k,node]of nodes)assert.equal(chart.nodes.get(k).shape,node);assert.doesNotMatch(chart.svg.outerHTML,/NaN|Infinity|undefined/);chart.destroy();}}finally{await win.happyDOM.close();}
});

test('all matrix columns retain positive ordered row spacing after a displayed 37% reversal and repeated interruptions',async()=>{
 const center=p=>[(p[0][0]+p[63][0]+p[64][0]+p[127][0])/4,(p[0][1]+p[63][1]+p[64][1]+p[127][1])/4],distance=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]),win=new Window();let checked=0;
 try{for(const [template,a,b,adapt]of[['matrix','structural-bubbles','structural-radial',structuralDocument],['radialheatmap','structural-radial','structural-bubbles',structuralDocument],['adjacency','relationx-adjacency','relationx-adjacency-radial',advancedRelationsDocument]])for(const effect of['guided','smooth','cascade']){
  const d=adapt(withRecordIds(getExample(template),{legacyNamespace:'polish:roll:'+template})),saved=structuredClone(d),chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:a,width:800,height:440,editable:true}),start=chart.layout,seek=chart.setDocument(d,b,{manual:true,effect}),target=chart.layout,columns=new Map();
  for(const mark of target.marks.filter(m=>m.role==='matrix-cell'||m.role==='relationx-cell')){const column=mark.matrixRoll.angle;if(!columns.has(column))columns.set(column,[]);columns.get(column).push(mark);}
  const check=()=>{for(const marks of columns.values()){marks.sort((x,y)=>x.matrixRoll.row-y.matrixRoll.row);for(let i=1;i<marks.length;i++){const x=marks[i-1],y=marks[i],s0=start.marks.find(m=>m.key===x.key),s1=start.marks.find(m=>m.key===y.key),minimum=Math.min(distance(center(s0.points),center(s1.points)),distance(center(x.points),center(y.points))),actual=distance(center(chart.current.get(x.key)),center(chart.current.get(y.key)));assert.ok(actual>=minimum*.9-1e-7,`${template}/${effect}, column ${x.matrixRoll.angle}, rows ${i-1}/${i}: ${actual} < ${minimum*.9}`);checked++;}}};
  for(const q of[.1,.25,.5,.75,.85,.9]){seek(q);check();}seek(.37);check();let displayed=structuredClone([...chart.current]),reverse=chart.setDocument(d,a,{manual:true,resume:true,effect});reverse(0);assert.deepEqual([...chart.current],displayed);for(const q of[.05,.1,.25,.5,.75,.9]){reverse(q);check();}reverse(.43);displayed=structuredClone([...chart.current]);const resume=chart.setDocument(d,b,{manual:true,resume:true,effect});resume(0);assert.deepEqual([...chart.current],displayed);for(const q of[.1,.25,.5,.75,.9]){resume(q);check();}resume(1);for(const m of target.marks)assert.deepEqual(chart.current.get(m.key),m.points);assert.deepEqual(d,saved);chart.destroy();
 }}finally{await win.happyDOM.close();}assert.ok(checked>500);
});

test('network caps and directed arrows follow their same original live nodes through cascade, backwards seek and interrupted edits',async()=>{
 const win=new Window();let checked=0;
 try{for(const preset of networkPresets)for(const a of preset.views)for(const b of preset.views){if(a===b)continue;for(const effect of['guided','smooth','cascade']){
  const d=networkDocument(networkRecords(preset.id)[0].doc),saved=structuredClone(d),chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:a,width:800,height:440,editable:true}),start=chart.layout,nodes=new Map([...chart.nodes].map(([k,n])=>[k,n.shape])),seek=chart.setDocument(d,b,{manual:true,effect}),target=chart.layout;
  const check=()=>{for(const mark of chart.layout.marks.filter(m=>m.role==='network-edge')){const points=chart.current.get(mark.key),refs=scientificMotionState(points)?.networkAttachments;assert.equal(refs?.length,2);for(const [end,cap]of[[0,16],[1,80]]){assert.equal(refs[end].nodeKey,mark.networkAttachments[end].nodeKey);const expected=networkAttachmentPoint(refs[end],chart.current.get(refs[end].nodeKey));for(const k of[0,1])near(points[cap][k],expected[k]);checked++;}const direction=chart.layout.marks.find(m=>m.networkEdgeKey===mark.key);if(direction)for(const k of[0,1])near(chart.current.get(direction.key)[0][k],points[80][k]);finite(points);if(preset.id==='network-collaboration-story')assert.equal(crossed(points),false,`${a} → ${b}/${effect}: folded live ribbon`);assert.equal(mark.originalSource,d.data[mark.row].source);assert.equal(mark.originalTarget,d.data[mark.row].target);assert.equal(mark.value,d.data[mark.row].value);}};
  for(const q of[.2,.37,.5,.75,.95]){seek(q);check();}seek(.37);const displayed=structuredClone([...chart.current]),reverse=chart.setDocument(d,a,{manual:true,resume:true,effect});reverse(0);assert.deepEqual([...chart.current],displayed);for(const q of[.1,.3,.6,.9]){reverse(q);check();}reverse(1);for(const m of start.marks)assert.deepEqual(chart.current.get(m.key),m.points);seek(.37);const again=structuredClone([...chart.current]),edited=structuredClone(d);edited.data.forEach(r=>r.value*=1.15);const update=chart.setDocument(edited,b,{manual:true,resume:true,effect});update(0);assert.deepEqual([...chart.current],again);update(.4);for(const mark of chart.layout.marks.filter(m=>m.role==='network-edge')){const points=chart.current.get(mark.key),refs=scientificMotionState(points).networkAttachments;for(const [end,cap]of[[0,16],[1,80]]){const expected=networkAttachmentPoint(refs[end],chart.current.get(refs[end].nodeKey));for(const k of[0,1])near(points[cap][k],expected[k]);}assert.equal(mark.value,edited.data[mark.row].value);}for(const[k,n]of nodes)assert.equal(chart.nodes.get(k).shape,n);assert.deepEqual(d,saved);assert.doesNotMatch(chart.svg.outerHTML,/NaN|Infinity|undefined/);chart.destroy();
 }}}finally{await win.happyDOM.close();}assert.ok(checked>3000);
});

test('UpSet count bars and their actual membership rows transpose together without overlapping rank strips',async()=>{
 const win=new Window(),dot=p=>p.reduce((a,v)=>a.map((n,k)=>n+v[k]/p.length),[0,0]);let checked=0;
 try{for(const effect of['guided','smooth','cascade'])for(const[a,b]of[['relationx-upset','relationx-intersections'],['relationx-intersections','relationx-upset']]){
  const d=advancedRelationsDocument(withRecordIds(getExample('upset'),{legacyNamespace:'polish:intersection'})),saved=structuredClone(d),chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:a,width:800,height:440}),nodes=new Map([...chart.nodes].map(([k,n])=>[k,n.shape])),seek=chart.setDocument(d,b,{manual:true,effect}),target=chart.layout;
  const check=()=>{const bars=chart.layout.marks.filter(m=>m.role==='relationx-intersection'),frames=[];for(const bar of bars){const points=chart.current.get(bar.key),base=points[0].map((v,k)=>(v+points[127][k])/2),tip=points[63].map((v,k)=>(v+points[64][k])/2),length=Math.hypot(tip[0]-base[0],tip[1]-base[1]),axis=tip.map((v,k)=>(v-base[k])/length),normal=[-axis[1],axis[0]],projection=p=>p[0]*normal[0]+p[1]*normal[1],rank=projection(base),lower=Math.min(...points.map(projection)),upper=Math.max(...points.map(projection));assert.equal(crossed(points),false);assert.ok(area(points)>0);for(const [x,y]of points){assert.ok(x>=chart.layout.plot.x-1e-7&&x<=chart.layout.plot.x+chart.layout.plot.w+1e-7);assert.ok(y>=chart.layout.plot.y-1e-7&&y<=chart.layout.plot.y+chart.layout.plot.h+1e-7);}assert.equal(bar.value,d.data[bar.row].count);frames.push({bar,length,axis,lower,upper});for(const member of chart.layout.marks.filter(m=>m.identity===bar.identity&&m.role.startsWith('relationx-membership-')&&m.role!=='relationx-membership-link')){const center=dot(chart.current.get(member.key));near(projection(center),rank);assert.ok((center[0]-base[0])*axis[0]+(center[1]-base[1])*axis[1]<0,'Membership stays on the negative side of its own count baseline');assert.equal(member.active,bar.members.includes(d.sets[Number(member.role.split('-').at(-1))]));}checked++;}for(const f of frames)for(const g of frames){if(f===g)continue;near(f.axis[0],g.axis[0]);near(f.axis[1],g.axis[1]);near(f.length/f.bar.value,g.length/g.bar.value);assert.ok(f.upper<g.lower||g.upper<f.lower,'Each original exclusive intersection retains a separate rank strip');}};
  for(const q of[.1,.25,.37,.5,.75,.9]){seek(q);check();}seek(.37);const shown=structuredClone([...chart.current]),resume=chart.setDocument(d,a,{manual:true,resume:true,effect});resume(0);assert.deepEqual([...chart.current],shown);for(const q of[.1,.25,.5,.75,.9]){resume(q);check();}resume(1);for(const[k,n]of nodes)assert.equal(chart.nodes.get(k).shape,n);seek(1);for(const m of target.marks)assert.deepEqual(chart.current.get(m.key),m.points);assert.deepEqual(d,saved);chart.destroy();
 }}finally{await win.happyDOM.close();}assert.ok(checked>600);
});
