import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {IDBFactory} from 'fake-indexeddb';
import {Window} from 'happy-dom';
import {createServer} from 'vite';
import {openWorkStore} from '../../src/forma/work-store.js';
import {createWorkSaveSession} from '../../src/forma/work-save-session.js';
import {getExample} from '../../src/forma/catalog.js';
import {presetWork,newWork} from '../../src/forma/work-model.js';
let win,server,mountWorkEditor;const originals=new Map();
before(async()=>{win=new Window({url:'http://localhost:4201/#editor'});for(const [key,value] of Object.entries({window:win,document:win.document,XMLSerializer:win.XMLSerializer,ResizeObserver:win.ResizeObserver,requestAnimationFrame:win.requestAnimationFrame.bind(win),cancelAnimationFrame:win.cancelAnimationFrame.bind(win)})){originals.set(key,Object.getOwnPropertyDescriptor(globalThis,key));Object.defineProperty(globalThis,key,{value,configurable:true,writable:true});}server=await createServer({server:{middlewareMode:true,hmr:false},appType:'custom'});({mountWorkEditor}=await server.ssrLoadModule('/src/forma/work-editor.js'));});
after(async()=>{await server?.close();await win?.happyDOM.close();for(const [key,value] of originals){if(value)Object.defineProperty(globalThis,key,value);else delete globalThis[key];}});
const memory=()=>{const data=new Map();return {getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};};
const settle=()=>new Promise(r=>setTimeout(r,60));
async function fixture(t,initial=presetWork('classic')){const indexedDB=new IDBFactory(),storage=memory(),open=()=>openWorkStore({indexedDB,storage,name:crypto.randomUUID(),broadcast:false}),repository=await open();t.after(()=>repository.close());const host=document.createElement('main'),messages=[];document.body.append(host);const app=mountWorkEditor(host,{initial,repository,storage,toast:m=>messages.push(m)});t.after(()=>{app.destroy();host.remove();});await app.flush();return {app,host,repository,messages};}
function input(host,selector,value){const node=host.querySelector(selector);node.value=value;node.dispatchEvent(new win.Event('input',{bubbles:true}));}

test('editor uses async repository, shows completed save only after commit, reopens entered values',async t=>{const f=await fixture(t);input(f.host,'[data-we-name]','异步保存的作品');assert.match(f.host.querySelector('[data-we-status]').textContent,/正在/);assert.equal(f.repository.current().work.name,'经典形变');await f.app.flush();assert.equal(f.repository.current().work.name,'异步保存的作品');assert.match(f.host.querySelector('[data-we-status]').textContent,/已保存/);assert.equal(f.app.hasUnsaved(),false);});
test('editor handles failure with durable message and enabled backup even with incomplete cells',async t=>{const f=await fixture(t),save=f.repository.save;f.repository.save=async()=>{throw new DOMException('full','QuotaExceededError');};input(f.host,'[data-we-name]','尚未提交');assert.equal(await f.app.flush(),false);const issue=f.host.querySelector('[data-we-storage-issue]');assert.equal(issue.hidden,false);assert.match(issue.textContent,/尚未保存/);assert.equal(issue.querySelector('[data-we=backup-current]').disabled,false);assert.equal(f.repository.current().work.name,'经典形变');f.repository.save=save;assert.equal(await f.app.flush(),true);assert.equal(issue.hidden,true);});
test('editor conflict becomes a new work identity without losing edits and opens original separately',async t=>{const f=await fixture(t),original=f.repository.current(),remote=structuredClone(original.work);remote.name='另一标签的新标题';await f.repository.save(remote,{expectedRevision:original.revision});input(f.host,'[data-we-name]','当前标签修改');await f.app.flush();assert.notEqual(f.app.getWork().id,original.id);assert.equal(f.repository.peek(original.id).work.name,remote.name);assert.equal(f.host.querySelector('[data-we-storage-issue]').dataset.kind,'conflict');assert.match(f.app.getWork().name,/冲突副本/);f.host.querySelector('[data-we=open-remote]').click();await settle();assert.equal(f.app.getWork().id,original.id);assert.equal(f.app.getWork().name,remote.name);});
test('storage panel restores a real persisted version and updates editor fields',async t=>{const f=await fixture(t);input(f.host,'[data-we-name]','修改后');f.host.querySelector('[data-we=save]').click();await settle();f.host.querySelector('[data-we=storage]').click();await settle();assert.equal(f.host.querySelector('[data-we-panel]').getAttribute('aria-modal'),'false');assert.ok(f.host.querySelector('[data-we-revision]'));f.host.querySelector('[data-we-revision]').click();await settle();assert.equal(f.app.getWork().name,'经典形变');assert.equal(f.host.querySelector('[data-we-name]').value,'经典形变');});
test('edits typed during slow commit are serialized after it, including conflict rehoming',async t=>{const f=await fixture(t),record=f.repository.current();let release;const real=f.repository.save;let count=0;const repo={...f.repository,save:async(...args)=>{if(count++===0)await new Promise(r=>release=r);return real(...args);}};const local=createWorkSaveSession(repo,record),a=structuredClone(record.work),b=structuredClone(record.work);a.name='first';b.name='latest typed';local.stage(a);const flushing=local.flush();local.stage(b);await real({...record.work,name:'remote'},{expectedRevision:record.revision});release();assert.equal(await flushing,true);assert.notEqual(local.id,record.id);assert.equal((await f.repository.get(local.id)).work.name,'latest typed');assert.equal((await f.repository.get(record.id)).work.name,'remote');});

test('large scientific editor does not turn every raw sample into a categorical legend',async t=>{const doc=getExample('histogram');doc.data=Array.from({length:600},(_,i)=>({label:`sample ${i}`,value:i*1e-9}));const f=await fixture(t,newWork([{doc}]));assert.equal(f.host.querySelector('.we-edit-legend').hidden,true);assert.equal(f.app.getWork().steps[0].doc.data.length,600);assert.equal(f.host.querySelectorAll('[data-dw-cell]').length,80);});
test('unfinished cell text persists in IndexedDB and reopens without zero filling',async t=>{const f=await fixture(t);input(f.host,'[data-dw-cell="0:1"]','未填写');await f.app.flush();const record=f.repository.current();assert.equal(record.work.steps[0].draft.cells[0][1],'未填写');const host=document.createElement('main');document.body.append(host);const reopened=mountWorkEditor(host,{repository:f.repository,storage:memory()});assert.equal(host.querySelector('[data-dw-cell="0:1"]').value,'未填写');assert.equal(host.querySelector('[data-we=save]').disabled,true);assert.ok(host.querySelector('[data-we=storage]'));await reopened.flush();reopened.destroy();host.remove();});
