import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {getExample} from '../../src/forma/catalog.js';
import {withRecordIds,recordId} from '../../src/forma/data-identity.js';
import {setLocale} from '../../src/forma/locale.js';
import {temporalViews,temporalViewMap,temporalDocument,temporalEligibility,temporalCompatibility,temporalBounds,temporalColorKeys,temporalColorSubjects,temporalGroups,temporalOrderFields,temporalGuide,temporalAgentGuide} from '../../src/forma/temporal-series-rules.js';
import {layoutTemporal} from '../../src/forma/temporal-series-morph.js';
import {temporalPresets,temporalRecords} from '../../src/forma/temporal-series-presets.js';
const raw=template=>withRecordIds(getExample(template),{legacyNamespace:'temporal-test'}),doc=template=>temporalDocument(raw(template));
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8*Math.max(1,Math.abs(a),Math.abs(b)),`${a} != ${b}`);
function finite(layout){const seen=new Set();assert.ok(layout.plot.h>0);for(const m of layout.marks){assert.equal(m.points.length,128,m.key);assert.ok(m.points.flat().every(Number.isFinite),m.key);assert.ok(m.anchor.every(Number.isFinite));assert.ok(!seen.has(m.key));seen.add(m.key);}for(const l of layout.labels)assert.ok(Number.isFinite(l.x)&&Number.isFinite(l.y));}

test('six native temporal adapters retain original schemas, all records, provenance and actual editable fields',()=>{
 assert.equal(Object.keys(temporalViewMap).length,6);assert.equal(temporalViews.length,9);
 for(const [template,view]of Object.entries(temporalViewMap)){const original=raw(template),before=structuredClone(original),d=temporalDocument(original),l=layoutTemporal(d,view);assert.deepEqual(original,before);assert.equal(temporalEligibility(d,view).valid,true,template);finite(l);assert.equal(d.unit,original.unit);assert.deepEqual(d.source,original.source);const records=l.marks.filter(m=>m.role==='temporal-observation');assert.equal(records.length,d.data.length);for(const mark of records){const r=d.data[mark.row];assert.equal(mark.identity,recordId(r));assert.ok(mark.opacity>0);assert.equal(mark.editable,d.family==='temporal-retention'?r.activeField:'value');for(const [key,value]of Object.entries(original.data[mark.row]))assert.deepEqual(r[key],value);}for(const [w,h]of[[300,240],[800,440],[1280,720]])finite(layoutTemporal(d,view,w,h));}
});

test('stream, horizon and raw lines preserve real date spacing and exact source amounts',()=>{
 const d=temporalDocument(temporalRecords('temporal-source-story')[0].doc),layouts=['temporal-stream','temporal-horizon','temporal-lines'].map(v=>layoutTemporal(d,v)),first=d.data.find(r=>r.period===d.periodOrder[0]),second=d.data.find(r=>r.period===d.periodOrder[1]),third=d.data.find(r=>r.period===d.periodOrder[2]);
 for(const l of layouts){const get=r=>l.marks.find(m=>m.role==='temporal-observation'&&m.identity===recordId(r));near((get(third).point[0]-get(first).point[0])/(get(second).point[0]-get(first).point[0]),4);for(const r of d.data)assert.equal(get(r).originalValue,r.value);finite(l);}
 const l=layouts[0];for(const group of l.statistics.layers)for(let i=0;i<group.length;i++)near(group[i][1]-group[i][0],l.statistics.table.rows[i].values[group.key]);
 for(const other of layouts.slice(1))assert.deepEqual(other.marks.map(m=>m.key).sort(),l.marks.map(m=>m.key).sort());
 for(const factor of[1e-15,1e10]){const tiny=structuredClone(d);tiny.data.forEach(r=>r.value*=factor);near(layoutTemporal(tiny,'temporal-horizon').statistics.band,Math.max(...tiny.data.map(r=>r.value))/3);}
});

test('signed horizon bands retain true null gaps, zeros and common exact threshold crossing times',()=>{
 const d=doc('horizon'),l=layoutTemporal(d,'temporal-horizon'),rawMarks=l.marks.filter(m=>m.role==='temporal-observation');assert.equal(temporalEligibility(d,'temporal-stream').valid,false);assert.equal(temporalEligibility(d,'temporal-lines').valid,true);assert.equal(rawMarks.filter(m=>m.missing).length,d.data.filter(r=>r.value===null).length);
 const missing=d.data.find(r=>r.value===null);for(const m of l.marks.filter(m=>m.derived&&m.recordIds.includes(recordId(missing))))assert.equal(m.opacity,0);assert.ok(l.marks.some(m=>m.sign===-1&&m.opacity>0));assert.ok(l.marks.some(m=>m.sign===1&&m.opacity>0));near(l.statistics.band,Math.max(...d.data.map(r=>Math.abs(r.value??0)))/3);
 for(const factor of[1e-12,1e12]){const scaled=structuredClone(d);scaled.data.forEach(r=>{if(r.value!==null)r.value*=factor;});assert.equal(temporalEligibility(scaled,'temporal-horizon').valid,true);const changed=layoutTemporal(scaled,'temporal-horizon'),byKey=new Map(changed.marks.map(m=>[m.key,m]));for(const m of rawMarks){const n=byKey.get(m.key);near(m.point[0],n.point[0]);near(m.point[1],n.point[1]);}}
 const zero=structuredClone(d);zero.data[0].value=0;const mark=layoutTemporal(zero,'temporal-horizon').marks.find(m=>m.identity===recordId(zero.data[0])&&m.role==='temporal-observation');assert.equal(mark.value,0);assert.equal(mark.missing,false);assert.ok(mark.opacity>0);
 const before=structuredClone(d);d.data[0].value=-1;assert.equal(temporalEligibility(d,'temporal-stream').valid,false);assert.equal(before.data.length,d.data.length);
});

test('stream-to-horizon bands share a monotone time contour through middle frames',()=>{
 const d=temporalDocument(temporalRecords('temporal-source-story')[0].doc),a=layoutTemporal(d,'temporal-stream'),b=layoutTemporal(d,'temporal-horizon'),old=new Map(a.marks.map(m=>[m.key,m]));for(const next of b.marks.filter(m=>m.role.startsWith('temporal-band'))){const prior=old.get(next.key);for(const q of[.25,.5,.75]){const points=next.points.map((p,i)=>p.map((v,k)=>v*q+prior.points[i][k]*(1-q)));for(let i=1;i<64;i++)assert.ok(points[i][0]>=points[i-1][0]-1e-8);for(let i=0;i<64;i++)assert.ok(points[i][1]<=points[127-i][1]+1e-8);}}
});

test('seasonal means use observed values only and views preserve cycle order and null rows',()=>{
 const d=temporalDocument(temporalRecords('temporal-season-story')[0].doc),a=layoutTemporal(d,'temporal-season'),b=layoutTemporal(d,'temporal-season-lines');assert.ok(d.data.some(r=>r.value===null));for(const g of temporalGroups(d)){const mark=a.marks.find(m=>m.role==='season-mean'&&m.group===g.name),observed=g.rows.filter(r=>r.value!==null);near(mark.mean,observed.reduce((s,r)=>s+r.value,0)/observed.length);}assert.deepEqual(a.marks.map(m=>m.key).sort(),b.marks.map(m=>m.key).sort());const bad=structuredClone(d);bad.cycleOrder.reverse();assert.notEqual(temporalCompatibility(d,bad),'');
});

test('rank clocks and lines use exact competition ties, original values and open paths',()=>{
 const d=doc('rankclock'),period=d.periodOrder[0],rows=d.data.filter(r=>r.period===period);rows.forEach((r,i)=>r.value=i<2?100:50-i);d.rankOrder='descending';for(const view of['temporal-rankclock','temporal-ranklines']){const l=layoutTemporal(d,view),marks=l.marks.filter(m=>m.role==='temporal-observation');for(const r of rows){const m=marks.find(m=>m.identity===recordId(r));assert.equal(m.rank,1+rows.filter(q=>q.value>r.value).length);assert.equal(m.originalValue,r.value);}assert.equal(l.marks.filter(m=>m.role==='rank-link').length,d.objectOrder.length*(d.periodOrder.length-1));assert.deepEqual(marks.filter(m=>rows.slice(0,3).map(recordId).includes(m.identity)).map(m=>m.rank),[1,1,3]);}const flipped=structuredClone(d);flipped.rankOrder='ascending';assert.notEqual(temporalCompatibility(d,flipped),'');finite(layoutTemporal(flipped,'temporal-rankclock'));
});

test('retention views preserve both native count schemas, fixed denominators and future blanks without imputing rows',()=>{
 for(const template of['cohort','cohortcurve']){const d=doc(template);for(const view of['temporal-cohort','temporal-retention']){const l=layoutTemporal(d,view);finite(l);const marks=l.marks.filter(m=>m.role==='temporal-observation');assert.equal(marks.length,d.data.length);for(const mark of marks){const r=d.data[mark.row];near(mark.rate,r.activeValue/r.size);assert.equal(mark.denominator,r.size);assert.equal(mark.editable,template==='cohort'?'active':'retained');assert.equal(mark.age,r.ageValue);}assert.equal(l.marks.filter(m=>m.role==='retention-link').length,d.data.length-d.cohortOrder.length);}const rebound=structuredClone(d),g=temporalGroups(rebound)[0],row=g.rows.at(-1);row[row.activeField]=row.size;row.activeValue=row.size;assert.equal(temporalEligibility(rebound,'temporal-retention').valid,true);finite(layoutTemporal(rebound,'temporal-retention'));for(const mutate of[c=>c.data[0].size=0,c=>c.data[0][c.data[0].activeField]=-1,c=>c.data[1].size+=1]){const bad=structuredClone(d);mutate(bad);assert.equal(temporalEligibility(bad,'temporal-retention').valid,false);}const changed=structuredClone(d);changed.data[1].size+=1;assert.notEqual(temporalCompatibility(d,changed),'');}
 const m=doc('cohort'),w=doc('cohortcurve');assert.notEqual(temporalCompatibility(m,w),'');
});

test('explicit malformed orders reject before layout while color and bounds readers remain safe',()=>{
 for(const template of Object.keys(temporalViewMap)){const original=raw(template);for(const [field,nativeField]of Object.entries(temporalOrderFields(original)))for(const value of[null,'bad',[],['MISSING'],[original.data[0][nativeField],original.data[0][nativeField]]]){const d=temporalDocument({...original,[field]:value});assert.equal(d[field],value);assert.equal(temporalEligibility(d,temporalViewMap[template]).valid,false,`${template}/${field}`);assert.equal(temporalColorKeys(d).length,d.data.length);assert.ok(temporalColorKeys(d).every(Boolean));assert.doesNotThrow(()=>temporalBounds(d));}}
 for(const template of Object.keys(temporalViewMap)){const d=doc(template),r=structuredClone(d);r.data.reverse();assert.equal(temporalCompatibility(d,r),'');assert.deepEqual(temporalColorKeys(d).sort(),temporalColorKeys(r).sort());}
 assert.deepEqual(temporalColorSubjects(doc('cohort')),[]);assert.deepEqual(temporalColorSubjects(doc('horizon')),[]);
});

test('maximum valid native datasets, signed magnitudes and compact canvases remain finite',()=>{
 const h=doc('horizon');h.seriesOrder=Array.from({length:5},(_,i)=>`S${i}`);h.periodOrder=Array.from({length:60},(_,i)=>new Date(Date.UTC(2025,0,1+i)).toISOString().slice(0,10));h.data=h.periodOrder.flatMap((period,i)=>h.seriesOrder.map((series,j)=>({_id:`${i}-${j}`,period,series,value:i%7===0?null:((i+j)%2?1:-1)*(i+1)*1e12,inputIndex:i*5+j})));assert.equal(temporalEligibility(h,'temporal-horizon').valid,true);for(const [w,height]of[[300,240],[1280,720]])finite(layoutTemporal(h,'temporal-horizon',w,height));
 const c=doc('cohortcurve');c.cohortOrder=Array.from({length:8},(_,i)=>`C${i}`);c.data=c.cohortOrder.flatMap((cohort,j)=>Array.from({length:36-j},(_,period)=>({_id:`${j}-${period}`,cohort,period,size:1000,retained:period?900-period*10:1000,ageValue:period,activeValue:period?900-period*10:1000,activeField:'retained',inputIndex:j*36+period})));assert.equal(temporalEligibility(c,'temporal-retention').valid,true);for(const view of['temporal-cohort','temporal-retention'])finite(layoutTemporal(c,view,300,240));
});

test('four independent presets clone complete raw records and expose bilingual renderer/Agent contracts',()=>{
 assert.equal(temporalPresets.length,4);assert.equal(temporalRecords('missing'),null);for(const p of temporalPresets){const steps=temporalRecords(p.id,'coral');assert.deepEqual(steps.map(s=>s.view),p.views);for(const s of steps){assert.deepEqual(s.doc.data,steps[0].doc.data);assert.equal(s.options.palette,'coral');assert.equal(temporalEligibility(temporalDocument(s.doc),s.view).valid,true);}steps[0].doc.data[0].sentinel=true;assert.equal(steps[1].doc.data[0].sentinel,undefined);}try{setLocale('en');for(const v of temporalViews){assert.equal(v.name,v.en);assert.doesNotMatch(v.note,/\p{Script=Han}/u);}for(const p of temporalPresets)assert.doesNotMatch(p.name+p.description+p.dataNote+p.relation,/\p{Script=Han}/u);assert.doesNotMatch(temporalAgentGuide(true),/\p{Script=Han}/u);assert.doesNotMatch(temporalGuide(doc('streamgraph'),'temporal-stream').join(' '),/\p{Script=Han}/u);}finally{setLocale('zh-CN');}
});

test('twelve directed temporal transitions keep original SVG objects through forward, reverse, seek and resume',async()=>{
 const {ScientificMorphChart}=await import('../../src/forma/scientific-morph.js');let directions=0;for(const p of temporalPresets)for(const from of p.views)for(const to of p.views){if(from===to)continue;directions++;const win=new Window(),d=temporalDocument(temporalRecords(p.id)[0].doc);let chart;try{chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:from,width:800,height:440,editable:true});const first=chart.layout,nodes=new Map([...chart.nodes].map(([k,n])=>[k,n.shape])),seek=chart.setDocument(d,to,{manual:true,effect:'guided',recipe:'temporal-unfold'});seek(.37);const captured=structuredClone([...chart.current]),reverse=chart.setDocument(d,from,{manual:true,resume:true,effect:'guided',recipe:'temporal-unfold'});reverse(0);assert.deepEqual([...chart.current],captured);reverse(1);for(const m of first.marks)assert.deepEqual(chart.current.get(m.key),m.points);const again=chart.setDocument(d,to,{manual:true,effect:'guided',recipe:'temporal-unfold'});again(.5);const half=structuredClone([...chart.current]);again(1);again(.5);assert.deepEqual([...chart.current],half);again(1);for(const m of chart.layout.marks)assert.deepEqual(chart.current.get(m.key),m.points);for(const[k,node]of nodes)assert.equal(chart.nodes.get(k).shape,node);assert.doesNotMatch(chart.svg.outerHTML,/NaN|Infinity|undefined/);}finally{chart?.destroy();await win.happyDOM.close();}}assert.equal(directions,12);
});

test('native fields remain editable after saved-work roundtrip and standalone SVG export escapes raw labels',async()=>{
 const [{newWork,cleanWork,transitionPlan,stepReport},{stepSVG},{ScientificMorphChart}]=await Promise.all([import('../../src/forma/work-model.js'),import('../../src/forma/work-export.js'),import('../../src/forma/scientific-morph.js')]),win=new Window(),old=new Map();for(const [k,v]of Object.entries({document:win.document,XMLSerializer:win.XMLSerializer})){old.set(k,Object.getOwnPropertyDescriptor(globalThis,k));Object.defineProperty(globalThis,k,{value:v,configurable:true,writable:true});}
 try{for(const preset of temporalPresets){const work=newWork(temporalRecords(preset.id));assert.deepEqual(cleanWork(JSON.parse(JSON.stringify(work))),work);for(const a of work.steps){assert.equal(stepReport(a).valid,true);for(const b of work.steps)if(a!==b)assert.equal(transitionPlan(a,b,{steps:work.steps}).mode,'morph');const svg=stepSVG(a,work.steps);assert.doesNotMatch(svg.replace(/<style>[\s\S]*?<\/style>/g,''),/NaN|Infinity|undefined/);assert.match(svg,/data-science-role="temporal-observation"/);const chart=new ScientificMorphChart(win.document.createElement('div'),temporalDocument(a.doc),{view:a.view,editable:true});for(const m of chart.layout.marks.filter(m=>m.editable)){assert.equal(chart.nodes.get(m.key).group.dataset.editField,m.editable);assert.equal(Number(chart.nodes.get(m.key).group.dataset.editRow),m.row);}chart.destroy();}}
 const d=doc('cycleplot'),oldName=d.seasonOrder[0],name='<script>&"';d.data.filter(r=>r.season===oldName).forEach(r=>r.season=name);d.seasonOrder[0]=name;const chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:'temporal-season-lines'});assert.equal(chart.svg.querySelectorAll('script').length,0);assert.match(chart.svg.outerHTML,/&lt;script&gt;/);chart.destroy();
 }finally{for(const[k,v]of old){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];}await win.happyDOM.close();}
});
