import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {getExample} from '../../src/forma/catalog.js';
import {withRecordIds,recordId} from '../../src/forma/data-identity.js';
import {setLocale} from '../../src/forma/locale.js';
import {timePlanningViews,timePlanningViewMap,timePlanningDocument,timePlanningEligibility,timePlanningCompatibility,timePlanningBounds,timePlanningGroups,timePlanningOrderFields,timePlanningColorSubjects,timePlanningColorKeys,timePlanningGuide,timePlanningAgentGuide} from '../../src/forma/time-planning-rules.js';
import {layoutTimePlanning,interpolateTimePlanningMark} from '../../src/forma/time-planning-morph.js';
import {timePlanningPresets,timePlanningRecords} from '../../src/forma/time-planning-presets.js';
const raw=template=>withRecordIds(getExample(template),{legacyNamespace:'planning-test'}),doc=template=>timePlanningDocument(raw(template));
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8*Math.max(1,Math.abs(a),Math.abs(b)),`${a} != ${b}`);
const compatibleViews=d=>timePlanningViews.filter(v=>timePlanningEligibility(d,v.id).valid).map(v=>v.id);
function finite(layout){const keys=new Set();assert.ok(layout.plot.h>0);for(const m of layout.marks){assert.equal(m.points.length,128,m.key);assert.ok(m.points.flat().every(Number.isFinite),m.key);assert.ok(m.anchor.every(Number.isFinite));assert.ok(!keys.has(m.key),m.key);keys.add(m.key);}for(const label of layout.labels){assert.ok(Number.isFinite(label.x)&&Number.isFinite(label.y));assert.doesNotMatch(String(label.text),/NaN|Infinity|undefined/);}}

test('six native planning adapters preserve every raw field, stable identity, units and source',()=>{
 assert.equal(Object.keys(timePlanningViewMap).length,6);assert.equal(timePlanningViews.length,11);
 for(const [template,view]of Object.entries(timePlanningViewMap)){const original=raw(template),before=structuredClone(original),d=timePlanningDocument(original);assert.deepEqual(original,before);assert.equal(timePlanningEligibility(d,view).valid,true,template);assert.equal(d.unit,original.unit);assert.deepEqual(d.source,original.source);for(const target of compatibleViews(d))for(const [w,h]of[[300,240],[800,440],[1280,720]]){const l=layoutTimePlanning(d,target,w,h);finite(l);const marks=l.marks.filter(m=>m.original);assert.equal(marks.length,original.data.length);for(const mark of marks){const r=d.data[mark.row];assert.equal(mark.identity,recordId(r));assert.ok(mark.opacity>0);assert.ok(Object.hasOwn(r,mark.editable));for(const [key,value]of Object.entries(original.data[mark.row]))assert.deepEqual(r[key],value);}}}
});

test('native daily limits remain real and absent or null days never turn into zero rows',()=>{
 const full=doc('calendar');assert.equal(timePlanningEligibility(full,'planning-barcode').valid,false);assert.equal(timePlanningEligibility(full,'planning-daily-line').valid,true);
 const d=timePlanningDocument(timePlanningRecords('planning-daily-story')[0].doc),count=d.data.length;for(const view of compatibleViews(d)){const l=layoutTimePlanning(d,view),missing=l.marks.filter(m=>m.role==='planning-observation'&&m.missing);assert.equal(missing.length,3);assert.equal(missing.filter(m=>m.absent).length,2);assert.equal(l.marks.filter(m=>m.original).length,count);assert.equal(missing.filter(m=>m.editable).length,1);for(const m of missing.filter(m=>m.absent)){assert.equal(m.row,undefined);assert.equal(m.value,null);assert.deepEqual(m.recordIds,[]);}const zero=l.marks.find(m=>m.original&&m.value===0);assert.ok(zero&&!zero.missing&&zero.opacity>0);if(view==='planning-daily-line')for(const m of l.marks.filter(m=>m.role==='daily-link'&&m.opacity>0)){const [a,b]=m.recordIds.map(id=>d.data.find(r=>recordId(r)===id));assert.equal(Date.parse(b.date)-Date.parse(a.date),86400000);assert.notEqual(a.value,null);assert.notEqual(b.value,null);}finite(l);}assert.equal(d.data.length,count);
 const bad=structuredClone(d);bad.data[0].date='2025-02-30';assert.equal(timePlanningEligibility(bad,'planning-calendar').valid,false);
});

test('daily stems and lines use actual UTC elapsed spacing, quantile emphasis and hollow weekends',()=>{
 const original=raw('barcode');original.data=original.data.filter((_,i)=>i!==1);const d=timePlanningDocument(original);for(const view of ['planning-barcode','planning-daily-line']){const l=layoutTimePlanning(d,view),marks=l.marks.filter(m=>m.original),p=marks.slice(0,3);near((p[1].point[0]-p[0].point[0])/(p[2].point[0]-p[1].point[0]),2);for(const m of marks){assert.equal(m.originalValue,d.data[m.row].value);if(view==='planning-barcode'){assert.equal(m.nativeColorRole,m.value>=l.statistics.threshold&&m.value>0?'accent':'fg');const cap=l.marks.find(n=>n.role==='barcode-cap'&&n.identity===m.identity);assert.equal(cap.paper,[0,6].includes(new Date(m.date).getUTCDay()));}}}
});

test('calendar cells preserve Monday-first UTC weekday geometry across leap dates and year boundaries',()=>{
 const d=doc('calendar');d.data=Array.from({length:90},(_,i)=>({_id:`day-${i}`,date:new Date(Date.UTC(2023,11,25+i)).toISOString().slice(0,10),value:i%13?i:0,inputIndex:i}));assert.equal(timePlanningEligibility(d,'planning-calendar').valid,true);const l=layoutTimePlanning(d,'planning-calendar'),marks=l.marks.filter(m=>m.original),get=date=>marks.find(m=>m.date===date);assert.ok(get('2024-02-29'));near(get('2023-12-25').point[0],get('2023-12-31').point[0]);near(get('2023-12-25').point[1],get('2024-01-01').point[1]);assert.ok(get('2024-01-01').point[0]>get('2023-12-25').point[0]);
});

test('Gantt translates actual exclusive intervals and preserves completion independently of elapsed time',()=>{
 const d=doc('gantt'),a=layoutTimePlanning(d,'planning-gantt'),b=layoutTimePlanning(d,'planning-duration');for(const l of[a,b])for(const m of l.marks.filter(m=>m.original)){const row=d.data[m.row],progress=l.marks.find(n=>n.role==='planning-completion'&&n.identity===m.identity);assert.equal(m.duration,(Date.parse(row.end)-Date.parse(row.start))/86400000);assert.equal(m.progress,row.progress);const width=p=>Math.max(...p.map(q=>q[0]))-Math.min(...p.map(q=>q[0]));near(width(progress.points)/width(m.points),row.progress/100);if(l===b)near(Math.min(...m.points.map(p=>p[0])),b.plot.x);assert.equal(m.editable,'progress');}assert.deepEqual(a.marks.map(m=>m.key),b.marks.map(m=>m.key));for(const [field,value]of[['progress',101],['end',d.data[0].start]]){const bad=structuredClone(d);bad.data[0][field]=value;assert.equal(timePlanningEligibility(bad,'planning-duration').valid,false);}const bad=structuredClone(d);bad.data[0].end='2025-06-13';assert.notEqual(timePlanningCompatibility(d,bad),'');
});

test('events retain their exact dates and groups on a common open angular scale',()=>{
 const d=doc('eventline'),a=layoutTimePlanning(d,'planning-eventline'),b=layoutTimePlanning(d,'planning-event-rings'),first=d.data[0];d.data[1].date=first.date;const same=layoutTimePlanning(d,'planning-event-rings').marks.filter(m=>m.original&&m.date===first.date);assert.equal(new Set(same.map(m=>m.identity)).size,same.length);for(const l of[a,b]){assert.equal(l.marks.filter(m=>m.original).length,d.data.length);assert.ok(l.scales.angle.range()[1]-l.scales.angle.range()[0]<2*Math.PI);}assert.deepEqual(a.marks.map(m=>m.key),b.marks.map(m=>m.key));assert.equal(timePlanningColorSubjects(d).length,timePlanningGroups(d).length);const onlyDate=structuredClone(d);onlyDate.data.forEach(r=>{r.date='2025-01-01';});assert.equal(timePlanningEligibility(onlyDate,'planning-event-rings').valid,true);finite(layoutTimePlanning(onlyDate,'planning-event-rings'));
});

test('ledger keeps complete observations, real month spacing, zero-baseline semantics and shared value scale',()=>{
 const d=timePlanningDocument(timePlanningRecords('planning-ledger-story')[0].doc),a=layoutTimePlanning(d,'planning-ledger'),b=layoutTimePlanning(d,'planning-monthly-lines');assert.ok(a.labels.some(l=>l.text==='—'));assert.equal(a.statistics.maximum,b.statistics.maximum);assert.equal(b.marks.filter(m=>m.original).length,d.data.length);for(const g of timePlanningGroups(d)){const r=g.rows.slice(0,3),p=r.map(row=>b.statistics.positions.get(recordId(row)));near((p[1][0]-p[0][0])/(p[2][0]-p[1][0]),31/28);}const bad=structuredClone(d);bad.data.pop();assert.equal(timePlanningEligibility(bad,'planning-monthly-lines').valid,false);const huge=structuredClone(d);huge.data[0].value=1e-300;huge.data[11].value=1e15;finite(layoutTimePlanning(huge,'planning-ledger'));
});

test('spiral cells retain raw order, partial final cycle, negative values and missing cells',()=>{
 const d=doc('spiralheatmap');d.data=d.data.slice(0,-5);d.data[0].value=-20;assert.equal(timePlanningEligibility(d,'planning-cycle-grid').valid,true);for(const view of ['planning-spiral','planning-cycle-grid']){const l=layoutTimePlanning(d,view);assert.equal(l.marks.filter(m=>m.original).length,55);assert.equal(l.statistics.cycles,5);assert.equal(l.marks.filter(m=>m.original&&m.missing).length,1);for(const m of l.marks.filter(m=>m.original)){assert.equal(m.position,m.row%d.cycleLength);assert.equal(m.cycle,Math.floor(m.row/d.cycleLength));assert.equal(m.originalValue,d.data[m.row].value);}finite(l);}const altered=structuredClone(d);altered.data.reverse();assert.notEqual(timePlanningCompatibility(d,altered),'');altered.cycleLength=5;assert.equal(timePlanningEligibility(altered,'planning-spiral').valid,false);
});

test('spiral unfolding keeps simple noninverted cell polygons throughout local-frame rotation',()=>{
 const d=doc('spiralheatmap'),a=layoutTimePlanning(d,'planning-spiral'),b=layoutTimePlanning(d,'planning-cycle-grid'),old=new Map(a.marks.map(m=>[m.key,m]));
 const area=p=>p.reduce((s,a,i)=>{const b=p[(i+1)%p.length];return s+a[0]*b[1]-b[0]*a[1];},0)/2;
 const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
 const intersects=p=>{for(let i=0;i<p.length;i++)for(let j=i+2;j<p.length;j++){if(i===0&&j===p.length-1)continue;const a=p[i],b=p[(i+1)%p.length],c=p[j],d=p[(j+1)%p.length];if(cross(a,b,c)*cross(a,b,d)<-1e-12&&cross(c,d,a)*cross(c,d,b)<-1e-12)return true;}return false;};
 for(const next of b.marks.filter(m=>m.original)){const prior=old.get(next.key);for(const q of[0,.25,.5,.75,1]){const points=interpolateTimePlanningMark(prior.points,prior,next,q);assert.ok(points.flat().every(Number.isFinite));assert.ok(Math.abs(area(points))>.001);assert.equal(intersects(points),false,`${next.row} at ${q}`);if(q===0)assert.deepEqual(points,prior.points);if(q===1)assert.deepEqual(points,next.points);}}
});

test('invalid explicit orders reject safely and irrelevant metadata cannot override a native order',()=>{
 for(const template of ['eventline','ledger']){const original=raw(template);for(const name of Object.keys(timePlanningOrderFields(original)))for(const value of[null,'bad',[],['unknown'],[original.data[0][template==='eventline'?'group':'label'],original.data[0][template==='eventline'?'group':'label']]]){const d=timePlanningDocument({...original,[name]:value});assert.equal(d[name],value);assert.equal(timePlanningEligibility(d,timePlanningViewMap[template]).valid,false);assert.doesNotThrow(()=>timePlanningBounds(d));assert.equal(timePlanningColorKeys(d).length,d.data.length);}const d=doc(template),groups=timePlanningGroups(d).map(g=>g.name);d[template==='eventline'?'metricOrder':'groupOrder']=[...groups].reverse();assert.deepEqual(timePlanningGroups(d).map(g=>g.name),groups);}
 for(const template of Object.keys(timePlanningViewMap)){const d=doc(template),changed=structuredClone(d);changed.axes={x:'Changed meaning'};assert.notEqual(timePlanningCompatibility(d,changed),'');changed.axes=d.axes;changed.unit='New unit';assert.notEqual(timePlanningCompatibility(d,changed),'');}
});

test('six presets clone complete records and localized contracts explain real units and timing',()=>{
 assert.equal(timePlanningPresets.length,6);assert.equal(timePlanningRecords('missing'),null);for(const preset of timePlanningPresets){const steps=timePlanningRecords(preset.id,'coral');assert.deepEqual(steps.map(s=>s.view),preset.views);for(const step of steps){assert.deepEqual(step.doc.data,steps[0].doc.data);assert.equal(step.options.palette,'coral');assert.equal(timePlanningEligibility(timePlanningDocument(step.doc),step.view).valid,true);}steps[0].doc.data[0].sentinel=true;assert.equal(steps[1].doc.data[0].sentinel,undefined);}try{setLocale('en');for(const v of timePlanningViews){assert.equal(v.name,v.en);assert.doesNotMatch(v.note,/\p{Script=Han}/u);}for(const p of timePlanningPresets)assert.doesNotMatch(p.name+p.description+p.dataNote+p.relation,/\p{Script=Han}/u);assert.doesNotMatch(timePlanningAgentGuide(true),/\p{Script=Han}/u);for(const [template,view]of Object.entries(timePlanningViewMap))assert.doesNotMatch(timePlanningGuide(doc(template),view).join(' '),/\p{Script=Han}/u);}finally{setLocale('zh-CN');}
});

test('sixteen directed transitions preserve SVG objects, exact end states and interruption continuity',async()=>{
 const {ScientificMorphChart}=await import('../../src/forma/scientific-morph.js');let count=0;for(const p of timePlanningPresets)for(const from of p.views)for(const to of p.views){if(from===to)continue;count++;const win=new Window(),d=timePlanningDocument(timePlanningRecords(p.id)[0].doc);let chart;try{chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:from,width:800,height:440,editable:true});const first=chart.layout,nodes=new Map([...chart.nodes].map(([k,n])=>[k,n.shape])),seek=chart.setDocument(d,to,{manual:true,effect:'guided',recipe:'planning-unfold'});seek(.37);const current=structuredClone([...chart.current]),reverse=chart.setDocument(d,from,{manual:true,resume:true,effect:'guided',recipe:'planning-unfold'});reverse(0);assert.deepEqual([...chart.current],current);reverse(1);for(const mark of first.marks)assert.deepEqual(chart.current.get(mark.key),mark.points);const again=chart.setDocument(d,to,{manual:true,effect:'guided',recipe:'planning-unfold'});again(.5);const half=structuredClone([...chart.current]);again(1);again(.5);assert.deepEqual([...chart.current],half);again(1);for(const mark of chart.layout.marks)assert.deepEqual(chart.current.get(mark.key),mark.points);for(const [k,n]of nodes)assert.equal(chart.nodes.get(k).shape,n);assert.doesNotMatch(chart.svg.outerHTML,/NaN|Infinity|undefined/);}finally{chart?.destroy();await win.happyDOM.close();}}assert.equal(count,16);
});

test('saved work and SVG export preserve original edit fields and escape untrusted labels',async()=>{
 const [{newWork,cleanWork,stepReport,transitionPlan},{stepSVG},{ScientificMorphChart}]=await Promise.all([import('../../src/forma/work-model.js'),import('../../src/forma/work-export.js'),import('../../src/forma/scientific-morph.js')]),win=new Window(),prior=new Map();for(const [k,v]of Object.entries({document:win.document,XMLSerializer:win.XMLSerializer})){prior.set(k,Object.getOwnPropertyDescriptor(globalThis,k));Object.defineProperty(globalThis,k,{value:v,configurable:true,writable:true});}
 try{for(const p of timePlanningPresets){const work=newWork(timePlanningRecords(p.id));assert.deepEqual(cleanWork(JSON.parse(JSON.stringify(work))),work);for(const a of work.steps){assert.equal(stepReport(a).valid,true,a.view);for(const b of work.steps)if(a!==b)assert.equal(transitionPlan(a,b,{steps:work.steps}).mode,'morph');assert.doesNotMatch(stepSVG(a,work.steps).replace(/<style>[\s\S]*?<\/style>/g,''),/NaN|Infinity|undefined/);const chart=new ScientificMorphChart(win.document.createElement('div'),timePlanningDocument(a.doc),{view:a.view,editable:true});for(const mark of chart.layout.marks.filter(m=>m.original)){const group=chart.nodes.get(mark.key).group;assert.equal(group.dataset.editField,mark.editable);assert.equal(Number(group.dataset.editRow),mark.row);}chart.destroy();}}
 const d=doc('gantt');d.data[0].label='<script>&"';const chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:'planning-duration'});assert.equal(chart.svg.querySelectorAll('script').length,0);assert.match(chart.svg.outerHTML,/&lt;script&gt;/);chart.destroy();
 }finally{for(const [k,v]of prior){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];}await win.happyDOM.close();}
});

test('maximum native daily and cycle capacities stay finite on narrow canvases',()=>{
 const calendar=doc('calendar');calendar.data=Array.from({length:366},(_,i)=>({_id:`d${i}`,inputIndex:i,date:new Date(Date.UTC(2024,0,1+i)).toISOString().slice(0,10),value:i%11?i*1e-12:null}));assert.equal(timePlanningEligibility(calendar,'planning-calendar').valid,true);for(const view of compatibleViews(calendar))finite(layoutTimePlanning(calendar,view,300,240));const spiral=doc('spiralheatmap');spiral.cycleLength=24;spiral.data=Array.from({length:144},(_,i)=>({_id:`s${i}`,inputIndex:i,period:`P${i}`,value:i%13?(i%2?-1:1)*i*1e12:null}));assert.equal(timePlanningEligibility(spiral,'planning-spiral').valid,true);for(const view of compatibleViews(spiral))finite(layoutTimePlanning(spiral,view,300,240));
});

test('opaque paper cells and task intervals render before completion fill, endpoint caps and missing texture',async()=>{
 const {ScientificMorphChart}=await import('../../src/forma/scientific-morph.js');const win=new Window();try{for(const id of ['planning-daily-story','planning-task-story','planning-cycle-story'])for(const step of timePlanningRecords(id)){const d=timePlanningDocument(step.doc),chart=new ScientificMorphChart(win.document.createElement('div'),d,{view:step.view,editable:true});try{const all=[...chart.svg.querySelectorAll('[data-science-role]')],primary=new Map(chart.layout.marks.filter(m=>m.original).map(m=>[m.identity,m]));let found=0;for(const overlay of chart.layout.marks.filter(m=>m.opacity>0&&(m.role==='planning-completion'||m.role==='barcode-cap'||m.role.startsWith('missing-hatch-')||m.role.startsWith('cycle-missing-')))){const original=primary.get(overlay.identity);if(!original)continue;assert.ok(all.indexOf(chart.nodes.get(overlay.key).group)>all.indexOf(chart.nodes.get(original.key).group),`${step.view}/${overlay.role} must paint above its paper background`);found++;}if(step.view!=='planning-daily-line')assert.ok(found>0,step.view);}finally{chart.destroy();}}}finally{await win.happyDOM.close();}
});
