import test from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {volume16Catalog,volume16English} from '../../src/forma/volume16-catalog.js';
import {radviz16,hive16,gains16,netBenefit16,decision16,rankClock16,funnelLimits16,labbe16,nomogram16} from '../../src/forma/volume16-data.js';
import {getExample} from '../../src/forma/catalog.js';
import {validateDocument,parseDataText,toCSV} from '../../src/forma/data.js';
import {ChartScene} from '../../src/forma/charts.js';
import {getDataGuide,agentBrief} from '../../src/forma/data-guides.js';
import {makeProject,readProject} from '../../src/forma/project-file.js';
import {staticSVG,standaloneHTML} from '../../src/forma/export.js';
import {setLocale} from '../../src/forma/locale.js';
const win=new Window();globalThis.document=win.document;globalThis.XMLSerializer=win.XMLSerializer;
const near=(a,b,tolerance=1e-9)=>assert.ok(Math.abs(a-b)<tolerance,`${a} != ${b}`),scene=(doc,options={})=>new ChartScene(document.createElement('div'),doc,{width:680,height:400,editable:true,interactive:false,...options});
const valid=d=>validateDocument(d).valid;
function bad(id,edit){const d=getExample(id);edit(d);assert.equal(valid(d),false,`${id} accepted invalid input`);}
test('eight volume 16 templates retain original records and complete shared export/guide contracts',()=>{
 assert.equal(volume16Catalog.length,8);for(const t of volume16Catalog){const d=getExample(t.id),before=structuredClone(d);assert.ok(valid(d),`${t.id}: ${validateDocument(d).errors}`);assert.deepEqual(parseDataText(toCSV(d),d,'csv').data,d.data);assert.deepEqual(readProject(JSON.stringify(makeProject(d,{}))).doc,d);const guide=getDataGuide(t.id);assert.ok(guide.rowMeaning);assert.equal(guide.fields.length,t.fields.length);assert.equal(volume16English[t.id].fields.length,t.fields.length);assert.ok(agentBrief(d).includes(t.id));assert.match(staticSVG(d),/确定性合成/);assert.ok(standaloneHTML(d,{},'var FormaPlayer={mount(){}};').includes(t.id));assert.deepEqual(d,before);}
});
test('RadViz uses normalized spring equilibrium, complete vectors and no false position for zero total weight',()=>{
 const input=['A','B','C'].flatMap((sample,i)=>['X','Y','Z'].map((variable,j)=>({sample,variable,group:'G',value:i===j?10:0}))),before=structuredClone(input),m=radviz16(input);m.points.forEach((p,i)=>{near(p.x,m.anchors[i].x);near(p.y,m.anchors[i].y);});assert.deepEqual(input,before);const d=getExample('radviz'),s=scene(d);assert.equal(s.svg.querySelectorAll('[data-mark="radviz-point"]').length,36);assert.equal(s.svg.querySelectorAll('[data-mark="radviz-anchor"]').length,5);assert.ok([...s.svg.querySelectorAll('[data-mark="radviz-point"]')].every(n=>Math.hypot(+n.dataset.x,+n.dataset.y)<=1+1e-12));s.destroy();bad('radviz',d=>d.data.pop());bad('radviz',d=>d.data.filter(r=>r.variable===d.data[0].variable).forEach(r=>r.value=4));bad('radviz',d=>{const sample=d.data[0].sample;for(const r of d.data.filter(r=>r.sample===sample))r.value=Math.min(...d.data.filter(q=>q.variable===r.variable).map(q=>q.value));});bad('radviz',d=>d.data[0].group='Another');
});
test('Hive nodes retain explicit positions and undirected weights without inferring layout from edge order',()=>{
 const d=getExample('hiveplot'),before=structuredClone(d),m=hive16(d),s=scene(d),edges=[...s.svg.querySelectorAll('[data-mark="hive-edge"]')];assert.equal(m.nodes.length,15);assert.equal(edges.length,d.data.length);near(+edges[0].getAttribute('stroke-width')/+edges[1].getAttribute('stroke-width'),d.data[0].value/d.data[1].value);assert.ok(edges.every(e=>e.hasAttribute('data-edit-row')));for(const n of s.svg.querySelectorAll('[data-mark="hive-node"]'))assert.equal(+n.dataset.position,m.nodes.find(q=>q.name===n.dataset.node).position);s.destroy();assert.deepEqual(d,before);bad('hiveplot',d=>d.data[0].sourcePosition=2);bad('hiveplot',d=>d.data[0].targetGroup=d.data[0].sourceGroup);bad('hiveplot',d=>d.axisOrder=['A','A','B']);bad('hiveplot',d=>{const r=d.data[0];d.data.push({...r,source:r.target,target:r.source,sourceGroup:r.targetGroup,targetGroup:r.sourceGroup,sourcePosition:r.targetPosition,targetPosition:r.sourcePosition});});
});
test('cumulative gains admit whole score ties and remain invariant to within-tie input order',()=>{
 const input=[{actual:1,score:.8},{actual:0,score:.8},{actual:1,score:.4},{actual:0,score:.2}],m=gains16(input);assert.deepEqual(m.points.map(p=>[p.fraction,p.gain]),[[0,0],[.5,.5],[.75,1],[1,1]]);assert.deepEqual(gains16([input[1],input[0],input[2],input[3]]).points.map(p=>[p.fraction,p.gain]),m.points.map(p=>[p.fraction,p.gain]));const d=getExample('cumulativegains'),s=scene(d);assert.equal(s.svg.querySelectorAll('[data-mark="prediction-raw"][data-edit-field="score"]').length,d.data.length);s.destroy();bad('cumulativegains',d=>d.data.pop());bad('cumulativegains',d=>d.data[0].actual=2);bad('cumulativegains',d=>d.data[0].score=1.1);bad('cumulativegains',d=>d.data.forEach(r=>r.actual=1));
});
test('decision net benefit uses threshold odds, complete ties and explicit action baselines',()=>{
 const rows=[{actual:1,score:.8},{actual:0,score:.8},{actual:1,score:.4},{actual:0,score:.2}];assert.deepEqual(netBenefit16(rows,.8),{threshold:.8,tp:1,fp:1,net:-.7500000000000002});near(netBenefit16(rows,.5).net,0);near(netBenefit16(rows,.9).net,0);const d=getExample('decisioncurve'),m=decision16(d);for(const p of m.all)near(p.net,m.prevalence-(1-m.prevalence)*p.threshold/(1-p.threshold));const score=d.data.find(r=>r.score>d.thresholdMin&&r.score<d.thresholdMax).score,index=m.thresholds.indexOf(score);assert.ok(index>=0&&m.thresholds[index+1]>score&&m.thresholds[index+1]-score<1e-14);const s=scene(d);assert.equal(s.svg.querySelectorAll('[data-mark="decision-model"]').length,2);assert.ok(s.svg.querySelector('[data-mark="decision-all"]'));assert.ok(s.svg.querySelector('[data-mark="decision-none"]'));s.destroy();bad('decisioncurve',d=>d.thresholdMax=1);bad('decisioncurve',d=>d.thresholdMin=0);bad('decisioncurve',d=>d.data[0].score=-.01);
});
test('rank clocks compute competition ranks with gaps, preserve periods and never close the time path',()=>{
 const d=getExample('rankclock');d.data=Array.from({length:4},(_,p)=>['A','B','C'].map((label,i)=>({period:`P${p}`,label,value:[9,9,2][i]}))).flat();const m=rankClock16(d);assert.deepEqual(m.series.map(q=>q.points[0].rank),[1,1,3]);d.rankOrder='ascending';assert.deepEqual(rankClock16(d).series.map(q=>q.points[0].rank),[2,2,1]);const s=scene(d);assert.equal(s.svg.querySelectorAll('[data-mark="rankclock-point"]').length,12);for(const line of s.svg.querySelectorAll('[data-mark="rankclock-line"]'))assert.doesNotMatch(line.getAttribute('d'),/Z/i);s.destroy();bad('rankclock',d=>d.data.pop());bad('rankclock',d=>d.rankOrder='random');
});
test('proportion control funnels use known binomial references and reject invalid normal approximations',()=>{
 const m=funnelLimits16(100,.2,3);near(m.low,.08);near(m.high,.32);assert.deepEqual(funnelLimits16(5,.5,4),{low:0,high:1});const d=getExample('funnelcontrol'),s=scene(d);assert.equal(s.svg.querySelectorAll('[data-mark="funnel-control-point"]').length,d.data.length);assert.ok(s.svg.querySelector('[data-outside="true"]'));s.destroy();bad('funnelcontrol',d=>d.data[0].events=1.5);bad('funnelcontrol',d=>d.data[0].total=10);bad('funnelcontrol',d=>d.targetRate=0);bad('funnelcontrol',d=>d.limitSigma=5);bad('funnelcontrol',d=>d.data[0].events=d.data[0].total+1);
});
test('L’Abbé coordinates are original arm rates and bubble areas represent total sample sizes',()=>{
 const rows=[{label:'A',controlEvents:0,controlTotal:100,treatmentEvents:25,treatmentTotal:100},{label:'B',controlEvents:100,controlTotal:400,treatmentEvents:200,treatmentTotal:400},{label:'C',controlEvents:20,controlTotal:200,treatmentEvents:40,treatmentTotal:200}],m=labbe16(rows);assert.equal(m[0].control,0);assert.equal(m[0].treatment,.25);assert.equal(m[1].size/m[0].size,4);const d=getExample('labbe');d.data=rows;const s=scene(d),marks=[...s.svg.querySelectorAll('[data-mark="labbe-study"]')];near((+marks.find(n=>n.dataset.size==='800').getAttribute('r'))**2/(+marks.find(n=>n.dataset.size==='200').getAttribute('r'))**2,4);s.destroy();bad('labbe',d=>d.data[0].controlTotal=0);bad('labbe',d=>d.data[0].treatmentEvents=-1);
});
test('nomograms keep signed contributions, explicit references and linear totals without a probability link',()=>{
 const d=getExample('nomogram'),before=structuredClone(d),m=nomogram16(d);near(m.total,50+.6*(88-75)-1.8*(7-10)+.22*(96-64)+.8*(14-8));assert.ok(m.minimum<m.total&&m.maximum>m.total);assert.ok(m.rows.some(r=>r.row.coefficient<0));const s=scene(d);near(+s.svg.querySelector('[data-mark="nomogram-total"]').dataset.total,m.total);assert.equal(s.svg.querySelectorAll('[data-mark="nomogram-input"][data-edit-field="value"]').length,d.data.length);s.destroy();assert.deepEqual(d,before);bad('nomogram',d=>d.data[0].value=1000);bad('nomogram',d=>d.data[0].reference=-1);bad('nomogram',d=>d.data.forEach(r=>r.coefficient=0));bad('nomogram',d=>delete d.intercept);
});
test('volume 16 rejects missing values without mutation and declares separate layout capacity',()=>{
 for(const t of volume16Catalog){const d=getExample(t.id),key=t.fields.find(([,type])=>type==='number')[0];d.data[0][key]=null;assert.equal(validateDocument(d).dataValid,false,t.id);}
 const d=getExample('labbe');d.data=Array.from({length:61},(_,i)=>({label:`Study ${i}`,controlEvents:3,controlTotal:10,treatmentEvents:2,treatmentTotal:10}));const before=structuredClone(d),report=validateDocument(d);assert.equal(report.dataValid,true);assert.equal(report.layoutValid,false);assert.deepEqual(d,before);
});
test('all scenes expose real reversible progress with finite compact, wide, portrait, dark and custom-color geometry',()=>{
 for(const t of volume16Catalog)for(const options of[{width:300,height:240,compact:true},{width:680,height:400,dark:true},{width:400,height:650,colors:['#325879','#bc795a','#82986d']}]){const d=getExample(t.id),before=structuredClone(d),s=scene(d,options),end=s.serialize();s.render(0);assert.notEqual(s.serialize(),end,t.id);s.render(.32);assert.notEqual(s.serialize(),end,t.id);for(const p of[.67,1,.5,0,1]){s.render(p);assert.doesNotMatch(s.serialize(),/NaN|Infinity|undefined/,t.id);}assert.equal(s.serialize(),end,t.id);assert.ok(s.svg.querySelector('[data-edit-row]'),t.id);s.destroy();assert.deepEqual(d,before);}
});
test('English help covers native data semantics rather than inherited generic row descriptions',()=>{try{setLocale('en');for(const t of volume16Catalog){const guide=getDataGuide(t.id);assert.doesNotMatch([guide.introduction,guide.rowMeaning,...guide.notes,...guide.fields.map(f=>f.description)].join(' '),/[\u3400-\u9fff]/,t.id);assert.equal(guide.fields.length,t.fields.length);}}finally{setLocale('zh-CN');}});

test('nomogram input rulers use actual declared ranges and every tick stays inside its contribution axis',()=>{
 const doc=getExample('nomogram');for(const options of[{width:680,height:400},{width:300,height:240,compact:true}]){const s=scene(doc,options),ticks=[...s.svg.querySelectorAll('[data-mark="nomogram-tick"]')];assert.ok(ticks.length>=doc.data.length*2);for(const tick of ticks){const row=doc.data.find(r=>r.variable===tick.dataset.variable),value=+tick.dataset.input,x=+tick.getAttribute('x1');assert.ok(value>=row.minimum&&value<=row.maximum,`${row.variable}: ${value} outside declared input range`);assert.ok(x>=(options.compact?77:118)-1e-8&&x<=options.width-25+1e-8,`${row.variable}: tick x=${x}`);}s.destroy();}
});

test('editable original numeric values keep full tooltip precision and extreme valid threshold ranges remain finite',()=>{
 for(const [id,key,value]of[['radviz','value',43.123456789],['hiveplot','value',14.123456789],['cumulativegains','score',.5123456789],['decisioncurve','score',.5123456789],['rankclock','value',73.123456789],['nomogram','value',83.123456789]]){const d=getExample(id);d.data[0][key]=value;const s=scene(d);assert.ok([...s.svg.querySelectorAll('[data-tip]')].some(n=>n.dataset.tip.includes(String(value))),id);s.destroy();}
 const d=getExample('decisioncurve');d.thresholdMin=1-Number.EPSILON;d.thresholdMax=1-Number.EPSILON/2;assert.ok(valid(d));const s=scene(d);assert.doesNotMatch(s.serialize(),/NaN|Infinity/);s.destroy();
 const tooSmall=getExample('nomogram');tooSmall.data.forEach(r=>r.coefficient=5e-324);assert.equal(validateDocument(tooSmall).dataValid,false);
});
