import test from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {getExample} from '../../src/forma/catalog.js';
import {volume13Catalog,volume13English} from '../../src/forma/volume13-catalog.js';
import {hierarchy13,tornado13,cohorts13,venn13,cyclicFlow13} from '../../src/forma/volume13-data.js';
import {validateDocument,parseDataText,toCSV} from '../../src/forma/data.js';
import {ChartScene} from '../../src/forma/charts.js';
import {palettes} from '../../src/forma/palettes.js';
import {getDataGuide,agentBrief} from '../../src/forma/data-guides.js';
import {staticSVG,standaloneHTML} from '../../src/forma/export.js';
import {makeProject,readProject} from '../../src/forma/project-file.js';
const window=new Window();globalThis.document=window.document;globalThis.XMLSerializer=window.XMLSerializer;
const scene=(doc,options={})=>new ChartScene(document.createElement('div'),doc,{width:680,height:360,editable:true,interactive:false,...options});
const near=(a,b,tol=1e-8)=>assert.ok(Math.abs(a-b)<=tol,`${a} differs from ${b}`),valid=doc=>validateDocument(doc).valid;
function bad(id,change){const doc=getExample(id);change(doc);assert.equal(valid(doc),false,`${id} accepted invalid data`);}
test('eight relational templates roundtrip all original rows, metadata and shared export contracts',()=>{
 assert.equal(volume13Catalog.length,8);
 for(const t of volume13Catalog){const doc=getExample(t.id),before=structuredClone(doc),guide=getDataGuide(t.id);assert.equal(valid(doc),true,`${t.id}: ${validateDocument(doc).errors}`);assert.deepEqual(parseDataText(toCSV(doc),doc,'csv').data,doc.data);assert.deepEqual(readProject(JSON.stringify(makeProject(doc,{}))).doc,doc);assert.ok(guide.rowMeaning);assert.equal(guide.fields.length,t.fields.length);assert.equal(volume13English[t.id].fields.length,t.fields.length);assert.ok(agentBrief(doc).includes(t.id));assert.ok(standaloneHTML(doc,{},'var FormaPlayer={mount(){}};').includes(t.id));assert.ok(staticSVG(doc).includes('确定性合成'));assert.deepEqual(doc,before);}
});
test('geographic routes preserve directed records, proportional widths and split antimeridian paths',()=>{
 const doc=getExample('geoflow'),before=structuredClone(doc),s=scene(doc),marks=[...s.svg.querySelectorAll('[data-mark=geoflow-link]')];assert.equal(marks.length,doc.data.length);near(+marks[0].getAttribute('stroke-width')/+marks[1].getAttribute('stroke-width'),doc.data[0].value/doc.data[1].value);const pacific=marks.find(n=>n.dataset.source==='Tokyo');assert.ok((pacific.getAttribute('d').match(/M/g)||[]).length>=2);assert.ok(pacific.getAttribute('data-tip').includes('139.69'));assert.ok(marks.every(n=>n.hasAttribute('data-edit-row')));s.destroy();assert.deepEqual(doc,before);
 bad('geoflow',d=>{d.data[0].sourceLatitude=90;});bad('geoflow',d=>{d.data[1].sourceLongitude+=1;});bad('geoflow',d=>{d.data[0].targetLongitude=d.data[0].sourceLongitude;d.data[0].targetLatitude=d.data[0].sourceLatitude;});bad('geoflow',d=>{d.data[0].value=0;});bad('geoflow',d=>{d.data.push({...d.data[0]});});
 const opposite=getExample('geoflow');opposite.data=[{source:'A',target:'B',sourceLongitude:0,sourceLatitude:0,targetLongitude:180,targetLatitude:0,value:1},{source:'B',target:'C',sourceLongitude:180,sourceLatitude:0,targetLongitude:100,targetLatitude:10,value:2}];assert.equal(valid(opposite),false);
});
test('hierarchies sum leaves exactly once and reject orphan cycles, shared ids and parent totals',()=>{
 const doc=getExample('circlehierarchy'),before=structuredClone(doc),h=hierarchy13(doc.data),leaves=h.nodes.filter(n=>!n.children.length);assert.equal(h.total,leaves.reduce((v,n)=>v+n.row.value,0));assert.equal(h.depth,3);assert.deepEqual(doc,before);
 for(const id of['circlehierarchy','radialtree']){bad(id,d=>{d.data.find(r=>r.id==='core').value=20;});bad(id,d=>{d.data[1].parent='missing';});bad(id,d=>{d.data[1].parent='workspace';});bad(id,d=>{d.data.push({...d.data[3]});});bad(id,d=>{d.data[2].parent='ROOT';});bad(id,d=>{d.data[6].value=0;});bad(id,d=>{d.data[0].id='ROOT';});}
 const s=scene(doc),leafMarks=[...s.svg.querySelectorAll('[data-mark=hierarchy-circle][data-leaf=true]')],a=leafMarks.find(n=>n.dataset.nodeId==='editor'),b=leafMarks.find(n=>n.dataset.nodeId==='review');near((+a.getAttribute('r'))**2/(+b.getAttribute('r'))**2,35/22);assert.equal(s.svg.querySelectorAll('[data-mark=hierarchy-circle]').length,doc.data.length);s.destroy();
 const tree=scene(getExample('radialtree'));assert.equal(tree.svg.querySelectorAll('[data-mark=radialtree-edge]').length,doc.data.length-1);assert.equal(tree.svg.querySelectorAll('[data-mark=radialtree-node]').length,doc.data.length);tree.destroy();
});
test('tornado retains negative sensitivity, same-side scenarios and stable impact ordering',()=>{
 const doc=getExample('tornado'),before=structuredClone(doc),rows=tornado13(doc);assert.ok(rows.every((row,i)=>!i||rows[i-1].impact>=row.impact));assert.ok(valid(doc));assert.ok(doc.data.some(r=>r.low>r.high));doc.data[0].low=120;doc.data[0].high=140;assert.ok(valid(doc));const s=scene(doc),marks=[...s.svg.querySelectorAll('[data-mark=tornado-scenario]')];assert.equal(marks.length,doc.data.length*2);assert.ok(marks.some(n=>n.dataset.scenario==='low'&&n.dataset.value==='121'));const low=marks.find(n=>n.dataset.value==='120'),high=marks.find(n=>n.dataset.value==='140');near(+high.getAttribute('width')/+low.getAttribute('width'),2);assert.ok(marks.every(n=>n.hasAttribute('data-edit-field')));s.destroy();assert.deepEqual(getExample('tornado'),before);bad('tornado',d=>{delete d.baseline;});bad('tornado',d=>{d.baseline=Infinity;});
});
test('cohort retention uses fixed denominators, permits returning users and does not extend immature cohorts',()=>{
 const doc=getExample('cohortcurve');doc.data.find(r=>r.cohort===doc.data[0].cohort&&r.period===2).retained=470;assert.ok(valid(doc));const groups=cohorts13(doc),s=scene(doc),marks=[...s.svg.querySelectorAll('[data-mark=cohort-point]')];assert.equal(marks.length,doc.data.length);for(const m of marks)near(+m.dataset.rate,+m.dataset.retained/+m.dataset.size);assert.equal(groups.at(-1).rows.at(-1).row.period,4);assert.equal(s.svg.querySelectorAll('[data-cohort="四月"] [data-mark=cohort-point]').length,5);s.destroy();bad('cohortcurve',d=>{d.data[1].size+=1;});bad('cohortcurve',d=>{d.data[0].retained-=1;});bad('cohortcurve',d=>{d.data.splice(2,1);});bad('cohortcurve',d=>{d.data[1].retained=d.data[1].size+1;});bad('cohortcurve',d=>{delete d.periodUnit;});
});
test('three-set Venn requires all seven exclusive intersections and keeps areas independent of counts',()=>{
 const doc=getExample('venn'),stats=venn13(doc);assert.equal(stats.total,195);assert.deepEqual(stats.setTotals,[101,101,90]);const a=scene(doc),radii=[...a.svg.querySelectorAll('[data-mark=venn-set]')].map(n=>+n.getAttribute('r'));assert.equal(a.svg.querySelectorAll('[data-mark=venn-region]').length,7);assert.ok(a.svg.textContent.includes('区域面积不编码数量'));a.destroy();doc.data[0].count=0;doc.data[6].count=1000;assert.ok(valid(doc));const b=scene(doc);assert.deepEqual([...b.svg.querySelectorAll('[data-mark=venn-set]')].map(n=>+n.getAttribute('r')),radii);b.destroy();bad('venn',d=>{d.data.pop();});bad('venn',d=>{d.data[0].members='设计|设计';});bad('venn',d=>{d.data[3].members='分析|设计';d.data[0].members='设计|分析';});bad('venn',d=>{d.data[0].members='unknown';});bad('venn',d=>{d.data[0].count=-1;});bad('venn',d=>{d.sets=['A','B','A'];});
});
test('cyclic Sankey preserves real flow widths, cycles, self-links and imbalance without mutating rows',()=>{
 const doc=getExample('sankeycycle');doc.data.push({source:'回收',target:'回收',value:7});assert.ok(valid(doc));const before=structuredClone(doc),g=cyclicFlow13(doc.data),returns=g.links.filter(l=>l.returning);assert.ok(returns.length>=2);assert.ok(returns.some(l=>l.source===l.target));for(const l of g.links)near(l.width/g.links[0].width,l.row.value/doc.data[0].value);for(const n of g.nodes){near(n.incoming,doc.data.filter(r=>r.target===n.name).reduce((a,r)=>a+r.value,0));near(n.outgoing,doc.data.filter(r=>r.source===n.name).reduce((a,r)=>a+r.value,0));near(n.height,Math.max(n.incoming,n.outgoing)/g.magnitude*g.scale);near(n.balance,n.incoming-n.outgoing);}assert.equal(g.nodes.find(n=>n.name==='原料').balance,-100);assert.deepEqual(doc,before);const s=scene(doc);assert.equal(s.svg.querySelectorAll('[data-mark=cycle-link]').length,doc.data.length);assert.ok(s.svg.querySelector('[data-source="回收"][data-target="回收"]').getAttribute('d').includes('C'));assert.equal(s.svg.querySelector('[data-node="原料"]').dataset.balance,'-100');s.destroy();bad('sankeycycle',d=>{d.data.push({...d.data[0]});});bad('sankeycycle',d=>{d.data[0].value=-1;});
});
test('directed adjacency preserves asymmetry, explicit zeros and one editable cell per ordered pair',()=>{
 const doc=getExample('adjacency'),before=structuredClone(doc),s=scene(doc),cells=[...s.svg.querySelectorAll('[data-mark=adjacency-cell]')];assert.equal(cells.length,doc.nodes.length**2);assert.equal(cells.filter(n=>n.dataset.source===n.dataset.target&&n.dataset.value==='0').length,doc.nodes.length);const a=cells.find(n=>n.dataset.source==='研究'&&n.dataset.target==='产品'),b=cells.find(n=>n.dataset.source==='产品'&&n.dataset.target==='研究');assert.notEqual(a.dataset.value,b.dataset.value);assert.notEqual(a.getAttribute('fill'),b.getAttribute('fill'));assert.ok(cells.every(n=>n.hasAttribute('data-edit-row')));s.destroy();assert.deepEqual(doc,before);bad('adjacency',d=>{d.data.pop();});bad('adjacency',d=>{d.data[0].target='missing';});bad('adjacency',d=>{d.data[0].value=-1;});bad('adjacency',d=>{d.nodes.push(d.nodes[0]);});
});
test('all eight scenes have actual deterministic entrance frames at compact, wide and portrait layouts with custom dark colors',()=>{
 for(const t of volume13Catalog)for(const[width,height,compact]of[[300,240,true],[680,360,false],[400,650,false]]){const doc=getExample(t.id),before=structuredClone(doc),s=scene(doc,{width,height,compact,dark:true,colors:['#aabbcc','#ff8877','#7799bb']}),final=s.serialize();s.render(0);const start=s.serialize();s.render(.3);const middle=s.serialize();assert.notEqual(start,final,t.id);assert.notEqual(middle,final,t.id);for(const p of[0,.25,.5,.75,1,.5,.25,0,1]){s.render(p);assert.doesNotMatch(s.serialize(),/NaN|Infinity/,`${t.id} at ${p}`);}assert.equal(s.serialize(),final,t.id);assert.match(final,/#aabbcc|#ff8877|rgb\(/,`${t.id} uses configured colors`);assert.ok(s.svg.querySelector('[data-edit-row]'),`${t.id} editable rows`);s.destroy();assert.deepEqual(doc,before);}
});

test('tornado low and high scenarios remain visually distinct in every built-in palette and dark mode',()=>{
 for(const palette of Object.keys(palettes))for(const dark of[false,true]){const s=scene(getExample('tornado'),{palette,dark});const low=s.svg.querySelector('[data-mark=tornado-scenario][data-scenario=low]'),high=s.svg.querySelector('[data-mark=tornado-scenario][data-scenario=high]');assert.notEqual(low.getAttribute('fill'),high.getAttribute('fill'),`${palette}, dark=${dark}`);assert.ok(+low.getAttribute('y')<+high.getAttribute('y'));s.destroy();}
 for(const colors of[['#aabbcc'],['#aabbcc','#aabbcc']]){const s=scene(getExample('tornado'),{colors});assert.notEqual(s.svg.querySelector('[data-scenario=low]').getAttribute('fill'),s.svg.querySelector('[data-scenario=high]').getAttribute('fill'));s.destroy();}
});
